# Generated by Django 4.2.13 on 2026-08-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0022_alter_rolemoduleaccess_module'),
        ('customers', '0019_segmentationconfig'),
        ('catalog', '0034_category_parent_itemtag_item_tags'),
        ('pos_orders', '0009_alter_softechsalesorder_channel'),
        ('branches', '0007_backfill_branch_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم العرض')),
                ('name_ar', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالعربية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('offer_type', models.CharField(choices=[('percent', 'خصم نسبة مئوية'), ('fixed', 'خصم مبلغ ثابت'), ('bxgy', 'اشترِ X واحصل على Y'), ('qty_tier', 'خصم متدرّج بالكمية')], db_index=True, max_length=12)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'فعّال'), ('paused', 'موقوف'), ('expired', 'منتهي')], db_index=True, default='draft', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='نسبة % (لخصم النسبة) أو مبلغ ثابت', max_digits=10, verbose_name='القيمة')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='سقف اختياري لخصم النسبة المئوية', max_digits=10, null=True, verbose_name='حد أقصى للخصم')),
                ('buy_qty', models.PositiveSmallIntegerField(default=0, verbose_name='اشترِ (كمية)')),
                ('get_qty', models.PositiveSmallIntegerField(default=0, verbose_name='احصل على (كمية)')),
                ('get_discount_percent', models.DecimalField(decimal_places=2, default=100, help_text='100 = مجاناً', max_digits=5, verbose_name='نسبة خصم المجاني %')),
                ('qty_tiers', models.JSONField(blank=True, default=list, verbose_name='شرائح الكمية')),
                ('target_all', models.BooleanField(default=False, verbose_name='كل الأصناف')),
                ('classification_filters', models.JSONField(blank=True, default=dict)),
                ('segments', models.JSONField(blank=True, default=list, help_text='قائمة مفاتيح الشرائح، مثال: ["vip","loyal"] — فارغ = الكل', verbose_name='شرائح العملاء')),
                ('channels', models.JSONField(blank=True, default=list, help_text='قنوات البيع، مثال: ["cash","home_delivery"] — فارغ = الكل')),
                ('min_basket_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='أقل إجمالي للسلة')),
                ('min_qty', models.PositiveSmallIntegerField(default=0, verbose_name='أقل كمية مؤهِّلة')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='يبدأ')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي')),
                ('stackable', models.BooleanField(default=False, help_text='إن كان قابلاً للدمج يُجمع مع عروض أخرى قابلة للدمج؛ وإلا فهو حصري.', verbose_name='قابل للدمج')),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='الأعلى يفوز عند تعارض العروض الحصرية', verbose_name='الأولوية')),
                ('is_clearance', models.BooleanField(default=False, verbose_name='تصفية (قرب انتهاء صلاحية)')),
                ('requires_approval', models.BooleanField(default=False, help_text='يتجاوز حد الهامش — يحتاج اعتماد مشرف قبل التنفيذ (مرحلة لاحقة).', verbose_name='يتطلب موافقة')),
                ('max_uses_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد الاستخدام الكلي')),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد الاستخدام لكل عميل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='offers', to='branches.branch')),
                ('categories', models.ManyToManyField(blank=True, related_name='offers', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_created', to='users.staffprofile')),
                ('items', models.ManyToManyField(blank=True, related_name='offers', to='catalog.item')),
                ('tags', models.ManyToManyField(blank=True, related_name='offers', to='catalog.itemtag')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfferApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('was_applied', models.BooleanField(db_index=True, default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_applications', to='customers.customer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='offers.offer')),
                ('pos_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_applications', to='pos_orders.softechsalesorder')),
            ],
            options={
                'verbose_name': 'تطبيق عرض',
                'verbose_name_plural': 'تطبيقات العروض',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'offer_type'], name='offers_offe_status_b5ccce_idx'),
        ),
    ]
