# Generated by Django 4.2.13 on 2026-08-24 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_rolemoduleaccess_module'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_margin_percent', models.DecimalField(decimal_places=2, default=10, help_text='هامش على صافي البيع = (الصافي − التكلفة) ÷ الصافي × 100', max_digits=5, verbose_name='أقل هامش ربح مسموح %')),
                ('enforce', models.BooleanField(default=True, help_text='عند الإيقاف يُحسب الهامش للعرض فقط دون اشتراط موافقة.', verbose_name='تفعيل الحماية')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile')),
            ],
            options={
                'verbose_name': 'إعدادات حماية الهامش',
                'verbose_name_plural': 'إعدادات حماية الهامش',
            },
        ),
    ]
