# Generated by Django 4.2.13 on 2026-08-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_marginconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='authorization_source',
            field=models.CharField(choices=[('item_card', 'من كارت الصنف (posdiscp)'), ('offer', 'من العرض (يتطلب موافقة)')], db_index=True, default='item_card', max_length=10, verbose_name='مصدر قيمة الخصم'),
        ),
        migrations.AddField(
            model_name='offer',
            name='bxgy_scope',
            field=models.CharField(choices=[('group_cheapest', 'الأقل سعرًا في المجموعة'), ('same_item', 'نفس الصنف')], default='group_cheapest', max_length=15, verbose_name='نطاق اشترِ واحصل'),
        ),
    ]
