# Generated by Django 4.2.13 on 2026-08-25 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_segmentationconfig'),
        ('catalog', '0034_category_parent_itemtag_item_tags'),
        ('branches', '0007_backfill_branch_kind'),
        ('offers', '0003_offer_authorization_source_offer_bxgy_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualOfferMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(choices=[('exact_offer', 'مطابقة عرض معرّف'), ('bxgy_cheapest', 'نمط 1+1 / 1+½ (الأقل سعرًا)'), ('unmapped_discount', 'خصم غير مرتبط بعرض')], db_index=True, max_length=20)),
                ('confidence', models.CharField(choices=[('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'منخفضة')], db_index=True, default='low', max_length=6)),
                ('disc_pct', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_offer_matches', to='catalog.item')),
                ('matched_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_matches', to='offers.offer')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_offer_matches', to='customers.purchasehistory')),
            ],
            options={
                'verbose_name': 'كشف عرض يدوي',
                'verbose_name_plural': 'كشف العروض اليدوية',
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['pattern', 'confidence'], name='offers_manu_pattern_94bef3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='manualoffermatch',
            constraint=models.UniqueConstraint(fields=('purchase', 'item'), name='uniq_manual_match_per_line'),
        ),
    ]
