# Generated by Django 4.2.13 on 2026-08-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_alter_item_shortage_dismiss_reason'),
        ('offers', '0004_manualoffermatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='excluded_items',
            field=models.ManyToManyField(blank=True, related_name='offers_excluded', to='catalog.item', verbose_name='أصناف مستبعَدة (يدوي)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='require_stock',
            field=models.BooleanField(default=True, help_text='الافتراضي: لا يُطبَّق العرض على صنف بلا رصيد بالفرع. أوقفه للتجاوز.', verbose_name='يشترط توفر رصيد'),
        ),
        migrations.AddField(
            model_name='offer',
            name='target_spec',
            field=models.JSONField(blank=True, default=dict, verbose_name='محدِّد الأصناف المرن'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='offers', to='catalog.item', verbose_name='أصناف مضمّنة (يدوي)'),
        ),
    ]
