# Generated by Django 4.2.13 on 2026-08-29 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_alter_item_shortage_dismiss_reason'),
        ('offers', '0005_offer_excluded_items_offer_require_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bundle_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر الباقة'),
        ),
        migrations.AddField(
            model_name='offer',
            name='gift_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_gifts', to='catalog.item', verbose_name='صنف الهدية'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('percent', 'خصم نسبة مئوية'), ('fixed', 'خصم مبلغ ثابت'), ('bxgy', 'اشترِ X واحصل على Y'), ('qty_tier', 'خصم متدرّج بالكمية'), ('gift', 'صنف هدية عند الشراء'), ('spend_threshold', 'مكافأة عند تجاوز مبلغ'), ('bundle', 'باقة بسعر ثابت'), ('mix_match', 'اختر أي N من مجموعة')], db_index=True, max_length=16),
        ),
    ]
