# Generated by Django 4.2.13 on 2026-06-01 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_db_connection'),
        ('delivery', '0004_delivery_fix_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAreaFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='المحافظة')),
                ('area', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='المنطقة / الحي')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='رسوم التوصيل (ج.م)')),
                ('free_above', models.DecimalField(decimal_places=2, default=0, help_text='0 = لا يوجد حد للتوصيل المجاني', max_digits=10, verbose_name='توصيل مجاني فوق (ج.م)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعَّل')),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رسوم توصيل منطقة',
                'verbose_name_plural': 'رسوم توصيل المناطق',
                'ordering': ['branch', 'governorate', 'area'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryCSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], null=True, verbose_name='التقييم (1-5)')),
                ('feedback', models.TextField(blank=True, verbose_name='تعليق العميل')),
                ('channel', models.CharField(choices=[('whatsapp', '💬 واتساب'), ('manual', '👤 يدوي'), ('app', '📱 تطبيق')], default='whatsapp', max_length=10, verbose_name='قناة التقييم')),
                ('wa_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت إرسال واتساب')),
                ('wa_sent', models.BooleanField(default=False, verbose_name='أُرسل واتساب')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تقييم عميل (توصيل)',
                'verbose_name_plural': 'تقييمات العملاء (توصيل)',
            },
        ),
        migrations.AlterModelOptions(
            name='deliveryorder',
            options={'ordering': ['-ordered_at'], 'verbose_name': 'طلب توصيل', 'verbose_name_plural': 'طلبات التوصيل'},
        ),
        migrations.RenameIndex(
            model_name='customerlocation',
            new_name='delivery_cu_custome_78ebfa_idx',
            old_name='del_loc_customer_default',
        ),
        migrations.RenameIndex(
            model_name='deliverydriver',
            new_name='delivery_de_status_c1a4ec_idx',
            old_name='del_driver_status_branch',
        ),
        migrations.RenameIndex(
            model_name='deliveryorder',
            new_name='del_order_status_branch_v2',
            old_name='del_order_status_branch',
        ),
        migrations.RenameIndex(
            model_name='deliveryorder',
            new_name='del_order_ordered_at_v2',
            old_name='del_order_ordered_at',
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='branches.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الخروج'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='ordered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='وقت الطلب'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='softech_branch_code',
            field=models.CharField(blank=True, help_text='piccrmorders.branchcode — الفرع المُنفِّذ للطلب', max_length=10, verbose_name='كود فرع التنفيذ (SOFTECH)'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='softech_crm_branch',
            field=models.CharField(blank=True, help_text='piccrmorders.crmbranchcode — دائماً 100 للكول سنتر', max_length=10, verbose_name='فرع CRM (SOFTECH)'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='softech_doc_ref',
            field=models.CharField(blank=True, db_index=True, help_text='piccrmorders.docnumber — رقم الفاتورة بعد الصرف', max_length=100, verbose_name='مرجع فاتورة SOFTECH'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='softech_order_status',
            field=models.SmallIntegerField(blank=True, help_text='piccrmorders.orderstatus — الحالة المصدر في SOFTECH', null=True, verbose_name='حالة SOFTECH الخام'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='softech_order_usercode',
            field=models.CharField(blank=True, help_text='piccrmorders.orderusercode — موظف الكول سنتر', max_length=10, verbose_name='كود موظف CRM'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي قيمة الأصناف'),
        ),
        migrations.AddField(
            model_name='deliverycsat',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='csat', to='delivery.deliveryorder', verbose_name='الطلب'),
        ),
        migrations.AddField(
            model_name='deliveryareafee',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_fees', to='branches.branch', verbose_name='الفرع'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryareafee',
            unique_together={('branch', 'governorate', 'area')},
        ),
    ]
