# Generated by Django 4.2.13 on 2026-06-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_delivery_area_fee_csat'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='softech_doc_date5',
            field=models.DateField(blank=True, help_text='piccrmorders.docdate5 — تاريخ مستند SOFTECH', null=True, verbose_name='تاريخ مستند التجهيز'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='softech_doc_number5',
            field=models.IntegerField(blank=True, db_index=True, help_text='piccrmorders.docnumber5 — المرجع الأساسي في SOFTECH للطلب المعلَّق', null=True, verbose_name='رقم مستند التجهيز (SOFTECH)'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='softech_doc_ref',
            field=models.CharField(blank=True, db_index=True, help_text='piccrmorders.docnumber — رقم الفاتورة بعد الصرف (0 = معلَّق)', max_length=100, verbose_name='رقم الفاتورة النهائية (SOFTECH)'),
        ),
    ]
