# Generated by Django 4.2.13 on 2026-06-14 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0004_branch_db_connection'),
        ('delivery', '0006_deliveryorder_softech_doc_date5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='pod_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='pod_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='pod_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='ملاحظة التسليم'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='pod_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_pod/%Y/%m/', verbose_name='صورة إثبات التسليم'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='pod_recipient_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='المستلِم'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='route_sequence',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ترتيب التسليم'),
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('planned', 'مُخطّط 📝'), ('dispatched', 'في الطريق 🚚'), ('completed', 'مكتمل ✅'), ('cancelled', 'ملغى 🚫')], db_index=True, default='planned', max_length=12, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_routes', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_routes', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='delivery.deliverydriver', verbose_name='السائق')),
            ],
            options={
                'verbose_name': 'مسار توصيل',
                'verbose_name_plural': 'مسارات التوصيل',
                'ordering': ['-route_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.deliveryroute', verbose_name='المسار'),
        ),
    ]
