# Generated by Django 4.2.13 on 2026-06-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_deliveryorder_pod_lat_deliveryorder_pod_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='مسافة التوصيل (كم)'),
        ),
    ]
