# Generated by Django 4.2.13 on 2026-06-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_deliveryorder_delivery_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='pod_backfilled',
            field=models.BooleanField(default=False, verbose_name='إدخال يدوي (تقديري)'),
        ),
    ]
