# Generated by Django 4.2.13 on 2026-05-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_experience', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productavailabilitycache',
            new_name='product_exp_item_id_5e6d43_idx',
            old_name='pe_avail_item_status_idx',
        ),
        migrations.RenameIndex(
            model_name='productmapping',
            new_name='product_exp_barcode_1b2d3a_idx',
            old_name='pe_mapping_barcode_idx',
        ),
        migrations.RenameIndex(
            model_name='productmedia',
            new_name='product_exp_item_id_d9fdf0_idx',
            old_name='pe_media_item_primary_idx',
        ),
        migrations.RenameIndex(
            model_name='productmedia',
            new_name='product_exp_item_id_fae63f_idx',
            old_name='pe_media_item_approved_idx',
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='pack_size_label',
            field=models.CharField(blank=True, help_text='مثال: 30 قرص, 100ml', max_length=100, verbose_name='مواصفات العبوة'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='prescription_required',
            field=models.BooleanField(blank=True, default=None, help_text='True=يحتاج, False=دون وصفة, None=غير محدد', null=True, verbose_name='يحتاج وصفة طبية'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='strength',
            field=models.CharField(blank=True, help_text='مثال: 500mg, 250mg/5ml', max_length=100, verbose_name='التركيز / القوة'),
        ),
        migrations.AlterField(
            model_name='productavailabilitycache',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='adherence_icons',
            field=models.JSONField(blank=True, default=list, help_text='[{"icon": "☀️", "label": "صباحاً", "note": "بعد الأكل"}, ...]', verbose_name='أيقونات الالتزام'),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text='[{"q": "السؤال", "a": "الإجابة"}, ...]', verbose_name='الأسئلة الشائعة'),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='instructions',
            field=models.TextField(blank=True, help_text='للإرشاد فقط — ليست وصفة طبية', verbose_name='تعليمات الاستخدام'),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='keywords',
            field=models.TextField(blank=True, help_text='مفصولة بفاصلة: بنادول, panadol, باراسيتامول', verbose_name='الكلمات المفتاحية'),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='long_description',
            field=models.TextField(blank=True, help_text='محتوى كامل — يظهر في صفحة المنتج', verbose_name='وصف تفصيلي'),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='short_description',
            field=models.TextField(blank=True, help_text='2-3 جمل — تُستخدم في بطاقات المنتج', verbose_name='وصف مختصر'),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='whatsapp_preview',
            field=models.TextField(blank=True, help_text='نص قصير للمشاركة عبر واتساب', verbose_name='معاينة واتساب'),
        ),
        migrations.AlterField(
            model_name='productexperience',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productrelation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
