# Generated by Django 4.2.13 on 2026-09-03 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0007_backfill_branch_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('pos_rx', 'روشتة (نقطة البيع)'), ('pos_voice', 'صوت (نقطة البيع)'), ('purchasing_shortage', 'نواقص السوق'), ('purchasing_invoice', 'فاتورة مورّد'), ('other', 'أخرى')], db_index=True, max_length=24)),
                ('engine', models.CharField(choices=[('gemini', 'Gemini'), ('inhouse', 'المحرك الداخلي'), ('tesseract', 'Tesseract'), ('paddle', 'PaddleOCR')], db_index=True, default='gemini', max_length=16)),
                ('media_type', models.CharField(choices=[('image', 'صورة'), ('audio', 'صوت')], default='image', max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vision/ocr/%Y/%m/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='vision/voice/%Y/%m/')),
                ('raw_readings', models.JSONField(blank=True, default=list)),
                ('confirmations', models.JSONField(blank=True, default=list)),
                ('source_ref', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='branches.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عيّنة OCR',
                'verbose_name_plural': 'عيّنات OCR',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'created_at'], name='vision_ocrs_module_b8e233_idx')],
            },
        ),
    ]
