# Generated by Django 4.2.13 on 2026-09-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrsample',
            name='engine_readings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='ocrsample',
            name='engine',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('easyocr', 'EasyOCR (داخلي)'), ('tesseract', 'Tesseract (داخلي)'), ('inhouse', 'المحرك الداخلي'), ('paddle', 'PaddleOCR')], db_index=True, default='gemini', max_length=16),
        ),
    ]
