# Generated by Django 4.2.13 on 2026-05-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_transfer_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandcalculationrun',
            name='calc_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandcalculationrun',
            name='params_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='abc_a_threshold',
            field=models.FloatField(default=70.0, help_text='Cumulative % of network value at which A ends and B begins (default 70)', verbose_name='حد فئة A (%)'),
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='abc_b_threshold',
            field=models.FloatField(default=90.0, help_text='Cumulative % of network value at which B ends and C begins (default 90)', verbose_name='حد فئة B (%)'),
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='weight_30d',
            field=models.FloatField(default=0.5, help_text='Weight for the 30-day window in the weighted monthly average (default 0.5)', verbose_name='وزن معدل 30 يوم'),
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='weight_365d',
            field=models.FloatField(default=0.2, help_text='Weight for the 365-day window in the weighted monthly average (default 0.2)', verbose_name='وزن معدل 365 يوم'),
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='weight_90d',
            field=models.FloatField(default=0.3, help_text='Weight for the 90-day window in the weighted monthly average (default 0.3)', verbose_name='وزن معدل 90 يوم'),
        ),
        migrations.AlterField(
            model_name='itemdemandaggregated',
            name='cumulative_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='itemdemandaggregated',
            name='total_current_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='itemdemandaggregated',
            name='total_gap',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='itemdemandaggregated',
            name='total_monthly_avg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemdemandaggregated',
            name='total_monthly_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='abc_class',
            field=models.CharField(choices=[('A', 'A — الأكثر قيمةً (أعلى 70% من الإيرادات)'), ('B', 'B — متوسط القيمة (70–90%)'), ('C', 'C — أقل قيمةً (90–100%)'), ('X', 'X — لا مبيعات خلال السنة')], db_index=True, default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='calc_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='coverage_months',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='معامل التغطية بالشهور'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الرصيد الحالي'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='gap',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الفرق مطلوب/راكد (يمكن أن يكون سالباً)'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='last_sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='monthly_avg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='المتوسط الشهري الموزون (3 معدلات)'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='pack_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='priority',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='معامل أولوية الطلب = (1 − تغطية) × فجوة'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='qty_30d',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='qty_365d',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='qty_90d',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='rate_30d',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='معدل البيع الشهري (30 يوم) = qty_30d'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='rate_365d',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='معدل البيع الشهري (365 يوم) = qty_365d / 12'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='rate_90d',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='معدل البيع الشهري (90 يوم) = qty_90d / 3'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='safety_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='كمية الأمان (MinRequired)'),
        ),
        migrations.AlterField(
            model_name='transferrecommendation',
            name='abc_class',
            field=models.CharField(choices=[('A', 'A — الأكثر قيمةً (أعلى 70% من الإيرادات)'), ('B', 'B — متوسط القيمة (70–90%)'), ('C', 'C — أقل قيمةً (90–100%)'), ('X', 'X — لا مبيعات خلال السنة')], db_index=True, default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='transferrecommendation',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='القيمة التقديرية = الكمية × السعر'),
        ),
        migrations.AlterField(
            model_name='transferrecommendation',
            name='from_safety',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='كمية الأمان (فرع المُرسِل)'),
        ),
        migrations.AlterField(
            model_name='transferrecommendation',
            name='from_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='رصيد الفرع المُرسِل'),
        ),
        migrations.AlterField(
            model_name='transferrecommendation',
            name='from_surplus',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الفائض المتاح = رصيد − أمان'),
        ),
        migrations.AlterField(
            model_name='transferrecommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transferrecommendation',
            name='priority_score',
            field=models.FloatField(default=0, verbose_name='درجة الأولوية (من فرع الاستلام)'),
        ),
        migrations.AlterField(
            model_name='transferrecommendation',
            name='to_gap',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الفجوة في فرع الاستلام'),
        ),
        migrations.AlterField(
            model_name='transferrecommendation',
            name='to_priority',
            field=models.FloatField(default=0, verbose_name='أولوية فرع الاستلام'),
        ),
        migrations.AlterField(
            model_name='transferrecommendationrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
