# Generated by Django 4.2.13 on 2026-05-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0009_engineconfig_ss_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineconfig',
            name='ss_high_threshold',
            field=models.FloatField(default=2.0, help_text='monthly_avg >= this → safety = ceil(avg × multiplier). Default 2.0.', verbose_name='حد الطلب العالي (وحدة/شهر)'),
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='ss_multiplier',
            field=models.FloatField(default=1.0, help_text='Multiplier applied to monthly_avg before the tier lookup for high-demand items. Default 1.0 = ceil(monthly_avg). 1.5 = ceil(monthly_avg × 1.5). Range [0.5, 3.0].', verbose_name='معامل كمية الأمان (مبيعات > حد عالي)'),
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='ss_tier_low',
            field=models.FloatField(default=1.0, help_text='Fixed safety stock for items with monthly_avg in [0.16, 0.5). Default 1.', verbose_name='كمية أمان فئة منخفضة (0.16 – 0.5)'),
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='ss_tier_mid',
            field=models.FloatField(default=2.0, help_text='Fixed safety stock for items with monthly_avg in [0.5, high_threshold). Default 2.', verbose_name='كمية أمان فئة متوسطة (0.5 – حد عالي)'),
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='ss_tier_vlow',
            field=models.FloatField(default=0.5, help_text='Fixed safety stock for items with monthly_avg in [0.016, 0.16). Default 0.5.', verbose_name='كمية أمان فئة نادرة (0.016 – 0.16)'),
        ),
    ]
