# Generated by Django 4.2.13 on 2026-05-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0013_engineconfig_lost_sales_params'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='itemdemandmetrics',
            name='purch_metrics_run_root',
        ),
        migrations.RemoveIndex(
            model_name='itemdemandmetrics',
            name='purch_metrics_lost_rev',
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='ls_bottleneck_days',
            field=models.FloatField(default=7.0, help_text='Items with coverage_days (current_stock / daily_demand) below this threshold while still in stock are flagged as "bottleneck" days. Default 7 days (1 week lead-time proxy). Range [1, 30].', verbose_name='أيام تغطية حد الاختناق'),
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='ls_bulk_sale_coverage_pct',
            field=models.FloatField(default=0.85, help_text='If actual qty sold in 30d ≥ monthly_avg × this value, the item is treated as "demand fulfilled in bulk" and stockout_days = 0. Prevents false stockouts for items sold in large one-off transactions (e.g. hospitals, institutional orders). Default 0.85 = 85%. Range [0.5, 1.5].', verbose_name='نسبة تغطية المبيعات الكبيرة (bulk sale)'),
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='ls_forecast_spike_ratio',
            field=models.FloatField(default=1.35, help_text='If rate_30d > rate_365d × this value, root cause is classified as "forecast" (unexpected demand spike). Default 1.35 = 35%% above annual rate. Range [1.1, 3.0].', verbose_name='معامل ارتفاع الطلب (توقعات)'),
        ),
        migrations.AlterField(
            model_name='engineconfig',
            name='ls_min_daily_demand',
            field=models.FloatField(default=0.03, help_text='Items whose daily_demand (monthly_avg / 30) is below this value are excluded from stockout counting — too slow-moving to detect gaps reliably. Default 0.03 ≈ 1 sale per ~33 days. Range [0.01, 0.5].', verbose_name='الحد الأدنى للطلب اليومي (مبيعات ضائعة)'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='availability_rate_30d',
            field=models.FloatField(default=100.0, help_text='(30 - stockout_days) / 30 × 100', verbose_name='معدل التوفر (30 يوم) %'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='bottleneck_days_30d',
            field=models.PositiveSmallIntegerField(default=0, help_text='Days where stock > 0 but coverage_days < lead_time threshold (7d default)', verbose_name='أيام الاختناق (30 يوم)'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='coverage_days',
            field=models.FloatField(blank=True, help_text='current_stock ÷ (monthly_avg / 30) — None when monthly_avg = 0', null=True, verbose_name='أيام التغطية (من اليوم)'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='lost_margin_30d',
            field=models.DecimalField(decimal_places=2, default=0, help_text='lost_revenue × std_gross_margin_pct', max_digits=18, verbose_name='هامش الربح الضائع (30 يوم) ج.م'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='lost_qty_30d',
            field=models.DecimalField(decimal_places=3, default=0, help_text='stockout_days × daily_demand_rate', max_digits=14, verbose_name='الكمية الضائعة (30 يوم)'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='lost_revenue_30d',
            field=models.DecimalField(decimal_places=2, default=0, help_text='lost_qty × pack_price', max_digits=18, verbose_name='الإيراد الضائع (30 يوم) ج.م'),
        ),
        migrations.AlterField(
            model_name='itemdemandmetrics',
            name='stockout_days_30d',
            field=models.PositiveSmallIntegerField(default=0, help_text='Estimated days with zero stock in the last 30-day window', verbose_name='أيام النفاد (30 يوم)'),
        ),
        migrations.AlterField(
            model_name='lostsalesrun',
            name='branch_item_pairs',
            field=models.PositiveIntegerField(default=0, help_text='Total (item, branch) rows processed'),
        ),
        migrations.AlterField(
            model_name='lostsalesrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lostsalesrun',
            name='items_affected',
            field=models.PositiveIntegerField(default=0, help_text='Items with stockout_days_30d > 0'),
        ),
        migrations.AlterField(
            model_name='lostsalesrun',
            name='total_lost_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='إجمالي الهامش الضائع (30 يوم) ج.م'),
        ),
        migrations.AlterField(
            model_name='lostsalesrun',
            name='total_lost_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='إجمالي الإيراد الضائع (30 يوم) ج.م'),
        ),
    ]
