# Generated by Django 4.2.13 on 2026-06-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0015_forecast_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdemandmetrics',
            name='demand_pattern',
        ),
        migrations.RemoveField(
            model_name='itemdemandmetrics',
            name='expected_expiry_risk_value',
        ),
        migrations.RemoveField(
            model_name='itemdemandmetrics',
            name='expected_stockout_date',
        ),
        migrations.RemoveField(
            model_name='itemdemandmetrics',
            name='forecast_confidence',
        ),
        migrations.RemoveField(
            model_name='itemdemandmetrics',
            name='forecast_next_30d',
        ),
        migrations.RemoveField(
            model_name='itemdemandmetrics',
            name='forecast_next_90d',
        ),
        migrations.RemoveField(
            model_name='itemdemandmetrics',
            name='seasonal_index',
        ),
        migrations.RemoveField(
            model_name='itemdemandmetrics',
            name='yoy_growth_rate',
        ),
    ]
