# Generated by Django 4.2.13 on 2026-08-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0022_run_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierLeadTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='كود المورد')),
                ('supplier_name', models.CharField(blank=True, max_length=150)),
                ('lead_time_days', models.FloatField(verbose_name='مهلة التوريد (أيام)')),
                ('sample_count', models.PositiveIntegerField(default=0, verbose_name='عدد العينات')),
                ('method', models.CharField(choices=[('order_to_receive', 'أمر → استلام'), ('receipt_interval', 'فترة بين التوريدات'), ('manual', 'يدوى')], default='manual', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مهلة توريد المورد',
                'verbose_name_plural': 'مهل توريد الموردين',
                'ordering': ['supplier_code'],
            },
        ),
    ]
