# Generated by Django 4.2.13 on 2026-08-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_item_shortage_dismiss_note_and_more'),
        ('purchasing', '0023_supplierleadtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('n_candidates', models.IntegerField(default=0)),
                ('n_confirmed', models.IntegerField(default=0)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shortage_snapshot', to='purchasing.demandcalculationrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortageObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(blank=True, default='', max_length=20)),
                ('coverage', models.FloatField(default=0.0)),
                ('suppression', models.FloatField(default=0.0)),
                ('annual_qty', models.FloatField(default=0.0)),
                ('is_candidate', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('healthy', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortage_observations', to='catalog.item')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='purchasing.shortagesnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'item'], name='purchasing__snapsho_41fac9_idx'), models.Index(fields=['item', 'id'], name='purchasing__item_id_fc63aa_idx')],
            },
        ),
    ]
