# Generated by Django 4.2.13 on 2026-09-15 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_backfill_branch_kind'),
        ('catalog', '0038_item_is_spike_item_spike_confirmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchasing', '0024_shortagesnapshot_shortageobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRatePush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'مقترح'), ('approved', 'معتمد'), ('executed', 'مُنفّذ'), ('failed', 'فشل'), ('cancelled', 'ملغى')], db_index=True, default='proposed', max_length=12)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('branches_count', models.PositiveIntegerField(default=0)),
                ('eligible_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('unreachable_count', models.PositiveIntegerField(default=0)),
                ('written_count', models.PositiveIntegerField(default=0)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('reverted_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_pushes_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_pushes_created', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, help_text='محرك الطلب الذي جاء منه المعدّل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_pushes', to='purchasing.demandcalculationrun')),
            ],
            options={
                'verbose_name': 'دفعة تحديث معدل الإستهلاك',
                'verbose_name_plural': 'دفعات تحديث معدل الإستهلاك',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesRatePushLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(db_index=True, max_length=20)),
                ('item_name', models.CharField(blank=True, max_length=120)),
                ('branchcode', models.CharField(max_length=10)),
                ('storecode', models.CharField(max_length=10)),
                ('old_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('new_rate', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('eligible', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('written', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_push_lines', to='branches.branch')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_push_lines', to='catalog.item')),
                ('push', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.salesratepush')),
            ],
            options={
                'indexes': [models.Index(fields=['push', 'branchcode'], name='purchasing__push_id_488af7_idx'), models.Index(fields=['itemcode', 'id'], name='purchasing__itemcod_b5d81e_idx')],
            },
        ),
    ]
