# Generated by Django 4.2.13 on 2026-09-18 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_backfill_branch_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchasing', '0025_salesratepush_salesratepushline'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsrPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchcode', models.CharField(db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('proposed', 'مقترح'), ('approved', 'معتمد'), ('pushed', 'مُرحّل'), ('failed', 'فشل'), ('cancelled', 'ملغى')], db_index=True, default='proposed', max_length=12)),
                ('isrdocnumber', models.BigIntegerField(blank=True, help_text='SOFTECH stockisrm.isrdocnumber once pushed', null=True)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('docvalue', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('lines_snapshot', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('readback', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isr_pushes_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isr_pushes', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isr_pushes_created', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isr_pushes', to='purchasing.demandcalculationrun')),
            ],
            options={
                'verbose_name': 'طلب توريد مقترح',
                'verbose_name_plural': 'طلبات التوريد المقترحة',
                'ordering': ['-created_at'],
            },
        ),
    ]
