# Generated by Django 4.2.13 on 2026-09-19 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0026_isrpush'),
    ]

    operations = [
        migrations.AddField(
            model_name='isrpush',
            name='dest_branchcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='isrpush',
            name='kind',
            field=models.CharField(choices=[('self', 'ذاتي'), ('hq_to_branch', 'من الرئيسي إلى فرع'), ('branch_to_hq', 'من فرع إلى الرئيسي')], db_index=True, default='self', max_length=16),
        ),
        migrations.AddField(
            model_name='isrpush',
            name='linked_push',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='purchasing.isrpush'),
        ),
    ]
