# Generated by Django 4.2.13 on 2026-09-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0027_isrpush_dest_branchcode_isrpush_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesratepush',
            name='method',
            field=models.CharField(choices=[('pivot', 'المحورية (Pivot)'), ('advanced', 'المتقدمة (Croston)')], db_index=True, default='pivot', max_length=12),
        ),
        migrations.AddField(
            model_name='salesratepush',
            name='method_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
