# Generated by Django 4.2.13 on 2026-09-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0028_salesratepush_method_salesratepush_method_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='isrpush',
            name='coverage_months',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
