# Generated by Django 4.2.13 on 2026-09-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0029_isrpush_coverage_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesratepush',
            name='target',
            field=models.CharField(choices=[('node', 'خادم الفرع'), ('hq', 'نسخة الرئيسي'), ('both', 'الاثنان')], db_index=True, default='node', max_length=8),
        ),
    ]
