# Generated by Django 4.2.13 on 2026-09-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0030_salesratepush_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesratepushline',
            name='old_rate_hq',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='salesratepush',
            name='target',
            field=models.CharField(choices=[('node', 'خادم الفرع'), ('hq', 'نسخة الرئيسي'), ('both', 'الاثنان')], db_index=True, default='both', max_length=8),
        ),
    ]
