# Generated by Django 4.2.13 on 2026-09-28 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchasing', '0031_salesratepushline_old_rate_hq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'تم'), ('partial', 'جزئي'), ('dry_run', 'معاينة')], db_index=True, max_length=10)),
                ('trigger', models.CharField(choices=[('schedule', 'تلقائي'), ('manual', 'يدوي')], default='manual', max_length=10)),
                ('months', models.FloatField()),
                ('target', models.CharField(max_length=8)),
                ('filled_count', models.PositiveIntegerField(default=0)),
                ('refreshed_count', models.PositiveIntegerField(default=0)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('not_confirmed_count', models.PositiveIntegerField(default=0)),
                ('unreachable_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_topups', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_topups', to='purchasing.demandcalculationrun')),
            ],
            options={
                'verbose_name': 'استكمال تغطية تلقائي',
                'verbose_name_plural': 'استكمالات التغطية',
                'ordering': ['-created_at'],
            },
        ),
    ]
