# Generated by Django 4.2.13 on 2026-10-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0032_coveragetopup'),
    ]

    operations = [
        migrations.AddField(
            model_name='isrpush',
            name='origin_isr',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='SOFTECH isrdocnumber of the branch request this return serves', null=True),
        ),
        migrations.AddConstraint(
            model_name='isrpush',
            constraint=models.UniqueConstraint(condition=models.Q(('origin_isr__isnull', False), ('status__in', ['proposed', 'approved', 'pushed'])), fields=('origin_isr', 'branchcode'), name='isrpush_one_live_return_per_origin_donor'),
        ),
    ]
