# Generated by Django 4.2.13 on 2026-10-04 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0005_branch_requests'),
        ('purchasing', '0033_isrpush_origin_isr'),
    ]

    operations = [
        migrations.AddField(
            model_name='isrpush',
            name='origin_donor',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='isrpush',
            name='origin_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isr_pushes', to='supply.branchrequest'),
        ),
        migrations.AddConstraint(
            model_name='isrpush',
            constraint=models.UniqueConstraint(condition=models.Q(('origin_request__isnull', False), ('status__in', ['proposed', 'approved', 'pushed'])), fields=('origin_request', 'origin_donor', 'kind'), name='isrpush_one_live_leg_per_request_donor'),
        ),
    ]
