# Generated by Django 4.2.13 on 2026-10-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0034_isrpush_origin_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesratepush',
            name='target',
            field=models.CharField(choices=[('node', 'سيرفر الفرع'), ('hq', 'نسخة الرئيسي'), ('both', 'الاثنان')], db_index=True, default='both', max_length=8),
        ),
    ]
