# Generated by Django 4.2.13 on 2026-04-25 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار — انتظار مخزون'), ('available', 'المخزون متاح — اتصل بالعميل'), ('contacted', 'تم التواصل — العميل على علم'), ('confirmed', 'مؤكد — العميل قادم'), ('fulfilled', 'تم التسليم — الصنف صُرف'), ('cancelled', 'ملغي'), ('expired', 'منتهي — لا استجابة')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'عادي'), ('urgent', 'عاجل'), ('chronic', 'مريض مزمن')], default='normal', max_length=20)),
                ('contact_phone', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('softech_reserve_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reservations', to='users.staffprofile')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to='users.staffprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='customers.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffprofile')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'branch'], name='reservation_status_dd306e_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['follow_up_date'], name='reservation_follow__be16fb_idx'),
        ),
    ]
