# Generated by Django 4.2.13 on 2026-04-26 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_staffprofile_role'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call_answered', '📞 اتصل — رد العميل'), ('call_no_answer', '📵 اتصل — لم يرد'), ('call_busy', '🔴 اتصل — المشغول'), ('call_wrong_number', '❌ رقم خاطئ'), ('call_callback_requested', '🔁 العميل طلب معاودة الاتصال'), ('customer_coming_today', '✅ العميل قادم اليوم'), ('customer_coming_date', '📅 العميل حدد موعد'), ('customer_not_interested', '🚫 العميل غير مهتم'), ('customer_wants_alternative', '🔄 العميل يريد بديل'), ('item_ordered_supplier', '🏭 تم طلب الصنف من المورد'), ('item_expected_date', '📦 تاريخ وصول الصنف متوقع'), ('item_arrived', '✅ وصل الصنف'), ('status_updated', '🔄 تم تحديث الحالة'), ('note_added', '📝 ملاحظة'), ('follow_up_set', '📅 تم تحديد موعد متابعة')], max_length=40)),
                ('note', models.TextField(blank=True)),
                ('callback_datetime', models.DateTimeField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='users.staffprofile')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['reservation', 'logged_at'], name='reservation_reserva_911000_idx')],
            },
        ),
    ]
