# Generated by Django 4.2.13 on 2026-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reservations/%Y/%m/'),
        ),
    ]
