# Generated by Django 4.2.13 on 2026-05-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_add_status_priority_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', '-created_at'], name='reservation_status_3633ee_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['branch', '-created_at'], name='reservation_branch__080d2f_idx'),
        ),
    ]
