# Generated by Django 4.2.13 on 2026-05-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_reservationactivity_voice_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationactivity',
            name='voice_note',
            field=models.FileField(blank=True, help_text='ملاحظة صوتية (WebRTC أو ملف صوتي)', null=True, upload_to='reservation_voices/%Y/%m/'),
        ),
    ]
