# Generated by Django 4.2.13 on 2026-05-14 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_erpuser_user_group'),
        ('reservations', '0014_reservationactivity_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='fulfillment_method',
            field=models.CharField(blank=True, choices=[('pickup', 'استلام من الفرع'), ('delivery', 'توصيل')], max_length=10, verbose_name='طريقة التسليم'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='order_source',
            field=models.CharField(blank=True, choices=[('cc_whatsapp', 'كول سنتر — واتساب'), ('cc_call', 'كول سنتر — مكالمة'), ('branch_whatsapp', 'الفرع — واتساب'), ('branch_call', 'الفرع — مكالمة'), ('online', 'طلب إلكتروني')], max_length=20, verbose_name='مصدر الطلب'),
        ),
        migrations.CreateModel(
            name='ReservationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reservations/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservations.reservation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reservation_images', to='users.staffprofile')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
