# Generated by Django 4.2.13 on 2026-05-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_reservation_erp_receipt_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='order_source',
            field=models.CharField(blank=True, choices=[('cc_whatsapp', 'كول سنتر — واتساب'), ('cc_call', 'كول سنتر — مكالمة'), ('branch_whatsapp', 'الفرع — واتساب'), ('branch_call', 'الفرع — مكالمة'), ('online', 'طلب إلكتروني'), ('walk_in', 'زيارة مباشرة')], max_length=20, verbose_name='مصدر الطلب'),
        ),
    ]
