# Generated by Django 4.2.13 on 2026-06-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_channel_softech_aligned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='contract_subtype',
            field=models.CharField(blank=True, choices=[('taakodat', 'تعاقدات / آجل'), ('loyal_customer', 'عميل دائم'), ('health_insurance', 'تأمين صحي'), ('compensation', 'تعويضات الشركات'), ('electronic', 'إيصال إلكتروني بالبطاقة الشخصية'), ('vip', 'Vip'), ('camac', 'تعاقد - سداد أجل - خصم يدوى'), ('clearing', 'مقاصات'), ('donation', 'تبرعات'), ('internal', 'موظفين شركة الرزيقى')], help_text='يُملأ فقط عند اختيار بيع بالكنتراكت', max_length=30, verbose_name='نوع العميل / قناة الكنتراكت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='priority',
            field=models.CharField(choices=[('normal', 'عادي'), ('urgent', 'عاجل'), ('chronic', 'مريض مزمن'), ('high', 'مهم')], db_index=True, default='normal', max_length=20),
        ),
    ]
