# Generated by Django 4.2.13 on 2026-05-29 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0021_itembarcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('source_type', models.CharField(choices=[('cache', 'كاش داخلي'), ('openfoodfacts', 'Open Food Facts'), ('openbeauty', 'Open Beauty Facts'), ('drugs_com', 'drugs.com'), ('rxlist', 'RxList'), ('manufacturer', 'موقع المورد'), ('pharmacy_site', 'موقع صيدلية'), ('duckduckgo', 'DuckDuckGo Images'), ('google', 'Google Images'), ('bing', 'Bing Images'), ('manual', 'رفع يدوي'), ('ai_generated', 'توليد AI')], max_length=20)),
                ('base_url', models.URLField(blank=True, max_length=500)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('rate_limit_rpm', models.PositiveSmallIntegerField(default=20)),
                ('requires_js', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('successful_hits', models.PositiveIntegerField(default=0)),
                ('avg_quality_score', models.FloatField(default=0.0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'مصدر صور',
                'verbose_name_plural': 'مصادر الصور',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ProductNormalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(blank=True, max_length=400)),
                ('normalized_name', models.CharField(blank=True, max_length=400)),
                ('search_query_en', models.CharField(blank=True, max_length=300)),
                ('search_query_ar', models.CharField(blank=True, max_length=300)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('strength', models.CharField(blank=True, max_length=50)),
                ('dosage_form', models.CharField(blank=True, max_length=60)),
                ('pack_size', models.CharField(blank=True, max_length=50)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('parse_confidence', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalization', to='catalog.item')),
            ],
            options={
                'verbose_name': 'تطبيع اسم المنتج',
                'verbose_name_plural': 'تطبيع أسماء المنتجات',
            },
        ),
        migrations.CreateModel(
            name='ImageSearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('running', 'جارٍ التشغيل'), ('done', 'مكتمل'), ('failed', 'فشل'), ('skipped', 'تخطي — صورة موجودة'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=12)),
                ('current_stage', models.PositiveSmallIntegerField(choices=[(1, 'المرحلة 1 — الكاش الداخلي'), (2, 'المرحلة 2 — الباركود / قواعد البيانات'), (3, 'المرحلة 3 — مواقع الموردين'), (4, 'المرحلة 4 — مواقع الصيدليات'), (5, 'المرحلة 5 — محركات البحث'), (6, 'المرحلة 6 — مراجعة بشرية')], default=1)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'منخفضة'), (2, 'عادية'), (3, 'عالية'), (4, 'عاجلة')], db_index=True, default=2)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('auto_approve_threshold', models.FloatField(default=0.85)),
                ('review_threshold', models.FloatField(default=0.5)),
                ('candidates_found', models.PositiveIntegerField(default=0)),
                ('candidates_scored', models.PositiveIntegerField(default=0)),
                ('best_score', models.FloatField(default=0.0)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_jobs', to='catalog.item')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_image_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مهمة بحث عن صورة',
                'verbose_name_plural': 'مهام البحث عن صور',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2000)),
                ('source_type', models.CharField(choices=[('cache', 'كاش داخلي'), ('openfoodfacts', 'Open Food Facts'), ('openbeauty', 'Open Beauty Facts'), ('drugs_com', 'drugs.com'), ('rxlist', 'RxList'), ('manufacturer', 'موقع المورد'), ('pharmacy_site', 'موقع صيدلية'), ('duckduckgo', 'DuckDuckGo Images'), ('google', 'Google Images'), ('bing', 'Bing Images'), ('manual', 'رفع يدوي'), ('ai_generated', 'توليد AI')], default='duckduckgo', max_length=20)),
                ('source_page_url', models.URLField(blank=True, max_length=2000)),
                ('query_used', models.CharField(blank=True, max_length=300)),
                ('local_file', models.ImageField(blank=True, null=True, upload_to='image_candidates/%Y/%m/')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('phash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('quality_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'جديد'), ('scored', 'تم التقييم'), ('auto_approved', 'موافقة تلقائية'), ('pending_review', 'قيد المراجعة'), ('approved', 'موافق عليها'), ('rejected', 'مرفوضة'), ('error', 'خطأ في التنزيل')], db_index=True, default='new', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('scraper_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_candidates', to='catalog.item')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='images.imagesearchjob')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'صورة مرشحة',
                'verbose_name_plural': 'صور مرشحة',
                'ordering': ['-total_score', '-quality_score'],
            },
        ),
        migrations.AddIndex(
            model_name='imagesearchjob',
            index=models.Index(fields=['status', 'priority'], name='images_imag_status_ceb2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='imagesearchjob',
            index=models.Index(fields=['item', 'status'], name='images_imag_item_id_e2c38f_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecandidate',
            index=models.Index(fields=['item', 'status'], name='images_imag_item_id_3bd620_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecandidate',
            index=models.Index(fields=['job', 'total_score'], name='images_imag_job_id_55cb95_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecandidate',
            index=models.Index(fields=['phash'], name='images_imag_phash_8b8d6b_idx'),
        ),
    ]
