# Generated by Django 4.2.13 on 2026-05-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageApprovalInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('source_type', models.CharField(max_length=20)),
                ('approved', models.PositiveIntegerField(default=0)),
                ('considered', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تعلم مصادر الصور',
                'verbose_name_plural': 'تعلم مصادر الصور',
                'ordering': ['-approved'],
                'unique_together': {('brand', 'source_type')},
            },
        ),
    ]
