# Generated by Django 4.2.13 on 2026-05-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_approval_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageapprovalinsight',
            name='avg_quality_score',
            field=models.FloatField(default=0.0),
        ),
    ]
