# Generated by Django 4.2.13 on 2026-06-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0018_drop_legacy_has_global_access'),
        ('branches', '0005_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('name_ar', models.CharField(blank=True, max_length=120, verbose_name='الاسم بالعربي')),
                ('items', models.JSONField(default=list, verbose_name='البنود')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قالب مراجعة جودة',
                'verbose_name_plural': 'قوالب مراجعة الجودة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QAInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُرسَلة')], db_index=True, default='draft', max_length=12, verbose_name='الحالة')),
                ('results', models.JSONField(default=list, verbose_name='النتائج')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='النتيجة %')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qa_inspections', to='branches.branch', verbose_name='الفرع')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_inspections', to='users.staffprofile', verbose_name='المراجِع')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='qa.qachecklisttemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'مراجعة جودة',
                'verbose_name_plural': 'مراجعات الجودة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'status'], name='qa_qainspec_branch__41489b_idx')],
            },
        ),
    ]
