# Generated by Django 4.2.13 on 2026-04-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
