# Generated by Django 4.2.13 on 2026-04-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
