# Generated by Django 4.2.13 on 2026-05-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_purchasehistory_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='docnumber',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='softech_user',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
