# Generated by Django 4.2.13 on 2026-05-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_purchasehistory_sales_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_branch_code',
            field=models.CharField(blank=True, help_text='localcustomers.orderbranchcode — default branch for delivery orders', max_length=10, verbose_name='كود فرع الطلبات الافتراضي'),
        ),
        migrations.AddField(
            model_name='customer',
            name='person_classif_label',
            field=models.CharField(blank=True, help_text='persontypesclassif.ptclassifdescr — Arabic label for ptclassifcode (= sales channel label: توصيل / كاش / تأمين صحي …)', max_length=150, verbose_name='وصف تصنيف الشخص'),
        ),
        migrations.AddField(
            model_name='customer',
            name='person_type_label',
            field=models.CharField(blank=True, help_text='persontypes.ptdescr — Arabic label for ptcode', max_length=150, verbose_name='وصف نوع الشخص'),
        ),
        migrations.AddField(
            model_name='customer',
            name='softech_global_code',
            field=models.CharField(blank=True, help_text='personsdata.personglobalcode — cross-branch global person code', max_length=50, verbose_name='الكود المركزي (personglobalcode)'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='sales_person_type',
            field=models.CharField(blank=True, db_index=True, help_text='personsdata.ptcode — person type of the linked customer', max_length=10, verbose_name='نوع شخص العميل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='softech_ptclassifcode',
            field=models.CharField(blank=True, db_index=True, help_text='personsdata.ptclassifcode — authoritative channel code (e.g. "90"=توصيل "91"=كاش "15"=تأمين). Falls back to localcustomers.branchcustclassif if personsdata row absent.', max_length=10, verbose_name='كود تصنيف الشخص'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='softech_ptcode',
            field=models.CharField(blank=True, db_index=True, help_text='personsdata.ptcode → persontypes.ptcode (e.g. "01" = عميل)', max_length=10, verbose_name='كود نوع الشخص'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='sales_channel',
            field=models.CharField(blank=True, db_index=True, help_text='personsdata.ptclassifcode — e.g. 90=توصيل 91=كاش 15=تأمين', max_length=10, verbose_name='قناة البيع'),
        ),
        # Backfill sales_person_type from the linked customer's softech_ptcode
        migrations.RunSQL(
            sql="""
                UPDATE customers_purchasehistory ph
                SET    sales_person_type = c.softech_ptcode
                FROM   customers_customer c
                WHERE  ph.customer_id = c.id
                  AND  ph.sales_person_type = ''
                  AND  c.softech_ptcode IS NOT NULL
                  AND  c.softech_ptcode != '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
