# Generated by Django 4.2.13 on 2026-05-31 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_rolemoduleaccess_role_alter_staffprofile_role'),
        ('customers', '0015_customer_segment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='churn_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='0-1: كلما ارتفعت زادت احتمالية انقطاع العميل. تُحسب يومياً.', verbose_name='درجة خطر الانقطاع'),
        ),
        migrations.AddField(
            model_name='customer',
            name='churn_segment',
            field=models.CharField(blank=True, choices=[('low', 'منخفض — عميل مستقر'), ('medium', 'متوسط — مراقبة'), ('high', 'مرتفع — تدخل مطلوب'), ('critical', 'حرج — على وشك الانقطاع')], db_index=True, max_length=10, verbose_name='شريحة الانقطاع'),
        ),
        migrations.AddField(
            model_name='customer',
            name='churn_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث لدرجة الانقطاع'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_phone',
            field=models.CharField(blank=True, db_index=True, help_text='رقم الواتساب إن اختلف عن الهاتف الأساسي', max_length=50, verbose_name='واتساب'),
        ),
        migrations.CreateModel(
            name='CustomerHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_diabetes', models.BooleanField(db_index=True, default=False)),
                ('has_hypertension', models.BooleanField(db_index=True, default=False)),
                ('has_cardiovascular', models.BooleanField(db_index=True, default=False)),
                ('has_thyroid', models.BooleanField(db_index=True, default=False)),
                ('has_cholesterol', models.BooleanField(db_index=True, default=False)),
                ('has_asthma', models.BooleanField(default=False)),
                ('has_psychiatric', models.BooleanField(default=False)),
                ('has_epilepsy', models.BooleanField(default=False)),
                ('has_osteoporosis', models.BooleanField(default=False)),
                ('has_renal', models.BooleanField(default=False)),
                ('has_oncology', models.BooleanField(default=False)),
                ('has_gerd', models.BooleanField(default=False)),
                ('has_anemia', models.BooleanField(default=False)),
                ('has_anticoagulant', models.BooleanField(default=False)),
                ('has_immunosuppressant', models.BooleanField(default=False)),
                ('has_other_chronic', models.BooleanField(default=False)),
                ('condition_confidence', models.JSONField(blank=True, default=dict, help_text='مثال: {"diabetes": 0.95, "hypertension": 0.80}', verbose_name='درجة الثقة لكل حالة')),
                ('active_medications', models.JSONField(blank=True, default=list, help_text='قائمة الأدوية المزمنة النشطة — تُجمَع من سجل المشتريات', verbose_name='الأدوية النشطة')),
                ('pregnancy_flag', models.BooleanField(default=False, help_text='يُحدَّد يدوياً بواسطة الصيدلاني', verbose_name='حامل')),
                ('lactation_flag', models.BooleanField(default=False, verbose_name='مرضعة')),
                ('pediatric_patient', models.BooleanField(default=False, help_text='العميل يشتري لمريض طفل (لا لنفسه)', verbose_name='يشتري لطفل')),
                ('polypharmacy_flag', models.BooleanField(default=False, help_text='يأخذ أكثر من 5 أدوية متزامنة', verbose_name='أدوية متعددة (>5)')),
                ('known_allergies', models.JSONField(blank=True, default=list, verbose_name='الحساسيات المعروفة')),
                ('declared_allergies_text', models.TextField(blank=True, help_text='نص حر أدخله الصيدلاني أو العميل', verbose_name='تفاصيل الحساسية (نص حر)')),
                ('last_computed_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر حساب تلقائي')),
                ('manually_overridden', models.BooleanField(default=False, help_text='إذا True: لن يُعيد الحساب التلقائي تجاوز الحقول اليدوية', verbose_name='تم التعديل يدوياً')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='customers.customer', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_health_profiles', to='users.staffprofile', verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'ملف صحي للعميل',
                'verbose_name_plural': 'الملفات الصحية للعملاء',
                'indexes': [models.Index(fields=['has_diabetes', 'has_hypertension'], name='customers_c_has_dia_1e242c_idx'), models.Index(fields=['has_cardiovascular'], name='customers_c_has_car_14260d_idx')],
            },
        ),
    ]
