# Generated by Django 4.2.13 on 2026-07-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_add_health_profile_churn_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistoryline',
            name='bonus_qty',
            field=models.DecimalField(decimal_places=3, default=0, help_text='stktrans.bonusqty — free/bonus units', max_digits=10, verbose_name='كمية البونص'),
        ),
        migrations.AddField(
            model_name='purchasehistoryline',
            name='disc_additional_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='خصم إضافي %'),
        ),
        migrations.AddField(
            model_name='purchasehistoryline',
            name='disc_customer_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='خصم العميل %'),
        ),
        migrations.AddField(
            model_name='purchasehistoryline',
            name='disc_pharmacy_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='خصم الصيدلية %'),
        ),
        migrations.AddField(
            model_name='purchasehistoryline',
            name='disc_special_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='خصم خاص %'),
        ),
        migrations.AddField(
            model_name='purchasehistoryline',
            name='list_price',
            field=models.DecimalField(decimal_places=3, default=0, help_text='stktrans.itemsaleprice — catalog/list unit price before discount', max_digits=10, verbose_name='سعر البيع قبل الخصم'),
        ),
    ]
