# Generated by Django 4.2.13 on 2026-08-03 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_purchasehistoryline_bonus_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistoryline',
            name='bonus_qty',
        ),
    ]
