# Generated by Django 4.2.13 on 2026-08-24 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_rolemoduleaccess_module'),
        ('customers', '0018_remove_purchasehistoryline_bonus_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_ltv_threshold', models.DecimalField(decimal_places=2, default=5000, max_digits=12, verbose_name='حد LTV لكبار العملاء (VIP)')),
                ('loyal_min_purchases', models.PositiveSmallIntegerField(default=3, verbose_name='أقل عدد فواتير (٩٠ يوم) للعميل المخلص')),
                ('new_grace_days', models.PositiveSmallIntegerField(default=60, verbose_name='مهلة اعتبار العميل "جديد" (أيام)')),
                ('at_risk_min_days', models.PositiveSmallIntegerField(default=90, verbose_name='بداية "في خطر" (أيام منذ آخر زيارة)')),
                ('at_risk_max_days', models.PositiveSmallIntegerField(default=180, verbose_name='نهاية "في خطر" (أيام)')),
                ('dormant_max_days', models.PositiveSmallIntegerField(default=365, verbose_name='نهاية "نائم" — بعدها "مفقود" (أيام)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile')),
            ],
            options={
                'verbose_name': 'إعدادات تصنيف العملاء',
                'verbose_name_plural': 'إعدادات تصنيف العملاء',
            },
        ),
    ]
