# Generated by Django 4.2.13 on 2026-10-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0019_segmentationconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="points_enrolled",
            field=models.BooleanField(
                default=True,
                help_text="localcustomers.picpoints — registered in the points system",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="softech_deceased",
            field=models.BooleanField(default=False, help_text="picdied"),
        ),
        migrations.AddField(
            model_name="customer",
            name="softech_locked",
            field=models.BooleanField(
                default=False,
                help_text="piclock — owner: marks an entity account, not a person",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="softech_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="phcodestatus: '1' active · '0' file closed (blocked) · '5' deceased · '' unset",
                max_length=2,
            ),
        ),
    ]
