# Generated by Django 4.2.13 on 2026-10-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0020_softech_account_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerStatusDrift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pic", models.CharField(db_index=True, max_length=13)),
                ("node_branch", models.CharField(db_index=True, max_length=5)),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("status", "حالة الملف"),
                            ("lock", "قفل (جهة)"),
                            ("points", "نظام النقاط"),
                        ],
                        max_length=10,
                    ),
                ),
                ("hq_value", models.CharField(blank=True, max_length=5)),
                ("node_value", models.CharField(blank=True, max_length=5)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("hq_stricter", "الرئيسي أشد — الفرع ما زال يخدم العميل"),
                            ("node_stricter", "الفرع أشد من الرئيسي"),
                            ("other", "اختلاف آخر"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField()),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.AddConstraint(
            model_name="customerstatusdrift",
            constraint=models.UniqueConstraint(
                fields=("pic", "node_branch", "field"),
                name="uniq_customer_status_drift",
            ),
        ),
    ]
