# Generated by Django 4.2.13 on 2026-10-08 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_alter_rolemoduleaccess_module"),
        ("customers", "0021_customer_status_drift"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchCopyWrite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pic", models.CharField(db_index=True, max_length=13)),
                ("node_branch", models.CharField(db_index=True, max_length=5)),
                (
                    "before",
                    models.JSONField(default=dict, help_text="branch copy before"),
                ),
                (
                    "target",
                    models.JSONField(default=dict, help_text="HQ values written"),
                ),
                (
                    "after",
                    models.JSONField(default=dict, help_text="branch copy read back"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dry_run", "تجربة بدون كتابة"),
                            ("no_change", "مطابق بالفعل"),
                            ("verified", "كُتب وتم التحقق"),
                            ("conflict", "تغيّر في الفرع أثناء التنفيذ"),
                            ("failed", "فشل"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
