# Generated by Django 4.2.13 on 2026-10-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0022_branch_copy_write"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchcopywrite",
            name="status",
            field=models.CharField(
                choices=[
                    ("dry_run", "تجربة بدون كتابة"),
                    ("no_change", "مطابق بالفعل"),
                    ("verified", "كُتب وتم التحقق"),
                    ("conflict", "تغيّر في الفرع أثناء التنفيذ"),
                    ("failed", "فشل"),
                    ("skipped", "تُرك للمراجعة (النسخ يخفف القيود)"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
