# Generated by Django 4.2.13 on 2026-10-09 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_alter_rolemoduleaccess_module"),
        ("customers", "0023_branch_copy_skipped"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointsRemoval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pic", models.CharField(db_index=True, max_length=13)),
                ("flag_before", models.PositiveSmallIntegerField(null=True)),
                ("balance_before", models.IntegerField(null=True)),
                ("flag_after", models.PositiveSmallIntegerField(null=True)),
                ("balance_after", models.IntegerField(null=True)),
                ("points_cleared", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dry_run", "تجربة بدون كتابة"),
                            ("no_change", "مستبعد بالفعل"),
                            ("verified", "تم الاستبعاد والتحقق"),
                            ("conflict", "تغيّر أثناء التنفيذ"),
                            ("failed", "فشل"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
