# Generated by Django 4.2.13 on 2026-10-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0024_points_removal"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointsremoval",
            name="discount_after",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pointsremoval",
            name="discount_before",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
