# Generated by Django 4.2.13 on 2026-10-10 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_alter_rolemoduleaccess_module"),
        ("customers", "0025_points_removal_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_pic", models.CharField(max_length=13, unique=True)),
                ("main_pic", models.CharField(db_index=True, max_length=13)),
                (
                    "main_auto_pic",
                    models.CharField(
                        help_text="main chosen by the rule", max_length=13
                    ),
                ),
                ("main_swapped", models.BooleanField(default=False)),
                (
                    "cluster",
                    models.CharField(
                        db_index=True,
                        help_text="smallest code of the duplicate group",
                        max_length=20,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        choices=[
                            ("strong", "قوي — نفس الاسم ونفس العنوان"),
                            ("medium", "نفس الاسم"),
                            ("review", "اسم مشابه — للمراجعة"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("facts", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "مقترح"),
                            ("marked", "معلَّم — بانتظار الاعتماد"),
                            ("approved", "معتمد — بانتظار الدمج"),
                            ("rejected", "مرفوض"),
                            ("merged", "تم الدمج"),
                            ("failed", "فشل الدمج"),
                            ("stale", "لم يعد مكررًا"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=10,
                    ),
                ),
                ("marked_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["cluster", "old_pic"],
            },
        ),
    ]
