# Generated by Django 4.2.13 on 2026-10-10 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_alter_rolemoduleaccess_module"),
        ("customers", "0026_merge_candidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="merged_into_pic",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="B7: this duplicate code was merged into that main code (apps/customers/merge_write.py)",
                max_length=13,
            ),
        ),
        migrations.CreateModel(
            name="CustomerMergeWrite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_pic", models.CharField(db_index=True, max_length=13)),
                ("main_pic", models.CharField(db_index=True, max_length=13)),
                (
                    "before",
                    models.JSONField(default=dict, help_text="HQ old + main before"),
                ),
                (
                    "after",
                    models.JSONField(default=dict, help_text="HQ old + main read back"),
                ),
                ("points_moved", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dry_run", "تجربة بدون كتابة"),
                            ("no_change", "مدموج بالفعل"),
                            ("verified", "تم الدمج والتحقق"),
                            ("conflict", "تغيّر أثناء التنفيذ"),
                            ("failed", "فشل"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="writes",
                        to="customers.mergecandidate",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
