# Generated by Django 4.2.13 on 2026-05-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operationaltask',
            new_name='tasks_opera_status_224e4b_idx',
            old_name='tasks_oper_status_pri_idx',
        ),
        migrations.RenameIndex(
            model_name='operationaltask',
            new_name='tasks_opera_branch__673fb5_idx',
            old_name='tasks_oper_branch_sta_idx',
        ),
        migrations.RenameIndex(
            model_name='operationaltask',
            new_name='tasks_opera_assigne_cc4dad_idx',
            old_name='tasks_oper_assign_sta_idx',
        ),
        migrations.RenameIndex(
            model_name='operationaltask',
            new_name='tasks_opera_due_dat_85f2dd_idx',
            old_name='tasks_oper_due_date_idx',
        ),
        migrations.AlterField(
            model_name='operationaltask',
            name='related_model',
            field=models.CharField(blank=True, help_text='e.g. transfer, reservation, stockcount', max_length=50, verbose_name='النموذج المرتبط'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='advance_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='Create task N days before due date', verbose_name='أيام مسبقة'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='assign_to_role',
            field=models.CharField(blank=True, help_text='pharmacist, admin, etc.', max_length=30, verbose_name='يُعيَّن إلى الدور'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-31 (for monthly)', null=True, verbose_name='يوم الشهر'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0=Monday … 6=Sunday (for weekly)', null=True, verbose_name='يوم الأسبوع'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='title_template',
            field=models.CharField(help_text='Use {date} for today, {branch} for branch name', max_length=255, verbose_name='قالب العنوان'),
        ),
    ]
