# Generated by Django 4.2.13 on 2026-05-13 00:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incentivetransaction',
            new_name='incentives__program_9054fe_idx',
            old_name='incv_prog_period_idx',
        ),
        migrations.RenameIndex(
            model_name='incentivetransaction',
            new_name='incentives__user_id_a45db1_idx',
            old_name='incv_user_period_idx',
        ),
        migrations.RenameIndex(
            model_name='incentivetransaction',
            new_name='incentives__doc_no_0854a1_idx',
            old_name='incv_doc_item_idx',
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='expiry_within_days',
            field=models.PositiveIntegerField(blank=True, help_text='تنطبق فقط على وحدات تنتهي صلاحيتها خلال N يوم', null=True, verbose_name='أيام الصلاحية'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='incentive_value',
            field=models.DecimalField(decimal_places=4, help_text='نسبة (0–100) للنوع المئوي، أو مبلغ ثابت لكل وحدة للنوع الثابت', max_digits=10, verbose_name='قيمة الحافز'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='person_code_filter',
            field=models.CharField(blank=True, help_text='اتركه فارغاً لتطبيقه على جميع المندوبين', max_length=50, verbose_name='فلتر كود المندوب (phcode)'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='الرقم الأعلى = الأولوية الأعلى عند تعارض القواعد', verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='incentivetransaction',
            name='incentive_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='سالب للمرتجعات', max_digits=12, verbose_name='مبلغ الحافز'),
        ),
        migrations.AlterField(
            model_name='incentivetransaction',
            name='is_reversed',
            field=models.BooleanField(db_index=True, default=False, help_text='True إذا تمت إعادة هذا البيع لاحقاً في نفس الفترة', verbose_name='مُعكوس'),
        ),
        migrations.AlterField(
            model_name='incentivetransaction',
            name='ref_doc_no',
            field=models.CharField(blank=True, db_index=True, help_text='للمرتجعات: رقم فاتورة البيع الأصلية (r_docnumber)', max_length=50, verbose_name='الفاتورة المرجعية'),
        ),
    ]
