# Generated by Django 4.2.13 on 2026-05-15 21:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0004_advanced_incentive_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incentiverule',
            options={'ordering': ['priority', 'item_code'], 'verbose_name': 'قاعدة حوافز', 'verbose_name_plural': 'قواعد الحوافز'},
        ),
        migrations.RenameIndex(
            model_name='incentivetransaction',
            new_name='incentive_prog_period_idx',
            old_name='incentives__program_9054fe_idx',
        ),
        migrations.RenameIndex(
            model_name='incentivetransaction',
            new_name='incentive_user_period_idx',
            old_name='incentives__user_id_a45db1_idx',
        ),
        migrations.RenameIndex(
            model_name='incentivetransaction',
            new_name='incentive_doc_item_idx',
            old_name='incentives__doc_no_0854a1_idx',
        ),
        migrations.AlterField(
            model_name='incentivecalculationlog',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='المدة (ثانية)'),
        ),
        migrations.AlterField(
            model_name='incentivecalculationlog',
            name='error_detail',
            field=models.TextField(blank=True, verbose_name='تفاصيل الخطأ'),
        ),
        migrations.AlterField(
            model_name='incentivecalculationlog',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء'),
        ),
        migrations.AlterField(
            model_name='incentivecalculationlog',
            name='skipped_person_codes',
            field=models.JSONField(default=list, verbose_name='كودات غير مربوطة'),
        ),
        migrations.AlterField(
            model_name='incentivecalculationlog',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='incentivecalculationlog',
            name='transactions_created',
            field=models.IntegerField(default=0, verbose_name='حركات أُنشئت'),
        ),
        migrations.AlterField(
            model_name='incentivecalculationlog',
            name='user_summaries',
            field=models.JSONField(default=dict, verbose_name='ملخص المستخدمين'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='branch_filter',
            field=models.CharField(blank=True, help_text='فارغ = جميع الفروع', max_length=50, verbose_name='فلتر الفرع (branchcode)'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='category_code',
            field=models.CharField(blank=True, help_text='معلوماتي فقط — لا يُطبَّق في المحرك', max_length=50, verbose_name='كود الفئة (groupcode)'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='incentive_value',
            field=models.DecimalField(decimal_places=4, help_text='نسبة (0–100) لـ percent | مبلغ لكل وحدة لـ fixed* | مبلغ ثابت للفاتورة لـ fixed_per_transaction | غير مستخدم عند tiered (استخدم slab_config)', max_digits=10, verbose_name='قيمة الحافز'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='item_code',
            field=models.CharField(blank=True, help_text='اتركه فارغاً عند استخدام قائمة الأصناف (IncentiveRuleItem)', max_length=50, verbose_name='كود الصنف (صنف وحيد)'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='min_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='الحد الأدنى للكمية (لكل حركة)'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='min_total_qty_in_period',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='القاعدة لا تُطبَّق إلا إذا بلغت الكمية الإجمالية للصنف هذا الحد', max_digits=10, null=True, verbose_name='الحد الأدنى لإجمالي الكمية في الفترة'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='person_code_filter',
            field=models.CharField(blank=True, help_text='فارغ = يُطبَّق على جميع المندوبين', max_length=50, verbose_name='فلتر كود المندوب (phcode)'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='الرقم الأقل = أولوية أعلى عند التعارض (0 = الأعلى أولوية)', verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='incentiveruleitem',
            name='incentive_override',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='فارغ → يُستخدم incentive_value من القاعدة الأصلية', max_digits=10, null=True, verbose_name='قيمة حافز خاصة (override)'),
        ),
        migrations.AlterField(
            model_name='incentivesettlement',
            name='total_incentive',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='إجمالي الحوافز (من الحركات)'),
        ),
        migrations.AlterField(
            model_name='incentivetransaction',
            name='is_cross_period_return',
            field=models.BooleanField(default=False, help_text='True إذا كانت حركة المرتجع تقع خارج نافذة الفترة الحالية', verbose_name='مرتجع من فترة مختلفة'),
        ),
        migrations.AlterField(
            model_name='incentivetransaction',
            name='is_reversed',
            field=models.BooleanField(db_index=True, default=False, help_text='True إذا تمت إعادة هذا البيع لاحقاً', verbose_name='مُعكوس (مُسترجَع)'),
        ),
        migrations.AlterField(
            model_name='incentivetransaction',
            name='ref_doc_no',
            field=models.CharField(blank=True, db_index=True, help_text='للمرتجعات: رقم فاتورة البيع الأصلية', max_length=50, verbose_name='الفاتورة المرجعية'),
        ),
    ]
