# Generated by Django 4.2.13 on 2026-06-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0007_incentive_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentiveprogram',
            name='sponsor_contribution_pct',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='0–100. مثال: 60 = الراعي يتحمّل 60%، الصيدلية تتحمّل 40%', max_digits=6, null=True, verbose_name='نسبة مساهمة الراعي %'),
        ),
        migrations.AlterField(
            model_name='incentiveprogram',
            name='sponsor_name',
            field=models.CharField(blank=True, help_text='اسم المورد أو الشركة التي تموّل البرنامج جزئياً أو كلياً', max_length=200, verbose_name='اسم الجهة الراعية'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='is_imported_filter',
            field=models.CharField(choices=[('any', 'الكل (محلي + مستورد)'), ('local', 'محلي فقط'), ('imported', 'مستورد فقط')], default='any', help_text='any = لا فلترة | local = محلي فقط | imported = مستورد فقط', max_length=10, verbose_name='فلتر المصدر'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='margin_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='مثال: 40 — تُطبَّق فقط على أصناف هامش ربحها <= 40%', max_digits=7, null=True, verbose_name='الحد الأقصى لهامش الربح %'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='margin_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='مثال: 15 — تُطبَّق فقط على أصناف هامش ربحها >= 15%', max_digits=7, null=True, verbose_name='الحد الأدنى لهامش الربح %'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='origin_codes',
            field=models.JSONField(blank=True, help_text='قائمة كودات الدولة (itemorigincode) المسموح بها. فارغ = جميع المصادر.', null=True, verbose_name='كودات المصدر'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='pack_price_max',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='مثال: 500 — تُطبَّق فقط على أصناف سعرها <= 500', max_digits=10, null=True, verbose_name='الحد الأقصى لسعر العبوة'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='pack_price_min',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='مثال: 50 — تُطبَّق فقط على أصناف سعرها >= 50', max_digits=10, null=True, verbose_name='الحد الأدنى لسعر العبوة'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='target_qty',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='الكمية الكاملة المستهدفة (100%) لكل مندوب. مطلوب عند نوع target_based.', max_digits=12, null=True, verbose_name='الهدف الكمي (وحدات/فترة)'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='target_tiers',
            field=models.JSONField(blank=True, help_text='شرائح نسب الإنجاز والمكافآت المقابلة لها', null=True, verbose_name='شرائح الإنجاز (target_based)'),
        ),
        migrations.AlterField(
            model_name='incentivetransaction',
            name='expiry_days_remaining',
            field=models.IntegerField(blank=True, help_text='عدد الأيام المتبقية في تاريخ البيع (سالب = انتهت الصلاحية)', null=True, verbose_name='أيام الصلاحية المتبقية'),
        ),
    ]
