# Generated by Django 4.2.13 on 2026-06-14 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_item_pack_price_tax_item_sale_tax_pct'),
        ('branches', '0004_branch_db_connection'),
        ('users', '0016_staffprofile_muted_notification_categories'),
        ('incentives', '0008_alter_incentiveprogram_sponsor_contribution_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='الاسم')),
                ('scope_type', models.CharField(choices=[('chain', 'الشبكة كاملة'), ('branch', 'فرع'), ('salesperson', 'مندوب'), ('category', 'فئة')], default='branch', max_length=12)),
                ('softech_user', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='كود المندوب (SOFTECH)')),
                ('metric', models.CharField(choices=[('net_revenue', 'صافي المبيعات (ج.م)'), ('orders', 'عدد الفواتير')], default='net_revenue', max_length=12)),
                ('period_start', models.DateField(verbose_name='من')),
                ('period_end', models.DateField(verbose_name='إلى')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='القيمة المستهدفة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffprofile')),
            ],
            options={
                'verbose_name': 'هدف بيعي',
                'verbose_name_plural': 'الأهداف البيعية',
                'ordering': ['-period_end', 'scope_type'],
            },
        ),
    ]
