# Generated by Django 4.2.13 on 2026-07-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0009_salestarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestarget',
            name='metric',
            field=models.CharField(choices=[('net_revenue', 'صافي المبيعات (ج.م)'), ('orders', 'عدد الفواتير'), ('cash_delivery', 'نقدى + توصيل (ج.م)'), ('cash', 'نقدى (ج.م)'), ('delivery', 'توصيل (ج.م)'), ('credit', 'آجل (ج.م)'), ('gross_profit', 'معامل الربحية (ج.م)'), ('beauty', 'التجميل (ج.م)'), ('customer_count', 'عدد العملاء')], default='net_revenue', max_length=20),
        ),
    ]
