# Generated by Django 4.2.13 on 2026-05-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enrichmentapprovallog',
            new_name='enrichment__field_n_db00a7_idx',
            old_name='enr_log_field_source_idx',
        ),
        migrations.RenameIndex(
            model_name='enrichmentsuggestion',
            new_name='enrichment__item_id_540709_idx',
            old_name='enr_sug_item_status_idx',
        ),
        migrations.RenameIndex(
            model_name='enrichmentsuggestion',
            new_name='enrichment__item_id_b27a77_idx',
            old_name='enr_sug_item_field_idx',
        ),
        migrations.RenameIndex(
            model_name='enrichmentsuggestion',
            new_name='enrichment__batch_i_3cb902_idx',
            old_name='enr_sug_batch_status_idx',
        ),
        migrations.AlterField(
            model_name='enrichmentbatch',
            name='auto_publish_threshold',
            field=models.FloatField(default=0.9, help_text='Suggestions with confidence ≥ this are auto-approved'),
        ),
        migrations.AlterField(
            model_name='enrichmentbatch',
            name='scope_params',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"category_id": 5, "threshold": 30}'),
        ),
    ]
