# Generated by Django 4.2.13 on 2026-05-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0002_rename_enr_log_field_source_idx_enrichment__field_n_db00a7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemenrichment',
            name='administration_route_ar',
            field=models.TextField(blank=True, verbose_name='طريقة الاستخدام'),
        ),
        migrations.AlterField(
            model_name='itemenrichment',
            name='age_range',
            field=models.TextField(blank=True, verbose_name='الفئة العمرية'),
        ),
        migrations.AlterField(
            model_name='itemenrichment',
            name='dosage_ar',
            field=models.TextField(blank=True, verbose_name='الجرعة'),
        ),
        migrations.AlterField(
            model_name='itemenrichment',
            name='duration_ar',
            field=models.TextField(blank=True, verbose_name='مدة العلاج'),
        ),
        migrations.AlterField(
            model_name='itemenrichment',
            name='frequency_ar',
            field=models.TextField(blank=True, verbose_name='التكرار'),
        ),
        migrations.AlterField(
            model_name='itemenrichment',
            name='storage_condition',
            field=models.TextField(blank=True, verbose_name='شروط التخزين'),
        ),
    ]
