# Generated by Django 4.2.13 on 2026-05-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0003_clinical_fields_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemenrichment',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='صورة المنتج (كاش)'),
        ),
    ]
