# Generated by Django 4.2.13 on 2026-06-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0023_item_pack_price_tax_item_sale_tax_pct'),
        ('branches', '0005_branch_latitude_branch_longitude'),
        ('callcenter', '0006_callitem'),
        ('users', '0018_drop_legacy_has_global_access'),
        ('customers', '0016_add_health_profile_churn_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftechSalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('ready', 'جاهز للإرسال'), ('pushing', 'جارٍ الإرسال'), ('pushed', 'بانتظار الكاشير'), ('push_failed', 'فشل الإرسال'), ('settled', 'تم التحصيل (الكاشير)'), ('cancelled', 'ملغى')], db_index=True, default='draft', max_length=12, verbose_name='الحالة')),
                ('channel', models.CharField(choices=[('cash', 'نقدى'), ('delivery', 'توصيل'), ('contract', 'تعاقد / آجل'), ('insurance', 'تأمين'), ('employee', 'موظفين'), ('vip', 'VIP'), ('permanent', 'عميل دائم')], db_index=True, default='cash', max_length=12, verbose_name='قناة البيع')),
                ('doc_kind', models.CharField(choices=[('sale', 'بيع'), ('return', 'مرتجع')], default='sale', max_length=8, verbose_name='نوع المستند')),
                ('client_token', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('softech_branchcode', models.CharField(max_length=5, verbose_name='كود فرع SOFTECH')),
                ('store_code', models.CharField(max_length=3, verbose_name='كود المخزن')),
                ('softech_pic', models.CharField(blank=True, max_length=18, verbose_name='PIC')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='اسم العميل')),
                ('cust_branch_code', models.CharField(blank=True, max_length=8, verbose_name='كود حساب العميل (personcode)')),
                ('softech_docnumber', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مسلسل الصرف (pending)')),
                ('softech_docdate', models.DateField(blank=True, null=True)),
                ('softech_final_docnumber', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='رقم الفاتورة النهائية')),
                ('return_of_invoice', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مرتجع للفاتورة')),
                ('doc_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='القيمة (صافي)')),
                ('doc_value_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي قبل الخصم')),
                ('doc_value_cogs', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='التكلفة')),
                ('doc_value_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الضريبة')),
                ('doc_value_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المحصّل الآن')),
                ('patient_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='دفعة العميل')),
                ('referral_doctor_name', models.CharField(blank=True, max_length=120, verbose_name='الطبيب المُحيل')),
                ('referral_doctor_code', models.CharField(blank=True, max_length=13, verbose_name='كود الطبيب (refdoctorcode)')),
                ('prescription_image', models.ImageField(blank=True, null=True, upload_to='pos_orders/prescriptions/%Y/%m/', verbose_name='صورة الروشتة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('seller_usercode', models.CharField(blank=True, max_length=5, verbose_name='كود البائع')),
                ('cashier_usercode', models.CharField(blank=True, max_length=5, verbose_name='كود الكاشير')),
                ('erp_executed_at', models.DateTimeField(blank=True, null=True)),
                ('erp_payload', models.JSONField(blank=True, default=dict, verbose_name='الحمولة المُرسلة')),
                ('erp_readback', models.JSONField(blank=True, default=dict, verbose_name='قراءة التحقق')),
                ('erp_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders', to='branches.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos_orders', to='users.staffprofile')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to='customers.customer', verbose_name='العميل')),
                ('source_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to='callcenter.calllog', verbose_name='المكالمة المصدر')),
                ('source_call_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to='callcenter.callitem')),
            ],
            options={
                'verbose_name': 'أمر بيع غير مباشر',
                'verbose_name_plural': 'أوامر البيع غير المباشرة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftechSalesOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(choices=[('cash', 'نقدى'), ('credit', 'آجل'), ('card', 'بطاقة')], default='cash', max_length=8, verbose_name='طريقة السداد')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ')),
                ('softech_paymentsno', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('card_brand', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('ref_invoice', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos_orders.softechsalesorder')),
            ],
            options={
                'verbose_name': 'سداد أمر بيع',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SoftechSalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softech_itemcode', models.CharField(max_length=6, verbose_name='كود الصنف')),
                ('item_name', models.CharField(blank=True, max_length=120)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='الكمية')),
                ('item_sale_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('item_sale_price_tax', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('sale_tax_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cust_discp', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='خصم %')),
                ('trans_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('trans_price_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_sale_tax', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('new_cost_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('item_expiry', models.DateField(blank=True, null=True)),
                ('return_of_invoice', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_order_lines', to='catalog.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos_orders.softechsalesorder')),
            ],
            options={
                'verbose_name': 'سطر أمر بيع',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='softechsalesorder',
            index=models.Index(fields=['status', 'branch'], name='pos_orders__status_bcfaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='softechsalesorder',
            index=models.Index(fields=['softech_branchcode', 'softech_docnumber'], name='pos_orders__softech_a578b2_idx'),
        ),
    ]
