# Generated by Django 4.2.13 on 2026-06-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softechsalesorderline',
            name='source_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
