# Generated by Django 4.2.13 on 2026-06-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_orders', '0002_softechsalesorderline_source_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='softechsalesorder',
            name='source_header_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
