# Generated by Django 4.2.13 on 2026-06-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_orders', '0003_softechsalesorder_source_header_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='softechsalesorder',
            name='source_cc_raw',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='softechsalesorder',
            name='source_companies_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
