# Generated by Django 4.2.13 on 2026-06-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_orders', '0004_softechsalesorder_source_cc_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softechsalesorder',
            name='alt_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='softechsalesorder',
            name='change_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='softechsalesorder',
            name='doc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softechsalesorder',
            name='items_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='softechsalesorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='softechsalesorder',
            name='print_receipt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='softechsalesorder',
            name='sell_at_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='softechsalesorderline',
            name='barcode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='softechsalesorderline',
            name='batchno',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='softechsalesorderline',
            name='bonus_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='softechsalesorderline',
            name='pkg_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='softechsalesorderpayment',
            name='cheque_card_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='softechsalesorderpayment',
            name='currency',
            field=models.CharField(default='L.E', max_length=10),
        ),
        migrations.AddField(
            model_name='softechsalesorderpayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='softechsalesorderpayment',
            name='internal_payserial',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
