# Generated by Django 4.2.13 on 2026-06-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_orders', '0005_softechsalesorder_alt_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softechsalesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('ready', 'جاهز للإرسال'), ('queued', 'بانتظار الاتصال (طابور)'), ('pushing', 'جارٍ الإرسال'), ('pushed', 'بانتظار الكاشير'), ('push_failed', 'فشل الإرسال'), ('settled', 'تم التحصيل (الكاشير)'), ('cancelled', 'ملغى')], db_index=True, default='draft', max_length=12, verbose_name='الحالة'),
        ),
    ]
