# Generated by Django 4.2.13 on 2026-06-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_orders', '0006_alter_softechsalesorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softechsalesorder',
            name='client_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
