# Generated by Django 4.2.13 on 2026-08-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_orders', '0007_alter_softechsalesorder_client_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='softechsalesorderline',
            name='is_reservation',
            field=models.BooleanField(default=False, verbose_name='حجز (غير متوفر)'),
        ),
    ]
