# Generated by Django 4.2.13 on 2026-08-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_orders', '0008_softechsalesorderline_is_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softechsalesorder',
            name='channel',
            field=models.CharField(choices=[('cash', 'نقدى'), ('delivery', 'توصيل'), ('contract', 'تعاقد / آجل'), ('insurance', 'تأمين'), ('employee', 'موظفين'), ('vip', 'VIP'), ('permanent', 'عميل دائم'), ('compensation', 'تعويضات الشركات'), ('donation', 'تبرعات'), ('card_receipt', 'إيصال بالبطاقة الشخصية')], db_index=True, default='cash', max_length=12, verbose_name='قناة البيع'),
        ),
    ]
