# Generated by Django 4.2.13 on 2026-08-29 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_manualoffermatch_and_more'),
        ('pos_orders', '0009_alter_softechsalesorder_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='softechsalesorderline',
            name='applied_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_order_lines', to='offers.offer', verbose_name='العرض المطبَّق'),
        ),
        migrations.AddField(
            model_name='softechsalesorderline',
            name='discount_source',
            field=models.CharField(choices=[('manual', 'يدوي'), ('offer', 'عرض')], default='manual', max_length=6, verbose_name='مصدر الخصم'),
        ),
    ]
