# Generated by Django 4.2.13 on 2026-09-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_orders', '0010_softechsalesorderline_applied_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softechsalesorderline',
            name='qty',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=12, verbose_name='الكمية'),
        ),
    ]
