# Generated by Django 4.2.13 on 2026-09-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_orders', '0011_alter_softechsalesorderline_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='softechsalesorder',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False, verbose_name='يحتاج مراجعة'),
        ),
        migrations.AddField(
            model_name='softechsalesorder',
            name='review_reason',
            field=models.CharField(blank=True, max_length=40, verbose_name='سبب المراجعة'),
        ),
    ]
