# Generated by Django 4.2.13 on 2026-09-14 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_item_is_phantom_substitution_and_more'),
        ('pos_orders', '0012_softechsalesorder_needs_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosCancelDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(db_index=True, max_length=5)),
                ('day', models.DateField(db_index=True)),
                ('doccode', models.CharField(default='115', max_length=3)),
                ('item_code', models.CharField(db_index=True, max_length=6)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('events', models.PositiveIntegerField(default=0)),
                ('priced_events', models.PositiveIntegerField(default=0)),
                ('lost_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_cancel_daily', to='catalog.item')),
            ],
            options={
                'verbose_name': 'مبيعات غير مخزنة (يومي)',
                'verbose_name_plural': 'المبيعات غير المخزنة (يومي)',
                'indexes': [models.Index(fields=['branch_code', 'day'], name='pos_orders__branch__c7c6f7_idx'), models.Index(fields=['item_code', 'day'], name='pos_orders__item_co_df4941_idx')],
                'unique_together': {('branch_code', 'day', 'item_code', 'doccode')},
            },
        ),
    ]
