# Generated by Django 4.2.13 on 2026-09-15 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_backfill_branch_kind'),
        ('users', '0026_staffprofile_notify_expiry_worklist_wa'),
        ('catalog', '0037_item_is_phantom_substitution_and_more'),
        ('pos_orders', '0013_poscanceldaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosSelectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_token', models.UUIDField(blank=True, db_index=True, help_text='== the order client_token when the cart is submitted', null=True)),
                ('softech_branchcode', models.CharField(max_length=5)),
                ('doc_kind', models.CharField(default='sale', max_length=8)),
                ('event_type', models.CharField(choices=[('add', 'إضافة صنف'), ('clear', 'مسح صنف')], default='add', max_length=8)),
                ('item_code', models.CharField(max_length=6)),
                ('item_name', models.CharField(blank=True, max_length=120)),
                ('itemsaleprice', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('transprice', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('transqty', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('transprice_total', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('custcode', models.CharField(blank=True, max_length=8)),
                ('seller_usercode', models.CharField(blank=True, max_length=5)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('softech_written_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('write_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_selection_events', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_selection_events', to='catalog.item')),
            ],
            options={
                'verbose_name': 'حدث اختيار صنف (POS)',
                'verbose_name_plural': 'أحداث اختيار الأصناف (POS)',
                'indexes': [models.Index(fields=['softech_written_at', 'occurred_at'], name='pos_orders__softech_7aef7a_idx'), models.Index(fields=['cart_token'], name='pos_orders__cart_to_03b38c_idx')],
            },
        ),
    ]
