# Generated by Django 4.2.13 on 2026-04-28 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_staffprofile_role'),
        ('branches', '0001_initial'),
        ('catalog', '0002_alter_item_unit_price_alter_item_unit_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'بانتظار الموافقة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('needs_revision', 'يحتاج تعديل'), ('sent_to_erp', 'تم الإرسال للـ ERP'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='حالة الطلب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('revision_notes', models.TextField(blank=True, verbose_name='ملاحظات التعديل')),
                ('erp_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع الـ ERP')),
                ('sent_to_erp_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_transfer_requests', to='users.staffprofile', verbose_name='أنشئ بواسطة')),
                ('destination_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_requests', to='branches.branch', verbose_name='الفرع المصدر')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transfer_requests', to='users.staffprofile', verbose_name='راجع بواسطة')),
                ('sent_to_erp_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_sent_requests', to='users.staffprofile', verbose_name='أُرسل للـ ERP بواسطة')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_requests', to='branches.branch', verbose_name='الفرع الطالب')),
            ],
            options={
                'verbose_name': 'طلب تحويل',
                'verbose_name_plural': 'طلبات التحويل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('message', '💬 رسالة'), ('system', '⚙️ نظام'), ('note', '📝 ملاحظة داخلية')], default='message', max_length=10)),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_messages', to='users.staffprofile', verbose_name='بواسطة')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='transfers.transferrequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'رسائل الطلب',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية المطلوبة')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_request_items', to='catalog.item', verbose_name='الصنف')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfers.transferrequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'صنف في الطلب',
                'verbose_name_plural': 'أصناف الطلب',
                'unique_together': {('request', 'item')},
            },
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['status', 'source_branch'], name='transfers_t_status_69e49b_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['status', 'destination_branch'], name='transfers_t_status_2c00e7_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['created_at'], name='transfers_t_created_32e9d7_idx'),
        ),
    ]
