# Generated by Django 4.2.13 on 2026-04-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transferrequest',
            new_name='transfers_t_status_1e0631_idx',
            old_name='transfers_status_req_idx',
        ),
        migrations.RenameIndex(
            model_name='transferrequest',
            new_name='transfers_t_status_69e49b_idx',
            old_name='transfers_status_src_idx',
        ),
        migrations.RenameIndex(
            model_name='transferrequest',
            new_name='transfers_t_flagged_e68365_idx',
            old_name='transfers_flagged_idx',
        ),
        migrations.RenameIndex(
            model_name='transferrequest',
            new_name='transfers_t_created_32e9d7_idx',
            old_name='transfers_created_idx',
        ),
    ]
