# Generated by Django 4.2.13 on 2026-04-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_redesign'),
        ('transfers', '0002_rename_transfers_status_req_idx_transfers_t_status_1e0631_idx_and_more'),
    ]

    operations = [
    ]
