# Generated by Django 4.2.13 on 2026-05-31 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0014_remove_itemdemandmetrics_purch_metrics_run_root_and_more'),
        ('transfers', '0008_erp_match_user_transtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='source_recommendation',
            field=models.ForeignKey(blank=True, help_text='إذا نشأ هذا الطلب من توصية تحويل تلقائية، تُحفظ هنا الرابط للقياس والتحليل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to='purchasing.transferrecommendation', verbose_name='التوصية المصدر'),
        ),
    ]
