# Generated by Django 4.2.13 on 2026-06-08 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('callcenter', '0006_callitem'),
        ('branches', '0004_branch_db_connection'),
        ('users', '0015_softechsystemmap_erpgroupmodulepermission'),
        ('customers', '0016_add_health_profile_churn_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(db_index=True, help_text='رقم التحويلة في Asterisk (e.g. "201", "SIP/201")', max_length=20, unique=True, verbose_name='رقم التحويلة')),
                ('sip_peer', models.CharField(blank=True, max_length=50, verbose_name='SIP Peer')),
                ('queue_name', models.CharField(blank=True, help_text='الـ queue الافتراضية لهذا العميل في Asterisk', max_length=50, verbose_name='اسم القائمة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pbx_extension', to='users.staffprofile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'تحويلة موظف',
                'verbose_name_plural': 'تحويلات الموظفين',
            },
        ),
        migrations.CreateModel(
            name='PBXQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم القائمة')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbx_queues', to='branches.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'قائمة PBX',
                'verbose_name_plural': 'قوائم PBX',
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='UniqueID')),
                ('linked_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='LinkedID')),
                ('direction', models.CharField(choices=[('inbound', 'وارد'), ('outbound', 'صادر'), ('internal', 'داخلي')], default='inbound', max_length=10, verbose_name='الاتجاه')),
                ('state', models.CharField(choices=[('ringing', 'يرن'), ('answered', 'أُجيب'), ('queued', 'في القائمة'), ('on_hold', 'قيد الانتظار'), ('transferred', 'محوَّل'), ('completed', 'مكتمل'), ('abandoned', 'أُهمل'), ('no_answer', 'لا رد'), ('busy', 'مشغول'), ('failed', 'فشل')], db_index=True, default='ringing', max_length=12, verbose_name='الحالة')),
                ('caller_number', models.CharField(db_index=True, max_length=50, verbose_name='رقم المتصل')),
                ('caller_name', models.CharField(blank=True, max_length=100)),
                ('destination_ext', models.CharField(blank=True, max_length=50, verbose_name='رقم المقصد')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('wait_seconds', models.PositiveIntegerField(default=0, verbose_name='وقت الانتظار')),
                ('talk_seconds', models.PositiveIntegerField(default=0, verbose_name='وقت الحديث')),
                ('recording_path', models.CharField(blank=True, help_text='Full path on Asterisk server, e.g. /var/spool/asterisk/monitor/...', max_length=500, verbose_name='مسار التسجيل')),
                ('recording_url', models.URLField(blank=True, verbose_name='رابط التسجيل')),
                ('cdr_disposition', models.CharField(blank=True, max_length=20)),
                ('cdr_userfield', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='pbx.agentextension', verbose_name='العامل')),
                ('call_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbx_session', to='callcenter.calllog', verbose_name='سجل المكالمة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbx_sessions', to='customers.customer', verbose_name='العميل')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='pbx.pbxqueue', verbose_name='القائمة')),
            ],
            options={
                'verbose_name': 'جلسة مكالمة PBX',
                'verbose_name_plural': 'جلسات مكالمات PBX',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PBXEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Newchannel', 'قناة جديدة'), ('Hangup', 'إغلاق المكالمة'), ('Bridge', 'ربط'), ('AgentCalled', 'عامل مُتصل'), ('AgentConnect', 'اتصال عامل'), ('AgentComplete', 'اكتمال عامل'), ('QueueCallerJoin', 'عميل دخل القائمة'), ('QueueCallerLeave', 'عميل غادر القائمة'), ('QueueCallerAbandon', 'عميل أهمل القائمة'), ('MusicOnHold', 'انتظار موسيقى'), ('DTMFBegin', 'DTMF'), ('VarSet', 'متغير'), ('Cdr', 'CDR'), ('Other', 'أخرى')], db_index=True, default='Other', max_length=30, verbose_name='نوع الحدث')),
                ('payload', models.JSONField(verbose_name='البيانات الخام')),
                ('unique_id', models.CharField(blank=True, db_index=True, help_text='Asterisk UniqueID for the call leg', max_length=50, verbose_name='UniqueID')),
                ('linked_id', models.CharField(blank=True, db_index=True, help_text='Shared across bridged legs', max_length=50, verbose_name='LinkedID')),
                ('channel', models.CharField(blank=True, max_length=100)),
                ('caller_id_num', models.CharField(blank=True, db_index=True, max_length=50)),
                ('caller_id_name', models.CharField(blank=True, max_length=100)),
                ('extension', models.CharField(blank=True, max_length=50)),
                ('queue_name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='pbx.callsession', verbose_name='جلسة المكالمة')),
            ],
            options={
                'verbose_name': 'حدث AMI',
                'verbose_name_plural': 'أحداث AMI',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['unique_id', 'received_at'], name='pbx_pbxeven_unique__32f28f_idx'), models.Index(fields=['linked_id', 'event_type'], name='pbx_pbxeven_linked__1ac15f_idx'), models.Index(fields=['caller_id_num', 'received_at'], name='pbx_pbxeven_caller__bd277b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['caller_number', 'started_at'], name='pbx_callses_caller__e733a5_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['state', 'started_at'], name='pbx_callses_state_d9de0a_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['agent', 'started_at'], name='pbx_callses_agent_i_f87d42_idx'),
        ),
    ]
