# Generated by Django 4.2.13 on 2026-06-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0002_agentextension_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentextension',
            options={'ordering': ['extension'], 'verbose_name': 'تحويلة', 'verbose_name_plural': 'التحويلات'},
        ),
        migrations.AlterField(
            model_name='agentextension',
            name='last_status',
            field=models.CharField(blank=True, help_text='e.g. OK (25 ms), UNKNOWN, UNREACHABLE', max_length=50, verbose_name='آخر حالة'),
        ),
    ]
