# Generated by Django 4.2.13 on 2026-06-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0003_agentextension_hq_type'),
        ('pbx', '0003_alter_agentextension_options_and_more'),
    ]

    operations = [
    ]
