# Generated by Django 4.2.13 on 2026-05-27 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaignmessage',
            new_name='campaigns_c_campaig_407020_idx',
            old_name='campaigns_c_campaig_idx',
        ),
        migrations.RenameIndex(
            model_name='campaignmessage',
            new_name='campaigns_c_campaig_bfb3ce_idx',
            old_name='campaigns_c_custome_idx',
        ),
    ]
