# Generated by Django 4.2.13 on 2026-09-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0019_segmentationconfig'),
        ('catalog', '0038_item_is_spike_item_spike_confirmed_and_more'),
        ('branches', '0007_backfill_branch_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(blank=True, help_text='يُستخدم عندما لا يكون الصنف مطابَقاً بعد', max_length=300, verbose_name='الاسم الخام')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الكمية المطلوبة')),
                ('source_type', models.CharField(choices=[('reservation', 'حجز عميل'), ('demand_item', 'طلب طلب (Demand)'), ('shortage_item', 'قائمة نواقص فرع'), ('market_shortage', 'كاشف نواقص السوق'), ('manual', 'يدوي')], db_index=True, max_length=20, verbose_name='نوع المصدر')),
                ('source_ref', models.CharField(help_text='معرّف السطر المصدري (idempotency)', max_length=64, verbose_name='مرجع المصدر')),
                ('provenance_class', models.CharField(choices=[('customer_commitment', 'التزام عميل (تُجمَع)'), ('branch_replenishment', 'طلب فرع (تُدمَج المكرَّرات)'), ('statistical', 'مؤشر سوق (إرشادي)')], db_index=True, max_length=24, verbose_name='فئة المصدر')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('fulfilled', 'مُلبّى'), ('cancelled', 'ملغى'), ('superseded', 'متجاوَز')], db_index=True, default='open', max_length=12, verbose_name='الحالة')),
                ('source_created_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ نشوء الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='فارغ = طلب على مستوى الشبكة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demand_signals', to='branches.branch', verbose_name='الفرع')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_signals', to='customers.customer', verbose_name='العميل')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demand_signals', to='catalog.item', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'إشارة طلب',
                'verbose_name_plural': 'إشارات الطلب',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', 'status'], name='ds_item_status_idx'), models.Index(fields=['branch', 'status'], name='ds_branch_status_idx'), models.Index(fields=['provenance_class', 'status'], name='ds_class_status_idx'), models.Index(fields=['item', 'branch', 'status'], name='ds_item_branch_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='demandsignal',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_ref'), name='unique_demand_signal_source'),
        ),
    ]
