# Generated by Django 4.2.13 on 2026-09-20 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_item_is_spike_item_spike_confirmed_and_more'),
        ('invoices', '0012_invoiceline_match_review'),
        ('users', '0026_staffprofile_notify_expiry_worklist_wa'),
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=255, verbose_name='اسم المورد كما ورد')),
                ('source', models.CharField(choices=[('whatsapp', 'واتساب'), ('image', 'صورة / لقطة'), ('excel', 'إكسل'), ('csv', 'CSV'), ('text', 'نص'), ('email', 'بريد'), ('manual', 'يدوي')], default='whatsapp', max_length=12, verbose_name='المصدر')),
                ('status', models.CharField(choices=[('open', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('actioned', 'تم التنفيذ'), ('archived', 'مؤرشف')], db_index=True, default='open', max_length=12, verbose_name='الحالة')),
                ('raw_content', models.TextField(blank=True, verbose_name='المحتوى الأصلي')),
                ('source_image', models.ImageField(blank=True, null=True, upload_to='supply/availability/%Y/%m/', verbose_name='صورة المصدر')),
                ('raw_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='بصمة المحتوى')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_batches', to='users.staffprofile', verbose_name='المُدخِل')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_batches', to='invoices.vendorprofile', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'دفعة إتاحة مورد',
                'verbose_name_plural': 'دفعات إتاحة الموردين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=300, verbose_name='النص كما ورد')),
                ('match_score', models.FloatField(blank=True, null=True, verbose_name='نسبة التطابق')),
                ('match_reason', models.JSONField(blank=True, default=dict, verbose_name='سبب المطابقة')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='مُؤكَّد')),
                ('is_unmatched', models.BooleanField(default=False, verbose_name='غير مطابق')),
                ('supplier_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='الكمية المتاحة لدى المورد')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='السعر المعروض')),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='الخصم %')),
                ('foc_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='البونص / الكمية المجانية')),
                ('expiry', models.CharField(blank=True, max_length=20, verbose_name='الصلاحية (كما وردت)')),
                ('supplier_item_code', models.CharField(blank=True, max_length=40, verbose_name='كود المورد للصنف')),
                ('source', models.CharField(choices=[('manual', 'يدوي'), ('bulk', 'استيراد نصي'), ('ocr', 'OCR'), ('file', 'ملف')], default='bulk', max_length=10, verbose_name='مصدر الإدخال')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supply.availabilitybatch', verbose_name='الدفعة')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_availability_lines', to='users.staffprofile')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.item', verbose_name='الصنف المطابق')),
            ],
            options={
                'verbose_name': 'صنف إتاحة',
                'verbose_name_plural': 'أصناف الإتاحة',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['batch', 'is_confirmed'], name='al_batch_confirmed_idx'), models.Index(fields=['item'], name='al_item_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='availabilitybatch',
            index=models.Index(fields=['status', '-created_at'], name='ab_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilitybatch',
            index=models.Index(fields=['supplier', '-created_at'], name='ab_supplier_created_idx'),
        ),
    ]
