# Generated by Django 4.2.13 on 2026-09-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_backfill_branch_kind'),
        ('users', '0026_staffprofile_notify_expiry_worklist_wa'),
        ('catalog', '0038_item_is_spike_item_spike_confirmed_and_more'),
        ('supply', '0002_availabilitybatch_availabilityline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('detected', 'مُكتشَف'), ('searching', 'جارٍ البحث'), ('availability_found', 'وُجد توفّر لدى مورد'), ('awaiting_decision', 'بانتظار قرار'), ('transfer_pending', 'تحويل داخلي قيد التنفيذ'), ('ordered', 'تم الطلب من مورد'), ('partially_fulfilled', 'مُلبّى جزئياً'), ('received', 'تم الاستلام'), ('fulfilled', 'مُلبّى ✅'), ('cancelled', 'ملغى')], db_index=True, default='detected', max_length=24, verbose_name='الحالة')),
                ('required_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الاحتياج الصافي')),
                ('residual_gap', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='فجوة الشراء الخارجي')),
                ('internal_cover', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='تغطية داخلية مقترحة')),
                ('customer_demand', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='طلب عملاء منتظرين')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الرصيد الحالي')),
                ('scarcity_score', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='درجة الندرة')),
                ('is_urgent', models.BooleanField(db_index=True, default=False, verbose_name='عاجل')),
                ('has_availability', models.BooleanField(db_index=True, default=False, verbose_name='يوجد توفّر لدى مورد')),
                ('last_ledger', models.JSONField(blank=True, default=dict, verbose_name='آخر دفتر كميات')),
                ('last_reasons', models.JSONField(blank=True, default=list, verbose_name='آخر أسباب التوصية')),
                ('execution_refs', models.JSONField(blank=True, default=dict, verbose_name='مراجع التنفيذ')),
                ('close_reason', models.CharField(blank=True, max_length=255, verbose_name='سبب الإغلاق')),
                ('notes', models.TextField(blank=True)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أول اكتشاف')),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تقييم')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تغيير حالة')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_cases', to='users.staffprofile', verbose_name='المسؤول')),
                ('availability_lines', models.ManyToManyField(blank=True, related_name='supply_cases', to='supply.availabilityline', verbose_name='عروض الموردين المطابقة')),
                ('branch', models.ForeignKey(blank=True, help_text='فارغ = حالة على مستوى الشبكة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_cases', to='branches.branch', verbose_name='الفرع')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_cases', to='catalog.item', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'حالة نقص / توريد',
                'verbose_name_plural': 'حالات النقص والتوريد',
                'ordering': ['-is_urgent', '-scarcity_score', 'first_detected_at'],
                'indexes': [models.Index(fields=['status', 'is_urgent', 'scarcity_score'], name='sc_queue_idx'), models.Index(fields=['item', 'branch'], name='sc_item_branch_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='supplycase',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False), models.Q(('status__in', ['fulfilled', 'cancelled']), _negated=True)), fields=('item', 'branch'), name='uniq_open_supply_case_branch'),
        ),
        migrations.AddConstraint(
            model_name='supplycase',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True), models.Q(('status__in', ['fulfilled', 'cancelled']), _negated=True)), fields=('item',), name='uniq_open_supply_case_network'),
        ),
    ]
