# Generated by Django 4.2.13 on 2026-09-27 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_staffprofile_notify_expiry_worklist_wa'),
        ('catalog', '0038_item_is_spike_item_spike_confirmed_and_more'),
        ('branches', '0007_backfill_branch_kind'),
        ('invoices', '0012_invoiceline_match_review'),
        ('supply', '0003_supplycase_supplycase_uniq_open_supply_case_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('internal_transfer', 'تحويل داخلي (مسودة)'), ('purchase', 'طلب شراء من مورد')], db_index=True, max_length=20)),
                ('recommended_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الكمية الموصى بها')),
                ('decided_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الكمية المعتمدة')),
                ('is_override', models.BooleanField(db_index=True, default=False, verbose_name='تجاوز للتوصية')),
                ('override_reason', models.CharField(blank=True, max_length=255, verbose_name='سبب التجاوز')),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('foc_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('effective_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('receipt_status', models.CharField(blank=True, choices=[('open', 'بانتظار الاستلام'), ('received', 'تم الاستلام'), ('cancelled', 'ملغى')], db_index=True, max_length=10, verbose_name='حالة الاستلام')),
                ('received_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('recommendation_snapshot', models.JSONField(blank=True, default=dict, verbose_name='لقطة التوصية وقت القرار')),
                ('revalidation', models.JSONField(blank=True, default=dict, verbose_name='نتيجة إعادة التحقق قبل التنفيذ')),
                ('result_refs', models.JSONField(blank=True, default=dict, verbose_name='مراجع التنفيذ (طلبات تحويل / طلب شراء)')),
                ('order_ref', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='مرجع قائمة الطلب')),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='مفتاح منع التكرار')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='supply.availabilityline')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_decisions', to='branches.branch', verbose_name='الفرع المستفيد')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='supply.supplycase', verbose_name='الحالة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_decisions', to='users.staffprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_decisions', to='catalog.item', verbose_name='الصنف')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_decisions', to='invoices.vendorprofile')),
            ],
            options={
                'verbose_name': 'قرار توريد',
                'verbose_name_plural': 'قرارات التوريد',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'receipt_status', 'item'], name='sd_pending_idx'), models.Index(fields=['case', '-created_at'], name='sd_case_idx')],
            },
        ),
    ]
