# Generated by Django 4.2.13 on 2026-10-04 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_item_is_spike_item_spike_confirmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0007_backfill_branch_kind'),
        ('shortage', '0004_branch_requests'),
        ('supply', '0004_supplydecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('whatsapp', 'واتساب')], default='whatsapp', max_length=12)),
                ('group_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المجموعة')),
                ('raw_text', models.TextField(blank=True, verbose_name='النص الملصوق')),
                ('status', models.CharField(choices=[('draft', 'قيد المراجعة'), ('confirmed', 'مؤكَّد'), ('cancelled', 'ملغى')], db_index=True, default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_requests', to='branches.branch', verbose_name='الفرع')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shortage_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_requests', to='shortage.shortagelist')),
            ],
            options={
                'verbose_name': 'طلب فرع (واتساب)',
                'verbose_name_plural': 'طلبات الفروع (واتساب)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('msg_index', models.PositiveIntegerField(default=0)),
                ('msg_sender', models.CharField(blank=True, max_length=120)),
                ('msg_time', models.CharField(blank=True, max_length=40)),
                ('from_ocr', models.BooleanField(default=False)),
                ('raw_text', models.CharField(max_length=500, verbose_name='كما كُتب')),
                ('match_text', models.CharField(blank=True, max_length=300, verbose_name='النص المستخدم للمطابقة')),
                ('kind', models.CharField(choices=[('item', 'صنف'), ('note', 'ملاحظة')], default='item', max_length=6)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('qty_unit', models.CharField(choices=[('pack', 'علبة'), ('strip', 'شريط')], default='pack', max_length=6)),
                ('qty_source', models.CharField(default='default', help_text='unit | count | default | manual', max_length=10)),
                ('all_variants', models.BooleanField(default=False, verbose_name='كل الأنواع')),
                ('score', models.FloatField(blank=True, null=True)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('confirmed', models.BooleanField(default=False)),
                ('picked_by_user', models.BooleanField(default=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.item')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supply.branchrequest')),
            ],
            options={
                'ordering': ['request', 'position'],
            },
        ),
    ]
