# Generated by Django 4.2.13 on 2026-10-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_item_is_spike_item_spike_confirmed_and_more'),
        ('supply', '0005_branch_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchrequestline',
            name='extra_items',
            field=models.ManyToManyField(blank=True, related_name='+', to='catalog.item'),
        ),
    ]
