# Generated by Django 4.2.13 on 2026-10-04 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_branch_request_multi_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityline',
            name='split_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siblings', to='supply.availabilityline', verbose_name='مقسوم من سطر'),
        ),
    ]
