# Generated by Django 4.2.13 on 2026-10-05 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_rolemoduleaccess_module'),
        ('supply', '0007_availability_line_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitybatch',
            name='branch_scope',
            field=models.JSONField(blank=True, default=list, verbose_name='الفروع المستهدفة'),
        ),
        migrations.AddField(
            model_name='availabilitybatch',
            name='lock_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظة الإقفال'),
        ),
        migrations.AddField(
            model_name='availabilitybatch',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='أُقفلت في'),
        ),
        migrations.AddField(
            model_name='availabilitybatch',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile', verbose_name='أقفلها'),
        ),
    ]
