# Generated by Django 4.2.13 on 2026-10-05 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoiceline_match_review'),
        ('users', '0027_alter_rolemoduleaccess_module'),
        ('supply', '0008_availability_scope_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierFileLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_key', models.CharField(db_index=True, max_length=120, verbose_name='المورد (كود SOFTECH أو الاسم)')),
                ('signature', models.CharField(max_length=500, verbose_name='بصمة صف العناوين')),
                ('headers', models.JSONField(blank=True, default=list)),
                ('header_row', models.PositiveSmallIntegerField(default=0, verbose_name='رقم صف العناوين')),
                ('mapping', models.JSONField(default=dict, verbose_name='الأعمدة')),
                ('use_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_layouts', to='invoices.vendorprofile')),
            ],
            options={
                'verbose_name': 'ترتيب أعمدة ملف مورد',
                'verbose_name_plural': 'ترتيبات أعمدة ملفات الموردين',
                'unique_together': {('supplier_key', 'signature')},
            },
        ),
    ]
