# Generated by Django 4.2.13 on 2026-10-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0009_supplier_file_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityline',
            name='bonus_buy',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='البونص: اشترِ'),
        ),
        migrations.AddField(
            model_name='availabilityline',
            name='bonus_tiers',
            field=models.JSONField(blank=True, default=list, verbose_name='شرائح البونص'),
        ),
        migrations.AddField(
            model_name='availabilityline',
            name='promo',
            field=models.CharField(blank=True, max_length=60, verbose_name='عرض داخل العبوة'),
        ),
        migrations.AddField(
            model_name='availabilityline',
            name='quota',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='الكوتة (أقصى طلب)'),
        ),
        migrations.AddField(
            model_name='availabilityline',
            name='signals',
            field=models.JSONField(blank=True, default=list, verbose_name='إشارات التوفر'),
        ),
    ]
