# Generated by Django 4.2.13 on 2026-05-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_purchaseline_tax_rate_pct'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='procurementalert',
            new_name='procurement_is_reso_11d529_idx',
            old_name='proc_alert_resolved_sev_idx',
        ),
        migrations.RenameIndex(
            model_name='procurementalert',
            new_name='procurement_alert_t_ab189a_idx',
            old_name='proc_alert_type_date_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseline',
            new_name='procurement_doc_dat_9deab5_idx',
            old_name='proc_pl_date_supp_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseline',
            new_name='procurement_doc_dat_cea50a_idx',
            old_name='proc_pl_date_item_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseline',
            new_name='procurement_supplie_4516d6_idx',
            old_name='proc_pl_supp_item_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseline',
            new_name='procurement_buyer_c_c835a5_idx',
            old_name='proc_pl_buyer_date_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseline',
            new_name='procurement_is_retu_674d2e_idx',
            old_name='proc_pl_return_date_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseline',
            new_name='procurement_is_foc_4cbc86_idx',
            old_name='proc_pl_foc_date_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseline',
            new_name='procurement_return__dae27e_idx',
            old_name='proc_pl_rettype_date_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseline',
            new_name='procurement_supplie_404a43_idx',
            old_name='proc_pl_cat_date_idx',
        ),
        migrations.RenameIndex(
            model_name='supplieritemmapping',
            new_name='procurement_supplie_5aac85_idx',
            old_name='proc_sim_supp_primary_idx',
        ),
        migrations.RenameIndex(
            model_name='supplieritemmapping',
            new_name='procurement_item_co_10d92a_idx',
            old_name='proc_sim_item_conf_idx',
        ),
        migrations.RenameIndex(
            model_name='supplieritemmapping',
            new_name='procurement_last_pu_ae5d1f_idx',
            old_name='proc_sim_last_purchase_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierprofile',
            new_name='procurement_total_s_e3e46e_idx',
            old_name='proc_supp_score_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierprofile',
            new_name='procurement_avg_mar_31eb6a_idx',
            old_name='proc_supp_margin_idx',
        ),
        migrations.RenameIndex(
            model_name='suppliersegmentation',
            new_name='procurement_supplie_09315f_idx',
            old_name='proc_seg_cat_val_idx',
        ),
        migrations.AlterField(
            model_name='buyerperformance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='procurementalert',
            name='alert_type',
            field=models.CharField(choices=[('price_spike', 'ارتفاع مفاجئ في السعر'), ('price_drop', 'انخفاض مفاجئ في السعر'), ('high_return_rate', 'معدل مرتجعات عالٍ'), ('supplier_overpriced', 'مورد بسعر أعلى من السوق'), ('low_margin', 'هامش ربح منخفض'), ('preferred_supplier', 'مورد مفضل متاح'), ('missed_discount', 'خصم فائت'), ('price_drift', 'تذبذب في الأسعار'), ('high_concentration', 'تركز عالٍ على مورد واحد'), ('stockout_risk', 'خطر نفاد المخزون'), ('foc_deterioration', 'تراجع في منح البضاعة المجانية'), ('tax_spike', 'ارتفاع حاد في الضرائب'), ('expiry_return_spike', 'ارتفاع في مرتجعات التالف'), ('patient_purchases_rising', 'ارتفاع المشتريات من المرضى'), ('warehouse_dependency', 'اعتماد مفرط على مستودعات صغيرة')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='procurementalert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='procurementenginerun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='procurementsnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='tax_rate_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='supplieritemmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='suppliersegmentation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
