# Generated by Django 4.2.13 on 2026-05-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_supplier_lost_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierprofile',
            name='avoidable_loss_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lost revenue where root_cause=supplier AND this supplier is primary', max_digits=18, verbose_name='الإيراد الضائع المنسوب للمورد (30 يوم) ج.م'),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='service_level_pct',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='(expected - lost_qty) / expected × 100 for items supplied by this vendor', max_digits=6, verbose_name='مستوى الخدمة % (30 يوم)'),
        ),
    ]
