# Generated by Django 4.2.13 on 2026-06-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_supplierprofile_avoidable_loss_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementalert',
            name='alert_type',
            field=models.CharField(choices=[('price_spike', 'ارتفاع مفاجئ في السعر'), ('price_drop', 'انخفاض مفاجئ في السعر'), ('high_return_rate', 'معدل مرتجعات عالٍ'), ('supplier_overpriced', 'مورد بسعر أعلى من السوق'), ('low_margin', 'هامش ربح منخفض'), ('preferred_supplier', 'مورد مفضل متاح'), ('missed_discount', 'خصم فائت'), ('price_drift', 'تذبذب في الأسعار'), ('high_concentration', 'تركز عالٍ على مورد واحد'), ('stockout_risk', 'خطر نفاد المخزون'), ('foc_deterioration', 'تراجع في منح البضاعة المجانية'), ('tax_spike', 'ارتفاع حاد في الضرائب'), ('expiry_return_spike', 'ارتفاع في مرتجعات التالف'), ('demand_reorder', 'طلب شراء مدفوع بطلب العملاء'), ('patient_purchases_rising', 'ارتفاع المشتريات من المرضى'), ('warehouse_dependency', 'اعتماد مفرط على مستودعات صغيرة')], db_index=True, max_length=30),
        ),
    ]
