# Generated by Django 4.2.13 on 2026-08-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_alter_procurementalert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='bonus_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
