# Generated by Django 4.2.13 on 2026-08-17 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_purchaseline_bonus_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Stable key stored on purchase lines / suppliers (e.g. OFFICIAL_DISTRIBUTOR)', max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('color', models.CharField(blank=True, default='', help_text='Tailwind badge tone key, e.g. "blue", "green", "amber" (UI hint)', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_fallback', models.BooleanField(default=False, help_text='The catch-all category assigned when no rule matches (only one).')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فئة مورد',
                'verbose_name_plural': 'فئات الموردين',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SupplierClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptcode', models.CharField(db_index=True, max_length=10, verbose_name='كود نوع الشخص')),
                ('ptclassifcode', models.CharField(blank=True, db_index=True, default='', max_length=10, verbose_name='كود التصنيف (فارغ = كل التصنيفات تحت النوع)')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower wins when multiple rules match.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='procurement.suppliercategory')),
            ],
            options={
                'verbose_name': 'قاعدة تصنيف مورد',
                'verbose_name_plural': 'قواعد تصنيف الموردين',
                'ordering': ['ptcode', 'ptclassifcode'],
                'indexes': [models.Index(fields=['ptcode', 'ptclassifcode', 'is_active'], name='procurement_ptcode_9912f0_idx')],
                'unique_together': {('ptcode', 'ptclassifcode')},
            },
        ),
    ]
