# Generated by Django 4.2.13 on 2026-06-02 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_rolemoduleaccess_role_alter_staffprofile_role'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceParentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العميل الأب')),
                ('name_short', models.CharField(blank=True, max_length=60, verbose_name='الاسم المختصر')),
                ('softech_personcode', models.CharField(blank=True, db_index=True, help_text='personcode الرئيسي الجامع في سوفتك (إن وُجد)', max_length=20, verbose_name='كود العميل الأب في سوفتك')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عميل أب',
                'verbose_name_plural': 'العملاء الآباء',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='dept_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='اسم الإدارة'),
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الفحص'),
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='file_no',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم الملف'),
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='financial_no',
            field=models.CharField(blank=True, max_length=15, verbose_name='الرقم المالي'),
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='hi_type_code',
            field=models.CharField(blank=True, max_length=2, verbose_name='نوع التأمين الصحي'),
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='membership_no',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم العضوية'),
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='patient_no',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم المريض'),
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='relative_degree',
            field=models.CharField(blank=True, help_text='للعضو / للزوجة / للأبناء', max_length=20, verbose_name='درجة القرابة'),
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='roshetta_no',
            field=models.CharField(blank=True, db_index=True, max_length=15, verbose_name='رقم الروشتة'),
        ),
        migrations.CreateModel(
            name='MotalbaCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personcode', models.CharField(db_index=True, max_length=8, verbose_name='كود العميل')),
                ('motalbano', models.IntegerField(db_index=True, verbose_name='رقم المطالبة')),
                ('branchcode', models.CharField(max_length=5, verbose_name='الفرع')),
                ('docnumber', models.CharField(db_index=True, max_length=10, verbose_name='رقم الفاتورة')),
                ('docdate', models.DateField(db_index=True, verbose_name='تاريخ الصرف')),
                ('motalbasdate', models.DateField(blank=True, null=True, verbose_name='بداية فترة المطالبة')),
                ('motalbafdate', models.DateField(blank=True, null=True, verbose_name='نهاية فترة المطالبة')),
                ('doccode', models.CharField(help_text='115=بيع, 30=مرتجع', max_length=3, verbose_name='كود المستند')),
                ('docvalue_grandtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالى سعر الجمهور')),
                ('docvaluerequired', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المطلوب')),
                ('motalba_docorder', models.SmallIntegerField(default=0, verbose_name='ترتيب في المطالبة')),
                ('ppersoncode', models.CharField(blank=True, max_length=8, verbose_name='كود المريض')),
                ('patientcode', models.IntegerField(blank=True, null=True, verbose_name='كود المريض (int)')),
                ('custbranchcode', models.CharField(blank=True, max_length=5, verbose_name='فرع العميل')),
                ('usercode', models.CharField(blank=True, max_length=5, verbose_name='كود المستخدم')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='آخر مزامنة')),
            ],
            options={
                'verbose_name': 'كاش مطالبة',
                'verbose_name_plural': 'كاش المطالبات',
                'indexes': [models.Index(fields=['personcode', 'motalbano'], name='insurance_m_personc_562f8d_idx'), models.Index(fields=['docdate'], name='insurance_m_docdate_18093b_idx'), models.Index(fields=['docnumber', 'branchcode'], name='insurance_m_docnumb_421ddb_idx')],
                'unique_together': {('personcode', 'motalbano', 'branchcode', 'docnumber', 'doccode')},
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaimBillingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مثال: CASH, INS, DEPT-ADMIN — يُستخدم كـ sub-personcode في التقارير', max_length=20, verbose_name='كود الفئة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('filter_relative_degree', models.CharField(blank=True, help_text='مثال: للعضو، للزوجة، للأبناء (من companiesitems.relativedegree)', max_length=20, verbose_name='تصفية حسب درجة القرابة')),
                ('filter_dept_name', models.CharField(blank=True, help_text='companiesitems.deptname', max_length=40, verbose_name='تصفية حسب الإدارة')),
                ('filter_hi_type_code', models.CharField(blank=True, help_text='companiesitems.hi_typecode', max_length=1, verbose_name='تصفية حسب نوع التأمين')),
                ('filter_patient_no_prefix', models.CharField(blank=True, help_text='مثال: A للموظفين، R للمتقاعدين', max_length=10, verbose_name='تصفية حسب بادئة رقم المريض')),
                ('rx_count', models.PositiveIntegerField(default=0, verbose_name='عدد الروشتات')),
                ('gross_before', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالى قبل الخصم')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالى الخصم')),
                ('net_after', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='صافى الفاتورة')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_groups', to='insurance.insuranceclaim', verbose_name='المطالبة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile', verbose_name='أُنشئت بواسطة')),
            ],
            options={
                'verbose_name': 'فئة فوترة',
                'verbose_name_plural': 'فئات الفوترة',
                'ordering': ['claim', 'sort_order', 'code'],
                'unique_together': {('claim', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CompaniesItemsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchcode', models.CharField(db_index=True, max_length=5, verbose_name='الفرع')),
                ('docnumber', models.CharField(db_index=True, max_length=10, verbose_name='رقم الفاتورة')),
                ('doccode', models.CharField(max_length=3, verbose_name='كود المستند')),
                ('docdate', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الصرف')),
                ('patientname', models.CharField(blank=True, max_length=40, verbose_name='اسم المريض')),
                ('patientno', models.CharField(blank=True, max_length=15, verbose_name='رقم المريض')),
                ('financialno', models.CharField(blank=True, max_length=10, verbose_name='الرقم المالي')),
                ('fileno', models.CharField(blank=True, max_length=10, verbose_name='رقم الملف')),
                ('roshettano', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='رقم الروشتة')),
                ('membershipno', models.CharField(blank=True, max_length=10, verbose_name='رقم العضوية')),
                ('deptname', models.CharField(blank=True, max_length=40, verbose_name='اسم الإدارة')),
                ('relativedegree', models.CharField(blank=True, max_length=20, verbose_name='درجة القرابة')),
                ('hi_typecode', models.CharField(blank=True, max_length=2, verbose_name='نوع التأمين الصحي')),
                ('examdate', models.DateField(blank=True, null=True, verbose_name='تاريخ الفحص')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='آخر مزامنة')),
            ],
            options={
                'verbose_name': 'كاش بيانات المرضى',
                'verbose_name_plural': 'كاش بيانات المرضى',
                'indexes': [models.Index(fields=['docnumber', 'branchcode'], name='insurance_c_docnumb_bf9a11_idx'), models.Index(fields=['docdate'], name='insurance_c_docdate_6c343e_idx')],
                'unique_together': {('branchcode', 'docnumber', 'doccode')},
            },
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='billing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='insurance.insuranceclaimbillinggroup', verbose_name='فئة الفوترة'),
        ),
        migrations.AddField(
            model_name='insuranceclient',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='insurance.insuranceparentclient', verbose_name='العميل الأب'),
        ),
    ]
