# Generated by Django 4.2.13 on 2026-06-03 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_rolemoduleaccess_role_alter_staffprofile_role'),
        ('insurance', '0002_parent_client_billing_groups_companiesitems_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceApplyMasterRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التطبيق')),
                ('apply_price', models.BooleanField(default=True, verbose_name='طُبِّقت الأسعار')),
                ('apply_category', models.BooleanField(default=True, verbose_name='طُبِّق التصنيف')),
                ('lines_updated', models.PositiveIntegerField(default=0, verbose_name='بنود محدَّثة')),
                ('prescriptions_updated', models.PositiveIntegerField(default=0, verbose_name='روشتات محدَّثة')),
                ('net_before', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الصافى قبل')),
                ('net_after', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الصافى بعد')),
                ('reverted', models.BooleanField(default=False, verbose_name='تم التراجع')),
                ('reverted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التراجع')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile', verbose_name='طُبِّق بواسطة')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_runs', to='insurance.insuranceclaim', verbose_name='المطالبة')),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile', verbose_name='تراجع بواسطة')),
            ],
            options={
                'verbose_name': 'تطبيق بيانات الكتالوج',
                'verbose_name_plural': 'عمليات تطبيق بيانات الكتالوج',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaimLineBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=10, verbose_name='التصنيف')),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='السعر')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالى')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم %')),
                ('discount_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الخصم')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الصافى')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='insurance.insuranceclaimline', verbose_name='البند')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_backups', to='insurance.insuranceapplymasterrun', verbose_name='عملية التطبيق')),
            ],
            options={
                'verbose_name': 'نسخة بند (تطبيق)',
                'verbose_name_plural': 'نسخ البنود (تطبيق)',
                'indexes': [models.Index(fields=['run', 'line'], name='insurance_i_run_id_1156d4_idx')],
            },
        ),
    ]
