# Generated by Django 4.2.13 on 2026-06-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_apply_master_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceapplymasterrun',
            name='pre_state',
            field=models.JSONField(blank=True, null=True, verbose_name='الحالة قبل التطبيق'),
        ),
    ]
