# Generated by Django 4.2.13 on 2026-06-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_apply_run_pre_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceExportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الملف')),
                ('is_default', models.BooleanField(default=False, help_text='يُطبَّق على كل المطالبات ما لم توجد قواعد أخص', verbose_name='الافتراضي العام')),
                ('header_left', models.TextField(blank=True, default='', verbose_name='ترويسة - يسار')),
                ('header_center', models.TextField(blank=True, default='', verbose_name='ترويسة - وسط')),
                ('header_right', models.TextField(blank=True, default='', verbose_name='ترويسة - يمين')),
                ('footer_left', models.TextField(blank=True, default='', verbose_name='تذييل - يسار')),
                ('footer_center', models.TextField(blank=True, default='صفحة {page} من {pages}', verbose_name='تذييل - وسط')),
                ('footer_right', models.TextField(blank=True, default='', verbose_name='تذييل - يمين')),
                ('font_name', models.CharField(default='Arial', max_length=40, verbose_name='الخط')),
                ('header_font_size', models.PositiveSmallIntegerField(default=10, verbose_name='حجم خط العناوين')),
                ('header_fill', models.CharField(default='1F4E79', max_length=6, verbose_name='لون تعبئة العناوين')),
                ('header_font_color', models.CharField(default='FFFFFF', max_length=6, verbose_name='لون خط العناوين')),
                ('subtotal_font_size', models.PositiveSmallIntegerField(default=10, verbose_name='حجم خط المجاميع اليومية')),
                ('subtotal_fill', models.CharField(default='D6E4F0', max_length=6, verbose_name='لون تعبئة المجاميع اليومية')),
                ('total_font_size', models.PositiveSmallIntegerField(default=11, verbose_name='حجم خط الإجمالى')),
                ('total_fill', models.CharField(default='E2EFDA', max_length=6, verbose_name='لون تعبئة الإجمالى')),
                ('border_style', models.CharField(choices=[('none', 'بدون'), ('thin', 'رفيع'), ('medium', 'متوسط'), ('thick', 'سميك')], default='thin', max_length=8, verbose_name='سُمك الإطار')),
                ('day_block_blank_rows', models.PositiveSmallIntegerField(default=4, verbose_name='أسطر فارغة بين الأيام')),
                ('repeat_header_each_page', models.BooleanField(default=True, verbose_name='تكرار العناوين بكل صفحة')),
                ('base_template_note', models.TextField(blank=True, default='', verbose_name='ملاحظات القالب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subclient', models.ForeignKey(blank=True, help_text='اتركه فارغاً ليكون ملفاً عاماً', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_profiles', to='insurance.insurancesubclient', verbose_name='خاص بالفئة')),
            ],
            options={
                'verbose_name': 'ملف طباعة المطالبة',
                'verbose_name_plural': 'ملفات طباعة المطالبات',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
