# Generated by Django 4.2.13 on 2026-06-03 14:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_export_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceexportprofile',
            name='watermark_anchor',
            field=models.CharField(default='C15', help_text='خلية الإرساء، مثل C15', max_length=6, verbose_name='موضع العلامة المائية'),
        ),
        migrations.AddField(
            model_name='insuranceexportprofile',
            name='watermark_image',
            field=models.FileField(blank=True, help_text='يُفضَّل صورة فاتحة/شفافة لتظهر كعلامة مائية خلف البيانات', null=True, upload_to='insurance/watermarks/', verbose_name='صورة العلامة المائية (PNG)'),
        ),
        migrations.AddField(
            model_name='insuranceexportprofile',
            name='watermark_width_cm',
            field=models.DecimalField(decimal_places=1, default=Decimal('8.0'), max_digits=5, verbose_name='عرض العلامة المائية (سم)'),
        ),
    ]
