# Generated by Django 4.2.13 on 2026-06-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_rolemoduleaccess_role_alter_staffprofile_role'),
        ('insurance', '0006_watermark'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePivotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('source', models.CharField(default='prescriptions', max_length=20, verbose_name='المصدر')),
                ('row_dim', models.CharField(max_length=30, verbose_name='تجميع الصفوف')),
                ('col_dim', models.CharField(blank=True, default='', max_length=30, verbose_name='تجميع الأعمدة')),
                ('measure', models.CharField(default='net', max_length=20, verbose_name='المقياس')),
                ('is_shared', models.BooleanField(default=True, verbose_name='متاح للجميع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile', verbose_name='أُنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'قالب تحليل',
                'verbose_name_plural': 'قوالب التحليل',
                'ordering': ['name'],
            },
        ),
    ]
