# Generated by Django 4.2.13 on 2026-06-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_pivot_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='softech_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='صافى سوفتك (مرجعي)'),
        ),
    ]
