# Generated by Django 4.2.13 on 2026-08-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_rolemoduleaccess_module'),
        ('insurance', '0008_insuranceclaimprescription_softech_net'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceItemClassificationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, help_text='itemcode في سوفتك', max_length=10, unique=True, verbose_name='كود الصنف')),
                ('item_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الصنف')),
                ('forced_category', models.CharField(choices=[('local', 'محلى'), ('imported', 'مستورد'), ('tarsia', 'ترسية')], default='local', max_length=10, verbose_name='التصنيف الصحيح')),
                ('is_active', models.BooleanField(default=True, verbose_name='مُفعَّل')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='سبب التصويب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile', verbose_name='أُنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'تصويب تصنيف صنف',
                'verbose_name_plural': 'تصويبات تصنيف الأصناف',
                'ordering': ['item_code'],
            },
        ),
    ]
