# Generated by Django 4.2.13 on 2026-08-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_insuranceitemclassificationoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceitemclassificationoverride',
            name='mode',
            field=models.CharField(choices=[('force', 'فرض تصنيف موحّد'), ('review', 'مراجعة يدوية لكل مطالبة (منشأ مزدوج)')], default='force', max_length=10, verbose_name='النوع'),
        ),
    ]
