# Generated by Django 4.2.13 on 2026-08-02 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_insuranceitemclassificationoverride_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaimmanualrx',
            name='billing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_rx', to='insurance.insuranceclaimbillinggroup', verbose_name='فئة الفوترة'),
        ),
    ]
