# Generated by Django 4.2.13 on 2026-08-02 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_insuranceclaimmanualrx_billing_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaimsupplement',
            name='billing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplements', to='insurance.insuranceclaimbillinggroup', verbose_name='فئة الفوترة'),
        ),
    ]
