# Generated by Django 4.2.13 on 2026-08-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_insuranceclaimsupplement_billing_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaimmanualrx',
            name='is_excluded',
            field=models.BooleanField(default=False, verbose_name='مُستثناة'),
        ),
        migrations.AddField(
            model_name='insuranceclaimmanualrx',
            name='is_manually_edited',
            field=models.BooleanField(default=False, verbose_name='عُدِّلت يدوياً'),
        ),
    ]
