# Generated by Django 4.2.13 on 2026-08-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_insuranceclaimmanualrx_is_excluded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaimsupplement',
            name='is_excluded',
            field=models.BooleanField(default=False, verbose_name='مُستثنى'),
        ),
        migrations.AddField(
            model_name='insuranceclaimsupplement',
            name='is_manually_edited',
            field=models.BooleanField(default=False, verbose_name='عُدِّل يدوياً'),
        ),
    ]
