# Generated by Django 4.2.13 on 2026-08-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0014_insuranceclaimsupplement_is_excluded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaimline',
            name='is_manually_edited',
            field=models.BooleanField(default=False, verbose_name='عُدِّل يدوياً'),
        ),
        migrations.AddField(
            model_name='insuranceclaimline',
            name='original_json',
            field=models.JSONField(blank=True, null=True, verbose_name='القيم الأصلية'),
        ),
    ]
