# Generated by Django 4.2.13 on 2026-08-31 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_rolemoduleaccess_module'),
        ('insurance', '0015_insuranceclaimline_is_manually_edited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceSeparationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='مثال: شركة الخدمات الطبية', max_length=150, verbose_name='اسم القائمة')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مُفعَّلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile', verbose_name='أُنشئت بواسطة')),
            ],
            options={
                'verbose_name': 'قائمة فصل أسماء',
                'verbose_name_plural': 'قوائم فصل الأسماء',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceSeparationName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('normalized', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='الاسم المُعيَّر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مُفعَّل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sep_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='insurance.insuranceseparationlist', verbose_name='القائمة')),
            ],
            options={
                'verbose_name': 'اسم للفصل',
                'verbose_name_plural': 'أسماء للفصل',
                'ordering': ['name'],
            },
        ),
    ]
