# Generated by Django 4.2.13 on 2026-09-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0016_insuranceseparationlist_insuranceseparationname'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='separation_reviewed',
            field=models.BooleanField(default=False, verbose_name='روجعت (فصل الأسماء)'),
        ),
    ]
