# Generated by Django 4.2.13 on 2026-09-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0017_insuranceclaimprescription_separation_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceapplymasterrun',
            name='scope_line_ids',
            field=models.JSONField(blank=True, null=True, verbose_name='بنود محددة'),
        ),
    ]
