# Generated by Django 4.2.13 on 2026-09-01 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_rolemoduleaccess_module'),
        ('insurance', '0018_insuranceapplymasterrun_scope_line_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile', verbose_name='أُضيفت بواسطة'),
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='مضافة يدوياً (تفصيلية)'),
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='manual_position',
            field=models.CharField(blank=True, max_length=10, verbose_name='موضع الطباعة (يدوي)'),
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='manual_print_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الطباعة (يدوي)'),
        ),
        migrations.AddField(
            model_name='insuranceclaimprescription',
            name='manual_reason',
            field=models.TextField(blank=True, verbose_name='سبب الإضافة اليدوية'),
        ),
    ]
