# Generated by Django 4.2.13 on 2026-09-02 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_rolemoduleaccess_module'),
        ('insurance', '0019_insuranceclaimprescription_added_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_change', 'تغيير الحالة'), ('apply_master', 'تطبيق بيانات الكتالوج'), ('apply_overrides', 'تطبيق تصويبات التصنيف'), ('apply_review', 'قرار صنف مزدوج المنشأ'), ('revert_apply', 'تراجع عن تطبيق'), ('line_edit', 'تعديل بند'), ('line_reset', 'استرجاع بند'), ('patient_edit', 'تعديل اسم المريض'), ('rx_adjust', 'تعديل قيم روشتة'), ('rx_exclude', 'استثناء/إدراج روشتة'), ('manual_add', 'إضافة يدوية'), ('manual_delete', 'حذف إضافة يدوية'), ('supplement', 'ملحق'), ('payment', 'تحصيل'), ('deduction', 'خصم/استقطاع'), ('billing_group', 'فئة فوترة'), ('bulk_exclude', 'استبعاد جماعي (فصل)'), ('other', 'أخرى')], db_index=True, max_length=30, verbose_name='الإجراء')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='الوقت')),
                ('actor_name', models.CharField(blank=True, max_length=150, verbose_name='اسم المُنفِّذ')),
                ('target_type', models.CharField(blank=True, max_length=30, verbose_name='نوع الهدف')),
                ('target_ref', models.CharField(blank=True, max_length=60, verbose_name='مرجع الهدف')),
                ('summary', models.CharField(max_length=300, verbose_name='الملخص')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='قبل')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='بعد')),
                ('meta', models.JSONField(blank=True, null=True, verbose_name='تفاصيل')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile', verbose_name='بواسطة')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='insurance.insuranceclaim', verbose_name='المطالبة')),
            ],
            options={
                'verbose_name': 'حدث تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['claim', '-at'], name='insurance_i_claim_i_a1ad86_idx'), models.Index(fields=['action', '-at'], name='insurance_i_action_af5918_idx')],
            },
        ),
    ]
