# Generated by Django 4.2.13 on 2026-09-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0021_insuranceclaimline_review_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceauditevent',
            name='action',
            field=models.CharField(choices=[('status_change', 'تغيير الحالة'), ('apply_master', 'تطبيق بيانات الكتالوج'), ('apply_overrides', 'تطبيق تصويبات التصنيف'), ('apply_review', 'قرار صنف مزدوج المنشأ'), ('revert_apply', 'تراجع عن تطبيق'), ('line_edit', 'تعديل بند'), ('line_reset', 'استرجاع بند'), ('line_review', 'اعتماد مراجعة بند'), ('gross_repair', 'إصلاح إجمالى العبوات الجزئية'), ('patient_edit', 'تعديل اسم المريض'), ('rx_adjust', 'تعديل قيم روشتة'), ('rx_exclude', 'استثناء/إدراج روشتة'), ('manual_add', 'إضافة يدوية'), ('manual_delete', 'حذف إضافة يدوية'), ('supplement', 'ملحق'), ('payment', 'تحصيل'), ('deduction', 'خصم/استقطاع'), ('billing_group', 'فئة فوترة'), ('bulk_exclude', 'استبعاد جماعي (فصل)'), ('other', 'أخرى')], db_index=True, max_length=30, verbose_name='الإجراء'),
        ),
    ]
