# Generated by Django 4.2.13 on 2026-09-13 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_staffprofile_notify_expiry_worklist_wa'),
        ('insurance', '0022_alter_insuranceauditevent_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftechRepriceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docnumber', models.CharField(max_length=20, verbose_name='رقم الإيصال')),
                ('branchcode', models.CharField(max_length=10, verbose_name='الفرع')),
                ('doccode', models.CharField(default='115', max_length=10)),
                ('cust_branch_code', models.CharField(blank=True, max_length=20, verbose_name='عميل التعاقد')),
                ('status', models.CharField(choices=[('preview', 'معاينة'), ('applied', 'مُطبَّق'), ('reverted', 'مُتراجَع'), ('failed', 'فشل')], db_index=True, default='preview', max_length=10)),
                ('new_prices', models.JSONField(default=dict, verbose_name='الأسعار الجديدة')),
                ('net_delta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nodes', models.JSONField(default=list, verbose_name='العُقد')),
                ('rebalanced', models.BooleanField(default=False, verbose_name='أُعيد ضبط الرصيد')),
                ('rebalance_count', models.PositiveIntegerField(default=0)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softech_reprice_runs', to='insurance.insuranceclaim')),
            ],
            options={
                'verbose_name': 'عملية تعديل سعر سوفتك',
                'verbose_name_plural': 'عمليات تعديل سعر سوفتك',
                'ordering': ['-applied_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SoftechRepriceEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=10)),
                ('table', models.CharField(max_length=20)),
                ('row_key', models.JSONField(default=dict)),
                ('field', models.CharField(max_length=40)),
                ('before', models.CharField(blank=True, max_length=60)),
                ('after', models.CharField(blank=True, max_length=60)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='insurance.softechrepricerun')),
            ],
            options={
                'verbose_name': 'تعديل حقل سوفتك',
            },
        ),
        migrations.AddIndex(
            model_name='softechrepricerun',
            index=models.Index(fields=['docnumber', 'branchcode'], name='insurance_s_docnumb_836ea5_idx'),
        ),
        migrations.AddIndex(
            model_name='softechrepriceedit',
            index=models.Index(fields=['run'], name='insurance_s_run_id_d07f37_idx'),
        ),
    ]
