# Generated by Django 4.2.13 on 2026-09-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0023_softechrepricerun_softechrepriceedit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaimline',
            name='softech_line_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='صافى سوفتك للبند'),
        ),
    ]
