# Generated by Django 4.2.13 on 2026-09-30 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_staffprofile_notify_expiry_worklist_wa'),
        ('insurance', '0027_manualrx_softech_patient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'مُطبَّق'), ('reverted', 'مُتراجَع')], db_index=True, default='applied', max_length=10)),
                ('added', models.PositiveIntegerField(default=0)),
                ('removed', models.PositiveIntegerField(default=0)),
                ('changed', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'عملية مزامنة سوفتك',
                'ordering': ['-applied_at', '-id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='insuranceclaimmanualrx',
            name='ins_mrx_pname_trgm',
        ),
        migrations.RemoveIndex(
            model_name='insuranceclaimprescription',
            name='ins_rx_pname_trgm',
        ),
        migrations.AddField(
            model_name='resyncrun',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile'),
        ),
        migrations.AddField(
            model_name='resyncrun',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resync_runs', to='insurance.insuranceclaim'),
        ),
    ]
