# Generated by Django 4.2.13 on 2026-09-30 14:48

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0028_resyncrun_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='insuranceclaimmanualrx',
            index=django.contrib.postgres.indexes.GinIndex(fields=['patient_name'], name='ins_mrx_pname_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='insuranceclaimprescription',
            index=django.contrib.postgres.indexes.GinIndex(fields=['patient_name'], name='ins_rx_pname_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
