# Generated by Django 4.2.13 on 2026-09-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_staffprofile_notify_expiry_worklist_wa'),
        ('insurance', '0029_insuranceclaimmanualrx_ins_mrx_pname_trgm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftechDateEditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docnumber', models.CharField(max_length=20, verbose_name='رقم الإيصال')),
                ('branchcode', models.CharField(max_length=10, verbose_name='الفرع')),
                ('doccode', models.CharField(default='115', max_length=10)),
                ('old_date', models.DateField(verbose_name='التاريخ الأصلي')),
                ('new_date', models.DateField(verbose_name='التاريخ الجديد')),
                ('nodes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('applied', 'مُطبَّق'), ('reverted', 'مُتراجَع'), ('failed', 'فشل')], db_index=True, default='applied', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='softech_date_runs', to='insurance.insuranceclaim')),
            ],
            options={
                'verbose_name': 'تعديل تاريخ إيصال سوفتك',
                'ordering': ['-applied_at', '-id'],
                'indexes': [models.Index(fields=['docnumber', 'branchcode'], name='insurance_s_docnumb_0bbbb9_idx')],
            },
        ),
    ]
