# Generated by Django 4.2.13 on 2026-05-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_pharmacyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
