# Generated by Django 4.2.13 on 2026-05-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='finance_acc_account_3b66f3_idx',
            old_name='finance_acc_account_type_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='finance_acc_parent__2ec6f3_idx',
            old_name='finance_acc_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='accountbalance',
            new_name='finance_acc_period__b220c3_idx',
            old_name='finance_ab_period_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='accountbalance',
            new_name='finance_acc_account_83d7f4_idx',
            old_name='finance_ab_account_period_idx',
        ),
        migrations.RenameIndex(
            model_name='expenserecord',
            new_name='finance_exp_expense_57c3b8_idx',
            old_name='finance_er_date_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='expenserecord',
            new_name='finance_exp_categor_0ce43d_idx',
            old_name='finance_er_category_idx',
        ),
        migrations.RenameIndex(
            model_name='expenserecord',
            new_name='finance_exp_period__11be94_idx',
            old_name='finance_er_period_idx',
        ),
        migrations.RenameIndex(
            model_name='financialsnapshot',
            new_name='finance_fin_period__185684_idx',
            old_name='finance_fs_period_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='finance_jou_entry_d_a79140_idx',
            old_name='finance_je_date_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='finance_jou_entry_t_784f15_idx',
            old_name='finance_je_entry_type_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='finance_jou_period__84c4bb_idx',
            old_name='finance_je_period_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='finance_jou_softech_312f21_idx',
            old_name='finance_je_softech_idx',
        ),
        migrations.RenameIndex(
            model_name='treasurymovement',
            new_name='finance_tre_movemen_b26e71_idx',
            old_name='finance_tm_date_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='treasurymovement',
            new_name='finance_tre_directi_d152a9_idx',
            old_name='finance_tm_direction_idx',
        ),
        migrations.RenameIndex(
            model_name='treasurymovement',
            new_name='finance_tre_payment_d6574d_idx',
            old_name='finance_tm_method_idx',
        ),
        migrations.RenameIndex(
            model_name='treasurymovement',
            new_name='finance_tre_period__5d4cc8_idx',
            old_name='finance_tm_period_idx',
        ),
        migrations.RenameIndex(
            model_name='treasurymovement',
            new_name='finance_tre_party_c_575ebf_idx',
            old_name='finance_tm_party_idx',
        ),
        migrations.RenameIndex(
            model_name='treasurymovement',
            new_name='finance_tre_softech_4ab8fe_idx',
            old_name='finance_tm_softech_idx',
        ),
    ]
