# Generated by Django 4.2.13 on 2026-05-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_widen_margin_pct_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialsnapshot',
            name='gross_margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialsnapshot',
            name='net_margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
