# Generated by Django 4.2.13 on 2026-09-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_allocation_apinvoice_matchcandidate_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apinvoice',
            name='person_new_bal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='trans_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='trans_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
