# Generated by Django 4.2.13 on 2026-09-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_apinvoice_person_new_bal_apinvoice_trans_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconexception',
            name='exception_type',
            field=models.CharField(choices=[('duplicate_payment', 'سند مكرر'), ('duplicate_invoice', 'فاتورة مكررة'), ('overpayment', 'دفع زائد'), ('underpayment', 'دفع ناقص'), ('unpaid_old', 'فاتورة قديمة غير مسددة'), ('orphan_payment', 'سند بلا فاتورة'), ('paid_no_link', 'مسدد بلا ربط'), ('balance_mismatch', 'فرق رصيد غير مفسَّر'), ('reused_reference', 'مرجع مُعاد استخدامه'), ('supplier_mismatch', 'عدم تطابق الطرف'), ('cancelled_reversed', 'ملغى/معكوس'), ('misallocation', 'ربط خاطئ (تبادل فواتير)'), ('anomaly', 'شذوذ')], db_index=True, max_length=20),
        ),
    ]
