# Generated by Django 4.2.13 on 2026-09-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_reconexception_exception_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchcandidate',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='matchcandidate',
            name='strategy',
            field=models.CharField(choices=[('pairwise', 'مطابقة مباشرة (مرجع/مبلغ)'), ('multi_ref', 'سند يذكر عدة فواتير'), ('exact_unique', 'مبلغ مطابق فريد'), ('subset_oldest', 'سداد بالأقدم (مجموع فواتير)'), ('subset_window', 'مجموع فواتير متتالية'), ('installments', 'أقساط لفاتورة واحدة'), ('fifo_residual', 'توزيع المتبقي بالأقدم')], db_index=True, default='pairwise', max_length=20),
        ),
    ]
