# Generated by Django 4.2.13 on 2026-09-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_matchcandidate_strategy_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchcandidate',
            name='strategy',
            field=models.CharField(choices=[('pairwise', 'مطابقة مباشرة (مرجع/مبلغ)'), ('multi_ref', 'سند يذكر عدة فواتير'), ('exact_unique', 'مبلغ مطابق فريد'), ('same_amount_nearest', 'نفس المبلغ — الأقرب تاريخًا'), ('subset_oldest', 'سداد بالأقدم (مجموع فواتير)'), ('subset_window', 'مجموع فواتير متتالية'), ('installments', 'أقساط لفاتورة واحدة'), ('fifo_residual', 'توزيع المتبقي بالأقدم')], db_index=True, default='pairwise', max_length=20),
        ),
    ]
