# Generated by Django 4.2.13 on 2026-09-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_strategy_same_amount_nearest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='chain_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='payment',
            name='chain_note',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='payment',
            name='chain_role',
            field=models.CharField(blank=True, choices=[('', '—'), ('reversed', 'سند صرف مُلغى بسند مقبوضات'), ('reversal', 'سند مقبوضات يلغي سند صرف'), ('reissue', 'سند صرف تصحيحي بعد الإلغاء'), ('refund', 'مقبوضات (استرداد من المورد)')], db_index=True, default='', max_length=10),
        ),
    ]
