# Generated by Django 4.2.13 on 2026-09-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_payment_chain_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_branchcode', models.CharField(max_length=5)),
                ('purchase_docnumber', models.CharField(max_length=20)),
                ('purchase_docdate', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_by', to='finance.apinvoice')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_links', to='finance.apinvoice')),
            ],
            options={
                'verbose_name': 'ربط مرتجع بفاتورة شراء',
                'verbose_name_plural': 'روابط المرتجعات',
            },
        ),
        migrations.AddConstraint(
            model_name='returnlink',
            constraint=models.UniqueConstraint(fields=('return_invoice', 'purchase_branchcode', 'purchase_docnumber', 'purchase_docdate'), name='uq_returnlink_key'),
        ),
    ]
