# Generated by Django 4.2.13 on 2026-09-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_strategy_net_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='apinvoice',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
