# Generated by Django 4.2.13 on 2026-09-28 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_apinvoice_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bind_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='payment',
            name='bound_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_receipts', to='finance.apinvoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bound_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_refunds', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='chain_partners',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Σ receipts bound to this payment (refunded part)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='reconexception',
            name='exception_type',
            field=models.CharField(choices=[('duplicate_payment', 'سند مكرر'), ('duplicate_invoice', 'فاتورة مكررة'), ('overpayment', 'دفع زائد'), ('underpayment', 'دفع ناقص'), ('unpaid_old', 'فاتورة قديمة غير مسددة'), ('orphan_payment', 'سند بلا فاتورة'), ('paid_no_link', 'مسدد بلا ربط'), ('balance_mismatch', 'فرق رصيد غير مفسَّر'), ('reused_reference', 'مرجع مُعاد استخدامه'), ('supplier_mismatch', 'عدم تطابق الطرف'), ('cancelled_reversed', 'ملغى/معكوس'), ('misallocation', 'ربط خاطئ (تبادل فواتير)'), ('paid_returned', 'فاتورة مسددة رغم إرجاعها'), ('open_return', 'مرتجع مستحق على المورد'), ('receipt_on_invoice', 'مقبوضات مرتبطة بفاتورة شراء (تحتاج تحديد)'), ('anomaly', 'شذوذ')], db_index=True, max_length=20),
        ),
    ]
