# Generated by Django 4.2.13 on 2026-06-08 14:31

import apps.referral.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0015_softechsystemmap_erpgroupmodulepermission'),
        ('customers', '0016_add_health_profile_churn_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=apps.referral.models._generate_code, max_length=20, unique=True, verbose_name='كود الإحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('total_leads', models.PositiveIntegerField(default=0, verbose_name='إجمالي الإحالات')),
                ('validated_leads', models.PositiveIntegerField(default=0, verbose_name='إحالات ناجحة')),
                ('total_points_earned', models.PositiveIntegerField(default=0, verbose_name='نقاط مكتسبة من الإحالات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'كود إحالة',
                'verbose_name_plural': 'أكواد الإحالة',
            },
        ),
        migrations.CreateModel(
            name='ReferralLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=255, verbose_name='اسم الصديق')),
                ('lead_phone', models.CharField(db_index=True, max_length=30, verbose_name='رقم هاتف الصديق')),
                ('relationship', models.CharField(choices=[('family', 'عائلة'), ('friend', 'صديق'), ('colleague', 'زميل'), ('neighbor', 'جار'), ('other', 'أخرى')], default='friend', max_length=15, verbose_name='الصلة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الاتصال'), ('invited', 'تم إرسال الدعوة'), ('registered', 'سجّل'), ('validated', 'تم التحقق'), ('rewarded', 'تم المكافأة'), ('rejected', 'مرفوض (احتيال)'), ('expired', 'انتهت الصلاحية'), ('frozen', 'مجمّد (OTP أبيوز)')], db_index=True, default='pending', max_length=12, verbose_name='الحالة')),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='محاولات OTP')),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('fraud_score', models.PositiveSmallIntegerField(default=0, verbose_name='درجة الاحتيال (0-100)')),
                ('fraud_flags', models.JSONField(blank=True, default=list, verbose_name='مؤشرات الاحتيال')),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='referral.referralcode', verbose_name='كود الإحالة')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_leads', to='customers.customer', verbose_name='المُحيل')),
                ('registered_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_source', to='customers.customer', verbose_name='العميل المُسجَّل')),
            ],
            options={
                'verbose_name': 'إحالة',
                'verbose_name_plural': 'الإحالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('submitted', 'تم الإرسال'), ('invited', 'تم إرسال الدعوة'), ('registered', 'سجّل'), ('validated', 'تم التحقق'), ('rewarded', 'تم المكافأة'), ('rejected', 'مرفوض'), ('otp_attempt', 'محاولة OTP'), ('frozen', 'مجمّد')], db_index=True, max_length=15)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffprofile', verbose_name='بواسطة')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='referral.referrallead', verbose_name='الإحالة')),
            ],
            options={
                'verbose_name': 'حدث إحالة',
                'verbose_name_plural': 'أحداث الإحالة',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('duplicate_phone', 'هاتف مكرر'), ('self_referral', 'إحالة ذاتية'), ('circular_referral', 'إحالة دائرية'), ('device_collision', 'تصادم الجهاز'), ('otp_abuse', 'إساءة استخدام OTP'), ('mass_submission', 'إرسال جماعي مشبوه'), ('velocity', 'تجاوز معدل الإرسال'), ('known_fraud_device', 'جهاز محظور مسبقاً')], db_index=True, max_length=25, verbose_name='نوع المؤشر')),
                ('score_delta', models.PositiveSmallIntegerField(help_text='النقاط المضافة إلى fraud_score للإحالة', verbose_name='إضافة للدرجة')),
                ('detail', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_signals', to='referral.referrallead', verbose_name='الإحالة')),
            ],
            options={
                'verbose_name': 'مؤشر احتيال',
                'verbose_name_plural': 'مؤشرات الاحتيال',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referrallead',
            index=models.Index(fields=['referrer', 'status'], name='referral_re_referre_743497_idx'),
        ),
        migrations.AddIndex(
            model_name='referrallead',
            index=models.Index(fields=['lead_phone', 'status'], name='referral_re_lead_ph_a81f7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='referrallead',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'invited', 'registered'])), fields=('lead_phone',), name='referral_lead_phone_active_unique'),
        ),
    ]
