# Generated by Django 4.2.13 on 2026-05-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0007_pic_as_unique_key'),
        ('users', '0010_erpuser_user_group'),
        ('vouchers', '0003_voucher_full_upgrade'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voucherassignment',
            name='unique_voucher_phone_assignment',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='customers.customer', verbose_name='عميل محدد (خاص)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_uses',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='الحد الأقصى للاستخدام الكلي'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('discount_pct', 'خصم بالنسبة المئوية'), ('discount_fixed', 'خصم بمبلغ ثابت'), ('credit', 'رصيد نقدي'), ('free_item', 'صنف مجاني')], max_length=20, verbose_name='آلية الخصم'),
        ),
        migrations.AlterField(
            model_name='voucherotp',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='voucherredemption',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_redemptions', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='voucherredemption',
            name='customer_phone',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucherredemption',
            name='otp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption', to='vouchers.voucherotp'),
        ),
        migrations.AlterField(
            model_name='voucherredemption',
            name='redeemed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_redemptions', to='users.staffprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='voucherassignment',
            unique_together={('voucher', 'customer_phone')},
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['status', 'valid_until'], name='vouchers_vo_status_2e56ee_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_category', 'status'], name='vouchers_vo_voucher_0e70bd_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherotp',
            index=models.Index(fields=['voucher', 'phone', 'is_used'], name='vouchers_vo_voucher_7b25da_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherredemption',
            index=models.Index(fields=['voucher', 'customer_phone'], name='vouchers_vo_voucher_8117d0_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherredemption',
            index=models.Index(fields=['redeemed_at'], name='vouchers_vo_redeeme_d730e9_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherredemptiondocument',
            index=models.Index(fields=['status', 'expires_at'], name='vouchers_vo_status_62d9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherredemptiondocument',
            index=models.Index(fields=['reference_code'], name='vouchers_vo_referen_a776f0_idx'),
        ),
    ]
