# Generated by Django 4.2.13 on 2026-10-05 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_staffprofile_notify_expiry_worklist_wa"),
        (
            "vouchers",
            "0004_remove_voucherassignment_unique_voucher_phone_assignment_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("generated", "مولّدة من النظام"),
                            ("imported", "مستوردة"),
                        ],
                        default="generated",
                        max_length=10,
                        verbose_name="المصدر",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "مولّدة — بانتظار الإدخال في SOFTECH"),
                            ("stocked", "تم الإدخال في SOFTECH"),
                            ("void", "ملغاة"),
                        ],
                        default="generated",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("size", models.PositiveIntegerField(verbose_name="عدد الكوبونات")),
                ("serial_from", models.PositiveIntegerField(verbose_name="من سريال")),
                ("serial_to", models.PositiveIntegerField(verbose_name="إلى سريال")),
                (
                    "expiry_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="من تاريخ صلاحية"
                    ),
                ),
                (
                    "expiry_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="إلى تاريخ صلاحية"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupon_batches",
                        to="users.staffprofile",
                        verbose_name="أنشئت بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة كوبونات",
                "verbose_name_plural": "دفعات الكوبونات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponSerial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="السريال"
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="الرقم المسلسل"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=10, verbose_name="الكود العشوائي"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("softech", "من مشتريات SOFTECH"),
                            ("excel", "من ملف الإكسل فقط"),
                            ("generated", "مولّد من النظام"),
                        ],
                        max_length=10,
                        verbose_name="المصدر",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "مولّد — لم يُدخل بعد"),
                            ("partial", "أُدخل على صنف واحد فقط"),
                            ("stocked", "أُدخل على الصنفين"),
                            ("unstocked", "غير موجود في SOFTECH"),
                            ("void", "ملغى"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "points_expiry",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="صلاحية صنف النقاط",
                    ),
                ),
                (
                    "points_docnumber",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مستند شراء صنف النقاط"
                    ),
                ),
                ("points_docdate", models.DateField(blank=True, null=True)),
                (
                    "served_expiry",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="صلاحية صنف الاستحقاق",
                    ),
                ),
                (
                    "served_docnumber",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مستند شراء صنف الاستحقاق"
                    ),
                ),
                ("served_docdate", models.DateField(blank=True, null=True)),
                (
                    "conflict_note",
                    models.TextField(blank=True, default="", verbose_name="تعارضات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="serials",
                        to="vouchers.couponbatch",
                        verbose_name="الدفعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سريال كوبون",
                "verbose_name_plural": "سريالات الكوبونات",
                "ordering": ["number"],
            },
        ),
        migrations.AddConstraint(
            model_name="couponserial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "generated")),
                fields=("number",),
                name="uniq_coupon_generated_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="couponserial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "generated")),
                fields=("code",),
                name="uniq_coupon_generated_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="couponserial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "generated")),
                fields=("points_expiry",),
                name="uniq_coupon_generated_expiry",
            ),
        ),
    ]
