# Generated by Django 4.2.13 on 2026-10-05 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0012_invoiceline_match_review"),
        ("vouchers", "0005_coupon_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponbatch",
            name="points_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="invoices.supplierinvoice",
                verbose_name="فاتورة صنف النقاط",
            ),
        ),
        migrations.AddField(
            model_name="couponbatch",
            name="served_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="invoices.supplierinvoice",
                verbose_name="فاتورة صنف الاستحقاق",
            ),
        ),
    ]
