# Generated by Django 4.2.13 on 2026-10-06 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0018_remove_purchasehistoryline_bonus_qty"),
        ("vouchers", "0006_coupon_batch_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponserial",
            name="anomalies",
            field=models.JSONField(
                blank=True, default=list, verbose_name="ملاحظات رقابية"
            ),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="issue_count",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="issued_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ الصرف للعميل"
            ),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="issued_branch",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="issued_doc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="issued_pic",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=30,
                verbose_name="كود العميل (صرف)",
            ),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="redeem_count",
            field=models.SmallIntegerField(
                default=0, verbose_name="صافي مرات الاستخدام"
            ),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="redeemed_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ الاستخدام"
            ),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="redeemed_branch",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=5,
                verbose_name="فرع الاستخدام",
            ),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="redeemed_doc",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="redeemed_pic",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=30,
                verbose_name="كود العميل (استخدام)",
            ),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="sent_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="sent_branch",
            field=models.CharField(
                blank=True, default="", max_length=5, verbose_name="أُرسل إلى فرع"
            ),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("stocked", "في المخزن الرئيسي"),
                    ("issued", "صُرف لعميل"),
                    ("at_branch", "في فرع"),
                    ("redeemed", "استُخدم"),
                ],
                db_index=True,
                default="",
                max_length=10,
                verbose_name="المرحلة",
            ),
        ),
        migrations.CreateModel(
            name="CouponEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_serial",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="السريال كما في SOFTECH",
                    ),
                ),
                ("leg", models.CharField(max_length=6)),
                ("itemcode", models.CharField(max_length=10)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("issue", "صرف لعميل مقابل نقاط (170)"),
                            ("transfer_out", "تحويل من فرع"),
                            ("transfer_in", "استلام في فرع"),
                            ("redeem", "استخدام على فاتورة بيع (115)"),
                            ("redeem_return", "مرتجع بيع (30)"),
                            ("supplier_return", "مرتجع للمورد (120)"),
                            ("other", "حركة أخرى"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("doccode", models.CharField(max_length=4)),
                ("doc_name", models.CharField(blank=True, default="", max_length=100)),
                ("branchcode", models.CharField(db_index=True, max_length=5)),
                ("storecode", models.CharField(blank=True, default="", max_length=5)),
                ("docnumber", models.PositiveIntegerField()),
                ("docdate", models.DateField(db_index=True)),
                ("line_no", models.IntegerField(default=0)),
                (
                    "qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("party_code", models.CharField(blank=True, default="", max_length=10)),
                (
                    "customer_pic",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=30
                    ),
                ),
                ("usercode", models.CharField(blank=True, default="", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupon_events",
                        to="customers.customer",
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="vouchers.couponserial",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة كوبون",
                "verbose_name_plural": "حركات الكوبونات",
                "ordering": ["docdate", "branchcode", "docnumber", "line_no"],
                "indexes": [
                    models.Index(
                        fields=["kind", "branchcode", "docdate"],
                        name="vouchers_co_kind_0161ff_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="couponevent",
            constraint=models.UniqueConstraint(
                fields=("branchcode", "doccode", "docnumber", "itemcode", "line_no"),
                name="uniq_coupon_event_line",
            ),
        ),
    ]
