# Generated by Django 4.2.13 on 2026-10-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vouchers", "0007_coupon_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponserial",
            name="points_qty",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="couponserial",
            name="served_qty",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="couponevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("issue", "صرف لعميل مقابل نقاط (170)"),
                    ("issue_return", "إلغاء صرف لعميل (70)"),
                    ("transfer_out", "تحويل من فرع"),
                    ("transfer_in", "استلام في فرع"),
                    ("transfer_cancel", "إلغاء تحويل (20)"),
                    ("redeem", "استخدام على فاتورة بيع (115/180)"),
                    ("redeem_return", "مرتجع بيع (30/81)"),
                    ("reservation", "حجز بضاعة (80/181)"),
                    ("stock_count", "تسوية جرد (150/50)"),
                    ("supplier_return", "مرتجع للمورد (120)"),
                    ("other", "حركة أخرى"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
