# Generated by Django 4.2.13 on 2026-06-08 14:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vouchers', '0004_remove_voucherassignment_unique_voucher_phone_assignment_and_more'),
        ('users', '0015_softechsystemmap_erpgroupmodulepermission'),
        ('customers', '0016_add_health_profile_churn_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.IntegerField(default=0, verbose_name='الرصيد الحالي')),
                ('points_lifetime', models.PositiveIntegerField(default=0, help_text='فقط المعاملات الإيجابية — يُستخدم لتحديد المستوى', verbose_name='إجمالي النقاط المكتسبة (مدى الحياة)')),
                ('points_redeemed', models.PositiveIntegerField(default=0, verbose_name='إجمالي النقاط المستبدلة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'حساب الولاء',
                'verbose_name_plural': 'حسابات الولاء',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم المستوى')),
                ('name_ar', models.CharField(blank=True, max_length=50, verbose_name='الاسم بالعربية')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='0 = أدنى (Bronze), higher = better', verbose_name='الترتيب')),
                ('min_points', models.PositiveIntegerField(default=0, help_text='النقاط المتراكمة (lifetime) للوصول إلى هذا المستوى', verbose_name='الحد الأدنى للنقاط')),
                ('color', models.CharField(default='#CD7F32', max_length=20, verbose_name='اللون')),
                ('icon', models.CharField(default='🥉', max_length=10, verbose_name='الأيقونة')),
                ('earn_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='e.g. 1.5 = يكسب 50% نقاط إضافية', max_digits=4, verbose_name='معامل الكسب')),
                ('benefits_description', models.TextField(blank=True, verbose_name='مزايا المستوى')),
            ],
            options={
                'verbose_name': 'مستوى الولاء',
                'verbose_name_plural': 'مستويات الولاء',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RewardCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المكافأة')),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('reward_type', models.CharField(choices=[('voucher', 'قسيمة خصم'), ('cashback', 'استرداد نقدي'), ('gift_product', 'منتج مجاني'), ('discount_coupon', 'كوبون خصم'), ('priority_delivery', 'توصيل أولوية'), ('vip_status', 'ترقية VIP')], db_index=True, max_length=20, verbose_name='نوع المكافأة')),
                ('points_cost', models.PositiveIntegerField(verbose_name='تكلفة النقاط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('reward_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات المكافأة')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('stock_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للاستبدال')),
                ('redeemed_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الاستبدال')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('min_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.loyaltytier', verbose_name='الحد الأدنى للمستوى')),
            ],
            options={
                'verbose_name': 'مكافأة',
                'verbose_name_plural': 'كتالوج المكافآت',
                'ordering': ['points_cost'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField(verbose_name='النقاط المستنفدة')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الموافقة'), ('approved', 'معتمد'), ('fulfilled', 'تم الصرف'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى')], db_index=True, default='pending', max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.loyaltyaccount', verbose_name='الحساب')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_redemptions', to='users.staffprofile', verbose_name='اعتمد بواسطة')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='loyalty.rewardcatalog', verbose_name='المكافأة')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_redemptions', to='vouchers.voucher', verbose_name='القسيمة المُنشأة')),
            ],
            options={
                'verbose_name': 'طلب استبدال',
                'verbose_name_plural': 'طلبات الاستبدال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='loyalty.loyaltytier', verbose_name='المستوى الحالي'),
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='موجب = كسب، سالب = استبدال/انتهاء/تعديل سالب', verbose_name='النقاط')),
                ('transaction_type', models.CharField(choices=[('earn', 'كسب'), ('redeem', 'استبدال'), ('adjust', 'تعديل يدوي'), ('expire', 'انتهاء صلاحية'), ('refund', 'استرداد'), ('referral', 'مكافأة إحالة'), ('campaign', 'مكافأة حملة'), ('bonus', 'مكافأة خاصة')], db_index=True, max_length=10, verbose_name='نوع المعاملة')),
                ('source_type', models.CharField(choices=[('purchase', 'فاتورة شراء'), ('referral', 'إحالة ناجحة'), ('reward', 'استبدال مكافأة'), ('campaign', 'حملة تسويقية'), ('manual', 'يدوي')], default='manual', max_length=15, verbose_name='المصدر')),
                ('source_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('reason', models.CharField(max_length=255, verbose_name='السبب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('balance_after', models.IntegerField(default=0, verbose_name='الرصيد بعد المعاملة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount', verbose_name='الحساب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffprofile', verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'معاملة نقاط',
                'verbose_name_plural': 'معاملات النقاط',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'created_at'], name='loyalty_poi_account_a70135_idx'), models.Index(fields=['transaction_type', 'created_at'], name='loyalty_poi_transac_4eb033_idx')],
            },
        ),
    ]
