# Generated by Django 4.2.13 on 2026-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_softech_points'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='softechpointslog',
            new_name='loyalty_sof_softech_36e3c3_idx',
            old_name='loyalty_sof_pic_created_idx',
        ),
        migrations.AlterField(
            model_name='softechpointslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
