# Generated by Django 4.2.13 on 2026-05-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_alter_item_phcode'),
        ('branches', '0001_initial'),
        ('users', '0007_alter_rolemoduleaccess_id_alter_userbranchaccess_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='الاسم (عربي)')),
                ('name_scientific', models.CharField(blank=True, max_length=200, verbose_name='الاسم العلمي / IUPAC')),
                ('atc_code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='كود ATC')),
                ('atc_level1', models.CharField(blank=True, max_length=2, verbose_name='ATC المستوى 1 (كود)')),
                ('atc_level1_name', models.CharField(blank=True, max_length=150, verbose_name='ATC المستوى 1 (اسم)')),
                ('atc_level2', models.CharField(blank=True, max_length=4, verbose_name='ATC المستوى 2 (كود)')),
                ('atc_level2_name', models.CharField(blank=True, max_length=150, verbose_name='ATC المستوى 2 (اسم)')),
                ('atc_level3', models.CharField(blank=True, max_length=5, verbose_name='ATC المستوى 3 (كود)')),
                ('atc_level3_name', models.CharField(blank=True, max_length=150, verbose_name='ATC المستوى 3 (اسم)')),
                ('atc_level4', models.CharField(blank=True, max_length=7, verbose_name='ATC المستوى 4 (كود)')),
                ('atc_level4_name', models.CharField(blank=True, max_length=150, verbose_name='ATC المستوى 4 (اسم)')),
                ('is_chronic', models.BooleanField(db_index=True, default=False, verbose_name='دواء مزمن')),
                ('chronic_class', models.CharField(blank=True, choices=[('diabetes', 'السكري'), ('hypertension', 'ضغط الدم'), ('cardiovascular', 'أمراض القلب والأوعية'), ('thyroid', 'الغدة الدرقية'), ('asthma', 'الربو وأمراض الجهاز التنفسي'), ('anticoagulant', 'مضادات التخثر'), ('epilepsy', 'الصرع'), ('parkinson', 'باركنسون'), ('depression', 'الاكتئاب والأمراض النفسية'), ('immunosuppressant', 'مثبطات المناعة'), ('osteoporosis', 'هشاشة العظام'), ('renal', 'أمراض الكلى المزمنة'), ('oncology', 'الأورام'), ('cholesterol', 'ارتفاع الكوليسترول'), ('gerd', 'ارتجاع المريء المزمن'), ('anemia', 'فقر الدم المزمن'), ('other_chronic', 'مزمن - أخرى')], max_length=30, verbose_name='تصنيف المرض المزمن')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ingredients', to='users.staffprofile', verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'مادة فعّالة',
                'verbose_name_plural': 'المواد الفعّالة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhcodeClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phcode', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='كود ATC (phcode)')),
                ('is_chronic', models.BooleanField(db_index=True, default=False, verbose_name='مزمن')),
                ('item_count', models.IntegerField(default=0, verbose_name='عدد الأصناف')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='عدد المعاملات')),
                ('total_qty_sold', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='إجمالي الكميات المباعة')),
                ('last_seen_date', models.DateField(blank=True, null=True, verbose_name='آخر ظهور في المبيعات')),
                ('walkin_count', models.IntegerField(default=0, verbose_name='مشي (كاش)')),
                ('delivery_count', models.IntegerField(default=0, verbose_name='توصيل منزلي')),
                ('b2b_count', models.IntegerField(default=0, verbose_name='شركات / تأمين')),
                ('classified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التصنيف')),
                ('auto_suggested', models.BooleanField(default=False, verbose_name='اقتراح تلقائي (بانتظار التأكيد)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('active_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phcode_mappings', to='chronic.activeingredient', verbose_name='المادة الفعّالة')),
                ('classified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_phcodes', to='users.staffprofile', verbose_name='صُنِّف بواسطة')),
            ],
            options={
                'verbose_name': 'تصنيف كود ATC',
                'verbose_name_plural': 'تصنيفات أكواد ATC',
                'ordering': ['-transaction_count'],
            },
        ),
        migrations.CreateModel(
            name='MedicationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالعربية')),
                ('tag_type', models.CharField(choices=[('diagnosis', '🏥 تشخيص'), ('disease', '🩺 مرض مزمن'), ('drug_class', '💊 تصنيف دوائي'), ('icd10', '📋 كود ICD-10'), ('atc_class', '🔬 تصنيف ATC'), ('custom', '🏷️ مخصص')], max_length=20, verbose_name='نوع التصنيف')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='لون الشارة')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medication_tags', to='users.staffprofile', verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'وسم دوائي',
                'verbose_name_plural': 'الوسوم الدوائية',
                'ordering': ['tag_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('active_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_tags', to='chronic.activeingredient', verbose_name='المادة الفعّالة')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffprofile', verbose_name='أضيف بواسطة')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_tags', to='chronic.medicationtag', verbose_name='الوسم')),
            ],
            options={
                'verbose_name': 'وسم على مادة فعّالة',
                'verbose_name_plural': 'وسوم المواد الفعّالة',
                'unique_together': {('active_ingredient', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='FollowUpProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم البروتوكول')),
                ('frequency_type', models.CharField(choices=[('days_after_purchase', '📅 بعد الشراء بـ X يوم'), ('before_runout', '⏳ قبل نفاد العبوة بـ X يوم'), ('on_runout', '🔴 عند يوم النفاد المتوقع'), ('days_after_last_task', '🔁 بعد آخر متابعة بـ X يوم'), ('fixed_monthly', '📆 شهري — نفس اليوم كل شهر')], max_length=30, verbose_name='نوع التكرار')),
                ('days', models.PositiveIntegerField(blank=True, help_text='مطلوب لأنواع: بعد الشراء، قبل النفاد، بعد آخر متابعة', null=True, verbose_name='عدد الأيام')),
                ('trigger_condition', models.CharField(choices=[('any_purchase', 'أي عملية شراء'), ('first_purchase', 'أول مرة فقط لهذا العميل'), ('repeat_only', 'عملاء متكررون فقط'), ('no_refill_missed', 'لم يعد لإعادة الصرف بعد الموعد')], default='any_purchase', max_length=30, verbose_name='شرط التفعيل')),
                ('customer_type_filter', models.CharField(choices=[('all', 'جميع العملاء'), ('home_delivery', 'توصيل منزلي فقط'), ('walkin', 'كاش / مشي فقط'), ('b2b', 'شركات / تأمين فقط')], default='all', max_length=20, verbose_name='نوع العميل')),
                ('task_type', models.CharField(choices=[('call', '📞 اتصال هاتفي'), ('whatsapp', '💬 واتساب'), ('sms', '📱 رسالة نصية'), ('visit', '🏥 زيارة')], default='call', max_length=20, verbose_name='وسيلة التواصل')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'مرتفع'), ('urgent', 'عاجل'), ('chronic', 'مزمن')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('message_template', models.TextField(blank=True, help_text='المتغيرات المتاحة: {customer_name}, {item_name}, {ingredient_name}, {days_since_purchase}, {branch_name}, {phone}', verbose_name='قالب الرسالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب التنفيذ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_protocols', to='chronic.activeingredient', verbose_name='المادة الفعّالة')),
                ('applies_to_branches', models.ManyToManyField(blank=True, help_text='اتركه فارغاً للتطبيق على جميع الفروع', to='branches.branch', verbose_name='الفروع المطبقة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffprofile', verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'بروتوكول متابعة',
                'verbose_name_plural': 'بروتوكولات المتابعة',
                'ordering': ['active_ingredient', 'sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='activeingredient',
            name='tags',
            field=models.ManyToManyField(blank=True, through='chronic.IngredientTag', to='chronic.medicationtag', verbose_name='الوسوم'),
        ),
        migrations.CreateModel(
            name='ItemIngredientMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.CharField(blank=True, max_length=50, verbose_name='التركيز')),
                ('is_primary', models.BooleanField(default=True, verbose_name='مادة رئيسية')),
                ('mapped_at', models.DateTimeField(auto_now_add=True)),
                ('active_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_maps', to='chronic.activeingredient', verbose_name='المادة الفعّالة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_maps', to='catalog.item', verbose_name='الصنف')),
                ('mapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffprofile', verbose_name='رُبط بواسطة')),
            ],
            options={
                'verbose_name': 'ربط صنف بمادة فعّالة',
                'verbose_name_plural': 'روابط الأصناف والمواد الفعّالة',
                'unique_together': {('item', 'active_ingredient')},
            },
        ),
    ]
