# Generated by Django 4.2.13 on 2026-05-31 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_rolemoduleaccess_role_alter_staffprofile_role'),
        ('chronic', '0002_drop_phcodeclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_a', models.CharField(db_index=True, max_length=200, verbose_name='المادة الفعّالة أ')),
                ('ingredient_b', models.CharField(db_index=True, max_length=200, verbose_name='المادة الفعّالة ب')),
                ('severity', models.CharField(choices=[('major', 'خطير — تجنب الجمع'), ('moderate', 'متوسط — استخدم بحذر'), ('minor', 'بسيط — راقب العميل')], db_index=True, max_length=10, verbose_name='شدة التفاعل')),
                ('mechanism', models.TextField(blank=True, verbose_name='آلية التفاعل')),
                ('clinical_effect', models.TextField(blank=True, verbose_name='الأثر السريري')),
                ('management_ar', models.TextField(blank=True, help_text='ما يجب على الصيدلاني فعله عند اكتشاف هذا التفاعل', verbose_name='توصية الإدارة (عربي)')),
                ('management_en', models.TextField(blank=True, verbose_name='Management (English)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source', models.CharField(blank=True, help_text='مثال: Drugs.com, BNF, Micromedex, Manual', max_length=50, verbose_name='المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffprofile', verbose_name='أُضيف بواسطة')),
            ],
            options={
                'verbose_name': 'تفاعل دوائي',
                'verbose_name_plural': 'التفاعلات الدوائية',
                'indexes': [models.Index(fields=['ingredient_a', 'severity'], name='chronic_dru_ingredi_8e8df5_idx'), models.Index(fields=['ingredient_b', 'severity'], name='chronic_dru_ingredi_7f6b12_idx'), models.Index(fields=['severity', 'is_active'], name='chronic_dru_severit_4472a8_idx')],
                'unique_together': {('ingredient_a', 'ingredient_b')},
            },
        ),
        migrations.CreateModel(
            name='DrugContraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(db_index=True, max_length=200, verbose_name='المادة الفعّالة')),
                ('condition', models.CharField(choices=[('diabetes', 'السكري'), ('hypertension', 'ضغط الدم'), ('cardiovascular', 'أمراض القلب والأوعية'), ('thyroid', 'الغدة الدرقية'), ('asthma', 'الربو وأمراض الجهاز التنفسي'), ('anticoagulant', 'مضادات التخثر'), ('epilepsy', 'الصرع'), ('parkinson', 'باركنسون'), ('depression', 'الاكتئاب والأمراض النفسية'), ('immunosuppressant', 'مثبطات المناعة'), ('osteoporosis', 'هشاشة العظام'), ('renal', 'أمراض الكلى المزمنة'), ('oncology', 'الأورام'), ('cholesterol', 'ارتفاع الكوليسترول'), ('gerd', 'ارتجاع المريء المزمن'), ('anemia', 'فقر الدم المزمن'), ('other_chronic', 'مزمن - أخرى')], db_index=True, max_length=30, verbose_name='الحالة المزمنة')),
                ('severity', models.CharField(choices=[('absolute', 'موانع مطلقة — لا تُعطَ أبداً'), ('relative', 'موانع نسبية — استشر الطبيب'), ('caution', 'تحذير — راقب العميل')], max_length=10, verbose_name='شدة التحذير')),
                ('population', models.CharField(blank=True, choices=[('', 'عام'), ('pregnancy', 'حامل'), ('lactation', 'مرضعة'), ('pediatric', 'أطفال'), ('geriatric', 'مسنون'), ('renal', 'قصور كلوي'), ('hepatic', 'قصور كبدي')], help_text='اتركه فارغاً إذا كان ينطبق على جميع المرضى بهذه الحالة', max_length=15, verbose_name='الفئة المعنية')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffprofile', verbose_name='أُضيف بواسطة')),
            ],
            options={
                'verbose_name': 'تحذير دواء × مرض',
                'verbose_name_plural': 'تحذيرات الأدوية والأمراض',
                'indexes': [models.Index(fields=['ingredient', 'severity'], name='chronic_dru_ingredi_b11f94_idx'), models.Index(fields=['condition', 'severity'], name='chronic_dru_conditi_0c1f9c_idx')],
                'unique_together': {('ingredient', 'condition', 'population')},
            },
        ),
    ]
