# Generated by Django 4.2.13 on 2026-08-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_rolemoduleaccess_module'),
        ('chronic', '0003_add_drug_interactions_contraindications'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم التصنيف')),
                ('name_ar', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالعربية')),
                ('softech_code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='كود سوفتك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تصنيف مادة فعّالة',
                'verbose_name_plural': 'تصنيفات المواد الفعّالة',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='activeingredient',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مُراجَع ومعتمد'),
        ),
        migrations.AddField(
            model_name='activeingredient',
            name='salt_form',
            field=models.CharField(blank=True, max_length=60, verbose_name='صورة الملح'),
        ),
        migrations.AddField(
            model_name='activeingredient',
            name='source',
            field=models.CharField(choices=[('softech', 'من سوفتك'), ('parsed', 'مُستخرَج آلياً'), ('manual', 'إدخال يدوي')], db_index=True, default='manual', max_length=10, verbose_name='المصدر'),
        ),
        migrations.AddField(
            model_name='activeingredient',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='activeingredient',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_ingredients', to='users.staffprofile', verbose_name='اعتمده'),
        ),
        migrations.AddField(
            model_name='itemingredientmap',
            name='source',
            field=models.CharField(choices=[('softech', 'من سوفتك'), ('parsed', 'مُستخرَج آلياً'), ('manual', 'إدخال يدوي')], default='manual', max_length=10, verbose_name='المصدر'),
        ),
        migrations.CreateModel(
            name='IngredientStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='قيمة التركيز')),
                ('strength_unit', models.CharField(blank=True, max_length=20, verbose_name='وحدة التركيز')),
                ('display_name', models.CharField(db_index=True, max_length=220, verbose_name='الاسم المعروض')),
                ('softech_aicode', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='كود سوفتك')),
                ('source', models.CharField(choices=[('softech', 'من سوفتك'), ('parsed', 'مُستخرَج آلياً'), ('manual', 'إدخال يدوي')], default='manual', max_length=10, verbose_name='المصدر')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='مُراجَع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strengths', to='chronic.activeingredient', verbose_name='المادة الفعّالة')),
            ],
            options={
                'verbose_name': 'تركيز مادة فعّالة',
                'verbose_name_plural': 'تراكيز المواد الفعّالة',
                'ordering': ['active_ingredient', 'strength_value'],
                'unique_together': {('active_ingredient', 'strength_value', 'strength_unit')},
            },
        ),
        migrations.AddField(
            model_name='activeingredient',
            name='ingredient_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='chronic.ingredientclass', verbose_name='التصنيف الدوائي'),
        ),
        migrations.AddField(
            model_name='itemingredientmap',
            name='strength',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_maps', to='chronic.ingredientstrength', verbose_name='التركيز المعياري'),
        ),
    ]
