# Generated by Django 4.2.13 on 2026-08-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronic', '0004_ingredientclass_activeingredient_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientclass',
            name='key',
            field=models.SlugField(blank=True, max_length=60, unique=True, verbose_name='المفتاح'),
        ),
    ]
