# Generated by Django 4.2.13 on 2026-09-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcount', '0002_transaction_driven_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcountsnapshot',
            name='entered_expiry_hint',
            field=models.DateField(blank=True, null=True, verbose_name='الصلاحية المُدخَلة (استرشادي)'),
        ),
        migrations.AddField(
            model_name='stockcountsnapshot',
            name='physical_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='الصلاحية الفعلية على الرف'),
        ),
        migrations.AlterField(
            model_name='stockcountsession',
            name='mode',
            field=models.CharField(choices=[('transaction', 'مبني على الحركات'), ('full', 'جرد شامل'), ('filtered', 'جرد مفلتر'), ('expiry_audit', 'جرد صلاحية (تدقيق مادي)')], default='transaction', max_length=20, verbose_name='النوع'),
        ),
    ]
