# Generated by Django 4.2.13 on 2026-05-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('followups', '0004_chronic_module_and_purchase_history_erp_fields'),
        ('branches', '0001_initial'),
        ('users', '0007_alter_rolemoduleaccess_id_alter_userbranchaccess_id'),
        ('customers', '0004_chronic_module_and_purchase_history_erp_fields'),
        ('reservations', '0007_ensure_activity_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=50, verbose_name='رقم الهاتف')),
                ('caller_name', models.CharField(blank=True, help_text='من يتصل — إذا مختلف عن اسم العميل في النظام', max_length=255, verbose_name='اسم المتصل')),
                ('direction', models.CharField(choices=[('inbound', '📲 واردة'), ('outbound', '📞 صادرة'), ('whatsapp', '💬 واتساب')], default='inbound', max_length=10, verbose_name='اتجاه المكالمة')),
                ('status', models.CharField(choices=[('answered', '✅ تمت الإجابة'), ('no_answer', '📵 لا رد'), ('busy', '📶 مشغول'), ('voicemail', '📬 بريد صوتي'), ('callback', '🔄 طلب معاودة اتصال')], default='answered', max_length=10, verbose_name='حالة المكالمة')),
                ('purpose', models.CharField(choices=[('reservation', '📋 استفسار حجز'), ('delivery', '🚚 متابعة توصيل'), ('refill', '💊 إعادة صرف'), ('complaint', '⚠️ شكوى'), ('new_order', '🛒 طلب جديد'), ('address', '📍 تحديث عنوان'), ('followup', '🔔 متابعة مزمن'), ('demand', '🔍 صنف غير متوفر'), ('general', '💬 استفسار عام')], db_index=True, default='general', max_length=15, verbose_name='الغرض')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='مدة المكالمة (ثانية)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات المكالمة')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='ملخص سريع')),
                ('payment_method', models.CharField(blank=True, help_text='كاش / فيزا / محفظة / تأمين', max_length=30, verbose_name='طريقة الدفع')),
                ('called_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('callback_due', models.DateTimeField(blank=True, null=True, verbose_name='موعد معاودة الاتصال')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='branches.branch', verbose_name='الفرع')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='customers.customer', verbose_name='العميل')),
                ('followup_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='followups.followuptask', verbose_name='مهمة المتابعة المرتبطة')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='users.staffprofile', verbose_name='تولّى المكالمة')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='reservations.reservation', verbose_name='الحجز المرتبط')),
            ],
            options={
                'verbose_name': 'سجل مكالمة',
                'verbose_name_plural': 'سجلات المكالمات',
                'ordering': ['-called_at'],
            },
        ),
        migrations.CreateModel(
            name='AddressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='home', max_length=15, verbose_name='نوع العنوان')),
                ('label_custom', models.CharField(blank=True, max_length=50)),
                ('address_text', models.TextField(verbose_name='العنوان الجديد')),
                ('area', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=10)),
                ('apartment', models.CharField(blank=True, max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('google_maps_link', models.URLField(blank=True)),
                ('delivery_phone', models.CharField(blank=True, max_length=50)),
                ('delivery_notes', models.TextField(blank=True)),
                ('set_as_default', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', '⏳ بانتظار التطبيق'), ('applied', '✅ تم التطبيق'), ('rejected', '❌ مرفوض')], default='pending', max_length=10, verbose_name='الحالة')),
                ('applied_location_ref', models.CharField(blank=True, help_text='يُحفظ هنا تلقائياً بعد تطبيق التحديث', max_length=100, verbose_name='مرجع العنوان المُنشأ')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffprofile', verbose_name='طبّقه')),
                ('call_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_updates', to='callcenter.calllog', verbose_name='سجل المكالمة')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_address_updates', to='users.staffprofile', verbose_name='جُمع بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_updates', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'تحديث عنوان',
                'verbose_name_plural': 'تحديثات العناوين',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['phone_number', 'called_at'], name='callcenter__phone_n_f80540_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['customer', 'called_at'], name='callcenter__custome_26ee44_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['purpose', 'called_at'], name='callcenter__purpose_bb89db_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['handled_by', 'called_at'], name='callcenter__handled_5ab3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['status', 'called_at'], name='callcenter__status_d79ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['callback_due'], name='callcenter__callbac_e394ec_idx'),
        ),
    ]
