# Generated by Django 4.2.13 on 2026-05-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0003_case_quality_attachments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customercase',
            new_name='callcenter__custome_aa45dc_idx',
            old_name='callcenter__cust_status_idx',
        ),
        migrations.RenameIndex(
            model_name='customercase',
            new_name='callcenter__status_a0a8b9_idx',
            old_name='callcenter__status_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='customercase',
            new_name='callcenter__assigne_1a798c_idx',
            old_name='callcenter__assigned_status_idx',
        ),
        migrations.RenameIndex(
            model_name='customercase',
            new_name='callcenter__categor_927893_idx',
            old_name='callcenter__cat_status_idx',
        ),
    ]
