# Generated by Django 4.2.13 on 2026-09-30 22:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0038_item_is_spike_item_spike_confirmed_and_more'),
        ('finance', '0016_suspect_amount_type'),
        ('customers', '0019_segmentationconfig'),
        ('lineage', '0001_initial'),
        ('branches', '0007_backfill_branch_kind'),
        ('users', '0027_alter_rolemoduleaccess_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconstructionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=10)),
                ('params', models.JSONField(default=dict)),
                ('counts', models.JSONField(default=dict)),
                ('rules_version', models.CharField(blank=True, max_length=20)),
                ('triggered_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'تشغيل إعادة بناء',
                'verbose_name_plural': 'تشغيلات إعادة البناء',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplacementCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('source_type', models.CharField(choices=[('insurance_rx', 'روشتة تأمين من صرفنا'), ('insurance_external', 'أدوية تأمين من خارج صرفنا'), ('client_buyback', 'شراء أدوية من عميل (غير تأمين)')], db_index=True, max_length=20)),
                ('settlement_mode', models.CharField(choices=[('products', 'منتجات'), ('cash', 'نقدي'), ('mixed', 'مختلط'), ('pending', 'لم يُصرف بعد')], default='pending', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('calculated', 'محسوبة'), ('awaiting_approval', 'بانتظار الموافقة'), ('approved', 'معتمدة'), ('executing', 'جارٍ التنفيذ'), ('entitlement_active', 'رصيد قائم'), ('settled', 'مستهلكة بالكامل'), ('reconciled', 'مطابقة'), ('closed', 'مغلقة'), ('cancelled', 'ملغاة'), ('reversing', 'جارٍ العكس'), ('reversed', 'معكوسة')], db_index=True, default='draft', max_length=20)),
                ('origin', models.CharField(choices=[('reconstructed', 'مُعاد بناؤها من التاريخ'), ('live', 'حالة تشغيلية')], db_index=True, default='live', max_length=14)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('branchcode', models.CharField(db_index=True, max_length=5)),
                ('softech_pic', models.CharField(blank=True, db_index=True, max_length=20)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('contract_personcode', models.CharField(blank=True, db_index=True, max_length=12)),
                ('supplier_personcode', models.CharField(db_index=True, max_length=12)),
                ('supplier_name', models.CharField(blank=True, max_length=300)),
                ('purchase_date', models.DateField(db_index=True)),
                ('public_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('entitlement', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('applied_deduction_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('supplier_tier_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('redeemed_products', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('redeemed_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('redeemed_unclassified', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reversed_by_return', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('absorbed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('customer_topup', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('native_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('link_confidence', models.CharField(blank=True, choices=[('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'منخفضة')], max_length=8)),
                ('open_exceptions', models.PositiveIntegerField(default=0)),
                ('max_severity', models.CharField(blank=True, max_length=10)),
                ('rules_version', models.CharField(blank=True, max_length=20)),
                ('reconstructed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_cases', to='branches.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_cases', to='customers.customer')),
                ('purchase_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_case', to='finance.apinvoice')),
                ('purchase_ref', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_case', to='lineage.documentref')),
            ],
            options={
                'verbose_name': 'حالة بدل',
                'verbose_name_plural': 'حالات البدل',
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReplacementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(db_index=True, max_length=6)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('disposition', models.CharField(choices=[('dispensed_as_prescribed', 'صُرف كما هو'), ('selected_for_replacement', 'مُستبدل'), ('partially_replaced', 'مُستبدل جزئياً')], max_length=24)),
                ('qty_prescribed', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('qty_replaced', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('public_unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('contract_unit_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('purchase_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('applied_deduction_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='replacement.replacementcase')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.item')),
            ],
            options={
                'verbose_name': 'صنف حالة بدل',
                'verbose_name_plural': 'أصناف حالات البدل',
                'ordering': ['disposition', 'itemcode'],
            },
        ),
        migrations.CreateModel(
            name='EntitlementLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('entitlement_created', 'إنشاء رصيد'), ('product_redemption', 'صرف منتجات'), ('cash_settlement', 'صرف نقدي'), ('redemption_unclassified', 'صرف غير مصنّف'), ('supplier_return_reversal', 'عكس بمرتجع مورد'), ('pos_return_credit', 'رد رصيد بمرتجع منتجات'), ('reversal', 'قيد عكسي')], db_index=True, max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('origin', models.CharField(default='reconstructed', max_length=14)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='replacement.replacementcase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='lineage.documentref')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='replacement.entitlementledgerentry')),
            ],
            options={
                'verbose_name': 'قيد رصيد بدل',
                'verbose_name_plural': 'قيود رصيد البدل',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('purchase_lines_missing', 'أصناف فاتورة الشراء غير متاحة في المرآة'), ('no_contract_sale', 'لا توجد فاتورة تعاقد مطابقة'), ('ambiguous_patient', 'أكثر من مريض محتمل لنفس الشراء'), ('sale_outside_window', 'فاتورة التعاقد خارج النافذة الزمنية'), ('multi_patient_purchase', 'فاتورة شراء لأكثر من مريض'), ('duplicate_purchase', 'شراء مكرر لنفس صنف الروشتة'), ('aged_outstanding', 'رصيد قائم قديم'), ('unlinked_voucher_likely', 'رصيد قائم مع سند صرف غير مربوط محتمل'), ('voucher_without_receipt', 'سند صرف بدون فاتورة منتجات'), ('cash_on_product_tier', 'صرف نقدي من رصيد بسعر المنتجات'), ('cash_remainder_high', 'باقي نقدي كبير من رصيد المنتجات'), ('receipts_exceed_voucher', 'فواتير المنتجات أكبر من السند'), ('anonymous_receipt', 'فاتورة منتجات بدون كود مريض — تحتاج تأكيد'), ('rate_deviation', 'نسبة الخصم المطبقة تختلف عن فئة المورد'), ('cross_branch_voucher', 'سند صرف من فرع مختلف'), ('voucher_reversed', 'سند صرف مُلغى'), ('supplier_return', 'مرتجع للمورد على الفاتورة'), ('ledger_native_mismatch', 'رصيد الدفتر لا يطابق رصيد SOFTECH'), ('negative_entitlement', 'رصيد سالب')], db_index=True, max_length=28)),
                ('key', models.CharField(blank=True, default='', max_length=60)),
                ('severity', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تحذير'), ('high', 'مرتفع'), ('critical', 'حرج')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('acknowledged', 'قيد المتابعة'), ('resolved', 'محلول'), ('auto_cleared', 'زال تلقائياً')], db_index=True, default='open', max_length=14)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('detail', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='replacement.replacementcase')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile')),
            ],
            options={
                'verbose_name': 'استثناء حالة بدل',
                'verbose_name_plural': 'استثناءات حالات البدل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('purchase', 'فاتورة الشراء (إنشاء الرصيد)'), ('supplier_return', 'مرتجع للمورد'), ('contract_sale', 'بيع التعاقد'), ('contract_return', 'مرتجع جزئي للتعاقد'), ('contract_void', 'بيع تعاقد ملغى بمرتجع'), ('voucher', 'سند صرف'), ('product_sale', 'فاتورة منتجات البدل')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'مقترح'), ('confirmed', 'مؤكد'), ('rejected', 'مرفوض')], db_index=True, default='proposed', max_length=10)),
                ('origin', models.CharField(default='matched', max_length=8)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='replacement.replacementcase')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_links', to='lineage.documentref')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='replacement.casedocument')),
            ],
            options={
                'verbose_name': 'مستند حالة',
                'verbose_name_plural': 'مستندات الحالات',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='replacementcase',
            index=models.Index(fields=['status', 'branchcode'], name='replacement_status_7a05ca_idx'),
        ),
        migrations.AddIndex(
            model_name='replacementcase',
            index=models.Index(fields=['supplier_personcode', 'purchase_date'], name='replacement_supplie_bcae2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitlementledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('amount', 0), _negated=True), name='ck_replacement_ledger_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='entitlementledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('document__isnull', False), ('reverses__isnull', True)), fields=('case', 'entry_type', 'document'), name='uq_replacement_ledger_doc'),
        ),
        migrations.AddIndex(
            model_name='caseexception',
            index=models.Index(fields=['status', 'severity'], name='replacement_status_09c677_idx'),
        ),
        migrations.AddConstraint(
            model_name='caseexception',
            constraint=models.UniqueConstraint(fields=('case', 'exception_type', 'key'), name='uq_replacement_exception'),
        ),
        migrations.AddConstraint(
            model_name='casedocument',
            constraint=models.UniqueConstraint(fields=('case', 'document', 'role'), name='uq_replacement_casedoc'),
        ),
    ]
