# Generated by Django 4.2.13 on 2026-09-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='role',
            field=models.CharField(choices=[('purchase', 'فاتورة الشراء (إنشاء الرصيد)'), ('supplier_return', 'مرتجع للمورد'), ('contract_sale', 'بيع التعاقد'), ('contract_return', 'مرتجع جزئي للتعاقد'), ('contract_void', 'بيع تعاقد ملغى بمرتجع'), ('voucher', 'سند صرف'), ('return_settlement', 'سند تسوية مرتجع'), ('product_sale', 'فاتورة منتجات البدل')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entitlementledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('entitlement_created', 'إنشاء رصيد'), ('product_redemption', 'صرف منتجات'), ('cash_settlement', 'صرف نقدي'), ('redemption_unclassified', 'صرف غير مصنّف'), ('supplier_return_reversal', 'عكس بمرتجع مورد'), ('return_settled', 'تسوية مرتجع (استرداد / مقاصة)'), ('pos_return_credit', 'رد رصيد بمرتجع منتجات'), ('reversal', 'قيد عكسي')], db_index=True, max_length=24),
        ),
    ]
