# Generated by Django 4.2.13 on 2026-10-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacement', '0002_alter_casedocument_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseexception',
            name='exception_type',
            field=models.CharField(choices=[('purchase_lines_missing', 'أصناف فاتورة الشراء غير متاحة في المرآة'), ('no_contract_sale', 'لا توجد فاتورة تعاقد مطابقة'), ('ambiguous_patient', 'أكثر من مريض محتمل لنفس الشراء'), ('sale_outside_window', 'فاتورة التعاقد خارج النافذة الزمنية'), ('multi_patient_purchase', 'فاتورة شراء لأكثر من مريض'), ('duplicate_purchase', 'شراء مكرر لنفس صنف الروشتة'), ('qty_exceeds_sale', 'الكمية المشتراة أكبر من كمية فاتورة التعاقد (قد تغطي أكثر من روشتة)'), ('aged_outstanding', 'رصيد قائم قديم'), ('unlinked_voucher_likely', 'رصيد قائم مع سند صرف غير مربوط محتمل'), ('voucher_without_receipt', 'سند صرف بدون فاتورة منتجات'), ('cash_on_product_tier', 'صرف نقدي من رصيد بسعر المنتجات'), ('cash_remainder_high', 'باقي نقدي كبير من رصيد المنتجات'), ('receipts_exceed_voucher', 'فواتير المنتجات أكبر من السند'), ('anonymous_receipt', 'فاتورة منتجات بدون كود مريض — تحتاج تأكيد'), ('rate_deviation', 'نسبة الخصم المطبقة تختلف عن فئة المورد'), ('cross_branch_voucher', 'سند صرف من فرع مختلف'), ('voucher_reversed', 'سند صرف مُلغى'), ('supplier_return', 'مرتجع للمورد على الفاتورة'), ('ledger_native_mismatch', 'رصيد الدفتر لا يطابق رصيد SOFTECH'), ('negative_entitlement', 'رصيد سالب')], db_index=True, max_length=28),
        ),
    ]
