# Generated by Django 4.2.13 on 2026-10-02 18:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoiceline_match_review'),
        ('pos_orders', '0014_posselectionevent'),
        ('approvals', '0004_approvalrequest_nominated_approvers_and_more'),
        ('users', '0027_alter_rolemoduleaccess_module'),
        ('lineage', '0001_initial'),
        ('replacement', '0003_alter_caseexception_exception_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementcase',
            name='approval_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='replacementcase',
            name='approval_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='approvals.approvalrequest'),
        ),
        migrations.AddField(
            model_name='replacementcase',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replacementcase',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile'),
        ),
        migrations.AddField(
            model_name='replacementcase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_cases_created', to='users.staffprofile'),
        ),
        migrations.AddField(
            model_name='replacementcase',
            name='is_shortage_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replacementcase',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replacementcase',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='replacementcase',
            name='prescription_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='replacementcase',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='caseexception',
            name='exception_type',
            field=models.CharField(choices=[('purchase_lines_missing', 'أصناف فاتورة الشراء غير متاحة في المرآة'), ('no_contract_sale', 'لا توجد فاتورة تعاقد مطابقة'), ('ambiguous_patient', 'أكثر من مريض محتمل لنفس الشراء'), ('sale_outside_window', 'فاتورة التعاقد خارج النافذة الزمنية'), ('multi_patient_purchase', 'فاتورة شراء لأكثر من مريض'), ('duplicate_purchase', 'شراء مكرر لنفس صنف الروشتة'), ('qty_exceeds_sale', 'الكمية المشتراة أكبر من كمية فاتورة التعاقد (قد تغطي أكثر من روشتة)'), ('aged_outstanding', 'رصيد قائم قديم'), ('unlinked_voucher_likely', 'رصيد قائم مع سند صرف غير مربوط محتمل'), ('voucher_without_receipt', 'سند صرف بدون فاتورة منتجات'), ('cash_on_product_tier', 'صرف نقدي من رصيد بسعر المنتجات'), ('cash_remainder_high', 'باقي نقدي كبير من رصيد المنتجات'), ('receipts_exceed_voucher', 'فواتير المنتجات أكبر من السند'), ('anonymous_receipt', 'فاتورة منتجات بدون كود مريض — تحتاج تأكيد'), ('rate_deviation', 'نسبة الخصم المطبقة تختلف عن فئة المورد'), ('cross_branch_voucher', 'سند صرف من فرع مختلف'), ('voucher_reversed', 'سند صرف مُلغى'), ('supplier_return', 'مرتجع للمورد على الفاتورة'), ('ledger_native_mismatch', 'رصيد الدفتر لا يطابق رصيد SOFTECH'), ('negative_entitlement', 'رصيد سالب'), ('self_approval', 'اعتماد من منشئ الحالة (فصل المهام)'), ('stale_approval', 'اعتماد على حساب تغيّر بعد الإرسال'), ('posting_failed', 'فشل الترحيل إلى SOFTECH'), ('purchase_value_mismatch', 'قيمة فاتورة الشراء في SOFTECH تختلف عن الرصيد المعتمد')], db_index=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='replacementcase',
            name='purchase_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_case', to='lineage.documentref'),
        ),
        migrations.CreateModel(
            name='ReplacementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(db_index=True, max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('source_type', models.CharField(choices=[('insurance_rx', 'روشتة تأمين من صرفنا'), ('insurance_external', 'أدوية تأمين من خارج صرفنا'), ('client_buyback', 'شراء أدوية من عميل (غير تأمين)')], max_length=20)),
                ('settlement_mode', models.CharField(choices=[('products', 'منتجات'), ('cash', 'نقدي')], max_length=10)),
                ('shortage_only', models.BooleanField(default=False)),
                ('contract_personcode', models.CharField(blank=True, max_length=12)),
                ('branchcode', models.CharField(blank=True, max_length=5)),
                ('deduction_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supplier_personcode', models.CharField(max_length=12)),
                ('rounding', models.CharField(choices=[('none', 'بدون تقريب'), ('floor_1', 'تقريب لأسفل لأقرب 1'), ('floor_5', 'تقريب لأسفل لأقرب 5'), ('floor_10', 'تقريب لأسفل لأقرب 10'), ('floor_50', 'تقريب لأسفل لأقرب 50')], default='none', max_length=10)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile')),
            ],
            options={
                'verbose_name': 'قاعدة خصم بدل',
                'verbose_name_plural': 'قواعد خصم البدل',
                'ordering': ['priority', 'rule_key', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ReplacementGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=True)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_post', models.BooleanField(default=False)),
                ('allowed_sources', models.JSONField(blank=True, default=list)),
                ('allowed_modes', models.JSONField(blank=True, default=list)),
                ('max_case_entitlement', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approve_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_override_pp', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_grant', to='users.staffprofile')),
            ],
            options={
                'verbose_name': 'صلاحية موظف على البدل',
                'verbose_name_plural': 'صلاحيات الموظفين على البدل',
            },
        ),
        migrations.CreateModel(
            name='ReplacementCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('rule_deduction_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applied_deduction_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('override_reason', models.CharField(blank=True, max_length=300)),
                ('lines', models.JSONField(default=list)),
                ('public_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('entitlement_raw', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rounding_adj', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entitlement', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='replacement.replacementcase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='replacement.replacementrule')),
            ],
            options={
                'ordering': ['-seq'],
            },
        ),
        migrations.CreateModel(
            name='PostingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('purchase', 'فاتورة شراء (إنشاء الرصيد)'), ('contract_sale', 'بيع تعاقد'), ('product_sale', 'بيع منتجات البدل')], max_length=16)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('planned', 'مُعد'), ('dry_run', 'تجربة بدون ترحيل'), ('posting', 'جارٍ الترحيل'), ('posted', 'مُرحّل — بانتظار الكاشير'), ('posted_verified', 'مُرحّل ومُتحقق'), ('failed', 'فشل'), ('cancelled', 'ملغى')], db_index=True, default='planned', max_length=16)),
                ('expected_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('result_docnumber', models.CharField(blank=True, max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='replacement.replacementcase')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos_orders.softechsalesorder')),
                ('supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='invoices.supplierinvoice')),
            ],
            options={
                'verbose_name': 'عملية ترحيل',
                'verbose_name_plural': 'عمليات الترحيل',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='replacementcase',
            name='current_calc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='replacement.replacementcalculation'),
        ),
        migrations.AddConstraint(
            model_name='replacementrule',
            constraint=models.UniqueConstraint(fields=('rule_key', 'version'), name='uq_replacement_rule_version'),
        ),
        migrations.AddConstraint(
            model_name='replacementcalculation',
            constraint=models.UniqueConstraint(fields=('case', 'seq'), name='uq_replacement_calc_seq'),
        ),
    ]
