# Generated by Django 4.2.13 on 2026-05-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('catalog', '0002_alter_item_unit_price_alter_item_unit_sale_price'),
        ('customers', '0003_alter_purchasehistory_invoice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique key: branchcode-doccode-docnumber-docdate', max_length=100, unique=True, verbose_name='معرف المعاملة')),
                ('doccode', models.CharField(choices=[('25', 'استلام تحويل'), ('30', 'مرتجع عميل'), ('115', 'بيع لعميل'), ('125', 'إصدار تحويل')], db_index=True, max_length=5, verbose_name='كود المستند')),
                ('reference_number', models.CharField(blank=True, help_text='stktransm.docnumber', max_length=50, verbose_name='رقم المستند')),
                ('softech_branch_code', models.CharField(blank=True, help_text='Raw branchcode from Sybase — kept for audit', max_length=10, verbose_name='كود الفرع في ERP')),
                ('phcode', models.CharField(blank=True, db_index=True, help_text='localcustomers.phcode — NULL for transfers', max_length=30, verbose_name='كود العميل (PIC)')),
                ('transaction_date', models.DateTimeField(db_index=True, verbose_name='تاريخ المعاملة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي المبلغ')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_transactions', to='branches.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'معاملة ERP',
                'verbose_name_plural': 'معاملات ERP',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='LocalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phcode', models.CharField(db_index=True, help_text='مثال: 140HD515 — كود العميل في نظام التوصيل', max_length=30, unique=True, verbose_name='كود PIC')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='اسم العميل')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='رقم الهاتف')),
                ('phone_alt', models.CharField(blank=True, max_length=50, verbose_name='هاتف بديل')),
                ('erp_branch_code', models.CharField(blank=True, max_length=10, verbose_name='كود الفرع في ERP')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('customer_type', models.CharField(blank=True, help_text='HD=Home Delivery, etc.', max_length=10, verbose_name='نوع العميل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_customers', to='branches.branch', verbose_name='الفرع')),
                ('linked_customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_customer_profile', to='customers.customer', verbose_name='عميل مرتبط')),
            ],
            options={
                'verbose_name': 'عميل توصيل (PIC)',
                'verbose_name_plural': 'عملاء التوصيل (PIC)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ERPTransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, help_text='Raw itemcode from stktrans — always stored for audit', max_length=20, verbose_name='كود الصنف')),
                ('item_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الصنف')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='سعر الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي السطر')),
                ('store_code', models.CharField(blank=True, max_length=5, verbose_name='كود المخزن')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_lines', to='catalog.item', verbose_name='الصنف')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.erptransaction', verbose_name='المعاملة')),
            ],
            options={
                'verbose_name': 'سطر معاملة ERP',
                'verbose_name_plural': 'أسطر معاملات ERP',
            },
        ),
        migrations.AddField(
            model_name='erptransaction',
            name='local_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='erp.localcustomer', verbose_name='عميل التوصيل'),
        ),
        migrations.AddField(
            model_name='erptransaction',
            name='personsdata_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_transactions', to='customers.customer', verbose_name='عميل النظام'),
        ),
        migrations.AddIndex(
            model_name='localcustomer',
            index=models.Index(fields=['phone'], name='erp_localcu_phone_3327cb_idx'),
        ),
        migrations.AddIndex(
            model_name='localcustomer',
            index=models.Index(fields=['erp_branch_code'], name='erp_localcu_erp_bra_b03bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='erptransactionline',
            index=models.Index(fields=['item_code'], name='erp_erptran_item_co_151461_idx'),
        ),
        migrations.AddIndex(
            model_name='erptransactionline',
            index=models.Index(fields=['transaction', 'item_code'], name='erp_erptran_transac_bd465d_idx'),
        ),
        migrations.AddIndex(
            model_name='erptransaction',
            index=models.Index(fields=['doccode', 'transaction_date'], name='erp_erptran_doccode_d0e47c_idx'),
        ),
        migrations.AddIndex(
            model_name='erptransaction',
            index=models.Index(fields=['doccode', 'branch'], name='erp_erptran_doccode_f9a2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='erptransaction',
            index=models.Index(fields=['phcode', 'transaction_date'], name='erp_erptran_phcode_f861e7_idx'),
        ),
        migrations.AddIndex(
            model_name='erptransaction',
            index=models.Index(fields=['transaction_date'], name='erp_erptran_transac_b5faca_idx'),
        ),
    ]
