# Generated by Django 4.2.13 on 2026-05-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_erpuser_user_group'),
        ('catalog', '0005_alter_item_phcode'),
        ('invoices', '0002_alter_invoiceline_id_alter_supplierinvoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم المورد')),
                ('aliases', models.TextField(blank=True, help_text='أسماء بديلة مفصولة بفاصلة', verbose_name='أسماء بديلة')),
                ('typical_discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='خصم نموذجي %')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.vendorprofile', verbose_name='المورد (ملف)'),
        ),
        migrations.CreateModel(
            name='VendorItemMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name_normalized', models.CharField(db_index=True, max_length=300, verbose_name='الاسم المُعيَّر')),
                ('use_count', models.PositiveIntegerField(default=1, verbose_name='عدد الاستخدامات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile', verbose_name='أُنشئ بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.item', verbose_name='الصنف')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_mappings', to='invoices.vendorprofile', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'ربط صنف بمورد',
                'verbose_name_plural': 'ربط الأصناف بالموردين',
                'unique_together': {('vendor', 'raw_name_normalized')},
            },
        ),
    ]
