# Generated by Django 4.2.13 on 2026-05-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_vendorprofile_vendoritemmapping_vendor_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='source_image',
            field=models.FileField(blank=True, null=True, upload_to='invoice_images/', verbose_name='ملف الفاتورة (صورة / PDF)'),
        ),
    ]
