# Generated by Django 4.2.13 on 2026-05-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_source_image_to_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='public_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='السعر العام'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='سعر الوحدة الصافي'),
        ),
    ]
