# Generated by Django 4.2.13 on 2026-05-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_add_public_price_to_invoice_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم التشغيلة'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='distributor_margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='هامش الموزع %'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=50, verbose_name='تاريخ الصلاحية'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='extra_discount_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='خصم إضافي % (خ.ص.د)'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم المورد/المصنع'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ضريبة القيمة المضافة %'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='discount_amt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='خصم بمبلغ'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='discount_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='خصم مطابقة %'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='إجمالي صيدلي'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='manual_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='اسم الصنف'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='public_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='سعر الجمهور'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='سعر الصيدلي'),
        ),
    ]
