# Generated by Django 4.2.13 on 2026-05-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_add_full_invoice_line_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='distributor_margin_pct',
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='distributor_margin_amt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هامش الموزع (مبلغ)'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='pharmacist_margin_amt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هامش الصيدلي (مبلغ)'),
        ),
    ]
