# Generated by Django 4.2.13 on 2026-05-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_rename_margin_to_amt_add_pharmacist_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='vendor_item_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='كود الصنف (المورد)'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='pharmacist_margin_amt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هامش ربح الصيدلي'),
        ),
    ]
