# Generated by Django 4.2.13 on 2026-06-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_add_vendor_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='ocr_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='ثقة الاستخراج (OCR)'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='declared_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='الإجمالي المقروء من الفاتورة'),
        ),
        migrations.AddField(
            model_name='vendoritemmapping',
            name='vendor_item_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='كود الصنف (المورد)'),
        ),
    ]
