# Generated by Django 4.2.13 on 2026-06-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoiceline_ocr_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='client_token',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='doc_kind',
            field=models.CharField(choices=[('purchase', 'شراء (doccode 10)'), ('return', 'مرتجع مورد (doccode 120)')], default='purchase', max_length=10, verbose_name='نوع المستند'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='erp_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='erp_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='erp_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='الحمولة المُرسلة'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='erp_readback',
            field=models.JSONField(blank=True, default=dict, verbose_name='قراءة التحقق'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='return_of_docnumber',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مرتجع للمستند رقم'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='softech_branchcode',
            field=models.CharField(blank=True, max_length=5, verbose_name='كود الفرع (SOFTECH)'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='softech_docdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='softech_docnumber',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='رقم المستند في SOFTECH'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='store_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='كود المخزن'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='softech_personcode',
            field=models.CharField(blank=True, db_index=True, max_length=8, verbose_name='كود المورد في SOFTECH'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('processing', 'جاري المعالجة'), ('review', 'قيد المراجعة'), ('confirmed', 'مُأكَّدة'), ('rejected', 'مرفوضة'), ('queued', 'بانتظار الترحيل'), ('pushing', 'جارٍ الترحيل'), ('finalized', 'مُرحَّلة إلى ERP'), ('push_failed', 'فشل الترحيل')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
