# Generated by Django 4.2.13 on 2026-07-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_supplierinvoice_client_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='is_main',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مورد رئيسي (رسمي)'),
        ),
    ]
