# Generated by Django 4.2.13 on 2026-07-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_vendorprofile_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='match_review',
            field=models.BooleanField(default=False, verbose_name='مطابقة تحتاج مراجعة'),
        ),
    ]
