# Generated by Django 4.2.13 on 2026-08-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0022_alter_rolemoduleaccess_module'),
        ('chronic', '0004_ingredientclass_activeingredient_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftechIngredientClassRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softech_code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='الاسم')),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تصنيف مادة فعّالة (سوفتك خام)',
                'verbose_name_plural': 'تصنيفات المواد الفعّالة (سوفتك خام)',
                'ordering': ['softech_code'],
            },
        ),
        migrations.CreateModel(
            name='SoftechIngredientRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aicode', models.IntegerField(unique=True, verbose_name='كود سوفتك')),
                ('ainame', models.CharField(db_index=True, max_length=300, verbose_name='الاسم في سوفتك')),
                ('class_code', models.CharField(blank=True, max_length=20, verbose_name='كود التصنيف')),
                ('class_name', models.CharField(blank=True, max_length=200, verbose_name='اسم التصنيف')),
                ('item_count', models.IntegerField(default=0, help_text='كم صنف يشير لهذه المادة عبر itemsai', verbose_name='عدد الأصناف المرتبطة')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='محظور')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='أعمدة إضافية')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مادة فعّالة (سوفتك خام)',
                'verbose_name_plural': 'المواد الفعّالة (سوفتك خام)',
                'ordering': ['ainame'],
            },
        ),
        migrations.CreateModel(
            name='IngredientParseCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_aicode', models.IntegerField(db_index=True, verbose_name='كود سوفتك')),
                ('raw_ainame', models.CharField(max_length=300, verbose_name='الاسم الخام')),
                ('parsed_components', models.JSONField(default=list, help_text='[{molecule, salt, strength_value, strength_unit, raw_fragment}, ...]', verbose_name='المكوّنات المُستخرَجة')),
                ('is_combination', models.BooleanField(default=False, verbose_name='تركيبة مركّبة')),
                ('is_placeholder', models.BooleanField(default=False, verbose_name='قيمة عامة/فارغة')),
                ('proposed_class_code', models.CharField(blank=True, max_length=20, verbose_name='كود التصنيف المقترح')),
                ('proposed_class_name', models.CharField(blank=True, max_length=200, verbose_name='اسم التصنيف المقترح')),
                ('confidence', models.FloatField(db_index=True, default=0.0, verbose_name='درجة الثقة')),
                ('parser_version', models.CharField(blank=True, max_length=10, verbose_name='إصدار المُحلّل')),
                ('status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('needs_review', 'يحتاج مراجعة دقيقة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=15, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_candidates', to='chronic.activeingredient', verbose_name='المادة المعتمدة')),
                ('raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='composition.softechingredientraw', verbose_name='السطر الخام')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ingredient_candidates', to='users.staffprofile', verbose_name='راجعها')),
            ],
            options={
                'verbose_name': 'اقتراح تحليل مادة فعّالة',
                'verbose_name_plural': 'اقتراحات تحليل المواد الفعّالة',
                'ordering': ['-confidence', 'raw_ainame'],
                'indexes': [models.Index(fields=['status', 'confidence'], name='composition_status_40b558_idx'), models.Index(fields=['is_combination', 'status'], name='composition_is_comb_573252_idx')],
            },
        ),
    ]
