# Generated by Django 4.2.13 on 2026-08-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronic', '0005_ingredientclass_key'),
        ('composition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientparsecandidate',
            name='class_confidence',
            field=models.FloatField(default=0.0, verbose_name='ثقة التصنيف'),
        ),
        migrations.AddField(
            model_name='ingredientparsecandidate',
            name='class_rule',
            field=models.CharField(blank=True, max_length=60, verbose_name='قاعدة التصنيف'),
        ),
        migrations.AddField(
            model_name='ingredientparsecandidate',
            name='proposed_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_candidates', to='chronic.ingredientclass', verbose_name='التصنيف الدوائي المقترح'),
        ),
    ]
