# Generated by Django 4.2.13 on 2026-08-24 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronic', '0005_ingredientclass_key'),
        ('composition', '0002_ingredientparsecandidate_class_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientparsecandidate',
            name='is_non_drug',
            field=models.BooleanField(db_index=True, default=False, verbose_name='غير دوائي'),
        ),
        migrations.CreateModel(
            name='CandidateMolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_form', models.CharField(blank=True, max_length=60, verbose_name='صورة الملح')),
                ('is_primary', models.BooleanField(default=False, verbose_name='مادة رئيسية')),
                ('active_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_links', to='chronic.activeingredient', verbose_name='المادة الفعّالة')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molecule_links', to='composition.ingredientparsecandidate', verbose_name='الاقتراح')),
                ('strength', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_links', to='chronic.ingredientstrength', verbose_name='التركيز')),
            ],
            options={
                'verbose_name': 'ربط اقتراح بمادة',
                'verbose_name_plural': 'روابط الاقتراحات بالمواد',
                'unique_together': {('candidate', 'active_ingredient')},
            },
        ),
    ]
