# Generated by Django 4.2.13 on 2026-08-29 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronic', '0005_ingredientclass_key'),
        ('catalog', '0034_category_parent_itemtag_item_tags'),
        ('composition', '0003_ingredientparsecandidate_is_non_drug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftechItemAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_softech_id', models.CharField(db_index=True, max_length=20, verbose_name='كود الصنف')),
                ('aicode', models.IntegerField(db_index=True, verbose_name='كود المادة')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='محظور')),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ربط صنف بمادة (سوفتك خام)',
                'verbose_name_plural': 'روابط الأصناف والمواد (سوفتك خام)',
                'indexes': [models.Index(fields=['aicode', 'item_softech_id'], name='composition_aicode_d5d543_idx')],
                'unique_together': {('item_softech_id', 'aicode')},
            },
        ),
        migrations.CreateModel(
            name='ItemMoleculeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_softech_id', models.CharField(db_index=True, max_length=20, verbose_name='كود الصنف')),
                ('item_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الصنف')),
                ('aicode', models.IntegerField(db_index=True, verbose_name='كود المادة')),
                ('molecule', models.CharField(db_index=True, max_length=200, verbose_name='المادة الفعّالة')),
                ('strength_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='قيمة التركيز')),
                ('strength_unit', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='وحدة التركيز')),
                ('dosage_form', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='الشكل الصيدلي')),
                ('source', models.CharField(db_index=True, default='parsed', max_length=10, verbose_name='المصدر')),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('active_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_index', to='chronic.activeingredient', verbose_name='المادة المعتمدة')),
                ('ingredient_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_index', to='chronic.ingredientclass', verbose_name='التصنيف الدوائي')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='molecule_index', to='catalog.item', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'فهرس صنف×مادة',
                'verbose_name_plural': 'فهرس الأصناف والمواد',
                'indexes': [models.Index(fields=['molecule', 'strength_value', 'strength_unit'], name='composition_molecul_1deb22_idx'), models.Index(fields=['molecule', 'dosage_form'], name='composition_molecul_0c75d4_idx'), models.Index(fields=['ingredient_class', 'dosage_form'], name='composition_ingredi_b7ce08_idx')],
                'unique_together': {('item_softech_id', 'aicode', 'molecule')},
            },
        ),
    ]
