# Generated by Django 4.2.13 on 2026-06-08 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0015_softechsystemmap_erpgroupmodulepermission'),
        ('customers', '0016_add_health_profile_churn_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WAConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='رقم واتساب')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('pending', 'بانتظار رد'), ('resolved', 'محلولة'), ('closed', 'مغلقة')], db_index=True, default='open', max_length=10, verbose_name='الحالة')),
                ('window_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء نافذة المحادثة')),
                ('last_message_preview', models.CharField(blank=True, max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unread_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_conversations', to='users.staffprofile', verbose_name='موكل إلى')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_conversations', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'محادثة واتساب',
                'verbose_name_plural': 'محادثات واتساب',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='WAMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_media_id', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='معرف الوسائط (Meta)')),
                ('file_type', models.CharField(choices=[('image', 'صورة'), ('document', 'مستند'), ('audio', 'صوت'), ('video', 'فيديو'), ('sticker', 'ملصق')], max_length=10, verbose_name='النوع')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='الحجم (بايت)')),
                ('local_file', models.FileField(blank=True, null=True, upload_to='whatsapp/media/%Y/%m/', verbose_name='الملف المحلي')),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffprofile', verbose_name='رُفع بواسطة')),
            ],
            options={
                'verbose_name': 'ملف وسائط واتساب',
                'verbose_name_plural': 'ملفات وسائط واتساب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WAMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'وارد'), ('outbound', 'صادر')], db_index=True, max_length=10, verbose_name='الاتجاه')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('document', 'مستند'), ('audio', 'صوت'), ('video', 'فيديو'), ('location', 'موقع'), ('template', 'قالب'), ('otp', 'OTP'), ('sticker', 'ملصق'), ('reaction', 'تفاعل'), ('order', 'طلب')], default='text', max_length=10, verbose_name='نوع الرسالة')),
                ('status', models.CharField(choices=[('pending', 'قيد الإرسال'), ('sent', 'أُرسل'), ('delivered', 'وصل'), ('read', 'قُرئ'), ('failed', 'فشل')], default='pending', max_length=10, verbose_name='الحالة')),
                ('wamid', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='معرف الرسالة (Meta)')),
                ('body', models.TextField(blank=True, verbose_name='نص الرسالة')),
                ('template_variables', models.JSONField(blank=True, default=list, help_text='[{"type":"text","text":"قيمة"}]', verbose_name='متغيرات القالب')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.waconversation', verbose_name='المحادثة')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.wamediafile', verbose_name='الوسائط')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_messages_sent', to='users.staffprofile', verbose_name='أُرسل بواسطة')),
            ],
            options={
                'verbose_name': 'رسالة واتساب',
                'verbose_name_plural': 'رسائل واتساب',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WATemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='حروف صغيرة وشرطات فقط — يطابق اسم القالب في Meta', max_length=100, unique=True, verbose_name='اسم القالب')),
                ('language', models.CharField(default='ar', max_length=10, verbose_name='اللغة')),
                ('category', models.CharField(choices=[('marketing', 'تسويق'), ('utility', 'خدمة'), ('authentication', 'مصادقة / OTP')], default='utility', max_length=20, verbose_name='التصنيف')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الموافقة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('paused', 'موقوف')], default='pending', max_length=10, verbose_name='الحالة')),
                ('body_text', models.TextField(verbose_name='نص القالب')),
                ('header_type', models.CharField(blank=True, choices=[('text', 'نص'), ('image', 'صورة'), ('document', 'مستند'), ('video', 'فيديو')], max_length=10, verbose_name='نوع الرأس')),
                ('header_text', models.CharField(blank=True, max_length=255, verbose_name='نص الرأس')),
                ('footer_text', models.CharField(blank=True, max_length=255, verbose_name='نص التذييل')),
                ('variable_map', models.JSONField(blank=True, default=dict, verbose_name='خريطة المتغيرات')),
                ('meta_template_id', models.CharField(blank=True, max_length=100, verbose_name='معرف Meta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب واتساب',
                'verbose_name_plural': 'قوالب واتساب',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WAWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_type', models.CharField(blank=True, max_length=50, verbose_name='نوع الكائن')),
                ('entry_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='معرف Entry')),
                ('phone_number_id', models.CharField(blank=True, max_length=50, verbose_name='Phone Number ID')),
                ('payload', models.JSONField(verbose_name='البيانات الخام')),
                ('processed', models.BooleanField(db_index=True, default=False, verbose_name='تمت المعالجة')),
                ('processing_error', models.TextField(blank=True, verbose_name='خطأ المعالجة')),
                ('wa_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='whatsapp.wamessage', verbose_name='الرسالة المرتبطة')),
            ],
            options={
                'verbose_name': 'سجل Webhook واتساب',
                'verbose_name_plural': 'سجلات Webhook واتساب',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='wamessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.watemplate', verbose_name='القالب المستخدم'),
        ),
        migrations.CreateModel(
            name='WAMessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'عاجل (OTP / تأكيد توصيل)'), (2, 'مرتفع (إشعار حجز)'), (3, 'عادي (حملة تسويقية)')], db_index=True, default=3, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الإرسال'), ('processing', 'قيد المعالجة'), ('sent', 'أُرسل'), ('failed', 'فشل نهائي')], db_index=True, default='pending', max_length=12)),
                ('message_type', models.CharField(default='text', max_length=10)),
                ('body', models.TextField(blank=True)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('template_vars', models.JSONField(blank=True, default=list)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='whatsapp.waconversation', verbose_name='المحادثة')),
                ('media_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_items', to='whatsapp.wamediafile')),
                ('wa_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_item', to='whatsapp.wamessage', verbose_name='الرسالة المُنشأة')),
            ],
            options={
                'verbose_name': 'عنصر قائمة الإرسال',
                'verbose_name_plural': 'قائمة الإرسال',
                'ordering': ['priority', 'next_attempt_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='whatsapp_wa_status_822236_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wamessage',
            index=models.Index(fields=['conversation', 'created_at'], name='whatsapp_wa_convers_8b6ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='wamessage',
            index=models.Index(fields=['wamid'], name='whatsapp_wa_wamid_68ec08_idx'),
        ),
        migrations.AddIndex(
            model_name='wamessage',
            index=models.Index(fields=['status', 'created_at'], name='whatsapp_wa_status_eb411c_idx'),
        ),
        migrations.AddIndex(
            model_name='waconversation',
            index=models.Index(fields=['status', 'last_message_at'], name='whatsapp_wa_status_b9b845_idx'),
        ),
        migrations.AddIndex(
            model_name='waconversation',
            index=models.Index(fields=['customer', 'status'], name='whatsapp_wa_custome_b81e68_idx'),
        ),
    ]
