# Generated by Django 4.2.13 on 2026-07-03 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0001_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waconversation',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_conversations', to='omni.channelaccount', verbose_name='حساب واتساب'),
        ),
        migrations.AddField(
            model_name='waconversation',
            name='omni_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_threads', to='omni.conversation', verbose_name='المحادثة الموحدة'),
        ),
    ]
