# Generated by Django 4.2.13 on 2026-07-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_waconversation_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waconversation',
            name='wa_id',
            field=models.CharField(db_index=True, max_length=30, verbose_name='رقم واتساب'),
        ),
        migrations.AddConstraint(
            model_name='waconversation',
            constraint=models.UniqueConstraint(fields=('account', 'wa_id'), name='uniq_wa_thread_per_account'),
        ),
    ]
