# Generated by Django 4.2.13 on 2026-10-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0029_alter_rolemoduleaccess_module"),
        ("branches", "0008_server_wording"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("name_ar", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
                ("desc_ar", models.CharField(blank=True, max_length=300)),
                ("desc_en", models.CharField(blank=True, max_length=300)),
                ("icon", models.CharField(default="🏅", max_length=8)),
                (
                    "criteria",
                    models.CharField(
                        choices=[
                            ("rule_count", "عدد مرات قاعدة"),
                            ("streak", "سلسلة أيام نظيفة"),
                            ("xp", "إجمالي الخبرة"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rule_key", models.SlugField(blank=True)),
                ("threshold", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("sort", models.PositiveIntegerField(default=100)),
            ],
            options={
                "verbose_name": "شارة",
                "verbose_name_plural": "الشارات",
                "ordering": ["sort", "key"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(unique=True, verbose_name="المستوى"),
                ),
                (
                    "min_xp",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="الحد الأدنى للخبرة"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=80, verbose_name="اللقب (عربي)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=80, verbose_name="اللقب (إنجليزي)"),
                ),
                ("icon", models.CharField(default="⭐", max_length=8)),
                ("color", models.CharField(default="slate", max_length=20)),
            ],
            options={
                "verbose_name": "مستوى",
                "verbose_name_plural": "المستويات",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="PointRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True, verbose_name="المفتاح")),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=150, verbose_name="الاسم (إنجليزي)"),
                ),
                (
                    "desc_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="الشرح (عربي)"
                    ),
                ),
                (
                    "desc_en",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="الشرح (إنجليزي)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sales", "المبيعات"),
                            ("reservations", "الحجوزات"),
                            ("demand", "الطلب الضائع والمتابعة"),
                            ("transfers", "التحويلات وطلبات الفروع"),
                            ("inventory", "المخزون والجرد والنواقص"),
                            ("tasks", "المهام"),
                            ("discipline", "الالتزام (لا تترك شيئاً خلفك)"),
                            ("manual", "تقدير يدوي"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="الفئة",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="النقاط")),
                (
                    "unit_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="لقواعد القيمة فقط: نقطة لكل هذا المبلغ (مثلاً 500 جنيه مبيعات)",
                        max_digits=12,
                        null=True,
                        verbose_name="قيمة الوحدة (جنيه)",
                    ),
                ),
                (
                    "cash_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="يُضرب في نقاط مبيعات الكاش (قناة 91)",
                        max_digits=4,
                        verbose_name="مضاعف الكاش",
                    ),
                ),
                (
                    "daily_cap",
                    models.IntegerField(
                        blank=True,
                        help_text="أقصى نقاط (أو خصم) من هذه القاعدة للموظف في اليوم — فارغ = بلا حد",
                        null=True,
                        verbose_name="الحد اليومي",
                    ),
                ),
                (
                    "grace_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="للقواعد الزمنية: الرد السريع خلال هذه المهلة",
                        null=True,
                        verbose_name="مهلة (ساعات)",
                    ),
                ),
                (
                    "roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="فارغ = كل الأدوار",
                        verbose_name="الأدوار",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="مفعّلة"
                    ),
                ),
                ("sort", models.PositiveIntegerField(default=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "قاعدة نقاط",
                "verbose_name_plural": "قواعد النقاط",
                "ordering": ["category", "sort", "key"],
            },
        ),
        migrations.CreateModel(
            name="StaffBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holders",
                        to="gamification.badge",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="PointEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_key", models.SlugField(verbose_name="القاعدة")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sales", "المبيعات"),
                            ("reservations", "الحجوزات"),
                            ("demand", "الطلب الضائع والمتابعة"),
                            ("transfers", "التحويلات وطلبات الفروع"),
                            ("inventory", "المخزون والجرد والنواقص"),
                            ("tasks", "المهام"),
                            ("discipline", "الالتزام (لا تترك شيئاً خلفك)"),
                            ("manual", "تقدير يدوي"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField(verbose_name="النقاط")),
                ("day", models.DateField(db_index=True, verbose_name="اليوم")),
                ("occurred_at", models.DateTimeField(verbose_name="وقت العمل")),
                (
                    "source_key",
                    models.CharField(
                        help_text="مرجع السجل الذي استحق النقاط — يمنع الاحتساب مرتين",
                        max_length=120,
                        verbose_name="المصدر",
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="للتقدير اليدوي فقط",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_events",
                        to="users.staffprofile",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة نقاط",
                "verbose_name_plural": "سجل النقاط",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp", models.PositiveIntegerField(default=0, verbose_name="الخبرة")),
                (
                    "net_points",
                    models.IntegerField(default=0, verbose_name="صافي النقاط"),
                ),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("best_streak", models.PositiveIntegerField(default=0)),
                ("last_clean_day", models.DateField(blank=True, null=True)),
                ("last_scored_day", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="gamification.level",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف لاعب",
                "verbose_name_plural": "ملفات اللاعبين",
            },
        ),
        migrations.CreateModel(
            name="LevelHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp", models.PositiveIntegerField(default=0)),
                ("reached_at", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="gamification.level",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_history",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-reached_at"],
            },
        ),
        migrations.CreateModel(
            name="GamificationChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                ("target", models.CharField(max_length=120)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("earned", models.IntegerField(default=0)),
                ("lost", models.IntegerField(default=0)),
                ("net", models.IntegerField(db_index=True, default=0)),
                ("events", models.PositiveIntegerField(default=0)),
                ("clean_day", models.BooleanField(default=False)),
                (
                    "left_behind",
                    models.PositiveIntegerField(
                        default=0, help_text="عدد البنود المتأخرة عند إغلاق اليوم"
                    ),
                ),
                ("finalized", models.BooleanField(default=False)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="branches.branch",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_scores",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-day"],
            },
        ),
        migrations.AddConstraint(
            model_name="staffbadge",
            constraint=models.UniqueConstraint(
                fields=("staff", "badge"), name="uniq_gamification_badge"
            ),
        ),
        migrations.AddIndex(
            model_name="pointevent",
            index=models.Index(
                fields=["staff", "day"], name="gamificatio_staff_i_67fb8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointevent",
            index=models.Index(
                fields=["day", "category"], name="gamificatio_day_9399e7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pointevent",
            constraint=models.UniqueConstraint(
                fields=("staff", "rule_key", "source_key"),
                name="uniq_gamification_event_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="levelhistory",
            constraint=models.UniqueConstraint(
                fields=("staff", "level"), name="uniq_gamification_level_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyscore",
            constraint=models.UniqueConstraint(
                fields=("staff", "day"), name="uniq_gamification_daily"
            ),
        ),
    ]
