# Generated by Django 4.2.13 on 2026-10-10 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0004_approvalrequest_nominated_approvers_and_more"),
        ("users", "0029_alter_rolemoduleaccess_module"),
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="الاسم (عربي)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=120, verbose_name="الاسم (إنجليزي)"),
                ),
                ("desc_ar", models.CharField(blank=True, max_length=300)),
                ("desc_en", models.CharField(blank=True, max_length=300)),
                ("icon", models.CharField(default="🎁", max_length=8)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("time_off", "وقت راحة"),
                            ("voucher", "قسائم وهدايا"),
                            ("recognition", "تقدير معنوي"),
                            ("development", "تطوير وتدريب"),
                            ("perk", "مزايا"),
                        ],
                        db_index=True,
                        default="perk",
                        max_length=20,
                    ),
                ),
                ("cost", models.PositiveIntegerField(verbose_name="التكلفة (نقاط)")),
                (
                    "stock",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="فارغ = بلا حد. يقل مع كل طلب ويعود عند الرفض/الإلغاء",
                        null=True,
                        verbose_name="المتاح",
                    ),
                ),
                (
                    "limit_per_month",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="حد شهري لكل موظف"
                    ),
                ),
                (
                    "min_level",
                    models.PositiveIntegerField(default=1, verbose_name="أقل مستوى"),
                ),
                (
                    "roles",
                    models.JSONField(
                        blank=True, default=list, help_text="فارغ = كل الأدوار"
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(default=True, verbose_name="يحتاج موافقة"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "مكافأة",
                "verbose_name_plural": "كتالوج المكافآت",
                "ordering": ["sort", "cost", "id"],
            },
        ),
        migrations.CreateModel(
            name="Redemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost",
                    models.PositiveIntegerField(help_text="تكلفة المكافأة وقت الطلب"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار الموافقة"),
                            ("approved", "معتمد — بانتظار التسليم"),
                            ("fulfilled", "تم التسليم"),
                            ("rejected", "مرفوض — أعيدت النقاط"),
                            ("cancelled", "ملغي — أعيدت النقاط"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="ملاحظة الموظف"
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.CharField(blank=True, max_length=300)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fulfillment_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="تفاصيل التسليم"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="approvals.approvalrequest",
                    ),
                ),
                (
                    "fulfilled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="gamification.reward",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب مكافأة",
                "verbose_name_plural": "طلبات المكافآت",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["staff", "status"],
                        name="gamificatio_staff_i_34d0af_idx",
                    )
                ],
            },
        ),
    ]
