# Generated by Django 4.2.13 on 2026-10-10 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0033_alter_notification_notification_type"),
        ("users", "0029_alter_rolemoduleaccess_module"),
        ("branches", "0008_server_wording"),
        ("gamification", "0002_reward_redemption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="criteria",
            field=models.CharField(
                choices=[
                    ("rule_count", "عدد مرات قاعدة"),
                    ("streak", "سلسلة أيام نظيفة"),
                    ("xp", "إجمالي الخبرة"),
                    ("champion", "ألقاب بطل الشهر"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pointevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("sales", "المبيعات"),
                    ("reservations", "الحجوزات"),
                    ("demand", "الطلب الضائع والمتابعة"),
                    ("transfers", "التحويلات وطلبات الفروع"),
                    ("inventory", "المخزون والجرد والنواقص"),
                    ("tasks", "المهام"),
                    ("discipline", "الالتزام (لا تترك شيئاً خلفك)"),
                    ("manual", "تقدير يدوي"),
                    ("champion", "بطل الشهر"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pointrule",
            name="category",
            field=models.CharField(
                choices=[
                    ("sales", "المبيعات"),
                    ("reservations", "الحجوزات"),
                    ("demand", "الطلب الضائع والمتابعة"),
                    ("transfers", "التحويلات وطلبات الفروع"),
                    ("inventory", "المخزون والجرد والنواقص"),
                    ("tasks", "المهام"),
                    ("discipline", "الالتزام (لا تترك شيئاً خلفك)"),
                    ("manual", "تقدير يدوي"),
                    ("champion", "بطل الشهر"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="الفئة",
            ),
        ),
        migrations.CreateModel(
            name="ChampionMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(help_text="أول يوم في الشهر", unique=True)),
                ("crowned_at", models.DateTimeField(auto_now_add=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="notifications.announcement",
                    ),
                ),
                (
                    "crowned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="فارغ = تلقائي من الجدولة",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "شهر متوَّج",
                "verbose_name_plural": "أشهر الأبطال",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="Champion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("branch", "بطل الفرع"),
                            ("network", "بطل الشبكة"),
                            ("branch_of_month", "فرع الشهر"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=20)),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                (
                    "net",
                    models.IntegerField(
                        default=0, help_text="نقاط الشهر (بدون مكافآت الأبطال)"
                    ),
                ),
                (
                    "players",
                    models.PositiveIntegerField(
                        default=0, help_text="عدد المنافسين في المجموعة"
                    ),
                ),
                ("bonus", models.IntegerField(default=0)),
                ("revoked", models.BooleanField(db_index=True, default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="branches.branch",
                    ),
                ),
                (
                    "champion_month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="champions",
                        to="gamification.championmonth",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="champion_titles",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "بطل شهر",
                "verbose_name_plural": "أبطال الشهر",
                "ordering": ["-month", "kind", "role", "rank"],
            },
        ),
    ]
