# Generated by Django 4.2.13 on 2026-06-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_db_connection'),
        ('catalog', '0023_item_pack_price_tax_item_sale_tax_pct'),
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastaccuracy',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_accuracy', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='forecastaccuracy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forecastaccuracy',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_accuracy', to='catalog.item'),
        ),
        migrations.AlterField(
            model_name='forecastrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seasonalityindex',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
