# Generated by Django 4.2.13 on 2026-07-29 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_latitude_branch_longitude'),
        ('forecasting', '0002_alter_forecastaccuracy_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyClassRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_type', models.CharField(help_text='catalog.Item.medicine_type — e.g. 50 = Cosmetics, 20 = Others', max_length=2, unique=True, verbose_name='كود itemmedicine')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='الوصف')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قاعدة تصنيف التجميل',
                'verbose_name_plural': 'قواعد تصنيف التجميل',
                'ordering': ['medicine_type'],
            },
        ),
        migrations.CreateModel(
            name='ChannelBucketMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(db_index=True, help_text='persontypes.ptcode — e.g. 10 = عملاء', max_length=10, verbose_name='نوع الشخص (ptcode)')),
                ('channel', models.CharField(db_index=True, help_text='persontypesclassif.ptclassifcode — stamped on the invoice as sales_channel', max_length=10, verbose_name='كود القناة (ptclassifcode)')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='الوصف')),
                ('bucket', models.CharField(choices=[('cash', 'نقدى'), ('credit', 'آجل'), ('insurance', 'تأمين'), ('exclude', 'مستبعد')], db_index=True, default='exclude', max_length=12, verbose_name='التصنيف')),
                ('subtype', models.CharField(blank=True, choices=[('', '—'), ('delivery', 'توصيل'), ('regular', 'عميل دائم')], default='', max_length=12, verbose_name='التصنيف الفرعي')),
                ('counts_customer', models.BooleanField(default=False, help_text='Include this channel in the distinct-customer count (عدد العملاء).', verbose_name='يُحسب ضمن عدد العملاء')),
                ('include_in_profit', models.BooleanField(default=False, help_text='Include this channel in the gross-profit metric (معامل الربحية).', verbose_name='يُحسب ضمن الربحية')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'ربط قناة البيع',
                'verbose_name_plural': 'ربط قنوات البيع',
                'ordering': ['person_type', 'channel'],
                'unique_together': {('person_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='KpiActualRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='السنة')),
                ('month', models.PositiveSmallIntegerField(verbose_name='الشهر (1–12)')),
                ('metric', models.CharField(db_index=True, max_length=20, verbose_name='المؤشر')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='القيمة')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='آخر حساب')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_rollups', to='branches.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'مؤشر شهري فعلى',
                'verbose_name_plural': 'المؤشرات الشهرية الفعلية',
                'ordering': ['-year', '-month', 'branch', 'metric'],
                'indexes': [models.Index(fields=['year', 'month', 'metric'], name='kpi_rollup_ym_metric_idx')],
                'unique_together': {('branch', 'year', 'month', 'metric')},
            },
        ),
    ]
