# Generated by Django 4.2.13 on 2026-07-29 09:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_rolemoduleaccess_module'),
        ('branches', '0005_branch_latitude_branch_longitude'),
        ('forecasting', '0003_beautyclassrule_channelbucketmap_kpiactualrollup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم السيناريو')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سنة الهدف')),
                ('month', models.PositiveSmallIntegerField(verbose_name='شهر الهدف (1–12)')),
                ('model', models.CharField(choices=[('a', 'Model A — نمو الهدف'), ('b', 'Model B — مزيج مرجّح'), ('avg', 'المتوسط (A+B)/2')], default='a', max_length=4, verbose_name='النموذج')),
                ('incentive_threshold', models.DecimalField(decimal_places=4, default=Decimal('0.9000'), max_digits=5, verbose_name='حد الحافز (÷)')),
                ('benchmark_growth', models.DecimalField(decimal_places=4, default=Decimal('0.3000'), max_digits=6, verbose_name='نمو مرجعي (YoY)')),
                ('inflation', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6, verbose_name='التضخم')),
                ('promotion_lift', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6, verbose_name='رفع العروض')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('generated', 'محسوب'), ('committed', 'معتمد')], db_index=True, default='draft', max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_scenarios', to='users.staffprofile')),
            ],
            options={
                'verbose_name': 'سيناريو تنبؤ',
                'verbose_name_plural': 'سيناريوهات التنبؤ',
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=20, verbose_name='المؤشر')),
                ('base_value', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='الأساس (نفس الشهر العام السابق)')),
                ('lm_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('pm_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('model_a', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('model_b', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('forecast_value', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='التنبؤ')),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='الهدف (تنبؤ ÷ حد الحافز)')),
                ('branch_share', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='حصة الفرع')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_results', to='branches.branch')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='forecasting.forecastscenario')),
            ],
            options={
                'verbose_name': 'نتيجة تنبؤ',
                'verbose_name_plural': 'نتائج التنبؤ',
                'ordering': ['scenario', 'metric', 'branch'],
                'unique_together': {('scenario', 'branch', 'metric')},
            },
        ),
        migrations.CreateModel(
            name='ForecastFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=20, verbose_name='المؤشر')),
                ('growth_goal', models.DecimalField(decimal_places=4, default=Decimal('0.2000'), max_digits=6, verbose_name='هدف النمو (Model A)')),
                ('w_lm', models.DecimalField(decimal_places=4, default=Decimal('0.5000'), max_digits=5, verbose_name='وزن الشهر السابق')),
                ('w_pm', models.DecimalField(decimal_places=4, default=Decimal('0.3000'), max_digits=5, verbose_name='وزن الشهر قبل السابق')),
                ('w_yoy', models.DecimalField(decimal_places=4, default=Decimal('0.2000'), max_digits=5, verbose_name='وزن العام السابق')),
                ('seasonality_index', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=6, verbose_name='مؤشر موسمي')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='forecasting.forecastscenario')),
            ],
            options={
                'verbose_name': 'عامل تنبؤ',
                'verbose_name_plural': 'عوامل التنبؤ',
                'ordering': ['scenario', 'metric'],
                'unique_together': {('scenario', 'metric')},
            },
        ),
    ]
