# Generated by Django 4.2.13 on 2026-07-29 10:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_rolemoduleaccess_module'),
        ('forecasting', '0004_forecastscenario_forecastresult_forecastfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('window_start_year', models.PositiveSmallIntegerField()),
                ('window_start_month', models.PositiveSmallIntegerField()),
                ('window_end_year', models.PositiveSmallIntegerField()),
                ('window_end_month', models.PositiveSmallIntegerField()),
                ('n_months', models.PositiveSmallIntegerField(default=0, verbose_name='عدد الشهور المختبرة')),
                ('benchmark_growth', models.DecimalField(decimal_places=4, default=Decimal('0.3000'), max_digits=6)),
                ('incentive_threshold', models.DecimalField(decimal_places=4, default=Decimal('0.9000'), max_digits=5)),
                ('inflation', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('promotion_lift', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtest_runs', to='users.staffprofile')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='forecasting.forecastscenario', verbose_name='مصدر العوامل')),
            ],
            options={
                'verbose_name': 'تشغيل اختبار رجعي',
                'verbose_name_plural': 'تشغيلات الاختبار الرجعي',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=20, verbose_name='المؤشر')),
                ('model', models.CharField(choices=[('a', 'Model A'), ('b', 'Model B')], max_length=4, verbose_name='النموذج')),
                ('n_points', models.PositiveSmallIntegerField(default=0)),
                ('mape', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='MAPE %')),
                ('wape', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='WAPE %')),
                ('bias', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='الانحياز %')),
                ('rmse', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('is_winner', models.BooleanField(default=False, verbose_name='الأفضل')),
                ('factor_snapshot', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='forecasting.backtestrun')),
            ],
            options={
                'verbose_name': 'نتيجة اختبار رجعي',
                'verbose_name_plural': 'نتائج الاختبار الرجعي',
                'ordering': ['run', 'metric', 'model'],
                'unique_together': {('run', 'metric', 'model')},
            },
        ),
    ]
