# Generated by Django 4.2.13 on 2026-07-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0005_backtestrun_backtestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_agent_usercodes', models.JSONField(default=list, help_text="e.g. ['62','63','64']", verbose_name='أكواد مندوبي الكول سنتر (SOFTECH)')),
                ('call_agent_extensions', models.JSONField(default=list, help_text="e.g. ['10','12','15']", verbose_name='امتدادات هاتف الكول سنتر (CDR)')),
                ('cdr_enabled', models.BooleanField(default=False, verbose_name='ربط CDR مباشر مُفعّل')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعداد الكول سنتر',
                'verbose_name_plural': 'إعداد الكول سنتر',
            },
        ),
    ]
