# Generated by Django 4.2.13 on 2026-07-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0006_callcenterconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastresult',
            options={'ordering': ['scenario', 'metric', 'scope_key'], 'verbose_name': 'نتيجة تنبؤ', 'verbose_name_plural': 'نتائج التنبؤ'},
        ),
        migrations.AlterUniqueTogether(
            name='forecastresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='forecastresult',
            name='scope_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='مفتاح النطاق'),
        ),
        migrations.AddField(
            model_name='forecastresult',
            name='scope_label',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم النطاق'),
        ),
        migrations.AddField(
            model_name='forecastscenario',
            name='scope_type',
            field=models.CharField(choices=[('branch', 'فرع'), ('salesperson', 'مندوب'), ('category', 'فئة')], default='branch', max_length=12, verbose_name='مستوى التنبؤ'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastresult',
            unique_together={('scenario', 'scope_key', 'metric')},
        ),
    ]
