# Generated by Django 4.2.13 on 2026-07-31 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_itemalias'),
        ('forecasting', '0007_alter_forecastresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCountExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='السبب')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_count_exclusion', to='catalog.item', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'استثناء من عدّ الوحدات',
                'verbose_name_plural': 'استثناءات عدّ الوحدات',
                'ordering': ['item'],
            },
        ),
    ]
