# Generated by Django 4.2.13 on 2026-07-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0008_unitcountexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricGuardrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='الاسم')),
                ('scope_type', models.CharField(choices=[('branch', 'فرع'), ('salesperson', 'مندوب'), ('category', 'فئة'), ('chain', 'الشبكة')], default='branch', max_length=12, verbose_name='النطاق')),
                ('reward_metric', models.CharField(blank=True, max_length=20, verbose_name='مؤشر المكافأة')),
                ('guardrail_metric', models.CharField(max_length=20, verbose_name='مؤشر الحارس')),
                ('operator', models.CharField(choices=[('lte', '≤'), ('gte', '≥'), ('lt', '<'), ('gt', '>')], default='lte', max_length=3, verbose_name='المُقارن')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الحد')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'حارس مؤشر',
                'verbose_name_plural': 'حراس المؤشرات',
                'ordering': ['scope_type', 'reward_metric', 'guardrail_metric'],
            },
        ),
    ]
