# Generated by Django 4.2.13 on 2026-10-08 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_item_supplier_link'),
        ('forecasting', '0009_metricguardrail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='السبب')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_exclusion', to='catalog.item', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'استثناء من الربحية',
                'verbose_name_plural': 'استثناءات الربحية',
                'ordering': ['item'],
            },
        ),
    ]
