# Generated by Django 4.2.13 on 2026-06-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvalrequest',
            new_name='approvals_a_status_0ec05a_idx',
            old_name='appr_req_status_step_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalrequest',
            new_name='approvals_a_workflo_8abdba_idx',
            old_name='appr_req_wf_status_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalrequest',
            new_name='approvals_a_request_093c05_idx',
            old_name='appr_req_by_status_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalrequest',
            new_name='approvals_a_content_39fd3d_idx',
            old_name='appr_req_content_idx',
        ),
        migrations.AlterField(
            model_name='approvalstepdefinition',
            name='escalation_hours',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = بدون تصعيد', verbose_name='ساعات التصعيد'),
        ),
        migrations.AlterField(
            model_name='approvalstepdefinition',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='إذا لم يستجب المعتمِد خلال مهلة التصعيد، تُعتمَد الخطوة تلقائياً', verbose_name='اختيارية'),
        ),
    ]
