# Generated by Django 4.2.13 on 2026-06-19 11:49

from django.db import migrations, models


HR_CODES = [
    'leave_request', 'emergency_leave', 'salary_advance',
    'expense_claim', 'mamoriya', 'overtime',
]


def backfill_hr_category(apps, schema_editor):
    """Existing rows default to 'operational'; flip the known HR workflows to 'hr'
    so the operational approvals inbox excludes them without needing a reseed."""
    WF = apps.get_model('approvals', 'ApprovalWorkflowDefinition')
    WF.objects.filter(code__in=HR_CODES).update(category='hr')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_rename_appr_req_status_step_idx_approvals_a_status_0ec05a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflowdefinition',
            name='category',
            field=models.CharField(choices=[('operational', 'تشغيلي'), ('hr', 'موارد بشرية'), ('finance', 'مالي')], db_index=True, default='operational', max_length=20, verbose_name='التصنيف'),
        ),
        migrations.RunPython(backfill_hr_category, noop),
    ]
