# Generated by Django 4.2.13 on 2026-08-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_rolemoduleaccess_module'),
        ('approvals', '0003_approvalworkflowdefinition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='nominated_approvers',
            field=models.ManyToManyField(blank=True, related_name='nominated_approval_requests', to='users.staffprofile', verbose_name='المعتمِدون المختارون'),
        ),
        migrations.AddField(
            model_name='approvalstepdefinition',
            name='use_nominated_approvers',
            field=models.BooleanField(default=False, verbose_name='معتمِدون يختارهم مقدّم الطلب'),
        ),
    ]
