# Generated by Django 4.2.13 on 2026-05-27 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_productbundle_discount_value'),
        ('customers', '0015_customer_segment_fields'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerrecommendation',
            new_name='recommendat_run_id_d01901_idx',
            old_name='rec_cust_run_customer_score_idx',
        ),
        migrations.RenameIndex(
            model_name='frequentlyboughttogether',
            new_name='recommendat_run_id_b08e26_idx',
            old_name='rec_fbt_run_itema_score_idx',
        ),
        migrations.RenameIndex(
            model_name='frequentlyboughttogether',
            new_name='recommendat_run_id_3f4042_idx',
            old_name='rec_fbt_run_itemb_score_idx',
        ),
        migrations.AlterField(
            model_name='customerrecommendation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='customers.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='customerrecommendation',
            name='is_chronic_related',
            field=models.BooleanField(default=False, help_text='True إذا كان الصنف لنفس المرض المزمن للعميل', verbose_name='مرتبط بمرض مزمن'),
        ),
        migrations.AlterField(
            model_name='customerrecommendation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='catalog.item', verbose_name='الصنف الموصى به'),
        ),
        migrations.AlterField(
            model_name='customerrecommendation',
            name='reason',
            field=models.CharField(blank=True, help_text='e.g. "اشترى معه 73% من العملاء"', max_length=255, verbose_name='سبب التوصية'),
        ),
        migrations.AlterField(
            model_name='customerrecommendation',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_recs', to='recommendations.recommendationenginerun', verbose_name='تشغيل'),
        ),
        migrations.AlterField(
            model_name='customerrecommendation',
            name='score',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='درجة التوصية'),
        ),
        migrations.AlterField(
            model_name='frequentlyboughttogether',
            name='co_occurrences',
            field=models.PositiveIntegerField(default=0, verbose_name='تكرار الاقتران'),
        ),
        migrations.AlterField(
            model_name='frequentlyboughttogether',
            name='confidence',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='الثقة'),
        ),
        migrations.AlterField(
            model_name='frequentlyboughttogether',
            name='item_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbt_as_anchor', to='catalog.item', verbose_name='الصنف الأساسي'),
        ),
        migrations.AlterField(
            model_name='frequentlyboughttogether',
            name='item_a_occurrences',
            field=models.PositiveIntegerField(default=0, verbose_name='تكرار الصنف الأساسي'),
        ),
        migrations.AlterField(
            model_name='frequentlyboughttogether',
            name='item_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbt_as_recommendation', to='catalog.item', verbose_name='الصنف الموصى به'),
        ),
        migrations.AlterField(
            model_name='frequentlyboughttogether',
            name='lift',
            field=models.FloatField(default=0.0, verbose_name='الرفع'),
        ),
        migrations.AlterField(
            model_name='frequentlyboughttogether',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbt_pairs', to='recommendations.recommendationenginerun', verbose_name='تشغيل'),
        ),
        migrations.AlterField(
            model_name='frequentlyboughttogether',
            name='score',
            field=models.FloatField(db_index=True, default=0.0, help_text='confidence × log(co_occurrences+1) — used for ranking', verbose_name='الدرجة المُركَّبة'),
        ),
        migrations.AlterField(
            model_name='frequentlyboughttogether',
            name='support',
            field=models.FloatField(default=0.0, verbose_name='الدعم'),
        ),
        migrations.AlterField(
            model_name='recommendationenginerun',
            name='min_confidence',
            field=models.FloatField(default=0.05, help_text='Minimum confidence threshold used'),
        ),
        migrations.AlterField(
            model_name='recommendationenginerun',
            name='min_support',
            field=models.FloatField(default=0.001, help_text='Minimum support threshold used'),
        ),
    ]
