# Generated by Django 4.2.13 on 2026-06-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_bank_statement_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementimport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bankstatementimport',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'كاش'), ('instapay', 'إنستاباي'), ('vodafone_cash', 'فودافون كاش'), ('orange_cash', 'أورنج كاش'), ('etisalat_cash', 'اتصالات كاش'), ('fawry', 'فوري'), ('pos_terminal', 'POS'), ('cash_deposit', 'إيداع نقدي'), ('bank_transfer', 'تحويل بنكي'), ('other', 'أخرى')], max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externalpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'كاش'), ('instapay', 'إنستاباي'), ('vodafone_cash', 'فودافون كاش'), ('orange_cash', 'أورنج كاش'), ('etisalat_cash', 'اتصالات كاش'), ('fawry', 'فوري'), ('pos_terminal', 'POS'), ('cash_deposit', 'إيداع نقدي'), ('bank_transfer', 'تحويل بنكي'), ('other', 'أخرى')], max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='paymentexception',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
