# Generated by Django 4.2.13 on 2026-05-27 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chequeinstalment',
            name='cheques_ins_plan_s_idx',
        ),
        migrations.RemoveIndex(
            model_name='chequeinstalment',
            name='cheques_ins_due_s_idx',
        ),
    ]
