# Generated by Django 4.2.13 on 2026-05-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_purchasehistory_invoice_date'),
        ('followups', '0002_make_customer_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chronicmedicationprofile',
            options={'ordering': ['item__name'], 'verbose_name': 'بروفايل دواء مزمن', 'verbose_name_plural': 'بروفايلات الأدوية المزمنة'},
        ),
        migrations.AlterModelOptions(
            name='followuptask',
            options={'ordering': ['due_date', '-created_at'], 'verbose_name': 'مهمة متابعة', 'verbose_name_plural': 'مهام المتابعة'},
        ),
        migrations.RenameIndex(
            model_name='followuptask',
            new_name='followups_f_status_359984_idx',
            old_name='fu_status_due_idx',
        ),
        migrations.RenameIndex(
            model_name='followuptask',
            new_name='followups_f_custome_f173e6_idx',
            old_name='fu_customer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='followuptask',
            new_name='followups_f_item_id_3d6c2a_idx',
            old_name='fu_item_status_idx',
        ),
        migrations.RenameIndex(
            model_name='followuptask',
            new_name='followups_f_branch__8cf0cd_idx',
            old_name='fu_branch_status_due_idx',
        ),
        migrations.AlterField(
            model_name='chronicmedicationprofile',
            name='avg_daily_usage',
            field=models.DecimalField(decimal_places=3, default=1, help_text='مثال: 1 قرص/يوم = 1.0, نصف قرص/يوم = 0.5', max_digits=8, verbose_name='متوسط الاستخدام اليومي (وحدة/يوم)'),
        ),
        migrations.AlterField(
            model_name='chronicmedicationprofile',
            name='expected_duration_days',
            field=models.PositiveIntegerField(default=30, help_text='يُحسب تلقائياً: حجم_العبوة ÷ الاستخدام_اليومي', verbose_name='مدة العبوة المتوقعة (يوم)'),
        ),
        migrations.AlterField(
            model_name='chronicmedicationprofile',
            name='followup_before_days',
            field=models.PositiveIntegerField(default=5, help_text='يُنشأ التذكير قبل نفاد الدواء بهذا العدد من الأيام', verbose_name='أيام التذكير قبل النفاد'),
        ),
        migrations.AlterField(
            model_name='chronicmedicationprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chronicmedicationprofile',
            name='pack_size',
            field=models.DecimalField(decimal_places=3, default=30, help_text='عدد الأقراص/الكبسولات/الجرعات في العبوة الواحدة', max_digits=8, verbose_name='حجم العبوة (وحدة)'),
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_tasks', to='customers.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='source_sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ آخر بيع في الـ ERP'),
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق — لم يُتواصل بعد'), ('called', 'تم الاتصال — لا رد'), ('done', 'مكتمل — تم الشراء'), ('missed', 'فائت — لا استجابة'), ('auto_closed', 'أُغلق تلقائياً — الـ ERP أكّد البيع'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=12, verbose_name='الحالة'),
        ),
    ]
