# Generated by Django 4.2.13 on 2026-05-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0003_alter_chronicmedicationprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuptask',
            name='source_erp_transaction',
            field=models.CharField(blank=True, help_text='docnumber من stktransm', max_length=50, verbose_name='رقم معاملة ERP المصدر'),
        ),
    ]
