# Generated by Django 4.2.13 on 2026-05-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0006_followuptask_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuptask',
            name='reminder_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='إذا حُدِّد، تُرسَل إشعار للمعيَّن له في هذا الوقت', null=True, verbose_name='موعد التذكير'),
        ),
    ]
