# Generated by Django 4.2.13 on 2026-06-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_campaigns_c_campaig_idx_campaigns_c_campaig_407020_idx_and_more'),
        ('demand', '0002_rename_demand_status_branch_idx_demand_dema_status_7047e1_idx_and_more'),
        ('users', '0012_alter_rolemoduleaccess_role_alter_staffprofile_role'),
        ('followups', '0013_followuptask_priority_phone_bridges'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='followuptaskassignment',
            name='unique_followup_task_assignment',
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='closing_erp_transaction',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم مستند ERP الإغلاق'),
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='demand_record',
            field=models.ForeignKey(blank=True, help_text='طلب طلب تم إنشاؤه تلقائياً من هذه المهمة (إعادة طلب أو صنف غير متوفر)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_tasks', to='demand.demandrecord', verbose_name='طلب مرتبط'),
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='source_campaign',
            field=models.ForeignKey(blank=True, help_text='الحملة التي أُنشئت منها هذه المهمة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_tasks', to='campaigns.whatsappcampaign', verbose_name='حملة المصدر'),
        ),
        migrations.AlterUniqueTogether(
            name='followuptaskassignment',
            unique_together={('task', 'staff')},
        ),
    ]
