# Generated by Django 4.2.13 on 2026-10-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0008_server_wording"),
        ("reservations", "0021_alter_reservation_contract_subtype_and_more"),
        ("customers", "0019_segmentationconfig"),
        ("users", "0027_alter_rolemoduleaccess_module"),
        (
            "followups",
            "0014_remove_followuptaskassignment_unique_followup_task_assignment_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RefillReminderOptOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="whatsapp_button", max_length=20)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refill_reminder_opt_out",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "إيقاف تذكيرات الصرف",
                "verbose_name_plural": "إيقاف تذكيرات الصرف",
            },
        ),
        migrations.CreateModel(
            name="RefillReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "أُرسل"),
                            ("failed", "فشل الإرسال"),
                            ("replied", "ردّ العميل"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("wamid", models.CharField(blank=True, db_index=True, max_length=120)),
                ("attempts", models.PositiveSmallIntegerField(default=1)),
                (
                    "reply_choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("branch", "تجهيز في الفرع"),
                            ("delivery", "توصيل للمنزل"),
                            ("stop", "إيقاف التذكيرات"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="branches.branch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refill_reminders",
                        to="customers.customer",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refill_reminder",
                        to="followups.followuptask",
                        verbose_name="مهمة المتابعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تذكير صرف واتساب",
                "verbose_name_plural": "تذكيرات الصرف واتساب",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "sent_at"],
                        name="followups_r_custome_191cb2_idx",
                    )
                ],
            },
        ),
    ]
