# Generated by Django 4.2.13 on 2026-07-03 22:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0016_add_health_profile_churn_whatsapp'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0019_alter_rolemoduleaccess_module'),
        ('branches', '0005_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'واتساب'), ('voice', 'مكالمات'), ('messenger', 'فيسبوك ماسنجر'), ('instagram', 'إنستجرام'), ('telegram', 'تيليجرام'), ('tiktok', 'تيك توك'), ('sms', 'رسائل SMS'), ('email', 'بريد إلكتروني')], db_index=True, max_length=12, verbose_name='القناة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحساب')),
                ('phone_or_handle', models.CharField(max_length=100, verbose_name='الرقم / المعرف')),
                ('department', models.CharField(blank=True, help_text='مثل: مركز الاتصالات، التوصيل، التأمين', max_length=50, verbose_name='القسم')),
                ('provider', models.CharField(choices=[('meta_cloud', 'Meta Cloud API'), ('d360', '360dialog'), ('twilio', 'Twilio'), ('android_bridge', 'جسر أندرويد (مرحلي)'), ('ami', 'Issabel / Asterisk AMI'), ('meta_graph', 'Meta Graph (ماسنجر/إنستجرام)'), ('telegram_bot', 'Telegram Bot API'), ('other', 'أخرى')], default='meta_cloud', max_length=15, verbose_name='المزوّد')),
                ('credentials', models.JSONField(blank=True, default=dict, verbose_name='بيانات الاعتماد')),
                ('status', models.CharField(choices=[('connected', 'متصل'), ('disconnected', 'منقطع'), ('degraded', 'متدهور'), ('pending_qr', 'بانتظار QR')], db_index=True, default='connected', max_length=12, verbose_name='الحالة')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر نبضة')),
                ('health', models.JSONField(blank=True, default=dict, verbose_name='الصحة')),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='{"sat": ["09:00","23:00"], ...} — فارغ = دائماً', verbose_name='ساعات العمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omni_accounts', to='branches.branch', verbose_name='الفرع')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_omni_accounts', to='users.staffprofile', verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'حساب قناة',
                'verbose_name_plural': 'حسابات القنوات',
                'ordering': ['channel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='هاتف جهة الاتصال')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('pending', 'بانتظار رد'), ('snoozed', 'مؤجلة'), ('resolved', 'محلولة'), ('closed', 'مغلقة')], db_index=True, default='open', max_length=10, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('normal', 'عادية'), ('high', 'مرتفعة'), ('urgent', 'عاجلة')], default='normal', max_length=8, verbose_name='الأولوية')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='الموضوع')),
                ('created_from_channel', models.CharField(blank=True, db_index=True, max_length=12, verbose_name='قناة الإنشاء')),
                ('first_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_event_preview', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omni_conversations', to='users.staffprofile', verbose_name='موكلة إلى')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omni_conversations', to='branches.branch', verbose_name='الفرع')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omni_conversations', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'محادثة موحدة',
                'verbose_name_plural': 'المحادثات الموحدة',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('message_in', 'رسالة واردة'), ('message_out', 'رسالة صادرة'), ('call', 'مكالمة'), ('call_missed', 'مكالمة فائتة'), ('note', 'ملاحظة داخلية'), ('assignment', 'إسناد'), ('status_change', 'تغيير حالة'), ('erp_reservation', 'حجز'), ('erp_delivery', 'توصيل'), ('erp_invoice', 'فاتورة'), ('erp_case', 'حالة خدمة'), ('erp_demand', 'طلب غير متوفر'), ('erp_payment', 'دفعة'), ('ai_insight', 'تحليل ذكي'), ('automation_action', 'إجراء آلي'), ('sla_breach', 'تجاوز SLA')], db_index=True, max_length=20, verbose_name='نوع الحدث')),
                ('channel', models.CharField(blank=True, max_length=12, verbose_name='القناة')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='الملخص')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='omni.channelaccount', verbose_name='حساب القناة')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omni_events', to='users.staffprofile', verbose_name='الموظف')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='omni.conversation', verbose_name='المحادثة')),
            ],
            options={
                'verbose_name': 'حدث محادثة',
                'verbose_name_plural': 'أحداث المحادثات',
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['conversation', 'occurred_at'], name='omni_timeli_convers_2f525b_idx'), models.Index(fields=['content_type', 'object_id'], name='omni_timeli_content_922243_idx'), models.Index(fields=['event_type', 'occurred_at'], name='omni_timeli_event_t_adcfac_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'last_activity_at'], name='omni_conver_status_94fd64_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['customer', 'status'], name='omni_conver_custome_234a81_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['assigned_to', 'status'], name='omni_conver_assigne_f74aa3_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelaccount',
            constraint=models.UniqueConstraint(fields=('channel', 'phone_or_handle'), name='uniq_omni_account_channel_handle'),
        ),
    ]
