# Generated by Django 4.2.13 on 2026-07-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelaccount',
            name='is_default',
            field=models.BooleanField(default=False, help_text='حساب الإرسال الافتراضي للقناة عندما لا يُحدَّد حساب', verbose_name='الحساب الافتراضي'),
        ),
        migrations.AddField(
            model_name='channelaccount',
            name='provider_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Meta phone_number_id — يوجّه Webhooks الواردة لهذا الحساب', max_length=100, verbose_name='معرف المزوّد'),
        ),
    ]
