# Generated by Django 4.2.13 on 2026-07-04 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_rolemoduleaccess_module'),
        ('omni', '0002_channelaccount_is_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم القاعدة')),
                ('trigger', models.CharField(choices=[('message_in', 'رسالة واردة'), ('call', 'مكالمة'), ('call_missed', 'مكالمة فائتة'), ('erp_reservation', 'حجز'), ('ai_insight', 'تحليل ذكي')], db_index=True, max_length=20, verbose_name='المُحفِّز')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='الشروط')),
                ('actions', models.JSONField(blank=True, default=list, verbose_name='الإجراءات')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
                ('stop_processing', models.BooleanField(default=False, verbose_name='إيقاف القواعد التالية')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='الترتيب')),
                ('run_count', models.PositiveIntegerField(default=0, verbose_name='مرات التنفيذ')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omni_automations', to='users.staffprofile')),
            ],
            options={
                'verbose_name': 'قاعدة أتمتة',
                'verbose_name_plural': 'قواعد الأتمتة',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched', models.BooleanField(default=False)),
                ('actions_run', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to='omni.conversation')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_runs', to='omni.timelineevent')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='omni.automationrule')),
            ],
            options={
                'verbose_name': 'تنفيذ أتمتة',
                'verbose_name_plural': 'تنفيذات الأتمتة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['trigger', 'is_active'], name='omni_automa_trigger_7d2598_idx'),
        ),
    ]
