# Generated by Django 4.2.13 on 2026-04-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_staffprofile_softech_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin — Full Access'), ('call_center', 'Call Center — All Branches'), ('pharmacist', 'Pharmacist — Own Branch'), ('salesperson', 'Sales Person — Own Branch'), ('viewer', 'Viewer — Read Only')], default='salesperson', max_length=20),
        ),
    ]
