# Generated by Django 4.2.13 on 2026-04-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('call_center', 'Call Center'), ('pharmacist', 'Pharmacist'), ('salesperson', 'Sales Person'), ('purchasing', 'Purchasing'), ('viewer', 'Viewer')], default='salesperson', max_length=20),
        ),
    ]
