# Generated by Django 4.2.13 on 2026-04-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin — Full Access'), ('call_center', 'Call Center — All Branches'), ('pharmacist', 'Pharmacist — Own Branch'), ('salesperson', 'Sales Person — Own Branch'), ('purchasing', 'Purchasing — HQ Only'), ('delivery', 'Delivery'), ('viewer', 'Viewer — Read Only')], default='salesperson', max_length=20),
        ),
    ]
