# Generated by Django 4.2.13 on 2026-05-13 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('users', '0008_erpuser_staffprofile_extensions_useractivitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'ملف الموظف', 'verbose_name_plural': 'ملفات الموظفين'},
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch', verbose_name='الفرع الأساسي'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin — Full Access'), ('call_center', 'Call Center — All Branches'), ('pharmacist', 'Pharmacist — Own Branch'), ('salesperson', 'Sales Person — Own Branch'), ('purchasing', 'Purchasing — HQ Only'), ('delivery', 'Delivery'), ('viewer', 'Viewer — Read Only')], default='salesperson', max_length=20, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='softech_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='رقم المستخدم في SOFTECH'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='softech_username',
            field=models.CharField(blank=True, max_length=50, verbose_name='اسم المستخدم في SOFTECH'),
        ),
    ]
