# Generated by Django 4.2.13 on 2026-05-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_staffprofile_notification_prefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemoduleaccess',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin — Full Access'), ('call_center', 'Call Center — All Branches'), ('pharmacist', 'Pharmacist — Own Branch'), ('salesperson', 'Sales Person — Own Branch'), ('purchasing', 'Purchasing — HQ Only'), ('delivery', 'Delivery'), ('viewer', 'Viewer — Read Only'), ('supervisor', 'Supervisor — Call Center Supervisor'), ('quality_manager', 'Quality Manager — QA & Scoring')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin — Full Access'), ('call_center', 'Call Center — All Branches'), ('pharmacist', 'Pharmacist — Own Branch'), ('salesperson', 'Sales Person — Own Branch'), ('purchasing', 'Purchasing — HQ Only'), ('delivery', 'Delivery'), ('viewer', 'Viewer — Read Only'), ('supervisor', 'Supervisor — Call Center Supervisor'), ('quality_manager', 'Quality Manager — QA & Scoring')], default='salesperson', max_length=20, verbose_name='الدور'),
        ),
    ]
