# Generated by Django 4.2.13 on 2026-06-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_extended_module_action_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitemname', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='كود الشاشة')),
                ('descr_ar', models.CharField(blank=True, max_length=120, verbose_name='الوصف')),
                ('descr_en', models.CharField(blank=True, max_length=120, verbose_name='Description')),
                ('system', models.CharField(blank=True, db_index=True, max_length=4, verbose_name='النظام')),
                ('subsystem', models.CharField(blank=True, max_length=20, verbose_name='النظام الفرعي')),
                ('item_order', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شاشة ERP',
                'verbose_name_plural': 'شاشات ERP',
                'ordering': ['system', 'subsystem', 'item_order', 'mitemname'],
            },
        ),
        migrations.CreateModel(
            name='ErpUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usergroup', models.IntegerField(db_index=True, unique=True, verbose_name='كود المجموعة')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='اسم المجموعة')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='محظورة')),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مجموعة مستخدمي ERP',
                'verbose_name_plural': 'مجموعات مستخدمي ERP',
                'ordering': ['usergroup'],
            },
        ),
        migrations.CreateModel(
            name='ErpGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitemname', models.CharField(db_index=True, max_length=20, verbose_name='كود الشاشة')),
                ('can_enable', models.BooleanField(default=False)),
                ('can_show', models.BooleanField(default=False)),
                ('can_retrieve', models.BooleanField(default=False)),
                ('can_save', models.BooleanField(default=False)),
                ('can_datain', models.BooleanField(default=False)),
                ('can_print', models.BooleanField(default=False)),
                ('can_scan', models.BooleanField(default=False)),
                ('can_data', models.BooleanField(default=False)),
                ('can_money', models.BooleanField(default=False)),
                ('can_cost', models.BooleanField(default=False)),
                ('can_brmb', models.BooleanField(default=False)),
                ('can_scanedit', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.erpusergroup', verbose_name='المجموعة')),
            ],
            options={
                'verbose_name': 'صلاحية مجموعة ERP',
                'verbose_name_plural': 'صلاحيات مجموعات ERP',
                'indexes': [models.Index(fields=['group', 'mitemname'], name='users_erpgr_group_i_c2a6e7_idx')],
                'unique_together': {('group', 'mitemname')},
            },
        ),
    ]
