# Generated by Django 4.2.13 on 2026-06-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_erpscreen_erpusergroup_erpgrouppermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftechSystemMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(db_index=True, max_length=4, verbose_name='نظام Softech')),
                ('django_module', models.CharField(db_index=True, max_length=40, verbose_name='وحدة المنصة')),
                ('note', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ربط نظام Softech بوحدة',
                'verbose_name_plural': 'ربط أنظمة Softech بالوحدات',
                'ordering': ['django_module', 'system'],
                'unique_together': {('system', 'django_module')},
            },
        ),
        migrations.CreateModel(
            name='ErpGroupModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=40)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_see_cost', models.BooleanField(default=False)),
                ('screens_count', models.PositiveIntegerField(default=0)),
                ('derived_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='users.erpusergroup')),
            ],
            options={
                'verbose_name': 'صلاحية وحدة مشتقّة',
                'verbose_name_plural': 'صلاحيات الوحدات المشتقّة',
                'ordering': ['group', 'module'],
                'unique_together': {('group', 'module')},
            },
        ),
    ]
