# Generated by Django 4.2.13 on 2026-06-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_softechsystemmap_erpgroupmodulepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='muted_notification_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='فئات إشعارات مكتومة'),
        ),
    ]
