# Generated by Django 4.2.13 on 2026-06-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_staffprofile_muted_notification_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='mfa_backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='رموز الاسترجاع (مجزّأة)'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='mfa_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تفعيل المصادقة الثنائية'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='mfa_enabled',
            field=models.BooleanField(default=False, verbose_name='المصادقة الثنائية مفعّلة'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='mfa_secret',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='سر TOTP'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('login_success', 'دخول ناجح'), ('login_failed', 'محاولة دخول فاشلة'), ('password_changed', 'تغيير كلمة المرور'), ('password_reset', 'إعادة تعيين كلمة المرور بواسطة المدير'), ('role_changed', 'تغيير الدور'), ('branch_changed', 'تغيير الفرع'), ('activated', 'تفعيل الحساب'), ('deactivated', 'تعطيل الحساب'), ('permissions_changed', 'تغيير الصلاحيات'), ('created', 'إنشاء المستخدم'), ('mfa_enabled', 'تفعيل المصادقة الثنائية'), ('mfa_disabled', 'إيقاف المصادقة الثنائية'), ('mfa_verified', 'اجتياز المصادقة الثنائية'), ('mfa_failed', 'فشل المصادقة الثنائية')], max_length=30, verbose_name='الإجراء'),
        ),
    ]
