# Generated by Django 4.2.13 on 2026-08-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_rolemoduleaccess_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='hr_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='كود الموارد البشرية'),
        ),
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('hr_code', ''), _negated=True), fields=('hr_code',), name='uniq_staffprofile_hr_code_nonblank'),
        ),
    ]
