# Generated by Django 4.2.13 on 2026-08-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_staffprofile_hr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='can_edit_erp_comments',
            field=models.BooleanField(default=False, help_text='يسمح بالكتابة في حقل الملاحظات على مستندات SOFTECH (كتابة فعلية للـ ERP)', verbose_name='تعديل ملاحظات مستندات SOFTECH'),
        ),
    ]
