# Generated by Django 4.2.13 on 2026-09-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_seed_insurance_commerce_rbac'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='allowed_pos_channels',
            field=models.JSONField(blank=True, default=list, help_text='قائمة قنوات البيع المسموح بها لهذا الموظف — فارغة تعني كل القنوات', verbose_name='قنوات البيع المسموح بها'),
        ),
    ]
