# Generated by Django 4.2.13 on 2026-09-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_staffprofile_allowed_pos_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='notify_expiry_worklist_wa',
            field=models.BooleanField(default=False, verbose_name='إشعار قائمة الصلاحيات عبر واتساب'),
        ),
    ]
