# Generated by Django 4.2.13 on 2026-06-03 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0022_item_additional_discp_item_pharmacy_discp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPriceChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('old_values', models.JSONField(verbose_name='القيم الحالية')),
                ('new_values', models.JSONField(verbose_name='القيم المقترحة')),
                ('reason', models.TextField(verbose_name='سبب التعديل')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('executed', 'منفذ في Softech'), ('failed', 'فشل في التنفيذ')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('erp_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التنفيذ في Softech')),
                ('erp_usercode', models.CharField(blank=True, max_length=10, verbose_name='كود المستخدم في Softech')),
                ('erp_error', models.TextField(blank=True, verbose_name='خطأ التنفيذ')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_change_requests', to='catalog.item', verbose_name='الصنف')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_price_changes', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد/رفض بواسطة')),
            ],
            options={
                'verbose_name': 'طلب تعديل سعر / خصم',
                'verbose_name_plural': 'طلبات تعديل الأسعار والخصومات',
                'ordering': ['-requested_at'],
            },
        ),
    ]
