# Generated by Django 4.2.13 on 2026-06-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempricechangerequest',
            name='erp_username',
            field=models.CharField(blank=True, max_length=50, verbose_name='اسم Softech للمعتمِد'),
        ),
        migrations.AddField(
            model_name='itempricechangerequest',
            name='executed_values',
            field=models.JSONField(default=dict, verbose_name='القيم المنفذة فعلياً'),
        ),
        migrations.AlterField(
            model_name='itempricechangerequest',
            name='erp_usercode',
            field=models.CharField(blank=True, max_length=10, verbose_name='كود Softech للمعتمِد'),
        ),
    ]
