# Generated by Django 4.2.13 on 2026-06-05 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount_approvals', '0002_itempricechangerequest_erp_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempricechangerequest',
            name='rolled_back_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollbacks', to='discount_approvals.itempricechangerequest', verbose_name='تراجع عن الطلب'),
        ),
        migrations.AddField(
            model_name='itempricechangerequest',
            name='source',
            field=models.CharField(choices=[('manual', 'يدوي'), ('import', 'استيراد ملف'), ('rollback', 'تراجع')], db_index=True, default='manual', max_length=20, verbose_name='مصدر الطلب'),
        ),
        migrations.CreateModel(
            name='ReplicationScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بدأ في')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى في')),
                ('days_window', models.PositiveIntegerField(default=30, verbose_name='نافذة الأيام')),
                ('status', models.CharField(choices=[('running', 'قيد التنفيذ'), ('done', 'مكتمل'), ('failed', 'فشل')], default='running', max_length=12)),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='مجدول')),
                ('items_checked', models.PositiveIntegerField(default=0, verbose_name='أصناف مفحوصة')),
                ('items_ok', models.PositiveIntegerField(default=0, verbose_name='متطابقة')),
                ('items_with_gaps', models.PositiveIntegerField(default=0, verbose_name='بها فجوات')),
                ('branches_down', models.JSONField(default=list, verbose_name='فروع غير متاحة')),
                ('error', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replication_scans', to=settings.AUTH_USER_MODEL, verbose_name='شُغّل بواسطة')),
            ],
            options={
                'verbose_name': 'فحص النسخ المتماثل',
                'verbose_name_plural': 'فحوصات النسخ المتماثل',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplicationGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_softech_id', models.CharField(db_index=True, max_length=6, verbose_name='كود الصنف')),
                ('item_name', models.CharField(blank=True, max_length=120, verbose_name='اسم الصنف')),
                ('branch_code', models.CharField(db_index=True, max_length=5, verbose_name='كود الفرع')),
                ('branch_name', models.CharField(blank=True, max_length=120, verbose_name='اسم الفرع')),
                ('hq_itemlastupdate', models.DateTimeField(null=True, verbose_name='آخر تحديث HQ')),
                ('branch_itemlastupdate', models.DateTimeField(null=True, verbose_name='آخر تحديث الفرع')),
                ('hq_usercode', models.CharField(blank=True, max_length=10, verbose_name='كود مستخدم HQ')),
                ('source_user', models.CharField(blank=True, max_length=120, verbose_name='مصدر التعديل')),
                ('source_channel', models.CharField(choices=[('module', 'وحدة الموافقات'), ('direct', 'تعديل مباشر في Softech')], default='direct', max_length=10)),
                ('diff_summary', models.JSONField(default=dict, verbose_name='فروق القيم')),
                ('status', models.CharField(choices=[('stale', 'متأخر'), ('unreachable', 'فرع غير متاح'), ('repaired', 'تم الإصلاح')], db_index=True, default='stale', max_length=12)),
                ('repaired_at', models.DateTimeField(blank=True, null=True)),
                ('repair_note', models.CharField(blank=True, max_length=200)),
                ('repaired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replication_repairs', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='discount_approvals.replicationscan')),
            ],
            options={
                'verbose_name': 'فجوة نسخ متماثل',
                'verbose_name_plural': 'فجوات النسخ المتماثل',
                'ordering': ['-scan__started_at', 'item_softech_id', 'branch_code'],
                'indexes': [models.Index(fields=['status', 'branch_code'], name='discount_ap_status_dcad2e_idx')],
            },
        ),
    ]
