# Generated by Django 4.2.13 on 2026-06-05 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount_approvals', '0003_itempricechangerequest_rolled_back_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplicationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_repair_enabled', models.BooleanField(default=False, help_text='عند التفعيل: تُعاد جدولة الفجوات تلقائياً بعد كل فحص يومي. عند الإيقاف: تنبيه فقط.', verbose_name='إصلاح تلقائي')),
                ('max_items_per_run', models.PositiveIntegerField(default=200, help_text='حد أمان لعدد الأصناف التي يُعاد جدولتها تلقائياً في الفحص الواحد.', verbose_name='حد أقصى للأصناف في المرة')),
                ('daily_window_days', models.PositiveIntegerField(default=30, verbose_name='نافذة الفحص اليومي (أيام)')),
                ('weekly_full_audit', models.BooleanField(default=True, help_text='فحص عميق أسبوعي لكل الأصناف (وليس المعدّلة حديثاً فقط) لاكتشاف الانحراف الصامت.', verbose_name='فحص أسبوعي شامل')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replication_policy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سياسة النسخ المتماثل',
                'verbose_name_plural': 'سياسة النسخ المتماثل',
            },
        ),
    ]
