# Generated by Django 4.2.13 on 2026-08-16 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount_approvals', '0004_replicationpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDiscountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('supplier', 'المورد'), ('origin', 'المنشأ')], db_index=True, default='supplier', max_length=10, verbose_name='نطاق السياسة')),
                ('code', models.CharField(db_index=True, help_text='supplier_code (للمورد) أو origin_code (للمنشأ)', max_length=20, verbose_name='الكود (مورد/منشأ)')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='الاسم')),
                ('expected_discount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='الخصم الأساسى المتوقع %')),
                ('expected_pos_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='أقصى خصم مبيعات متوقع %')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_policy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سياسة خصم المورد/المنشأ',
                'verbose_name_plural': 'سياسات خصم الموردين/المناشئ',
                'ordering': ['scope', 'code'],
                'unique_together': {('scope', 'code')},
            },
        ),
    ]
