# Generated by Django 4.2.13 on 2026-09-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_approvals', '0005_supplierdiscountpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempricechangerequest',
            name='source',
            field=models.CharField(choices=[('manual', 'يدوي'), ('import', 'استيراد ملف'), ('rollback', 'تراجع'), ('near_expiry', 'قرب انتهاء الصلاحية')], db_index=True, default='manual', max_length=20, verbose_name='مصدر الطلب'),
        ),
    ]
