# Generated by Django 4.2.13 on 2026-09-02 02:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0022_alter_rolemoduleaccess_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='رقم المستند')),
                ('doc_date', models.DateField(verbose_name='التاريخ')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='صالح حتى')),
                ('status', models.CharField(default='draft', max_length=30, verbose_name='الحالة')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('14.00'), max_digits=5, verbose_name='نسبة ض.ق.م %')),
                ('subtotal_ex_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الصافي قبل الضريبة')),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي شامل الضريبة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile', verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'مستند تجاري',
                'verbose_name_plural': 'المستندات التجارية',
                'ordering': ['-doc_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('number_prefix', models.CharField(max_length=8, verbose_name='بادئة الترقيم')),
                ('pricing_profile', models.CharField(choices=[('manual_line', 'سعر يدوي لكل بند'), ('pq_aggregate', 'تجميعي (تأمين)'), ('none', 'بدون تسعير')], default='manual_line', max_length=20, verbose_name='طريقة التسعير')),
                ('is_allocation', models.BooleanField(default=False, verbose_name='شبكة توزيع (فروع)')),
                ('lifecycle', models.JSONField(blank=True, default=list, verbose_name='مراحل الحالة')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('14.00'), max_digits=5, verbose_name='نسبة ض.ق.م الافتراضية %')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوع مستند',
                'verbose_name_plural': 'أنواع المستندات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('kind', models.CharField(choices=[('hospital', 'مستشفى / جهة متعددة الفروع'), ('retail', 'عميل تجزئة / توصيل'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='النوع')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('tax_id', models.CharField(blank=True, max_length=40, verbose_name='الرقم الضريبي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جهة مستلمة',
                'verbose_name_plural': 'الجهات المستلمة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipientLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم الفرع')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='كود الفرع')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='commerce.recipient', verbose_name='الجهة')),
            ],
            options={
                'verbose_name': 'فرع الجهة',
                'verbose_name_plural': 'فروع الجهات',
                'ordering': ['recipient', 'sort_order', 'name'],
                'unique_together': {('recipient', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('item_code', models.CharField(blank=True, max_length=40, verbose_name='كود الصنف')),
                ('item_name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الوحدة (شامل الضريبة)')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية')),
                ('vat_applicable', models.BooleanField(default=False, verbose_name='خاضع للضريبة')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commerce.commercedocument', verbose_name='المستند')),
            ],
            options={
                'verbose_name': 'بند مستند',
                'verbose_name_plural': 'بنود المستند',
                'ordering': ['document', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='commercedocument',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='commerce.documenttype', verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='commercedocument',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='commerce.recipient', verbose_name='الجهة'),
        ),
        migrations.CreateModel(
            name='AllocationCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='commerce.documentline', verbose_name='البند')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='commerce.recipientlocation', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'خلية توزيع',
                'verbose_name_plural': 'خلايا التوزيع',
                'indexes': [models.Index(fields=['line', 'location'], name='commerce_al_line_id_468dc8_idx')],
                'unique_together': {('line', 'location')},
            },
        ),
    ]
