"""
Pharmacological class taxonomy + deterministic classification rules.
====================================================================

Two things live here:

1. CLASSES — the class taxonomy we seed into ``chronic.IngredientClass``. It
   MAPS SOFTECH's 23 classes (basic_data bdatasno=600, by ``softech_code``) and
   EXTENDS them with the common families SOFTECH lacks (antibiotics, NSAIDs,
   antihistamines, SSRIs, …). Classes with ``softech_code=None`` don't exist in
   SOFTECH yet and would be pushed there later via the gated Track B.

2. Classification rules (OVERRIDES / CONTAINS / STEM_RULES) — the deterministic
   basis for PROPOSING a class for a molecule. These use WHO INN common stems
   (‑pril, ‑sartan, ‑statin, …), which are a standardised, rule-based mapping —
   NOT fuzzy guessing. Every proposal is still reviewed by a pharmacist before it
   is trusted (rules 5/10).

Arabic names are supplied for daily Arabic-first use; the owner can edit any.
"""

# ── class_key : (english, arabic, softech_code|None) ─────────────────────────
CLASSES = [
    # ---- SOFTECH's 23 (basic_data bdatasno=600) ----------------------------
    ('sglt2_inhibitors',            'SGLT2 Inhibitors',                     'مثبطات SGLT2',                         '1'),
    ('dpp4_inhibitors',             'DPP-4 Inhibitors',                     'مثبطات DPP-4',                         '2'),
    ('biguanides',                  'Biguanides',                           'بيجوانيدات',                           '3'),
    ('statins',                     'Statins (HMG-CoA Reductase Inhib.)',   'ستاتينات (مخفضات الكوليسترول)',        '4'),
    ('beta_blockers',               'Beta-Blockers',                        'حاصرات بيتا',                          '5'),
    ('glp1_agonists',               'Incretin Mimetics / GLP-1 Agonists',   'ناهضات GLP-1',                         '6'),
    ('thiazide_diuretics',          'Thiazide Diuretics',                   'مدرات ثيازيدية',                       '7'),
    ('arbs',                        'Angiotensin II Receptor Antagonists',  'حاصرات مستقبلات الأنجيوتنسين',         '8'),
    ('antiplatelets',               'Anti-Platelet',                        'مضادات الصفيحات',                      '9'),
    ('p2y12_inhibitors',            'P2Y12 Receptor Antagonists',           'حاصرات مستقبل P2Y12',                  '10'),
    ('ace_inhibitors',              'ACE Inhibitors',                       'مثبطات الإنزيم المحول للأنجيوتنسين',   '11'),
    ('calcium_channel_blockers',    'Calcium Channel Blockers',             'حاصرات قنوات الكالسيوم',               '12'),
    ('thiazolidinediones',          'Thiazolidinediones',                   'ثيازوليدين ديونات',                    '13'),
    ('sulfonylureas',               'Sulfonylureas',                        'سلفونيل يوريا',                        '14'),
    ('meglitinides',                'Meglitinides',                         'ميجليتينيدات',                         '15'),
    ('alpha_glucosidase_inhibitors','Alpha-Glucosidase Inhibitors',         'مثبطات ألفا جلوكوزيداز',               '16'),
    ('dopamine_agonists',           'Dopamine Agonists',                    'ناهضات الدوبامين',                     '17'),
    ('alpha_blockers',              'Alpha Receptor Blockers',              'حاصرات ألفا',                          '18'),
    ('alpha2_agonists',             'Alpha-2 Adrenergic Agonists',          'ناهضات ألفا-2 الأدرينالية',            '19'),
    ('macrolides',                  'Macrolides',                           'ماكروليدات',                           '20'),
    ('ppi',                         'Proton Pump Inhibitors (PPIs)',        'مثبطات مضخة البروتون',                 '21'),
    ('unclassified',                'N/A Unidentified',                     'غير مصنّف',                            '22'),
    ('antivirals',                  'Antivirals',                           'مضادات الفيروسات',                     '23'),

    # ---- Extended taxonomy (no SOFTECH code yet — Track B would push these) --
    ('antiedematous_enzymes',       'Systemic Anti-inflammatory & Anti-edematous Agents', 'مضادات الالتهاب والوذمة الجهازية (إنزيمات)', None),
    ('penicillins',                 'Penicillins',                          'بنسلينات',                             None),
    ('cephalosporins',              'Cephalosporins',                       'سيفالوسبورينات',                       None),
    ('fluoroquinolones',            'Fluoroquinolones',                     'فلوروكينولونات',                       None),
    ('tetracyclines',               'Tetracyclines',                        'تتراسيكلينات',                         None),
    ('aminoglycosides',             'Aminoglycosides',                      'أمينوجليكوزيدات',                      None),
    ('sulfonamides',                'Sulfonamides',                         'سلفوناميدات',                          None),
    ('nitroimidazoles',             'Nitroimidazoles',                      'نيترو إيميدازولات',                    None),
    ('carbapenems',                 'Carbapenems',                          'كاربابينيمات',                         None),
    ('glycopeptides',               'Glycopeptides',                        'جليكوببتيدات',                         None),
    ('lincosamides',                'Lincosamides',                         'لينكوزاميدات',                         None),
    ('other_antibacterials',        'Other Antibacterials',                 'مضادات بكتيرية أخرى',                  None),
    ('nsaids',                      'NSAIDs',                               'مضادات الالتهاب غير الستيرويدية',      None),
    ('non_opioid_analgesics',       'Non-Opioid Analgesics',                'مسكنات غير أفيونية',                   None),
    ('opioid_analgesics',           'Opioid Analgesics',                    'مسكنات أفيونية',                       None),
    ('antihistamines',              'Antihistamines (H1)',                  'مضادات الهيستامين',                    None),
    ('h2_antagonists',              'H2 Receptor Antagonists',              'حاصرات مستقبلات H2',                   None),
    ('antacids',                    'Antacids',                             'مضادات الحموضة',                       None),
    ('antiemetics',                 'Antiemetics',                          'مضادات القيء',                         None),
    ('laxatives',                   'Laxatives',                            'ملينات',                               None),
    ('antidiarrheals',              'Antidiarrheals',                       'مضادات الإسهال',                       None),
    ('antispasmodics',              'Antispasmodics',                       'مضادات التقلص',                        None),
    ('corticosteroids',             'Corticosteroids',                      'كورتيكوستيرويدات',                     None),
    ('ssri',                        'SSRIs',                                'مثبطات استرداد السيروتونين الانتقائية',None),
    ('snri',                        'SNRIs',                                'مثبطات استرداد السيروتونين والنورإبينفرين', None),
    ('tca',                         'Tricyclic Antidepressants',            'مضادات اكتئاب ثلاثية الحلقات',         None),
    ('antipsychotics',              'Antipsychotics',                       'مضادات الذهان',                        None),
    ('benzodiazepines',             'Benzodiazepines',                      'بنزوديازيبينات',                       None),
    ('antiepileptics',              'Antiepileptics',                       'مضادات الصرع',                         None),
    ('beta2_agonists',              'Beta-2 Agonists (Bronchodilators)',    'ناهضات بيتا-2 (موسعات شعبية)',         None),
    ('inhaled_corticosteroids',     'Inhaled Corticosteroids',             'كورتيكوستيرويدات استنشاقية',           None),
    ('leukotriene_antagonists',     'Leukotriene Antagonists',              'مضادات الليكوترين',                    None),
    ('anticholinergic_bronchodilators', 'Anticholinergic Bronchodilators',  'موسعات شعبية مضادة للكولين',           None),
    ('azole_antifungals',           'Azole Antifungals',                    'مضادات فطرية أزولية',                  None),
    ('polyene_antifungals',         'Polyene Antifungals',                  'مضادات فطرية بولية',                   None),
    ('allylamine_antifungals',      'Allylamine Antifungals',               'مضادات فطرية أليلامينية',              None),
    ('antiretrovirals',             'Antiretrovirals',                      'مضادات الفيروسات القهقرية',            None),
    ('loop_diuretics',              'Loop Diuretics',                       'مدرات عروية',                          None),
    ('potassium_sparing_diuretics', 'Potassium-Sparing Diuretics',          'مدرات موفرة للبوتاسيوم',               None),
    ('nitrates',                    'Nitrates',                             'نيترات',                               None),
    ('anticoagulants',              'Anticoagulants',                       'مضادات التخثر',                        None),
    ('doac',                        'Direct Oral Anticoagulants',           'مضادات تخثر فموية مباشرة',             None),
    ('heparins',                    'Heparins',                             'هيبارينات',                            None),
    ('thyroid_hormones',            'Thyroid Hormones',                     'هرمونات الغدة الدرقية',                None),
    ('antithyroid',                 'Antithyroid Agents',                   'مضادات الغدة الدرقية',                 None),
    ('insulins',                    'Insulins',                             'أنسولينات',                            None),
    ('bisphosphonates',             'Bisphosphonates',                      'بيسفوسفونات',                          None),
    ('triptans',                    'Triptans (Antimigraine)',              'تريبتانات (مضادات الصداع النصفي)',     None),
    ('pde5_inhibitors',             'PDE5 Inhibitors',                      'مثبطات PDE5',                          None),
    ('antigout',                    'Antigout Agents',                      'مضادات النقرس',                        None),
    ('muscle_relaxants',            'Muscle Relaxants',                     'مرخيات العضلات',                       None),
    ('local_anesthetics',           'Local Anesthetics',                    'مخدرات موضعية',                        None),
    ('vitamins',                    'Vitamins',                             'فيتامينات',                            None),
    ('minerals',                    'Minerals & Electrolytes',              'معادن وأملاح',                         None),
    ('supplements',                 'Nutritional Supplements',              'مكملات غذائية',                        None),
    ('probiotics',                  'Probiotics',                           'بروبيوتيك',                            None),
    ('vaccines',                    'Vaccines',                             'لقاحات',                               None),
    ('monoclonal_antibodies',       'Monoclonal Antibodies',                'أجسام مضادة وحيدة النسيلة',            None),
    ('kinase_inhibitors',           'Kinase Inhibitors',                    'مثبطات الكيناز',                       None),
    ('immunosuppressants',          'Immunosuppressants',                   'مثبطات المناعة',                       None),
    ('sex_hormones',                'Sex Hormones / Contraceptives',        'هرمونات جنسية / موانع حمل',            None),
    ('mucolytics',                  'Mucolytics & Expectorants',            'مذيبات المخاط وطاردات البلغم',         None),
    ('dermatologicals',             'Dermatologicals (Topical)',            'مستحضرات جلدية موضعية',                None),
    ('ophthalmicals',               'Ophthalmic Preparations',              'مستحضرات عينية',                       None),
    ('antiseptics',                 'Antiseptics & Disinfectants',          'مطهرات',                               None),
    # non-drug buckets (support the reconciliation "not a molecule" disposition)
    ('cosmetics',                   'Cosmetics (non-drug)',                 'مستحضرات تجميل (غير دوائية)',          None),
    ('medical_supplies',            'Medical Supplies (non-drug)',          'مستلزمات طبية (غير دوائية)',           None),
    ('infant_formula',              'Infant / Follow-on Formula (non-drug)','ألبان أطفال (غير دوائية)',             None),
]

# Valid keys (for validation in tests / classifier).
CLASS_KEYS = {c[0] for c in CLASSES}

# ── Exact molecule → class (checked FIRST, highest confidence) ───────────────
# For molecules whose class a stem can't reach or would mis-hit.
OVERRIDES = {
    'METFORMIN': 'biguanides', 'BUFORMIN': 'biguanides',
    'GLIBENCLAMIDE': 'sulfonylureas', 'GLICLAZIDE': 'sulfonylureas',
    'GLIMEPIRIDE': 'sulfonylureas', 'GLIPIZIDE': 'sulfonylureas',
    'GLIQUIDONE': 'sulfonylureas', 'TOLBUTAMIDE': 'sulfonylureas',
    'CHLORPROPAMIDE': 'sulfonylureas',
    'REPAGLINIDE': 'meglitinides', 'NATEGLINIDE': 'meglitinides',
    'ACARBOSE': 'alpha_glucosidase_inhibitors', 'MIGLITOL': 'alpha_glucosidase_inhibitors',
    'PIOGLITAZONE': 'thiazolidinediones', 'ROSIGLITAZONE': 'thiazolidinediones',
    'PARACETAMOL': 'non_opioid_analgesics', 'ACETAMINOPHEN': 'non_opioid_analgesics',
    'ACETYLSALICYLIC': 'antiplatelets', 'ASPIRIN': 'antiplatelets',
    'CLOPIDOGREL': 'p2y12_inhibitors', 'PRASUGREL': 'p2y12_inhibitors',
    'TICAGRELOR': 'p2y12_inhibitors', 'TICLOPIDINE': 'p2y12_inhibitors',
    'WARFARIN': 'anticoagulants', 'ACENOCOUMAROL': 'anticoagulants',
    'LEVOTHYROXINE': 'thyroid_hormones', 'LIOTHYRONINE': 'thyroid_hormones',
    'CARBIMAZOLE': 'antithyroid', 'METHIMAZOLE': 'antithyroid',
    'PROPYLTHIOURACIL': 'antithyroid',
    'ALLOPURINOL': 'antigout', 'FEBUXOSTAT': 'antigout', 'COLCHICINE': 'antigout',
    'SALBUTAMOL': 'beta2_agonists', 'ALBUTEROL': 'beta2_agonists',
    'IPRATROPIUM': 'anticholinergic_bronchodilators', 'TIOTROPIUM': 'anticholinergic_bronchodilators',
    'GENTAMICIN': 'aminoglycosides', 'AMIKACIN': 'aminoglycosides',
    'TOBRAMYCIN': 'aminoglycosides', 'NEOMYCIN': 'aminoglycosides',
    'STREPTOMYCIN': 'aminoglycosides',
    'VANCOMYCIN': 'glycopeptides', 'TEICOPLANIN': 'glycopeptides',
    'CLINDAMYCIN': 'lincosamides', 'LINCOMYCIN': 'lincosamides',
    'NYSTATIN': 'polyene_antifungals', 'AMPHOTERICIN': 'polyene_antifungals',
    'TERBINAFINE': 'allylamine_antifungals',
    'FLUOXETINE': 'ssri', 'PAROXETINE': 'ssri', 'SERTRALINE': 'ssri',
    'CITALOPRAM': 'ssri', 'ESCITALOPRAM': 'ssri', 'FLUVOXAMINE': 'ssri',
    'DULOXETINE': 'snri', 'VENLAFAXINE': 'snri', 'DESVENLAFAXINE': 'snri',
    'CARBAMAZEPINE': 'antiepileptics', 'VALPROATE': 'antiepileptics',
    'VALPROIC': 'antiepileptics', 'LAMOTRIGINE': 'antiepileptics',
    'LEVETIRACETAM': 'antiepileptics', 'PHENYTOIN': 'antiepileptics',
    'GABAPENTIN': 'antiepileptics', 'PREGABALIN': 'antiepileptics',
    'TOPIRAMATE': 'antiepileptics',
    'SPIRONOLACTONE': 'potassium_sparing_diuretics', 'EPLERENONE': 'potassium_sparing_diuretics',
    'AMILORIDE': 'potassium_sparing_diuretics', 'TRIAMTERENE': 'potassium_sparing_diuretics',
    'VERAPAMIL': 'calcium_channel_blockers', 'DILTIAZEM': 'calcium_channel_blockers',
    'MORPHINE': 'opioid_analgesics', 'CODEINE': 'opioid_analgesics',
    'TRAMADOL': 'opioid_analgesics', 'FENTANYL': 'opioid_analgesics',
    'OXYCODONE': 'opioid_analgesics', 'PETHIDINE': 'opioid_analgesics',
    'BACLOFEN': 'muscle_relaxants', 'TIZANIDINE': 'muscle_relaxants',
    'ORPHENADRINE': 'muscle_relaxants', 'CHLORZOXAZONE': 'muscle_relaxants',
    'CICLOSPORIN': 'immunosuppressants', 'CYCLOSPORINE': 'immunosuppressants',
    'TACROLIMUS': 'immunosuppressants', 'MYCOPHENOLATE': 'immunosuppressants',
    'AZATHIOPRINE': 'immunosuppressants',
    'ACETYLCYSTEINE': 'mucolytics', 'CARBOCISTEINE': 'mucolytics',
    'BROMHEXINE': 'mucolytics', 'AMBROXOL': 'mucolytics', 'GUAIFENESIN': 'mucolytics',
    'MONTELUKAST': 'leukotriene_antagonists', 'ZAFIRLUKAST': 'leukotriene_antagonists',
    'LORATADINE': 'antihistamines', 'DESLORATADINE': 'antihistamines',
    'CETIRIZINE': 'antihistamines', 'LEVOCETIRIZINE': 'antihistamines',
    'FEXOFENADINE': 'antihistamines', 'CHLORPHENIRAMINE': 'antihistamines',
    'DIPHENHYDRAMINE': 'antihistamines', 'CINNARIZINE': 'antihistamines',
    'FOLIC': 'vitamins', 'CYANOCOBALAMIN': 'vitamins', 'CHOLECALCIFEROL': 'vitamins',
    'ERGOCALCIFEROL': 'vitamins', 'ASCORBIC': 'vitamins', 'THIAMINE': 'vitamins',
    'PYRIDOXINE': 'vitamins', 'RIBOFLAVIN': 'vitamins', 'TOCOPHEROL': 'vitamins',
    'FERROUS': 'minerals', 'CALCIUM': 'minerals', 'MAGNESIUM': 'minerals',
    'ZINC': 'minerals', 'POTASSIUM': 'minerals', 'SELENIUM': 'minerals',
    # Proteolytic / anti-edematous enzymes (word-level: hits inside combos like
    # "A -CHYMOTRYPSIN + TRYPSIN + BROMELAIN")
    'SERRATIOPEPTIDASE': 'antiedematous_enzymes', 'SERRAPEPTASE': 'antiedematous_enzymes',
    'CHYMOTRYPSIN': 'antiedematous_enzymes', 'TRYPSIN': 'antiedematous_enzymes',
    'BROMELAIN': 'antiedematous_enzymes', 'PAPAIN': 'antiedematous_enzymes',
    'CHYMOTRYPSINTRYPSIN': 'antiedematous_enzymes',
}

# ── Substring → class (checked after exact overrides) ────────────────────────
CONTAINS = [
    ('INSULIN',        'insulins'),
    ('VACCINE',        'vaccines'),
    ('VITAMIN',        'vitamins'),
    ('LACTOBACILLUS',  'probiotics'),
    ('SACCHAROMYCES',  'probiotics'),
    ('SULFAMETHOXAZOLE','sulfonamides'),
    ('SULFADIAZINE',   'sulfonamides'),
    ('COTRIMOXAZOLE',  'sulfonamides'),
    ('ESTRADIOL',      'sex_hormones'),
    ('LEVONORGESTREL', 'sex_hormones'),
    ('PROGESTERONE',   'sex_hormones'),
    ('TESTOSTERONE',   'sex_hormones'),
]

# ── INN-stem rules (('suffix'|'prefix'|'contains', stem, class_key)) ─────────
# Ordered specific → general; first match wins.
STEM_RULES = [
    ('suffix', 'gliflozin',  'sglt2_inhibitors'),
    ('suffix', 'gliptin',    'dpp4_inhibitors'),
    ('suffix', 'glitazone',  'thiazolidinediones'),
    ('suffix', 'glutide',    'glp1_agonists'),
    ('suffix', 'enatide',    'glp1_agonists'),
    ('suffix', 'vastatin',   'statins'),
    ('suffix', 'statin',     'statins'),
    ('suffix', 'prazole',    'ppi'),
    ('suffix', 'sartan',     'arbs'),
    ('suffix', 'pril',       'ace_inhibitors'),
    ('suffix', 'dipine',     'calcium_channel_blockers'),
    ('suffix', 'olol',       'beta_blockers'),
    ('suffix', 'alol',       'beta_blockers'),
    ('suffix', 'ilol',       'beta_blockers'),
    ('suffix', 'floxacin',   'fluoroquinolones'),
    ('suffix', 'thromycin',  'macrolides'),
    ('suffix', 'cycline',    'tetracyclines'),
    ('suffix', 'cillin',     'penicillins'),
    ('prefix', 'cef',        'cephalosporins'),
    ('prefix', 'ceph',       'cephalosporins'),
    ('suffix', 'penem',      'carbapenems'),
    ('suffix', 'nidazole',   'nitroimidazoles'),
    ('suffix', 'conazole',   'azole_antifungals'),
    ('suffix', 'navir',      'antiretrovirals'),
    ('suffix', 'vudine',     'antiretrovirals'),
    ('suffix', 'tegravir',   'antiretrovirals'),
    ('suffix', 'clovir',     'antivirals'),
    ('suffix', 'ciclovir',   'antivirals'),
    ('suffix', 'amivir',     'antivirals'),
    ('suffix', 'buvir',      'antivirals'),
    ('suffix', 'previr',     'antivirals'),
    ('suffix', 'asvir',      'antivirals'),
    ('suffix', 'parin',      'heparins'),
    ('suffix', 'xaban',      'doac'),
    ('suffix', 'gatran',     'doac'),
    ('suffix', 'afil',       'pde5_inhibitors'),
    ('suffix', 'dronate',    'bisphosphonates'),
    ('suffix', 'dronic',     'bisphosphonates'),
    ('suffix', 'triptan',    'triptans'),
    ('suffix', 'setron',     'antiemetics'),
    ('suffix', 'oxetine',    'ssri'),
    ('suffix', 'triptyline', 'tca'),
    ('suffix', 'pramine',    'tca'),
    ('suffix', 'azepam',     'benzodiazepines'),
    ('suffix', 'azolam',     'benzodiazepines'),
    ('suffix', 'peridone',   'antipsychotics'),
    ('suffix', 'peridol',    'antipsychotics'),
    ('suffix', 'piprazole',  'antipsychotics'),
    ('suffix', 'apine',      'antipsychotics'),
    ('suffix', 'tiracetam',  'antiepileptics'),
    ('suffix', 'semide',     'loop_diuretics'),
    ('suffix', 'tanide',     'loop_diuretics'),
    ('suffix', 'actone',     'potassium_sparing_diuretics'),
    ('suffix', 'thiazide',   'thiazide_diuretics'),
    ('suffix', 'terol',      'beta2_agonists'),
    ('suffix', 'onide',      'corticosteroids'),
    ('suffix', 'asone',      'corticosteroids'),
    ('suffix', 'solone',     'corticosteroids'),
    ('suffix', 'lukast',     'leukotriene_antagonists'),
    ('suffix', 'profen',     'nsaids'),
    ('suffix', 'fenac',      'nsaids'),
    ('suffix', 'oxicam',     'nsaids'),
    ('suffix', 'coxib',      'nsaids'),
    ('suffix', 'caine',      'local_anesthetics'),
    ('suffix', 'tinib',      'kinase_inhibitors'),
    ('suffix', 'ciclib',     'kinase_inhibitors'),
    ('suffix', 'parib',      'kinase_inhibitors'),
    ('suffix', 'mab',        'monoclonal_antibodies'),
    ('suffix', 'prazosin',   'alpha_blockers'),
    ('suffix', 'azosin',     'alpha_blockers'),
]
