# Generated by Django 4.2.13 on 2026-06-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expenseclaim',
            new_name='hr_expensec_staff_i_0930c8_idx',
            old_name='hr_exp_staff_status_idx',
        ),
        migrations.RenameIndex(
            model_name='expenseclaim',
            new_name='hr_expensec_expense_9b9816_idx',
            old_name='hr_exp_date_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='hr_leavereq_staff_i_bbe821_idx',
            old_name='hr_leave_staff_status_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='hr_leavereq_start_d_9e9e54_idx',
            old_name='hr_leave_dates_idx',
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='accrues_balance',
            field=models.BooleanField(default=True, help_text='إذا كانت True يُخصم من الرصيد السنوي عند الاعتماد', verbose_name='ترصيد سنوي'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='days_of_week',
            field=models.CharField(help_text='مفصولة بفاصلة: saturday,sunday,monday', max_length=120, verbose_name='أيام العمل'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
