# Generated by Django 4.2.13 on 2026-06-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_latitude_branch_longitude'),
        ('users', '0018_drop_legacy_has_global_access'),
        ('hr', '0002_rename_hr_exp_staff_status_idx_hr_expensec_staff_i_0930c8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('check_in_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحضور')),
                ('check_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_distance_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='مسافة الحضور (م)')),
                ('check_in_ok', models.BooleanField(null=True, verbose_name='ضمن النطاق عند الحضور')),
                ('check_out_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('check_out_ok', models.BooleanField(null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='branches.branch', verbose_name='الفرع')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.staffprofile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-check_in_at'],
                'indexes': [models.Index(fields=['staff', 'work_date'], name='hr_attendan_staff_i_f7c2f3_idx')],
            },
        ),
    ]
