# Generated by Django 4.2.13 on 2026-06-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_attendancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseclaim',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُقدَّم'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('paid', 'تم الصرف'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُقدَّم'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُقدَّم'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('settled', 'تمت التسوية'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=15),
        ),
    ]
