# Generated by Django 4.2.13 on 2026-08-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_rolemoduleaccess_module'),
        ('branches', '0007_backfill_branch_kind'),
        ('approvals', '0003_approvalworkflowdefinition_category'),
        ('hr', '0004_alter_expenseclaim_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='return_to_work_date',
            field=models.DateField(blank=True, null=True, verbose_name='العودة للعمل يوم'),
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('mamoriya', 'اذن مأمورية'), ('shift_change', 'اذن تعديل شيفت')], db_index=True, max_length=20, verbose_name='نوع الإذن')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time_from', models.TimeField(verbose_name='من الساعة')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='حتى الساعة')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='جهة المأمورية')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُقدَّم'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=15, verbose_name='الحالة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permit', to='approvals.approvalrequest')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='branches.branch', verbose_name='الفرع')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='users.staffprofile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'إذن',
                'verbose_name_plural': 'الأذونات',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['staff', 'status'], name='hr_permit_staff_i_5db731_idx'), models.Index(fields=['permit_type', 'date'], name='hr_permit_permit__d22f49_idx')],
            },
        ),
    ]
