# Generated by Django 4.2.13 on 2026-08-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_staffprofile_hr_code_and_more'),
        ('hr', '0005_leaverequest_return_to_work_date_permit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='employee_hr_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='كود الموارد البشرية'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='اسم الموظف'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='softech_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='كود سوفتك'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_submitted', to='users.staffprofile', verbose_name='مُقدَّم بواسطة'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_hr_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='كود الموارد البشرية'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='اسم الموظف'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='softech_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='كود سوفتك'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_submitted', to='users.staffprofile', verbose_name='مُقدَّم بواسطة'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='employee_hr_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='كود الموارد البشرية'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='اسم الموظف'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='softech_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='كود سوفتك'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_submitted', to='users.staffprofile', verbose_name='مُقدَّم بواسطة'),
        ),
        migrations.AddField(
            model_name='permit',
            name='employee_hr_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='كود الموارد البشرية'),
        ),
        migrations.AddField(
            model_name='permit',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='اسم الموظف'),
        ),
        migrations.AddField(
            model_name='permit',
            name='softech_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='كود سوفتك'),
        ),
        migrations.AddField(
            model_name='permit',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_submitted', to='users.staffprofile', verbose_name='مُقدَّم بواسطة'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='employee_hr_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='كود الموارد البشرية'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='اسم الموظف'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='softech_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='كود سوفتك'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_submitted', to='users.staffprofile', verbose_name='مُقدَّم بواسطة'),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='users.staffprofile', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='users.staffprofile', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overtime_requests', to='users.staffprofile', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='users.staffprofile', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_advances', to='users.staffprofile', verbose_name='الموظف'),
        ),
    ]
