# Generated by Django 4.2.13 on 2026-06-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_item_pack_price_tax_item_sale_tax_pct'),
        ('branches', '0004_branch_db_connection'),
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockbatch',
            name='batch_unique_item_branch_lot',
        ),
        migrations.AlterUniqueTogether(
            name='stockbatch',
            unique_together={('item', 'branch', 'batch_number')},
        ),
    ]
