# Generated by Django 4.2.13 on 2026-09-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_backfill_branch_kind'),
        ('catalog', '0035_alter_item_shortage_dismiss_reason'),
        ('batches', '0002_remove_stockbatch_batch_unique_item_branch_lot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseExpiryAuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'يعمل'), ('success', 'ناجح'), ('failed', 'فشل')], default='running', max_length=10)),
                ('window_from', models.DateField(verbose_name='من تاريخ')),
                ('window_to', models.DateField(verbose_name='إلى تاريخ')),
                ('branch_scope', models.CharField(blank=True, default='', max_length=10, verbose_name='الفرع (فارغ = كل الفروع)')),
                ('categories', models.JSONField(default=list, verbose_name='فئات الموردين المشمولة')),
                ('suppliers_count', models.PositiveIntegerField(default=0, verbose_name='عدد الموردين')),
                ('lines_fetched', models.PositiveIntegerField(default=0, verbose_name='الأسطر المقروءة')),
                ('lines_upserted', models.PositiveIntegerField(default=0, verbose_name='الأسطر المضافة')),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'تشغيل مزامنة صلاحيات الشراء',
                'verbose_name_plural': 'تشغيلات مزامنة صلاحيات الشراء',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseExpiryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(db_index=True, max_length=10, verbose_name='كود الفرع')),
                ('supplier_code', models.CharField(db_index=True, max_length=10, verbose_name='كود المورد')),
                ('supplier_name', models.CharField(blank=True, max_length=255, verbose_name='اسم المورد')),
                ('supplier_category', models.CharField(blank=True, db_index=True, max_length=25, verbose_name='تصنيف المورد')),
                ('doc_number', models.CharField(max_length=20, verbose_name='رقم الفاتورة')),
                ('doc_date', models.DateField(db_index=True, verbose_name='تاريخ إدخال الفاتورة')),
                ('item_code', models.CharField(db_index=True, max_length=6, verbose_name='كود الصنف')),
                ('item_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الصنف')),
                ('dblitemflag', models.IntegerField(default=1, verbose_name='رقم الدفعة داخل الفاتورة')),
                ('entered_expiry', models.DateField(db_index=True, verbose_name='تاريخ الصلاحية المُدخَل')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الكمية المشتراة')),
                ('store_code', models.CharField(blank=True, max_length=5, verbose_name='كود المخزن')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_expiry_entries', to='branches.branch', verbose_name='الفرع')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_expiry_entries', to='catalog.item', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'إدخال صلاحية شراء',
                'verbose_name_plural': 'إدخالات صلاحية الشراء',
                'ordering': ['-doc_date', 'item_code'],
                'indexes': [models.Index(fields=['item_code', 'entered_expiry'], name='pxe_item_expiry_idx'), models.Index(fields=['doc_date', 'supplier_code'], name='pxe_date_supplier_idx'), models.Index(fields=['supplier_category', 'doc_date'], name='pxe_cat_date_idx'), models.Index(fields=['branch_code', 'doc_date'], name='pxe_branch_date_idx')],
                'unique_together': {('branch_code', 'supplier_code', 'doc_number', 'doc_date', 'item_code', 'dblitemflag')},
            },
        ),
    ]
