# Generated by Django 4.2.13 on 2026-09-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_purchaseexpiryauditrun_purchaseexpiryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExpirySyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'يعمل'), ('success', 'ناجح'), ('partial', 'جزئي'), ('failed', 'فشل')], default='running', max_length=10)),
                ('nodes_total', models.PositiveIntegerField(default=0)),
                ('nodes_ok', models.PositiveIntegerField(default=0)),
                ('nodes_failed', models.PositiveIntegerField(default=0)),
                ('rows_synced', models.PositiveIntegerField(default=0)),
                ('detail', models.JSONField(default=dict)),
                ('triggered_by', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'تشغيل مزامنة صلاحية المخزون',
                'verbose_name_plural': 'تشغيلات مزامنة صلاحية المخزون',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StockExpiryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(db_index=True, max_length=10, verbose_name='الفرع')),
                ('store_code', models.CharField(blank=True, max_length=10, verbose_name='المخزن')),
                ('item_code', models.CharField(db_index=True, max_length=6, verbose_name='كود الصنف')),
                ('item_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الصنف')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='رقم التشغيلة')),
                ('expiry_date', models.DateField(db_index=True, verbose_name='تاريخ الصلاحية')),
                ('qty', models.DecimalField(decimal_places=5, default=0, max_digits=14, verbose_name='الكمية')),
                ('is_quarantine', models.BooleanField(default=False, verbose_name='مخزن عزل/تالف')),
                ('synced_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'رصيد صلاحية مخزون',
                'verbose_name_plural': 'أرصدة صلاحية المخزون',
                'ordering': ['expiry_date', 'item_code'],
                'indexes': [models.Index(fields=['expiry_date', 'qty'], name='sxb_expiry_qty_idx'), models.Index(fields=['branch_code', 'expiry_date'], name='sxb_branch_expiry_idx'), models.Index(fields=['item_code'], name='sxb_item_idx')],
            },
        ),
    ]
