# Generated by Django 4.2.13 on 2026-09-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_staffprofile_notify_expiry_worklist_wa'),
        ('batches', '0004_stockexpirysyncrun_stockexpirybalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryDisposalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=6, verbose_name='كود الصنف')),
                ('item_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الصنف')),
                ('branch_code', models.CharField(db_index=True, max_length=10, verbose_name='الفرع')),
                ('store_code', models.CharField(blank=True, max_length=10, verbose_name='المخزن')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='رقم التشغيلة')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الصلاحية')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='تكلفة الوحدة')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='القيمة')),
                ('decision', models.CharField(choices=[('destroy', 'إتلاف'), ('return_supplier', 'مرتجع للمورد'), ('quarantine', 'عزل'), ('review', 'مراجعة')], db_index=True, max_length=20, verbose_name='القرار')),
                ('supplier_code', models.CharField(blank=True, max_length=10, verbose_name='كود المورد (للمرتجع)')),
                ('supplier_name', models.CharField(blank=True, max_length=255, verbose_name='اسم المورد')),
                ('reason', models.TextField(blank=True, verbose_name='السبب / ملاحظات')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('done', 'منفّذ'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=12, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_records_created', to='users.staffprofile', verbose_name='أنشأ بواسطة')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_records_decided', to='users.staffprofile', verbose_name='اعتمد/نفّذ بواسطة')),
            ],
            options={
                'verbose_name': 'قرار إتلاف/مرتجع صلاحية',
                'verbose_name_plural': 'قرارات الإتلاف/المرتجع',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'branch_code'], name='disp_status_branch_idx'), models.Index(fields=['decision', 'status'], name='disp_decision_status_idx')],
            },
        ),
    ]
