# Generated by Django 4.2.13 on 2026-05-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_softechpersontype_softechpersonclassif'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='softechpersonclassif',
            name='sync_softechpersonclassif_ptcode_ptclassifcode_uniq',
        ),
        migrations.AlterUniqueTogether(
            name='softechpersonclassif',
            unique_together={('ptcode', 'ptclassifcode')},
        ),
    ]
