# Generated by Django 4.2.13 on 2026-09-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_remove_softechpersonclassif_sync_softechpersonclassif_ptcode_ptclassifcode_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
