# Generated by Django 4.2.13 on 2026-05-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortagelist',
            name='source',
            field=models.CharField(default='manual', help_text='manual | ocr | imported', max_length=30, verbose_name='المصدر'),
        ),
    ]
