# Generated by Django 4.2.13 on 2026-05-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_erpuser_user_group'),
        ('shortage', '0002_alter_shortagelist_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortageitem',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التأكيد'),
        ),
        migrations.AddField(
            model_name='shortageitem',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_shortage_items', to='users.staffprofile', verbose_name='أُكِّد بواسطة'),
        ),
        migrations.AddField(
            model_name='shortageitem',
            name='source',
            field=models.CharField(choices=[('manual', 'يدوي'), ('voice', 'صوتي'), ('ocr', 'OCR'), ('bulk', 'استيراد نصي')], default='manual', max_length=10, verbose_name='مصدر الإدخال'),
        ),
        migrations.AddIndex(
            model_name='shortageitem',
            index=models.Index(fields=['shortage_list', 'is_confirmed'], name='si_list_confirmed_idx'),
        ),
        migrations.AddIndex(
            model_name='shortageitem',
            index=models.Index(fields=['item'], name='si_item_idx'),
        ),
    ]
