# Generated by Django 4.2.13 on 2026-10-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0003_shortageitem_source_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortageitem',
            name='source',
            field=models.CharField(choices=[('manual', 'يدوي'), ('voice', 'صوتي'), ('ocr', 'OCR'), ('bulk', 'استيراد نصي'), ('whatsapp', 'واتساب')], default='manual', max_length=10, verbose_name='مصدر الإدخال'),
        ),
    ]
