# Generated by Django 4.2.13 on 2026-06-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='intransittransfer',
            new_name='transits_in_transit_bc1aa9_idx',
            old_name='transits_status_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='intransittransfer',
            new_name='transits_in_supplyi_1bbf29_idx',
            old_name='transits_supply_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='intransittransfer',
            new_name='transits_in_receivi_85825d_idx',
            old_name='transits_recv_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='intransittransfer',
            new_name='transits_in_issue_d_d1dedf_idx',
            old_name='transits_issue_date_idx',
        ),
        migrations.AlterField(
            model_name='intransittransfer',
            name='cancellation_available',
            field=models.BooleanField(default=True, help_text='True ما دام في نطاق مهلة SOFTECH (~5 أيام)', verbose_name='الإلغاء ممكن'),
        ),
        migrations.AlterField(
            model_name='intransittransfer',
            name='erp_doc_code',
            field=models.CharField(default='125', help_text='دائماً 125 = صرف تبادل بين الفروع', max_length=10, verbose_name='كود نوع المستند'),
        ),
        migrations.AlterField(
            model_name='intransittransfer',
            name='erp_doc_number',
            field=models.CharField(db_index=True, help_text='stktransm.docnumber — المعرّف الفريد في SOFTECH', max_length=50, unique=True, verbose_name='رقم المستند (ERP)'),
        ),
        migrations.AlterField(
            model_name='intransittransfer',
            name='erp_received_date',
            field=models.DateField(blank=True, help_text='يُكشف حين يظهر المستند في stktrans برمز فرع المستلم', null=True, verbose_name='تاريخ الاستلام (ERP)'),
        ),
        migrations.AlterField(
            model_name='intransittransfer',
            name='erp_receiving_branch_code',
            field=models.CharField(blank=True, help_text='مُشتق من stktrans — الفرع الآخر في نفس المستند', max_length=20, verbose_name='كود فرع المستلم (ERP)'),
        ),
        migrations.AlterField(
            model_name='intransittransfer',
            name='erp_user_code',
            field=models.CharField(blank=True, help_text='من أصدر المستند في SOFTECH', max_length=20, verbose_name='كود المستخدم (ERP)'),
        ),
        migrations.AlterField(
            model_name='intransittransfer',
            name='issue_date',
            field=models.DateField(help_text='stktransm.docdate', verbose_name='تاريخ الإصدار'),
        ),
    ]
