# Generated by Django 4.2.13 on 2026-06-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0002_rename_transits_status_priority_idx_transits_in_transit_bc1aa9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intransittransfer',
            name='has_discrepancy',
            field=models.BooleanField(db_index=True, default=False, verbose_name='يوجد تباين مع ERP'),
        ),
        migrations.AddField(
            model_name='intransittransfer',
            name='received_items_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='بيانات الأصناف المستلمة (25)'),
        ),
        migrations.AddField(
            model_name='intransittransfer',
            name='reconciliation',
            field=models.JSONField(blank=True, default=dict, help_text='{checked_at, missing_items, extra_items, qty_diffs, sent_value, received_value, value_diff, qty_diff_total}', verbose_name='مطابقة 125↔25'),
        ),
        migrations.AlterField(
            model_name='intransittransfer',
            name='transit_status',
            field=models.CharField(choices=[('in_transit', 'قيد النقل'), ('received', 'مستلم'), ('erp_mismatch', '⚠️ تباين مع ERP (125≠25)'), ('cancelled', 'ملغي في ERP'), ('expired_pending', 'انتهت مهلة الإلغاء — معلق'), ('force_closed', 'مغلق قسراً')], db_index=True, default='in_transit', max_length=20, verbose_name='حالة النقل'),
        ),
    ]
