# Generated by Django 4.2.13 on 2026-07-14 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_rolemoduleaccess_module'),
        ('catalog', '0024_itemalias'),
        ('transits', '0003_intransittransfer_has_discrepancy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المنطقة')),
                ('sort_key', models.PositiveSmallIntegerField(db_index=True, default=100, help_text='الأصغر يُجمَّع أولاً', verbose_name='ترتيب مسار التجميع')),
                ('location', models.CharField(blank=True, help_text='يظهر بجوار اسم المنطقة في ورقة التجميع', max_length=120, verbose_name='الموقع / الرف بالمخزن')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='لون')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('is_price_zone', models.BooleanField(default=False, help_text='تستقبل الأصناف التي يبلغ سعرها حد الغوالي أو أكثر', verbose_name='منطقة الغوالي')),
                ('is_fridge_zone', models.BooleanField(default=False, help_text='تستقبل أصناف الثلاجة (علامة الكتالوج أو كلمة FRIDGE بالاسم)', verbose_name='منطقة الثلاجة')),
                ('is_fallback', models.BooleanField(default=False, help_text='تستقبل الأصناف التي لا تطابق أي قاعدة', verbose_name='منطقة غير المصنف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'منطقة تجميع',
                'verbose_name_plural': 'مناطق التجميع',
                'ordering': ['sort_key', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PickZoneRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(default=list, help_text='قائمة كلمات — أي تطابق واحد يكفي (بحث داخل اسم الصنف)', verbose_name='الكلمات المفتاحية')),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=100, help_text='الأصغر يُقيَّم أولاً — أول تطابق يفوز', verbose_name='أولوية التقييم')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='transits.pickzone', verbose_name='المنطقة')),
            ],
            options={
                'verbose_name': 'قاعدة تصنيف',
                'verbose_name_plural': 'قواعد التصنيف',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPickOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, help_text='مثال: رف A3 — يظهر في ملاحظات ورقة التجميع', max_length=100, verbose_name='وسم / موقع خاص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_overrides', to='users.staffprofile', verbose_name='بواسطة')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pick_override', to='catalog.item', verbose_name='الصنف')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_overrides', to='transits.pickzone', verbose_name='المنطقة')),
            ],
            options={
                'verbose_name': 'تخصيص صنف لمنطقة',
                'verbose_name_plural': 'تخصيصات الأصناف',
                'ordering': ['-updated_at'],
            },
        ),
    ]
