# Generated by Django 4.2.13 on 2026-07-14 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_itemalias'),
        ('branches', '0005_branch_latitude_branch_longitude'),
        ('transits', '0004_pickzone_pickzonerule_itempickoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempickoverride',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='فارغ = تخصيص افتراضي لكل المخازن', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_pick_overrides', to='branches.branch', verbose_name='المخزن / الفرع المصدر'),
        ),
        migrations.AddField(
            model_name='pickzone',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='فارغ = الإعداد الافتراضي لكل المخازن التي لا تملك إعداداً خاصاً', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick_zones', to='branches.branch', verbose_name='المخزن / الفرع المصدر'),
        ),
        migrations.AddField(
            model_name='pickzonerule',
            name='match_field',
            field=models.CharField(choices=[('name', 'اسم الصنف (كلمات)'), ('shape', 'شكل الصنف'), ('medicine_type', 'نوع الدواء'), ('family', 'عائلة الصنف'), ('producer', 'الشركة المنتجة'), ('origin', 'بلد المنشأ'), ('unit', 'وحدة العبوة')], default='name', help_text='اسم الصنف = بحث كلمات؛ الباقي = مطابقة قيمة عمود جدول الأصناف', max_length=20, verbose_name='نوع المطابقة'),
        ),
        migrations.AlterField(
            model_name='itempickoverride',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_overrides', to='catalog.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='pickzone',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المنطقة'),
        ),
        migrations.AlterField(
            model_name='pickzonerule',
            name='keywords',
            field=models.JSONField(default=list, help_text='كلمات للبحث بالاسم، أو قيم (أكواد) عمود الأصناف — أي تطابق واحد يكفي', verbose_name='الكلمات / القيم'),
        ),
        migrations.AlterUniqueTogether(
            name='itempickoverride',
            unique_together={('branch', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='pickzone',
            unique_together={('branch', 'name')},
        ),
    ]
