# Generated by Django 4.2.13 on 2026-07-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_latitude_branch_longitude'),
        ('catalog', '0024_itemalias'),
        ('transits', '0005_itempickoverride_branch_pickzone_branch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itempickoverride',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pickzone',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itempickoverride',
            name='purpose',
            field=models.CharField(choices=[('picking', '🚚 تجميع — مسار مخزن المصدر'), ('stocking', '🗄️ ترصيص — أرفف الفرع المستلم')], db_index=True, default='picking', help_text='تخصيص التجميع مستقل عن تخصيص الترصيص — لكل غرض تخصيصه', max_length=10, verbose_name='الغرض'),
        ),
        migrations.AddField(
            model_name='pickzone',
            name='purpose',
            field=models.CharField(choices=[('picking', '🚚 تجميع — مسار مخزن المصدر'), ('stocking', '🗄️ ترصيص — أرفف الفرع المستلم')], db_index=True, default='picking', help_text='تجميع = مسار مخزن المصدر؛ ترصيص = ترتيب أرفف الفرع (يُستخدم أيضاً للجرد)', max_length=10, verbose_name='الغرض'),
        ),
        migrations.AlterField(
            model_name='itempickoverride',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='فارغ = تخصيص افتراضي لكل المواقع', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_pick_overrides', to='branches.branch', verbose_name='المخزن / الفرع'),
        ),
        migrations.AlterField(
            model_name='pickzone',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='فارغ = الإعداد الافتراضي لكل المواقع التي لا تملك إعداداً خاصاً', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick_zones', to='branches.branch', verbose_name='المخزن / الفرع'),
        ),
        migrations.AlterUniqueTogether(
            name='itempickoverride',
            unique_together={('branch', 'purpose', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='pickzone',
            unique_together={('branch', 'purpose', 'name')},
        ),
    ]
