# Generated by Django 4.2.13 on 2026-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0006_alter_itempickoverride_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intransittransfer',
            name='erp_receipt_doc_number',
            field=models.CharField(blank=True, help_text='docnumber الخاص بمستند الاستلام لدى الفرع المستلم — يرتبط بالصرف عبر docnumber2', max_length=50, verbose_name='رقم مستند الاستلام (25)'),
        ),
        migrations.AlterField(
            model_name='intransittransfer',
            name='erp_doc_number',
            field=models.CharField(db_index=True, help_text='stktransm.docnumber — فريد فقط ضمن تسلسل الفرع المصدر', max_length=50, verbose_name='رقم المستند (ERP)'),
        ),
        migrations.AlterField(
            model_name='intransittransfer',
            name='erp_received_date',
            field=models.DateField(blank=True, help_text='docdate لمستند الاستلام (doccode=25) لدى الفرع المستلم', null=True, verbose_name='تاريخ الاستلام (ERP)'),
        ),
        migrations.AlterField(
            model_name='intransittransfer',
            name='erp_receiving_branch_code',
            field=models.CharField(blank=True, help_text='stktransm.cust_branch_code — الوجهة المسجلة على مستند الصرف 125', max_length=20, verbose_name='كود فرع المستلم (ERP)'),
        ),
        migrations.AlterUniqueTogether(
            name='intransittransfer',
            unique_together={('erp_doc_number', 'erp_supplying_branch_code')},
        ),
    ]
