# Generated by Django 4.2.13 on 2026-05-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_staffprofile_notification_prefs'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abuseflag',
            options={'ordering': ['-detected_at'], 'verbose_name': 'إشارة مشكلة', 'verbose_name_plural': 'إشارات المشاكل'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل مراجعة', 'verbose_name_plural': 'سجلات المراجعة'},
        ),
        migrations.RenameIndex(
            model_name='abuseflag',
            new_name='audit_abuse_staff_i_beac94_idx',
            old_name='abuse_staff_type_idx',
        ),
        migrations.RenameIndex(
            model_name='abuseflag',
            new_name='audit_abuse_status_68849d_idx',
            old_name='abuse_status_sev_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_766c6d_idx',
            old_name='audit_action_date_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_model_n_20c0d3_idx',
            old_name='audit_model_obj_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_user_id_a3c2bc_idx',
            old_name='audit_user_date_idx',
        ),
        migrations.AlterField(
            model_name='abuseflag',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الأحداث'),
        ),
        migrations.AlterField(
            model_name='abuseflag',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='abuseflag',
            name='evidence',
            field=models.JSONField(blank=True, help_text='Supporting AuditLog IDs or counts', null=True, verbose_name='الأدلة'),
        ),
        migrations.AlterField(
            model_name='abuseflag',
            name='flag_type',
            field=models.CharField(choices=[('frequent_cancellations', '⚠️ إلغاءات متكررة'), ('frequent_status_changes', '⚠️ تغييرات حالة متكررة'), ('frequent_edits', '⚠️ تعديلات متكررة'), ('erp_mismatch', '⚠️ عدم تطابق ERP'), ('after_hours_activity', '⚠️ نشاط خارج أوقات العمل'), ('bulk_deletions', '⚠️ حذف جماعي'), ('override_pattern', '⚠️ تجاوزات متكررة')], db_index=True, max_length=30, verbose_name='نوع المشكلة'),
        ),
        migrations.AlterField(
            model_name='abuseflag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='abuseflag',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='ملاحظة المراجعة'),
        ),
        migrations.AlterField(
            model_name='abuseflag',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_abuse_flags', to='users.staffprofile', verbose_name='راجع بواسطة'),
        ),
        migrations.AlterField(
            model_name='abuseflag',
            name='severity',
            field=models.CharField(choices=[('info', 'معلومة'), ('warning', 'تحذير'), ('critical', 'حرج')], db_index=True, default='warning', max_length=10, verbose_name='الخطورة'),
        ),
        migrations.AlterField(
            model_name='abuseflag',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_flags', to='users.staffprofile', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='abuseflag',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('reviewed', 'تمت المراجعة'), ('dismissed', 'تم التجاهل'), ('escalated', 'تم التصعيد')], db_index=True, default='open', max_length=12, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='abuseflag',
            name='window_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='النافذة الزمنية (ساعة)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('reservation_created', 'حجز — إنشاء'), ('reservation_updated', 'حجز — تعديل'), ('reservation_status_changed', 'حجز — تغيير حالة'), ('reservation_cancelled', 'حجز — إلغاء'), ('reservation_erp_validated', 'حجز — تحقق ERP'), ('transfer_created', 'تحويل — إنشاء'), ('transfer_submitted', 'تحويل — تقديم'), ('transfer_approved', 'تحويل — اعتماد'), ('transfer_rejected', 'تحويل — رفض'), ('transfer_sent_to_erp', 'تحويل — إرسال للـ ERP'), ('transfer_erp_validated', 'تحويل — تحقق ERP'), ('customer_created', 'عميل — إنشاء'), ('customer_updated', 'عميل — تعديل'), ('customer_tag_added', 'عميل — إضافة تاج'), ('customer_location_added', 'عميل — إضافة عنوان'), ('demand_created', 'طلب — إنشاء'), ('demand_status_changed', 'طلب — تغيير حالة'), ('demand_lost', 'طلب — بيع ضائع'), ('followup_created', 'متابعة — إنشاء'), ('followup_done', 'متابعة — اكتمال'), ('followup_auto_closed', 'متابعة — إغلاق تلقائي'), ('user_login', 'مستخدم — دخول'), ('user_login_failed', 'مستخدم — محاولة دخول فاشلة'), ('sync_completed', 'مزامنة — اكتمال'), ('sync_failed', 'مزامنة — فشل')], db_index=True, max_length=40, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, help_text='Dict of {field: [old, new]} for updates', null=True, verbose_name='التغييرات فقط'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='extra',
            field=models.JSONField(blank=True, null=True, verbose_name='بيانات إضافية'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, help_text='e.g. Reservation, TransferRequest', max_length=50, verbose_name='النموذج'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_data',
            field=models.JSONField(blank=True, null=True, verbose_name='البيانات بعد التعديل'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='معرف الكيان'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(blank=True, help_text='Human-readable str(obj) at time of action', max_length=200, verbose_name='وصف الكيان'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_data',
            field=models.JSONField(blank=True, null=True, verbose_name='البيانات قبل التعديل'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.staffprofile', verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_name',
            field=models.CharField(blank=True, help_text='Snapshot at time of action — preserved even if user is deleted', max_length=150, verbose_name='اسم المستخدم'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_role',
            field=models.CharField(blank=True, max_length=20, verbose_name='دور المستخدم'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx'),
        ),
    ]
