# Generated by Django 4.2.13 on 2026-09-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('reservation_created', 'حجز — إنشاء'), ('reservation_updated', 'حجز — تعديل'), ('reservation_status_changed', 'حجز — تغيير حالة'), ('reservation_cancelled', 'حجز — إلغاء'), ('reservation_erp_validated', 'حجز — تحقق ERP'), ('transfer_created', 'تحويل — إنشاء'), ('transfer_submitted', 'تحويل — تقديم'), ('transfer_approved', 'تحويل — اعتماد'), ('transfer_rejected', 'تحويل — رفض'), ('transfer_sent_to_erp', 'تحويل — إرسال للـ ERP'), ('transfer_erp_validated', 'تحويل — تحقق ERP'), ('customer_created', 'عميل — إنشاء'), ('customer_updated', 'عميل — تعديل'), ('customer_tag_added', 'عميل — إضافة تاج'), ('customer_location_added', 'عميل — إضافة عنوان'), ('demand_created', 'طلب — إنشاء'), ('demand_status_changed', 'طلب — تغيير حالة'), ('demand_lost', 'طلب — بيع ضائع'), ('followup_created', 'متابعة — إنشاء'), ('followup_done', 'متابعة — اكتمال'), ('followup_auto_closed', 'متابعة — إغلاق تلقائي'), ('user_login', 'مستخدم — دخول'), ('user_login_failed', 'مستخدم — محاولة دخول فاشلة'), ('sync_completed', 'مزامنة — اكتمال'), ('sync_failed', 'مزامنة — فشل'), ('supply_case_opened', 'توريد — فتح حالة نقص'), ('supply_case_status_changed', 'توريد — تغيير حالة'), ('supply_case_closed', 'توريد — إغلاق حالة'), ('supply_case_assigned', 'توريد — تعيين مسؤول'), ('supply_transfer_drafted', 'توريد — مسودة تحويل داخلي'), ('supply_purchase_ordered', 'توريد — طلب شراء من مورد'), ('replacement_case_reconstructed', 'بدل — إعادة بناء حالة من التاريخ'), ('replacement_link_confirmed', 'بدل — تأكيد ربط فاتورة منتجات'), ('replacement_link_rejected', 'بدل — رفض ربط فاتورة منتجات'), ('replacement_exception_resolved', 'بدل — معالجة استثناء')], db_index=True, max_length=40, verbose_name='الإجراء'),
        ),
    ]
