# Generated by Django 4.2.13 on 2026-10-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_alter_auditlog_action'),
        ('audit', '0010_points_removal'),
    ]

    operations = [
    ]
