# Generated by Django 4.2.13 on 2026-10-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_merge_0010_alter_auditlog_action_0010_points_removal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('reservation_created', 'حجز — إنشاء'), ('reservation_updated', 'حجز — تعديل'), ('reservation_status_changed', 'حجز — تغيير حالة'), ('reservation_cancelled', 'حجز — إلغاء'), ('reservation_erp_validated', 'حجز — تحقق ERP'), ('transfer_created', 'تحويل — إنشاء'), ('transfer_submitted', 'تحويل — تقديم'), ('transfer_approved', 'تحويل — اعتماد'), ('transfer_rejected', 'تحويل — رفض'), ('transfer_sent_to_erp', 'تحويل — إرسال للـ ERP'), ('transfer_erp_validated', 'تحويل — تحقق ERP'), ('customer_created', 'عميل — إنشاء'), ('customer_updated', 'عميل — تعديل'), ('customer_tag_added', 'عميل — إضافة تاج'), ('customer_location_added', 'عميل — إضافة عنوان'), ('demand_created', 'طلب — إنشاء'), ('demand_status_changed', 'طلب — تغيير حالة'), ('demand_lost', 'طلب — بيع ضائع'), ('followup_created', 'متابعة — إنشاء'), ('followup_done', 'متابعة — اكتمال'), ('followup_auto_closed', 'متابعة — إغلاق تلقائي'), ('user_login', 'مستخدم — دخول'), ('user_login_failed', 'مستخدم — محاولة دخول فاشلة'), ('sync_completed', 'مزامنة — اكتمال'), ('sync_failed', 'مزامنة — فشل'), ('supply_case_opened', 'توريد — فتح حالة نقص'), ('supply_case_status_changed', 'توريد — تغيير حالة'), ('supply_case_closed', 'توريد — إغلاق حالة'), ('supply_case_assigned', 'توريد — تعيين مسؤول'), ('supply_transfer_drafted', 'توريد — مسودة تحويل داخلي'), ('supply_purchase_ordered', 'توريد — طلب شراء من مورد'), ('supply_availability_locked', 'إتاحة مورد — إقفال القائمة'), ('supply_availability_unlocked', 'إتاحة مورد — فتح القائمة'), ('supply_availability_edited', 'إتاحة مورد — تعديل'), ('replacement_case_reconstructed', 'بدل — إعادة بناء حالة من التاريخ'), ('replacement_link_confirmed', 'بدل — تأكيد ربط فاتورة منتجات'), ('replacement_link_rejected', 'بدل — رفض ربط فاتورة منتجات'), ('replacement_exception_resolved', 'بدل — معالجة استثناء'), ('replacement_case_created', 'بدل — إنشاء حالة'), ('replacement_case_updated', 'بدل — تعديل أصناف'), ('replacement_case_calculated', 'بدل — حساب الرصيد'), ('replacement_case_submitted', 'بدل — إرسال للاعتماد'), ('replacement_case_approved', 'بدل — اعتماد'), ('replacement_case_rejected', 'بدل — رفض'), ('replacement_case_reopened', 'بدل — إعادة فتح'), ('replacement_case_cancelled', 'بدل — إلغاء'), ('replacement_leg_prepared', 'بدل — تجهيز مستند'), ('replacement_leg_posted', 'بدل — ترحيل مستند'), ('replacement_leg_failed', 'بدل — فشل ترحيل'), ('replacement_contract_linked', 'بدل — ربط فاتورة التعاقد'), ('coupon_batch_generated', 'كوبونات — توليد دفعة'), ('coupon_batch_exported', 'كوبونات — تنزيل ملف الطباعة'), ('coupon_batch_stocked', 'كوبونات — إدخال دفعة في SOFTECH'), ('customer_branch_copy_written', 'عميل — نسخ حالة الرئيسي لنسخة الفرع'), ('customer_points_removed', 'عميل — استبعاد من نظام النقاط وتصفير الرصيد'), ('sales_target_changed', 'هدف بيعي — تعديل القيمة'), ('sales_target_created', 'هدف بيعي — إضافة هدف'), ('sales_target_deleted', 'هدف بيعي — حذف هدف'), ('sales_target_committed', 'هدف بيعي — اعتماد الأهداف من سيناريو')], db_index=True, max_length=40, verbose_name='الإجراء'),
        ),
    ]
