# Generated by Django 4.2.13 on 2026-09-30 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0027_alter_rolemoduleaccess_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('pays', 'يسدد'), ('funded_by', 'مموَّل منه'), ('returns', 'مرتجع لـ'), ('cancels', 'يلغي'), ('related_to', 'مرتبط بـ')], db_index=True, max_length=12)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('origin', models.CharField(choices=[('native', 'من SOFTECH'), ('matched', 'مطابقة آلية'), ('manual', 'يدوي')], max_length=8)),
                ('status', models.CharField(choices=[('proposed', 'مقترح'), ('confirmed', 'مؤكد'), ('rejected', 'مرفوض'), ('superseded', 'مُستبدل')], db_index=True, default='proposed', max_length=10)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'علاقة مستندات',
                'verbose_name_plural': 'علاقات المستندات',
            },
        ),
        migrations.CreateModel(
            name='DocumentRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('softech', 'SOFTECH'), ('pos_order', 'أمر بيع (المنصة)')], default='softech', max_length=12)),
                ('doc_kind', models.CharField(choices=[('purchase', 'فاتورة شراء'), ('supplier_return', 'مرتجع مورد'), ('sale', 'فاتورة بيع'), ('sale_return', 'مرتجع بيع'), ('payment_voucher', 'سند صرف / قبض')], db_index=True, max_length=20)),
                ('branchcode', models.CharField(db_index=True, max_length=5)),
                ('doccode', models.CharField(max_length=5)),
                ('docnumber', models.CharField(db_index=True, max_length=20)),
                ('docdate', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('party_code', models.CharField(blank=True, db_index=True, max_length=12)),
                ('party_name', models.CharField(blank=True, max_length=300)),
                ('phcode', models.CharField(blank=True, db_index=True, max_length=20)),
                ('channel', models.CharField(blank=True, max_length=5)),
                ('usercode', models.CharField(blank=True, max_length=20)),
                ('doc_time', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('source_model', models.CharField(blank=True, max_length=60)),
                ('source_pk', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مستند مرجعي',
                'verbose_name_plural': 'مستندات مرجعية',
                'indexes': [models.Index(fields=['source_model', 'source_pk'], name='lineage_doc_source__0a9832_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentref',
            constraint=models.UniqueConstraint(fields=('system', 'branchcode', 'doccode', 'docnumber', 'docdate'), name='uq_lineage_docref_4part'),
        ),
        migrations.AddField(
            model_name='documentedge',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.staffprofile'),
        ),
        migrations.AddField(
            model_name='documentedge',
            name='from_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edges_out', to='lineage.documentref'),
        ),
        migrations.AddField(
            model_name='documentedge',
            name='to_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edges_in', to='lineage.documentref'),
        ),
        migrations.AddConstraint(
            model_name='documentedge',
            constraint=models.UniqueConstraint(fields=('from_ref', 'to_ref', 'relation'), name='uq_lineage_edge'),
        ),
    ]
