# Generated by Django 4.2.13 on 2026-04-25 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softech_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softech_id', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('name_scientific', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=15)),
                ('supplier_code', models.CharField(blank=True, max_length=8)),
                ('family_code', models.CharField(blank=True, max_length=5)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medicine_type', models.CharField(blank=True, max_length=2)),
                ('requires_fridge', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softech_store_code', models.CharField(blank=True, max_length=3)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('monthly_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('on_order_qty', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.item')),
            ],
            options={
                'unique_together': {('item', 'branch', 'softech_store_code')},
            },
        ),
    ]
