# Generated by Django 4.2.13 on 2026-04-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_sale_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
