# Generated by Django 4.2.13 on 2026-05-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_phcode_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='phcode',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
