# Generated by Django 4.2.13 on 2026-05-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_item_price_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='family_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='item',
            name='medicine_type_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='medicine_type_name_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='pack_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='سعر العبوة'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='سعر الوحدة'),
        ),
    ]
