# Generated by Django 4.2.13 on 2026-05-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_item_producer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='producer_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='producer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
