# Generated by Django 4.2.13 on 2026-05-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_item_enrichment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='effect_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='effect_code2',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='origin_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='shape_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_code',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
