# Generated by Django 4.2.13 on 2026-05-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_item_store_classif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='branch_trans',
            field=models.CharField(blank=True, help_text='SOFTECH items.itemtrans1. Branch transfer permissions. 0=صرف+ارتجاع, 1=صرف فقط, 2=ارتجاع فقط, 3=إيقاف كامل.', max_length=1, verbose_name='صلاحية — الفروع'),
        ),
        migrations.AlterField(
            model_name='item',
            name='customer_trans',
            field=models.CharField(blank=True, help_text='SOFTECH items.itemtrans3. Customer sale permissions. 0=بيع+ارتجاع, 1=بيع فقط, 2=ارتجاع فقط, 3=إيقاف كامل.', max_length=1, verbose_name='صلاحية — العملاء'),
        ),
        migrations.AlterField(
            model_name='item',
            name='has_points',
            field=models.BooleanField(default=False, help_text='SOFTECH items.itempointsys. 1 = eligible for points program.', verbose_name='مؤهل لنظام النقاط'),
        ),
        migrations.AlterField(
            model_name='item',
            name='insurance_type',
            field=models.CharField(blank=True, db_index=True, help_text='SOFTECH items.hi_typecode. 0=غير خاضع للتأمين (not covered), 1=طلبية (Talbia), 2=TPA, 3=تكافل (Takaful), 4=Other.', max_length=1, verbose_name='نوع التأمين الصحي'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_fast_moving',
            field=models.BooleanField(db_index=True, default=False, help_text='SOFTECH items.fmi. Fast Moving Item flag — high sales velocity.', verbose_name='سريع التداول (FMI)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_level',
            field=models.PositiveSmallIntegerField(default=0, help_text='SOFTECH items.itemslevel. Distribution: 0=standard (50,338 items), 1=special (1,014 items). Exact business meaning needs user confirmation — sample items with level=1 include CENTRUM SILVER, ADVIL, ROGAINE, ASHWAGANDHA, BIO SOFT (mostly imported brand-name items). NOT narcotics. Possible meaning: imported/branded/special tier. NOTE: تصنيف جدول مخدرات (Narcotics Schedule) shown in the SOFTECH UI maps to a DIFFERENT column not yet identified. TODO: confirm with business team.', verbose_name='مستوى الصنف'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nosale_classif',
            field=models.CharField(blank=True, help_text='SOFTECH items.itemnosaleclassif. Contract/dispensing restriction. 10=normal (no restriction), 20=#2, 30=#3, 31=#4.', max_length=5, verbose_name='تصنيف منع الصرف'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pack_qty',
            field=models.PositiveSmallIntegerField(default=1, help_text='SOFTECH items.packqty — units (strips/vials/ampoules) per pack.', verbose_name='كمية العبوة'),
        ),
        migrations.AlterField(
            model_name='item',
            name='store_classif',
            field=models.CharField(blank=True, db_index=True, help_text='SOFTECH items.itemstoreclassif → custdiscpclassif.custdiscpcode. Contract discount classification tier. Used to determine which discount rate applies to this item under contract pricing. Common values: 10=Med Local, 11=Med Local Under License 20%, 12=Med Local 25%, 13=Med Imported/Egydrug 12%, 14=Med Imported/Agent 15%, 15=Med Imported 18%, 25=Med Local 25% Shortage, 84=SERVICES, 87=Children Supplies, 88=Baby Formula, 89=Baby Care, 90=Imported Devices. NULL/empty = not classified.', max_length=5, verbose_name='تصنيف خصم التعاقدات'),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier_trans',
            field=models.CharField(blank=True, help_text='SOFTECH items.itemtrans2. Supplier purchase permissions. 0=شراء+ارتجاع, 1=شراء فقط, 2=ارتجاع فقط, 3=إيقاف كامل.', max_length=1, verbose_name='صلاحية — الموردين'),
        ),
    ]
