# Generated by Django 4.2.13 on 2026-05-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_variant_groups_bundles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbundle',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='نسبة مئوية (0-100) أو مبلغ ثابت حسب نوع الخصم', max_digits=8, verbose_name='قيمة الخصم'),
        ),
    ]
