# Generated by Django 4.2.13 on 2026-06-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_itembarcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_discp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SOFTECH items.additionaldiscp — secondary discount tier %.', max_digits=5, verbose_name='خصم إضافي %'),
        ),
        migrations.AddField(
            model_name='item',
            name='pharmacy_discp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SOFTECH items.pharmacydiscp — wholesale/pharmacy customer discount %.', max_digits=5, verbose_name='خصم الصيدلية %'),
        ),
        migrations.AddField(
            model_name='item',
            name='pos_discp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SOFTECH items.posdiscp — retail POS discount %. Currently 10% on 87.5% of items.', max_digits=5, verbose_name='خصم POS %'),
        ),
        migrations.AddField(
            model_name='item',
            name='special_discp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SOFTECH items.specialdiscp — special event discount %.', max_digits=5, verbose_name='خصم خاص %'),
        ),
    ]
