# Generated by Django 4.2.13 on 2026-06-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_item_additional_discp_item_pharmacy_discp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pack_price_tax',
            field=models.DecimalField(decimal_places=3, default=0, help_text='SOFTECH items.itemsaleprice_tax. Must be updated whenever pack_price changes.', max_digits=10, verbose_name='سعر العبوة شامل الضريبة'),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_tax_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SOFTECH items.itemsalestaxp. Used to auto-compute pack_price_tax on approval.', max_digits=5, verbose_name='نسبة الضريبة %'),
        ),
    ]
