# Generated by Django 4.2.13 on 2026-07-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_item_pack_price_tax_item_sale_tax_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized', models.CharField(db_index=True, max_length=300, verbose_name='الاسم المُعيَّر')),
                ('vendor_code', models.CharField(blank=True, db_index=True, max_length=8, verbose_name='كود المورد (اختياري)')),
                ('source', models.CharField(choices=[('shortage', 'قائمة نواقص'), ('invoice', 'فاتورة مورد'), ('import', 'استيراد'), ('manual', 'يدوي')], default='manual', max_length=20, verbose_name='المصدر')),
                ('use_count', models.PositiveIntegerField(default=1, verbose_name='عدد التأكيدات')),
                ('sample_raw', models.CharField(blank=True, max_length=300, verbose_name='آخر نص خام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.item', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'اسم مُتعلَّم للصنف',
                'verbose_name_plural': 'الأسماء المُتعلَّمة',
                'ordering': ['-use_count'],
                'indexes': [models.Index(fields=['normalized', 'vendor_code'], name='itemalias_lookup_idx')],
                'unique_together': {('normalized', 'vendor_code', 'item')},
            },
        ),
    ]
