# Generated by Django 4.2.13 on 2026-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_item_no_more_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_archive',
            field=models.BooleanField(db_index=True, default=False, help_text='SOFTECH items.itemarchive = 1 — archived item.', verbose_name='مؤرشف'),
        ),
    ]
