# Generated by Django 4.2.13 on 2026-08-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_staffprofile_can_edit_erp_comments'),
        ('catalog', '0027_item_bool_db_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_shortage',
            field=models.BooleanField(db_index=True, default=False, help_text='مؤكَّد يدويًا: صنف يصعب توريده من الموردين أو يأتي بكمية محدودة (كوتة).', verbose_name='في نقص بالسوق'),
        ),
        migrations.AddField(
            model_name='item',
            name='shortage_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_market_shortages', to='users.staffprofile', verbose_name='أكَّده'),
        ),
        migrations.AddField(
            model_name='item',
            name='shortage_flagged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحديد'),
        ),
        migrations.AddField(
            model_name='item',
            name='shortage_note',
            field=models.CharField(blank=True, default='', help_text='e.g. كوتة / لا يوجد بالموردين / بديل مطلوب.', max_length=300, verbose_name='ملاحظة النقص'),
        ),
        migrations.AddField(
            model_name='item',
            name='shortage_source',
            field=models.CharField(blank=True, default='', help_text="'auto' (candidate confirmed) | 'manual' (added by hand).", max_length=10, verbose_name='مصدر التحديد'),
        ),
    ]
