# Generated by Django 4.2.13 on 2026-08-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_staffprofile_can_edit_erp_comments'),
        ('catalog', '0028_item_in_shortage_item_shortage_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shortage_dismiss_note',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='ملاحظة الاستبعاد'),
        ),
        migrations.AddField(
            model_name='item',
            name='shortage_dismiss_reason',
            field=models.CharField(blank=True, choices=[('variant', 'مقاس/شكل بديل لمنتج متاح'), ('on_request', 'يُطلب عند الحاجة فقط'), ('obsolete', 'غير متوفر بالسوق المصري'), ('not_shortage', 'ليس نقصًا (موقوف/موسمي)'), ('other', 'أخرى')], default='', max_length=15, verbose_name='سبب الاستبعاد'),
        ),
        migrations.AddField(
            model_name='item',
            name='shortage_dismissed',
            field=models.BooleanField(db_index=True, default=False, help_text='مُستبعد من قائمة المرشحين مع حفظ السبب — قابل للاسترجاع.', verbose_name='مُستبعد من النواقص'),
        ),
        migrations.AddField(
            model_name='item',
            name='shortage_dismissed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستبعاد'),
        ),
        migrations.AddField(
            model_name='item',
            name='shortage_dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_market_shortages', to='users.staffprofile', verbose_name='استبعده'),
        ),
        migrations.AddField(
            model_name='item',
            name='shortage_matching_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covers_shortage_variants', to='catalog.item', verbose_name='المنتج البديل المتاح'),
        ),
    ]
