# Generated by Django 4.2.13 on 2026-08-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_item_shortage_dismiss_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shortage_matching_item',
        ),
        migrations.AddField(
            model_name='item',
            name='shortage_matching_items',
            field=models.ManyToManyField(blank=True, related_name='covers_shortage_variants', to='catalog.item', verbose_name='المنتجات البديلة المتاحة'),
        ),
    ]
