# Generated by Django 4.2.13 on 2026-08-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_remove_item_shortage_matching_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shortage_softech_error',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='خطأ مزامنة سوفتك'),
        ),
        migrations.AddField(
            model_name='item',
            name='shortage_softech_synced',
            field=models.BooleanField(db_index=True, default=True, verbose_name='مُتزامن مع سوفتك'),
        ),
        migrations.AddField(
            model_name='item',
            name='shortage_softech_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة سوفتك'),
        ),
    ]
