# Generated by Django 4.2.13 on 2026-08-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_item_shortage_softech_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shortage_supply_suspended',
            field=models.BooleanField(default=False, verbose_name='أوقفنا التوريد (موقوف)'),
        ),
    ]
