# Generated by Django 4.2.13 on 2026-08-24 16:55

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_item_shortage_supply_suspended'),
    ]

    operations = [
        # pg_trgm powers the GIN index below (gin_trgm_ops) + universal-search
        # similarity/ILIKE. Idempotent: CREATE EXTENSION IF NOT EXISTS.
        TrigramExtension(),
        migrations.AddField(
            model_name='item',
            name='search_name',
            field=models.TextField(blank=True, default='', help_text='Derived normalized search haystack — powers universal search. Do not edit by hand.', verbose_name='اسم البحث (منسّق)'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_name'], name='catalog_item_searchname_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
