# Generated by Django 4.2.13 on 2026-08-24 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_rolemoduleaccess_module'),
        ('catalog', '0033_item_search_name_item_catalog_item_searchname_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='catalog.category', verbose_name='التصنيف الأب'),
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='المعرّف')),
                ('name', models.CharField(max_length=60, verbose_name='الاسم')),
                ('name_ar', models.CharField(blank=True, max_length=60, verbose_name='الاسم بالعربية')),
                ('color', models.CharField(blank=True, default='', help_text='#RRGGBB', max_length=7)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_item_tags', to='users.staffprofile')),
            ],
            options={
                'verbose_name': 'وسم صنف',
                'verbose_name_plural': 'وسوم الأصناف',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='catalog.itemtag', verbose_name='الوسوم'),
        ),
    ]
