# Generated by Django 4.2.13 on 2026-08-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_category_parent_itemtag_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shortage_dismiss_reason',
            field=models.CharField(blank=True, choices=[('variant', 'مقاس/شكل بديل لمنتج متاح'), ('on_request', 'يُطلب عند الحاجة'), ('obsolete', 'غير متوفر بالسوق المصري'), ('not_shortage', 'ليس ناقصًا (موقوف/موسمي)'), ('false_positive', 'اكتشاف خاطئ — ليس ناقصًا'), ('other', 'أخرى')], default='', max_length=15, verbose_name='سبب الاستبعاد'),
        ),
    ]
