# Generated by Django 4.2.13 on 2026-09-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_alter_item_shortage_dismiss_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='batch_required',
            field=models.BooleanField(db_index=True, default=False, help_text='Synced from SOFTECH items.itempartno («رقم القطعة أو الباتش»). 1 = batch/expiry selection is MANDATORY at POS before dispensing (not merely "batches exist"). 0 = optional. Sparse: only ~9 items master-wide carry it.', verbose_name='اختيار الباتش إلزامي (Batch required)'),
        ),
    ]
