# Generated by Django 4.2.13 on 2026-09-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_staffprofile_notify_expiry_worklist_wa'),
        ('catalog', '0036_item_batch_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_phantom_substitution',
            field=models.BooleanField(db_index=True, default=False, help_text='معظم مبيعاته يُعاد شراؤها من العميل/المريض (تعاقد) لا من الموردين — لا يُطلب أو تُقلَّل كميته.', verbose_name='مبيعات وهمية'),
        ),
        migrations.AddField(
            model_name='item',
            name='phantom_buyback_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='كمية إعادة الشراء (نافذة)'),
        ),
        migrations.AddField(
            model_name='item',
            name='phantom_contract_ratio',
            field=models.FloatField(default=0.0, help_text='حصة مبيعات قناة التعاقد/التأمين — سياقية فقط، ليست شرط التحديد.', verbose_name='نسبة قناة التعاقد'),
        ),
        migrations.AddField(
            model_name='item',
            name='phantom_detected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر فحص وهمية'),
        ),
        migrations.AddField(
            model_name='item',
            name='phantom_genuine_need',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الطلب الحقيقي (مبيعات − إعادة شراء)'),
        ),
        migrations.AddField(
            model_name='item',
            name='phantom_order_pct',
            field=models.FloatField(default=1.0, help_text='1 − النسبة الوهمية (مرجَّحة زمنيًا) — الجزء الحقيقي المطلوب توريده من الموردين.', verbose_name='النسبة الموصى بطلبها'),
        ),
        migrations.AddField(
            model_name='item',
            name='phantom_override',
            field=models.CharField(blank=True, choices=[('', 'تلقائي (بدون مراجعة)'), ('confirmed', 'مؤكَّد يدويًا'), ('excluded', 'ليست مبيعات وهمية')], default='', max_length=10, verbose_name='قرار المراجعة'),
        ),
        migrations.AddField(
            model_name='item',
            name='phantom_override_note',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='ملاحظة المراجعة'),
        ),
        migrations.AddField(
            model_name='item',
            name='phantom_ratio',
            field=models.FloatField(default=0.0, help_text='buyback_qty / sold_qty على مدى نافذة التحديد (12 شهر) — أساس التحديد.', verbose_name='نسبة الوهمية'),
        ),
        migrations.AddField(
            model_name='item',
            name='phantom_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AddField(
            model_name='item',
            name='phantom_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_phantom_items', to='users.staffprofile', verbose_name='راجعه'),
        ),
        migrations.AddField(
            model_name='item',
            name='phantom_sold_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='كمية المبيعات (نافذة)'),
        ),
        migrations.AddField(
            model_name='item',
            name='phantom_source',
            field=models.CharField(blank=True, default='', help_text="'auto' | 'manual'.", max_length=10, verbose_name='مصدر التحديد'),
        ),
    ]
