# Generated by Django 4.2.13 on 2026-09-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_staffprofile_notify_expiry_worklist_wa'),
        ('catalog', '0037_item_is_phantom_substitution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_spike',
            field=models.BooleanField(db_index=True, default=False, help_text='قفزة طلب حديثة قد لا تدوم (نمط الوصفة المستهدفة) — راجِع قبل الشراء بكمية كبيرة.', verbose_name='ذروة طلب غير مؤكدة'),
        ),
        migrations.AddField(
            model_name='item',
            name='spike_confirmed',
            field=models.BooleanField(default=False, help_text='مراجعة بشرية: ذروة غير مستدامة فعلاً — يُسمح بتقليل الكمية عند التفعيل.', verbose_name='مؤكَّدة (طبّق التقليل)'),
        ),
        migrations.AddField(
            model_name='item',
            name='spike_detected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر رصد ذروة'),
        ),
        migrations.AddField(
            model_name='item',
            name='spike_prior',
            field=models.FloatField(default=0.0, verbose_name='المعدل السابق (شهري)'),
        ),
        migrations.AddField(
            model_name='item',
            name='spike_ratio',
            field=models.FloatField(default=0.0, help_text='الطلب الربع أخير ÷ طلب الأشهر التسعة السابقة.', verbose_name='مضاعف الذروة'),
        ),
        migrations.AddField(
            model_name='item',
            name='spike_recent',
            field=models.FloatField(default=0.0, verbose_name='المعدل الحديث (شهري)'),
        ),
        migrations.AddField(
            model_name='item',
            name='spike_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='spike_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_spike_items', to='users.staffprofile', verbose_name='راجع الذروة'),
        ),
        migrations.AddField(
            model_name='item',
            name='spike_tier',
            field=models.CharField(blank=True, choices=[('', '—'), ('strong', 'ذروة قوية'), ('watch', 'ذروة للمراقبة')], default='', max_length=8, verbose_name='درجة الذروة'),
        ),
        migrations.AddField(
            model_name='item',
            name='strategic_hold',
            field=models.BooleanField(db_index=True, default=False, help_text='مُحتفَظ به عمدًا رغم قلة البيع (مريض تعاقد/أورام) — يُستثنى من رصد الركود.', verbose_name='احتفاظ استراتيجي'),
        ),
    ]
