# Generated by Django 4.2.13 on 2026-10-04 10:50

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_item_is_spike_item_spike_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAliasGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized', models.CharField(db_index=True, max_length=300)),
                ('vendor_code', models.CharField(blank=True, db_index=True, max_length=8)),
                ('item_ids', models.JSONField(default=list)),
                ('items_key', models.CharField(max_length=300)),
                ('use_count', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('sample_raw', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اسم مُتعلَّم لعدة أصناف',
                'verbose_name_plural': 'الأسماء المُتعلَّمة لعدة أصناف',
                'ordering': ['-use_count'],
            },
        ),
        migrations.CreateModel(
            name='ItemAliasRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized', models.CharField(db_index=True, max_length=300)),
                ('vendor_code', models.CharField(blank=True, db_index=True, max_length=8)),
                ('count', models.PositiveIntegerField(default=1)),
                ('sample_raw', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مطابقة مرفوضة',
                'verbose_name_plural': 'المطابقات المرفوضة',
            },
        ),
        migrations.AlterField(
            model_name='itemalias',
            name='source',
            field=models.CharField(choices=[('shortage', 'قائمة نواقص'), ('invoice', 'فاتورة مورد'), ('import', 'استيراد'), ('manual', 'يدوي'), ('whatsapp', 'طلبات واتساب'), ('availability', 'إتاحة مورد'), ('pos_rx_ocr', 'روشتة POS')], default='manual', max_length=20, verbose_name='المصدر'),
        ),
        migrations.AddIndex(
            model_name='itemalias',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized'], name='itemalias_norm_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddField(
            model_name='itemaliasrejection',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_rejections', to='catalog.item'),
        ),
        migrations.AlterUniqueTogether(
            name='itemaliasgroup',
            unique_together={('normalized', 'vendor_code', 'items_key')},
        ),
        migrations.AlterUniqueTogether(
            name='itemaliasrejection',
            unique_together={('normalized', 'vendor_code', 'item')},
        ),
    ]
