# Generated by Django 4.2.13 on 2026-10-05 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_item_name_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSupplierLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=10, verbose_name='كود الصنف')),
                ('supp_code', models.CharField(db_index=True, max_length=10, verbose_name='كود المورد')),
                ('supp_item_code', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='كود الصنف لدى المورد')),
                ('is_main', models.BooleanField(default=False, verbose_name='المورد الأساسي')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_links', to='catalog.item', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'صنف لدى مورد (SOFTECH)',
                'verbose_name_plural': 'أصناف الموردين (SOFTECH)',
                'indexes': [models.Index(fields=['supp_code', 'supp_item_code'], name='isl_supp_code_idx')],
                'unique_together': {('item_code', 'supp_code')},
            },
        ),
    ]
