# Generated by Django 4.2.13 on 2026-08-13 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0020_staffprofile_hr_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftechIdentityClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('supplier', 'مورد'), ('customer', 'عميل / موظف'), ('salesperson', 'مسئول بيع / مستخدم ERP')], db_index=True, max_length=15, verbose_name='نوع الهوية')),
                ('person_code', models.CharField(db_index=True, max_length=40, verbose_name='كود SOFTECH')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='الاسم في SOFTECH')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=10, verbose_name='الحالة')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة الطلب')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_identity_claims', to='users.staffprofile', verbose_name='روجع بواسطة')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softech_identities', to='users.staffprofile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'هوية SOFTECH شخصية',
                'verbose_name_plural': 'هويات SOFTECH الشخصية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(db_index=True, max_length=40, verbose_name='نوع اللوحة')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='العنوان')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='الإعدادات')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('column', models.PositiveSmallIntegerField(default=0, verbose_name='العمود')),
                ('size', models.CharField(choices=[('sm', 'صغير'), ('md', 'متوسط'), ('lg', 'كبير'), ('xl', 'كامل العرض')], default='md', max_length=10)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='personal.softechidentityclaim', verbose_name='الهوية')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_widgets', to='users.staffprofile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'لوحة شخصية',
                'verbose_name_plural': 'اللوحات الشخصية',
                'ordering': ['column', 'position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='softechidentityclaim',
            constraint=models.UniqueConstraint(fields=('staff', 'kind', 'person_code'), name='uniq_identity_staff_kind_code'),
        ),
    ]
