# Generated by Django 4.2.13 on 2026-08-14 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_staffprofile_can_edit_erp_comments'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCommentEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchcode', models.CharField(db_index=True, max_length=20)),
                ('doccode', models.CharField(max_length=10)),
                ('docnumber', models.CharField(db_index=True, max_length=30)),
                ('old_comment', models.CharField(blank=True, max_length=100, verbose_name='الملاحظة السابقة')),
                ('new_comment', models.CharField(blank=True, max_length=100, verbose_name='الملاحظة الجديدة')),
                ('hq_result', models.CharField(blank=True, max_length=120, verbose_name='نتيجة المركز')),
                ('branch_host', models.CharField(blank=True, max_length=60, verbose_name='خادم الفرع')),
                ('branch_result', models.CharField(blank=True, max_length=120, verbose_name='نتيجة الفرع')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_edits', to='personal.softechidentityclaim', verbose_name='الهوية')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_edits', to='users.staffprofile', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعديل ملاحظة مستند',
                'verbose_name_plural': 'تعديلات ملاحظات المستندات',
                'ordering': ['-created_at'],
            },
        ),
    ]
