# Generated by Django 4.2.13 on 2026-08-14 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_staffprofile_can_edit_erp_comments'),
        ('personal', '0002_documentcommentedit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('document', 'مستند'), ('cheque', 'شيك')], db_index=True, max_length=10)),
                ('branchcode', models.CharField(db_index=True, max_length=20)),
                ('doccode', models.CharField(max_length=10)),
                ('docnumber', models.CharField(db_index=True, max_length=30)),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='كود المراجعة')),
                ('status', models.CharField(choices=[('revised', 'تمت المراجعة'), ('revoked', 'أُلغيت')], db_index=True, default='revised', max_length=10)),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='ملاحظة المراجعة')),
                ('hq_result', models.CharField(blank=True, max_length=120)),
                ('branch_host', models.CharField(blank=True, max_length=60)),
                ('branch_result', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='personal.softechidentityclaim')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='users.staffprofile', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مراجعة مستند',
                'verbose_name_plural': 'مراجعات المستندات',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.UniqueConstraint(fields=('staff', 'kind', 'branchcode', 'doccode', 'docnumber'), name='uniq_revision_staff_key'),
        ),
    ]
