# Generated by Django 4.2.13 on 2026-10-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_documentrevision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcommentedit',
            name='branch_host',
            field=models.CharField(blank=True, max_length=60, verbose_name='سيرفر الفرع'),
        ),
    ]
