# Generated by Django 4.2.13 on 2026-10-10 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0028_alter_rolemoduleaccess_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_key", models.CharField(db_index=True, max_length=80)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("save", "حفظ تعديل"),
                            ("revert", "رجوع للنسخة الأصلية"),
                        ],
                        max_length=10,
                    ),
                ),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تعديل شرح",
                "verbose_name_plural": "سجل تعديلات الشرح",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HelpOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "screen_key",
                    models.CharField(max_length=80, unique=True, verbose_name="الشاشة"),
                ),
                (
                    "data",
                    models.JSONField(default=dict, verbose_name="المحتوى المعدّل"),
                ),
                ("base_hash", models.CharField(blank=True, default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعديل شرح شاشة",
                "verbose_name_plural": "تعديلات شرح الشاشات",
            },
        ),
        migrations.CreateModel(
            name="HelpFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_key", models.CharField(db_index=True, max_length=80)),
                ("tab", models.CharField(blank=True, default="", max_length=60)),
                ("helpful", models.BooleanField()),
                ("comment", models.CharField(blank=True, default="", max_length=500)),
                ("lang", models.CharField(default="ar", max_length=2)),
                ("role", models.CharField(blank=True, default="", max_length=20)),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم شرح",
                "verbose_name_plural": "تقييمات الشرح",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HelpEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("open", "فتح الشرح"), ("search", "بحث")],
                        max_length=10,
                    ),
                ),
                (
                    "screen_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=80
                    ),
                ),
                ("tab", models.CharField(blank=True, default="", max_length=60)),
                ("query", models.CharField(blank=True, default="", max_length=200)),
                ("results", models.IntegerField(blank=True, null=True)),
                ("role", models.CharField(blank=True, default="", max_length=20)),
                ("branch_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "استخدام الشرح",
                "verbose_name_plural": "استخدام الشرح",
                "ordering": ["-created_at"],
            },
        ),
    ]
