# Generated by Django 4.2.13 on 2026-10-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_rolemoduleaccess_module"),
        ("help", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("open", "فتح الشرح"),
                    ("search", "بحث"),
                    ("ask", "اسأل النظام"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="HelpQuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_key", models.CharField(db_index=True, max_length=40)),
                ("score", models.PositiveSmallIntegerField()),
                ("total", models.PositiveSmallIntegerField()),
                ("passed", models.BooleanField()),
                ("answers", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "محاولة اختبار",
                "verbose_name_plural": "محاولات الاختبارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HelpLearned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_key", models.CharField(max_length=80)),
                ("version", models.CharField(blank=True, default="", max_length=10)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "شاشة تم فهمها",
                "verbose_name_plural": "مسار التدريب — الشاشات المفهومة",
            },
        ),
        migrations.AddConstraint(
            model_name="helplearned",
            constraint=models.UniqueConstraint(
                fields=("staff", "screen_key"), name="help_learned_once"
            ),
        ),
    ]
