# Generated by Django 4.2.13 on 2026-10-10 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_rolemoduleaccess_module"),
        ("help", "0002_onboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpTrainingOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("path", "مسار تدريبي لدور"),
                            ("quiz", "اختبار موديول"),
                        ],
                        max_length=10,
                    ),
                ),
                ("key", models.CharField(max_length=40)),
                ("data", models.JSONField(default=dict)),
                ("base_hash", models.CharField(blank=True, default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعديل مسار/اختبار تدريبي",
                "verbose_name_plural": "تعديلات المسارات والاختبارات",
            },
        ),
        migrations.AddConstraint(
            model_name="helptrainingoverride",
            constraint=models.UniqueConstraint(
                fields=("kind", "key"), name="help_training_override_once"
            ),
        ),
    ]
