# Generated by Django 4.2.13 on 2026-10-10 22:39

from django.db import migrations, models


def stamp_existing(apps, schema_editor):
    """Attempts made before versioning were taken against the quiz in force then —
    the repo quiz unless a trainer had saved one. Stamp them with that version so
    existing passes keep counting."""
    import hashlib
    import json
    from apps.help.content import onboarding

    def ver(qs):
        return hashlib.sha256(json.dumps(qs or [], ensure_ascii=False, sort_keys=True).encode()).hexdigest()[:12]

    Attempt = apps.get_model('help', 'HelpQuizAttempt')
    Override = apps.get_model('help', 'HelpTrainingOverride')
    current = {k: ver(v) for k, v in onboarding.QUIZZES.items()}
    for o in Override.objects.filter(kind='quiz'):
        current[o.key] = ver(o.data.get('questions') or [])
    for module, v in current.items():
        Attempt.objects.filter(module_key=module, version='').update(version=v)


class Migration(migrations.Migration):

    dependencies = [
        ("help", "0003_training_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpquizattempt",
            name="version",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.RunPython(stamp_existing, migrations.RunPython.noop),
    ]
