# Generated by Django 4.2.13 on 2026-10-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help", "0004_quiz_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpTrainingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=10)),
                ("key", models.CharField(max_length=40)),
                ("data", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="helptrainingsnapshot",
            constraint=models.UniqueConstraint(
                fields=("kind", "key"), name="help_training_snapshot_once"
            ),
        ),
    ]
