# Generated by Django 4.2.13 on 2026-10-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help", "0005_training_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("open", "فتح الشرح"),
                    ("search", "بحث"),
                    ("ask", "اسأل النظام"),
                    ("tour", "جولة اعرض لي"),
                ],
                max_length=10,
            ),
        ),
    ]
