# Generated by Django 4.2.13 on 2026-06-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_options_alter_branch_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='db_host',
            field=models.CharField(blank=True, help_text='عنوان IP لخادم Sybase الخاص بالفرع — مثال: 192.168.1.5', max_length=50, verbose_name='IP قاعدة البيانات'),
        ),
        migrations.AddField(
            model_name='branch',
            name='db_name',
            field=models.CharField(blank=True, default='SOFTECHDB9', help_text='اسم قاعدة بيانات SOFTECH (افتراضي SOFTECHDB9)', max_length=50, verbose_name='اسم قاعدة البيانات'),
        ),
        migrations.AddField(
            model_name='branch',
            name='db_port',
            field=models.PositiveIntegerField(default=5000, help_text='منفذ jConnect Sybase (افتراضي 5000)', verbose_name='منفذ قاعدة البيانات'),
        ),
    ]
