# Generated by Django 4.2.13 on 2026-08-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='kind',
            field=models.CharField(choices=[('hq', 'المركز الرئيسي'), ('retail', 'فرع بيع'), ('call_center', 'كول سنتر'), ('closed', 'مُغلق / لاغى')], db_index=True, default='retail', help_text='التصنيف التشغيلي الموثوق — يُستخدم لفحص الاتصال وتفعيل نقاط البيع والقوائم', max_length=20, verbose_name='نوع النقطة'),
        ),
        migrations.AddField(
            model_name='branch',
            name='pos_enabled',
            field=models.BooleanField(default=False, help_text='يسمح بإنشاء أوامر بيع POS غير مباشرة لهذا الفرع', verbose_name='مفعّل لنقطة البيع'),
        ),
    ]
