# Generated by Django 4.2.13 on 2026-10-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_backfill_branch_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='db_host',
            field=models.CharField(blank=True, help_text='عنوان IP لسيرفر Sybase الخاص بالفرع — مثال: 192.168.1.5', max_length=50, verbose_name='IP قاعدة البيانات'),
        ),
    ]
