# Generated by Django 4.2.13 on 2026-04-28 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_staffprofile_role'),
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='demandrecord',
            new_name='demand_dema_status_7047e1_idx',
            old_name='demand_status_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='demandrecord',
            new_name='demand_dema_follow__3ba63f_idx',
            old_name='demand_followup_idx',
        ),
        migrations.RenameIndex(
            model_name='demandrecord',
            new_name='demand_dema_phone_3c3a27_idx',
            old_name='demand_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='demandrecord',
            new_name='demand_dema_status_397644_idx',
            old_name='demand_status_priority_idx',
        ),
        migrations.AlterField(
            model_name='demanditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='demanditem',
            name='is_discontinued',
            field=models.BooleanField(default=False, help_text='إذا كان الصنف متوقفاً من المصنع', verbose_name='متوقف عن الإنتاج'),
        ),
        migrations.AlterField(
            model_name='demanditem',
            name='is_long_shortage',
            field=models.BooleanField(default=False, help_text='إذا كان الصنف غير متاح منذ فترة طويلة', verbose_name='نقص طويل الأمد'),
        ),
        migrations.AlterField(
            model_name='demanditem',
            name='item_name_free',
            field=models.CharField(blank=True, help_text='يُستخدم إذا لم يكن الصنف في الكتالوج', max_length=255, verbose_name='اسم الصنف (حر)'),
        ),
        migrations.AlterField(
            model_name='demandlog',
            name='call_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة المكالمة (ثانية)'),
        ),
        migrations.AlterField(
            model_name='demandlog',
            name='call_outcome',
            field=models.CharField(blank=True, choices=[('answered', 'رد'), ('no_answer', 'لم يرد'), ('busy', 'مشغول'), ('wrong_number', 'رقم خاطئ'), ('callback', 'طلب الاتصال لاحقاً')], max_length=20, verbose_name='نتيجة المكالمة'),
        ),
        migrations.AlterField(
            model_name='demandlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='demandrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_demands', to='users.staffprofile', verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='demandrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='demandrecord',
            name='phcode',
            field=models.CharField(blank=True, db_index=True, help_text='مثال: 140HD515 — يُجلب تلقائياً من ERP', max_length=20, verbose_name='كود PIC (ERP)'),
        ),
        migrations.AlterField(
            model_name='demandrecord',
            name='status',
            field=models.CharField(choices=[('new', 'جديد — لم يُعالَج'), ('assigned', 'مُعيَّن — جارٍ المتابعة'), ('follow_up', 'متابعة — في الانتظار'), ('stock_eta', 'في انتظار المخزون'), ('transfer_suggested', 'تم اقتراح تحويل'), ('purchasing_flagged', 'مُرسَل للمشتريات'), ('fulfilled', 'تم التسليم ✅'), ('lost', 'مبيعة ضائعة ❌'), ('cancelled', 'ملغي')], db_index=True, default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemdemandstat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='demandrecord',
            index=models.Index(fields=['phcode'], name='demand_dema_phcode_b146c5_idx'),
        ),
    ]
