# Generated by Django 4.2.13 on 2026-06-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_rename_demand_status_branch_idx_demand_dema_status_7047e1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanditem',
            name='cost_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='نسخة من سعر التكلفة (item.cost_price) وقت التسجيل — لحساب الهامش', max_digits=12, null=True, verbose_name='سعر التكلفة المُجمَّد'),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='price_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='نسخة من سعر العبوة (item.pack_price) وقت التسجيل — للتقييم والاسترداد', max_digits=12, null=True, verbose_name='سعر الوحدة المُجمَّد'),
        ),
    ]
