# Generated by Django 4.2.13 on 2026-06-11 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_alter_reservation_contract_subtype_and_more'),
        ('users', '0015_softechsystemmap_erpgroupmodulepermission'),
        ('demand', '0003_demanditem_cost_price_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanditem',
            name='back_in_stock_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ عودته للمخزون'),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='contact_opt_out',
            field=models.BooleanField(db_index=True, default=False, verbose_name='رفض التواصل بخصوص هذا الصنف'),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='contact_opt_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='contact_opt_out_reason',
            field=models.CharField(blank=True, choices=[('not_needed', 'لم يعد بحاجته'), ('moved', 'انتقل / غادر'), ('for_other_person', 'كان يطلبه لشخص آخر'), ('other', 'أخرى')], max_length=20),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='disqualified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مُستبعَد من الاسترداد'),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='disqualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='disqualified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disqualified_demand_items', to='users.staffprofile'),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='disqualified_reason',
            field=models.CharField(blank=True, choices=[('not_in_egypt', 'غير متوفر في مصر'), ('discontinued', 'متوقف عن الإنتاج'), ('not_allowed', 'غير مسموح ببيعه في الصيدلية'), ('unknown_item', 'صنف غير معروف'), ('never_available', 'لن يتوفر مطلقاً'), ('other', 'أخرى')], max_length=20),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='notified_customer_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر تواصل مع العميل'),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='recovered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاسترداد'),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='recovered_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الإيراد المُسترَد (ج.م)'),
        ),
        migrations.AddField(
            model_name='demanditem',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_demand_items', to='reservations.reservation', verbose_name='الحجز الناتج'),
        ),
        migrations.AlterField(
            model_name='demanditem',
            name='item_status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('sourcing', 'جارٍ التوفير'), ('available_again', 'عاد للمخزون 🔔'), ('recovered', 'تم الاسترداد 💰'), ('fulfilled', 'تم التسليم ✅'), ('lost', 'ضاعت المبيعة ❌'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=20, verbose_name='حالة الصنف'),
        ),
    ]
