# Generated by Django 4.2.13 on 2026-06-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0004_demanditem_back_in_stock_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdemandstat',
            name='lost_value_30d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
