# Generated by Django 4.2.13 on 2026-06-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_item_pack_price_tax_item_sale_tax_pct'),
        ('demand', '0005_itemdemandstat_lost_value_30d'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanditem',
            name='substitute_for_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_as_substitute_in', to='catalog.item', verbose_name='بديل علمي لـ'),
        ),
    ]
