# Generated by Django 4.2.13 on 2026-06-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0006_demanditem_substitute_for_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanditem',
            name='price_is_manual',
            field=models.BooleanField(default=False, help_text='القيمة تقديرية أُدخلت يدوياً ولم تُجلب من ERP', verbose_name='سعر مُدخَل يدوياً'),
        ),
    ]
