# Generated by Django 4.2.13 on 2026-06-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0007_demanditem_price_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdemandstat',
            name='suggested_order_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
