# Generated by Django 4.2.13 on 2026-06-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0008_itemdemandstat_suggested_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandrecord',
            name='source',
            field=models.CharField(choices=[('walk_in', 'زيارة مباشرة'), ('phone', 'اتصال هاتفي'), ('whatsapp', 'واتساب'), ('delivery', 'توصيل'), ('online', 'أونلاين'), ('call_center', 'مركز الاتصالات'), ('self_service', 'تسجيل ذاتي (QR/رابط)'), ('other', 'أخرى')], default='walk_in', max_length=20),
        ),
    ]
