from . import T

MODULE = {
    'key': 'analytics', 'group': 'analytics', 'icon': '📈',
    'title': T('التحليلات والأهداف', 'Analytics & targets'),
    'summary': T(
        'تقارير المبيعات وأداء الموظفين والحجوزات والتحويلات من فواتير SOFTECH، والأهداف البيعية ومتابعة تحقيقها لكل فرع (لوحة «تارجت/تحقيق»)، '
        'وسيناريوهات توليد الأهداف بنماذج تنبؤ مختبرة على التاريخ، ومحرك التنبؤ بالمبيعات والموسمية، والتقارير السردية للمديرين، وإحالات الأطباء.',
        'Reports on sales, staff performance, reservations and transfers from SOFTECH invoices, sales targets and their attainment per branch (the "target/achievement" board), '
        'target-generation scenarios with forecasting models tested on history, the sales forecast engine and seasonality, narrative reports for directors, and doctor referrals.'),
}

_FILTERS = T('الفلاتر أعلى الصفحة (الفرع، نوع المستند، الموظف، القناة، نوع الدواء، التاريخ والساعة واليوم) تنطبق على كل التبويبات.',
             'The filters at the top (branch, document type, employee, channel, medicine type, date, hour and weekday) apply to every tab.')

SCREENS = [
    {
        'key': 'analytics.sales',
        'routes': ['/analytics/sales'],
        'title': T('لوحة المبيعات', 'Sales dashboard'),
        'summary': T('ذكاء المبيعات: صافي الإيراد والربح والهامش والخصومات والفواتير والعملاء والأصناف والمرتجعات، مع تحليل بالفرع والكاشير والقناة ونوع الدواء والصنف والوقت.',
                     'Sales intelligence: net revenue, profit, margin, discounts, invoices, customers, items and returns, analysed by branch, cashier, channel, medicine type, item and time.'),
        'audience': T('الإدارة والمشتريات والصيادلة والمشرفون والجودة.', 'Management, purchasing, pharmacists, supervisors and quality.'),
        'tabs': [
            {'key': 'overview', 'title': T('📊 نظرة عامة', '📊 Overview'), 'body': T('مؤشرات الفترة والاتجاه اليومي للإيرادات والإيرادات حسب التصنيف العلاجي.', 'Period KPIs, the daily revenue trend and revenue by therapeutic class.')},
            {'key': 'branches', 'title': T('🏪 الفروع', '🏪 Branches'), 'body': T('الإيراد والربح والهامش والخصم والفواتير والعملاء والأصناف لكل فرع.', 'Revenue, profit, margin, discount, invoices, customers and items per branch.')},
            {'key': 'users', 'title': T('👤 الكاشيرون', '👤 Cashiers'), 'body': T('نفس المؤشرات لكل كاشير/مستخدم SOFTECH.', 'The same KPIs per cashier/SOFTECH user.')},
            {'key': 'channels', 'title': T('🛒 قنوات البيع', '🛒 Sales channels'), 'body': T('نقدي، توصيل، تعاقد، تأمين… حصة كل قناة وربحيتها.', 'Cash, delivery, contract, insurance… each channel\'s share and profitability.')},
            {'key': 'medicine', 'title': T('💊 أنواع الأدوية', '💊 Medicine types'), 'body': T('المبيعات حسب نوع الدواء.', 'Sales by medicine type.')},
            {'key': 'items', 'title': T('📦 أفضل الأصناف', '📦 Top items'), 'body': T('الأصناف الأعلى إيراداً وربحاً مع المورد والمنتج والعائلة.', 'Top items by revenue and profit with supplier, producer and family.')},
            {'key': 'time', 'title': T('🕐 التوزيع الزمني', '🕐 Time distribution'), 'body': T('المبيعات بالساعة ويوم الأسبوع — لتنظيم الورديات.', 'Sales by hour and weekday — to plan shifts.')},
            {'key': 'contribution', 'title': T('🏦 مساهمة الفروع', '🏦 Branch contribution'), 'body': T('هامش المساهمة لكل فرع = إجمالي الربح − مصروفات الفرع.', 'Each branch\'s contribution margin = gross profit − branch expenses.')},
            {'key': 'churn', 'title': T('👻 العملاء الغائبون', '👻 Lapsed customers'), 'body': T('عملاء انقطعوا عن الشراء مع الخسارة السنوية المقدّرة — قائمة للتواصل.', 'Customers who stopped buying with the estimated annual loss — a contact list.')},
        ],
        'tips': [_FILTERS],
        'related': ['analytics.performance', 'finance.dashboard'],
        'updated': '2026-10-10',
    },
    {
        'key': 'analytics.performance',
        'routes': ['/analytics/performance'],
        'title': T('أداء الموظفين', 'Staff performance'),
        'summary': T('أداء كل موظف بيعي: الإيراد، الربح، الهامش، الخصم، الفواتير، متوسط الفاتورة، الأصناف لكل فاتورة، والعملاء الفريدون، مع المتصدرين.',
                     'Each salesperson\'s performance: revenue, profit, margin, discount, invoices, average invoice, items per invoice and unique customers, with the leaders.'),
        'audience': T('الإدارة والمشرفون.', 'Management and supervisors.'),
        'tabs': [
            {'key': 'employees', 'title': T('👤 الموظفون', '👤 Employees'), 'body': T('جدول الموظفين مرتباً بالإيراد.', 'The employee table sorted by revenue.')},
            {'key': 'branches', 'title': T('🏪 الفروع', '🏪 Branches'), 'body': T('عدد الموظفين وتوزيع الإيراد عليهم لكل فرع.', 'Number of employees and revenue distribution per branch.')},
            {'key': 'time', 'title': T('🕐 التوزيع الزمني', '🕐 Time distribution'), 'body': T('الإيراد بالساعة ويوم الأسبوع.', 'Revenue by hour and weekday.')},
        ],
        'tips': [_FILTERS],
        'related': ['incentives.programs', 'analytics.targets'],
        'updated': '2026-10-10',
    },
    {
        'key': 'analytics.reservations',
        'routes': ['/analytics/reservations'],
        'title': T('تحليلات الحجوزات', 'Reservation analytics'),
        'summary': T('إجمالي الحجوزات ومعدل التسليم ومتوسط وقت التسليم والطلب المفقود (ملغي/منتهي)، معدل التسليم بالفرع، أكثر 20 صنفاً محجوزاً، التحويل حسب القناة، والطلب المفقود حسب الصنف.',
                     'Total reservations, fulfilment rate, average time to fulfil and lost demand (cancelled/expired), fulfilment by branch, the top 20 reserved items, conversion by channel, and lost demand by item.'),
        'audience': T('الإدارة والمشرفون.', 'Management and supervisors.'),
        'related': ['reservations.board'],
        'updated': '2026-10-10',
    },
    {
        'key': 'analytics.transfers',
        'routes': ['/analytics/transfers'],
        'title': T('تحليلات طلبات التحويل', 'Transfer analytics'),
        'summary': T('أداء وسير عمل التحويلات بين الفروع لآخر 7/30/90 يوماً أو سنة.', 'Performance and flow of inter-branch transfers for the last 7/30/90 days or a year.'),
        'audience': T('الإدارة والمشرفون والمشتريات.', 'Management, supervisors and purchasing.'),
        'tabs': [
            {'key': 'analytics', 'title': T('📊 التحليلات', '📊 Analytics'), 'body': T('إجمالي الطلبات، نسب الإكمال والرفض، متوسط دورة الطلب ووقت الاستجابة، أكثر الأصناف تحويلاً، أنشط المسارات، ومعدل الرفض بالفرع المصدر.', 'Total requests, completion and rejection rates, average cycle and response time, most-transferred items, busiest routes, and rejection rate by supplying branch.')},
            {'key': 'discrepancy', 'title': T('⚠️ تقرير التباينات', '⚠️ Discrepancy report'), 'body': T('طلبات استُلمت كمياتها مختلفة عن المعتمد — راجعها مع الفرعين.', 'Requests received in quantities different from approved — review them with both branches.')},
        ],
        'related': ['transfers.list'],
        'updated': '2026-10-10',
    },
    {
        'key': 'analytics.forecasting',
        'routes': ['/forecasting'],
        'title': T('محرك التنبؤ بالمبيعات', 'Sales forecast engine'),
        'summary': T('تشغيل التنبؤ بالمبيعات للأصناف ومتابعة دقته ومؤشرات الموسمية.', 'Run the item sales forecast and follow its accuracy and seasonality indices.'),
        'audience': T('المشتريات والإدارة والصيادلة والجودة.', 'Purchasing, management, pharmacists and quality.'),
        'tabs': [
            {'key': 'runs', 'title': T('🏃 سجل التشغيلات', '🏃 Run history'), 'body': T('كل تشغيل: البداية والنهاية والأصناف المعالجة والحالة. «تشغيل التنبؤ الآن» لتشغيل جديد.', 'Each run: start, end, items processed and status. "Run forecast now" starts a new one.')},
            {'key': 'accuracy', 'title': T('🎯 دقة التنبؤ', '🎯 Accuracy'), 'body': T('التنبؤ مقابل الفعلي لكل صنف وفترة، ومتوسط الخطأ (MAPE) — الأقل أفضل.', 'Forecast vs actual per item and period, and the average error (MAPE) — lower is better.')},
            {'key': 'seasonality', 'title': T('📅 مؤشرات الموسمية', '📅 Seasonality'), 'body': T('مؤشر كل شهر لكل صنف أو تصنيف: أكبر من 1 = موسم مرتفع، أقل من 1 = موسم منخفض. «إعادة حساب الموسمية» بعد بيانات جديدة.', 'A monthly index per item or class: above 1 = high season, below 1 = low season. "Recalculate seasonality" after new data.')},
        ],
        'related': ['analytics.scenarios', 'purchasing.engine'],
        'updated': '2026-10-10',
    },
    {
        'key': 'analytics.targets',
        'routes': ['/targets'],
        'title': T('الأهداف البيعية', 'Sales targets'),
        'summary': T('تحديد هدف (للشبكة أو فرع أو مندوب بكوده في SOFTECH) بقيمة صافي المبيعات أو عدد الفواتير، ومتابعة التحقيق لحظياً: المحقق، الباقي، المتوقع حتى اليوم، وهل الأداء متقدّم أم متأخّر.',
                     'Set a target (for the network, a branch or a salesperson by SOFTECH code) as net sales or invoice count, and follow attainment live: achieved, remaining, expected by today, and whether performance is ahead or behind.'),
        'audience': T('الإدارة والمشرفون والمشتريات والصيادلة.', 'Management, supervisors, purchasing and pharmacists.'),
        'related': ['analytics.kpi_board', 'analytics.scenarios'],
        'updated': '2026-10-10',
    },
    {
        'key': 'analytics.kpi_board',
        'routes': ['/kpi-board'],
        'title': T('لوحة مؤشرات الفروع (تارجت/تحقيق)', 'Branch KPI board (target/achievement)'),
        'summary': T('مصفوفة فرع × مؤشر لشهر (مثل ملف Excel للتارجت والتحقيق): المحقق من فواتير SOFTECH (صافي بعد المرتجعات) مقابل التارجت من الأهداف البيعية، مع الوتيرة وإجمالي الفروع والكول سنتر.',
                     'A branch × KPI matrix for a month (like the target/achievement Excel): achieved from SOFTECH invoices (net after returns) vs target from sales targets, with pace, the branch total and the call center.'),
        'audience': T('الإدارة والمشرفون.', 'Management and supervisors.'),
        'tips': [T('لو «لا توجد بيانات محسوبة لهذا الشهر» يجب تشغيل حساب مؤشرات الشهر أولاً.', 'If "no computed data for this month", the month\'s KPI calculation must run first.')],
        'related': ['analytics.targets'],
        'updated': '2026-10-10',
    },
    {
        'key': 'analytics.scenarios',
        'routes': ['/forecast-scenarios'],
        'title': T('سيناريوهات التنبؤ بالأهداف', 'Target forecast scenarios'),
        'summary': T('توليد الأهداف بالعوامل بدل التخمين: أنشئ سيناريو لشهر، اضبط العوامل (النمو، التضخم، رفع العروض…)، «احسب التنبؤ» بنموذجين (A: نمو الهدف، B: مزيج مرجّح) ومتوسطهما، راجع لكل فرع/مندوب/فئة، ثم «اعتماد الأهداف» فتظهر في لوحة المؤشرات. «اختبار رجعي» يقارن دقة النموذجين على الأشهر السابقة ويختار الأفضل.',
                     'Generate targets from factors instead of guesses: create a scenario for a month, tune factors (growth, inflation, promo uplift…), "Calculate forecast" with two models (A: target growth, B: weighted blend) and their average, review by branch/salesperson/category, then "Commit targets" so they show on the KPI board. A "backtest" compares both models on past months and picks the better one.'),
        'audience': T('الإدارة والمشرفون والمشتريات.', 'Management, supervisors and purchasing.'),
        'related': ['analytics.kpi_board', 'incentives.programs'],
        'updated': '2026-10-10',
    },
    {
        'key': 'analytics.insights',
        'routes': ['/insights'],
        'title': T('التقارير السردية', 'Narrative reports'),
        'summary': T('تقارير مكتوبة بلغة واضحة بالعربي والإنجليزي (يومي، أسبوعي، حتى تاريخه، شهري) تلخص المبيعات والخصومات والمقارنات والإنجازات والتنبيهات (حرج/تنبيه/معلومة) — للمديرين غير التقنيين، وتُنسخ لواتساب.',
                     'Plain-language reports in Arabic and English (daily, weekly, month-to-date, monthly) summarising sales, discounts, comparisons, achievements and alerts (critical/warning/info) — for non-technical directors, copyable to WhatsApp.'),
        'audience': T('الإدارة والمشرفون والجودة.', 'Management, supervisors and quality.'),
        'tabs': [
            {'key': 'reports', 'title': T('التقارير', 'Reports'), 'body': T('اختر نوع التقرير والفترة ← «توليد» ← اقرأ بالعربي أو الإنجليزي وانسخه.', 'Choose the report type and period → "Generate" → read in Arabic or English and copy it.')},
            {'key': 'rules', 'title': T('القواعد والحدود', 'Rules & thresholds'), 'body': T('الحدود التي تولّد التنبيهات: انخفاض مبيعات الفرع بنسبة، حدود الخصم لكل قناة، الفاتورة النقدية الكبيرة، المرتجعات، تراجع الهامش، فروق الجرد، الراكد، تغيّر المشتريات… اضبطها حسب سياسة الإدارة.', 'The thresholds that trigger alerts: branch sales drop %, discount limits per channel, large cash invoice, returns, margin drop, count variances, dead stock, purchase changes… tune them to management policy.')},
        ],
        'updated': '2026-10-10',
    },
    {
        'key': 'analytics.referral_stats',
        'routes': ['/referral-stats'],
        'title': T('إحصاءات إحالات الأطباء', 'Doctor referral statistics'),
        'summary': T('أداء الأطباء المُحيلين من مبيعات نقطة البيع المُرحَّلة: عدد الطلبات، صافي القيمة، عدد المرضى، وآخر إحالة لكل طبيب في الفترة.', 'Referring doctors\' performance from posted POS sales: orders, net value, patients and last referral per doctor in the period.'),
        'audience': T('الإدارة والمشرفون والصيادلة والجودة.', 'Management, supervisors, pharmacists and quality.'),
        'related': ['loyalty.referral', 'pos.order'],
        'updated': '2026-10-10',
    },
]
