from . import T

MODULE = {
    'key': 'catalog', 'group': 'inventory', 'icon': '💊',
    'title': T('المنتجات والمخزون', 'Products & stock'),
    'summary': T(
        'كتالوج كل الأصناف (أكثر من 37 ألف صنف) المتزامن من SOFTECH مع السعر والتوافر بالفروع، وملف شامل لكل صنف، '
        'ومحتوى تسويقي وصور، ومؤشرات المخزون (نواقص، فائض، راكد، رأس المال)، وذكاء الكتالوج (مجموعات المتغيرات، الباقات، ما يُشترى معاً، إثراء البيانات بالذكاء الاصطناعي). '
        'تنبيه: الاسم العلمي في SOFTECH غير موثوق لكثير من الأصناف — لا تعتمد عليه وحده في البدائل.',
        'The catalog of all items (over 37 thousand) synced from SOFTECH with price and availability by branch, a full file per item, '
        'marketing content and images, stock indicators (shortage, overstock, dead stock, capital), and catalog intelligence (variant groups, bundles, '
        'frequently bought together, AI data enrichment). Note: the SOFTECH scientific name is unreliable for many items — never rely on it alone for alternatives.'),
}

SCREENS = [
    {
        'key': 'catalog.products',
        'routes': ['/products'],
        'title': T('كتالوج المنتجات', 'Product catalog'),
        'summary': T('بحث في كل الأصناف بالاسم أو الكود أو الباركود أو المادة الفعالة (أو بكاميرا الموبايل)، مع فلاتر (التوافر، التصنيف العلاجي، الشكل، التأمين، ثلاجة، مزمن، سريع التداول، وصفة)، ومقارنة حتى 3 أصناف، وتصدير قائمة الأسعار.',
                     'Search all items by name, code, barcode or active ingredient (or the phone camera), with filters (availability, therapeutic class, form, insurance, fridge, chronic, fast-moving, prescription), compare up to 3 items, and export the price list.'),
        'audience': T('كل الموظفين.', 'Every employee.'),
        'tabs': [
            {'key': 'catalog', 'title': T('الكتالوج', 'Catalog'), 'body': T('كل الأصناف مع البحث والفلاتر والترتيب (الأكثر شهرة، السعر، أبجدي…).', 'All items with search, filters and sorting (most popular, price, A–Z…).')},
            {'key': 'fmi', 'title': T('سريع التداول', 'Fast moving'), 'body': T('الأصناف سريعة الحركة (FMI) — يجب ألا تنقص أبداً.', 'Fast-moving items (FMI) — they must never run out.')},
            {'key': 'low_stock', 'title': T('مخزون منخفض', 'Low stock'), 'body': T('أصناف قلّ مخزونها — راجعها للتحويل أو الطلب.', 'Items running low — review them for a transfer or an order.')},
            {'key': 'bundles', 'title': T('الباقات', 'Bundles'), 'body': T('الباقات النشطة (مجموعة أصناف بخصم) المُعدّة في ذكاء الكتالوج.', 'Active bundles (a set of items at a discount) set up in catalog intelligence.')},
            {'key': 'recent', 'title': T('آخر تحديث', 'Recently updated'), 'body': T('أحدث الأصناف تحديثاً من SOFTECH (أسعار أو بيانات جديدة).', 'The items most recently updated from SOFTECH (new prices or data).')},
        ],
        'steps': [
            T('ابحث أو امسح الباركود، واضغط الصنف لفتح صفحته.', 'Search or scan, and click an item to open its page.'),
            T('«إضافة للمقارنة» على حتى 3 أصناف لمقارنة السعر والهامش والتصنيف والمورد.', '"Add to compare" on up to 3 items to compare price, margin, class and supplier.'),
            T('«تصدير Excel» يصدّر قائمة الأسعار للنتائج الحالية.', '"Export Excel" exports the price list for the current results.'),
        ],
        'tips': [T('الهامش = سعر العبوة − سعر التكلفة؛ يظهر حسب صلاحيتك.', 'Margin = pack price − cost; shown according to your permissions.')],
        'related': ['catalog.product', 'catalog.inventory', 'catalog.mobile_items'],
        'tour': [
            {'target': 'catalog-products-search', 'text': T('ابحث بالاسم أو الكود أو الباركود أو المادة الفعالة.',
                                              'Search by name, code, barcode or active ingredient.')},
            {'target': 'catalog-products-scan', 'text': T('📷 امسح الباركود بالكاميرا.',
                                              '📷 Scan a barcode with the camera.')},
            {'target': 'catalog-products-filters', 'text': T('«⚙ فلتر» للتصنيف والتوافر.',
                                              '"⚙ Filter" by category and availability.')},
            {'target': 'catalog-products-sort', 'text': T('الترتيب.',
                                              'Sort order.')},
            {'target': 'catalog-products-tabs', 'text': T('التبويبات: الكتالوج، سريع التداول، مخزون منخفض…',
                                              'Tabs: catalog, fast movers, low stock…')},
            {'target': 'catalog-products-results', 'text': T('النتائج — افتح أي صنف لتفاصيله.',
                                              'The results — open an item for its details.')},
        ],
        'updated': '2026-10-10',
    },
    {
        'key': 'catalog.product',
        'routes': ['/products/:id'],
        'title': T('صفحة المنتج', 'Product page'),
        'summary': T('ملف الصنف للعرض والبيع: الصور، السعر، الوصف، التعليمات، الخصائص، التوافر بالفروع (متاح / محدود / غير متاح فقط بدون كميات)، البدائل والمرتبطات، والطلب المفتوح عليه.',
                     'The item file for viewing and selling: images, price, description, instructions, attributes, availability by branch (available / limited / unavailable only, no quantities), alternatives and related items, and open demand.'),
        'audience': T('كل الموظفين.', 'Every employee.'),
        'tabs': [
            {'key': 'info', 'title': T('نظرة عامة', 'Overview'), 'body': T('الوصف، الفوائد، معلومات سريعة (الاسم العلمي، المادة الفعالة، الشركة، التركيز، العبوة)، والأسئلة الشائعة.', 'Description, benefits, quick facts (scientific name, active ingredient, company, strength, pack) and FAQ.')},
            {'key': 'instructions', 'title': T('التعليمات والتخزين', 'Instructions & storage'), 'body': T('طريقة الاستخدام، شروط ودرجة حرارة التخزين، مدة الصلاحية، موانع الاستخدام والتحذيرات.', 'How to use, storage conditions and temperature, shelf life, contraindications and warnings.')},
            {'key': 'attributes', 'title': T('الخصائص', 'Attributes'), 'body': T('التصنيف، المورد، البلد، التركيز، النكهة، اللون، الحجم، الباركود، كود SOFTECH، والوصفة الطبية.', 'Class, supplier, country, strength, flavour, colour, size, barcode, SOFTECH code and prescription status.')},
            {'key': 'availability', 'title': T('التوافر بالفروع', 'Branch availability'), 'body': T('حالة التوافر في كل فرع، تُحدَّث تلقائياً من SOFTECH.', 'Availability at each branch, updated automatically from SOFTECH.')},
            {'key': 'similar', 'title': T('منتجات مشابهة', 'Similar products'), 'body': T('أصناف من نفس التصنيف.', 'Items in the same class.')},
            {'key': 'related', 'title': T('منتجات مرتبطة', 'Related products'), 'body': T('موصى به، يُشترى معاً، بديل، مكمل، حزمة البداية.', 'Recommended, bought together, alternative, complementary, starter pack.')},
            {'key': 'demand', 'title': T('الطلب المفتوح', 'Open demand'), 'body': T('طلبات العملاء المفتوحة والنواقص المسجّلة على هذا الصنف.', 'Open customer requests and recorded shortages for this item.')},
        ],
        'steps': [T('«مشاركة واتساب» ينسخ وصفاً جاهزاً للصنف لإرساله للعميل. «ملف الصنف الشامل» يفتح ذكاء الصنف.', '"Share on WhatsApp" copies a ready description to send to the customer. "Full item file" opens item intelligence.')],
        'related': ['catalog.products', 'catalog.intel', 'catalog.content_admin'],
        'tour': [
            {'target': 'catalog-product-summary', 'text': T('ملخص الصنف والتوافر.',
                                              'The item summary and availability.')},
            {'target': 'catalog-product-price', 'text': T('سعر العبوة والوحدة.',
                                              'Pack and unit price.')},
            {'target': 'catalog-product-tabs', 'text': T('التبويبات: نظرة عامة، التعليمات والتخزين، التوافر بالفروع…',
                                              'Tabs: overview, instructions and storage, availability by branch…')},
            {'target': 'catalog-product-content', 'text': T('محتوى التبويب.',
                                              'The tab\'s content.')},
            {'target': 'catalog-product-share', 'text': T('«📤 مشاركة واتساب» لبيانات الصنف.',
                                              '"📤 Share on WhatsApp" for the item\'s details.')},
            {'target': 'catalog-product-intel', 'text': T('«🔬 ملف الصنف الشامل».',
                                              '"🔬 Full item profile".')},
        ],
        'updated': '2026-10-10',
    },
    {
        'key': 'catalog.content_admin',
        'routes': ['/products/:id/admin'],
        'title': T('إدارة محتوى المنتج', 'Product content admin'),
        'summary': T('تحرير ما يظهر عن الصنف: الصور والوسائط، النصوص، الخصائص الدوائية، وبيانات SEO.', 'Edit what is shown about the item: images and media, texts, pharmaceutical attributes and SEO data.'),
        'audience': T('مسؤولو المحتوى والمدير.', 'Content managers and admins.'),
        'tabs': [
            {'key': 'media', 'title': T('🖼 الصور والوسائط', '🖼 Images & media'), 'body': T('ارفع صوراً (JPG/PNG/WebP حتى 10MB) أو فيديو أو نشرة، اعتمدها، اجعل واحدة «رئيسية»، واكتب النص البديل.', 'Upload images (JPG/PNG/WebP up to 10MB), video or leaflets, approve them, set one as "main", and write alt text.')},
            {'key': 'content', 'title': T('📝 المحتوى والوصف', '📝 Content'), 'body': T('الاسم التجاري، الوصف المختصر (يظهر في البطاقة وواتساب) والتفصيلي، التعليمات، الموانع، الفوائد، الكلمات المفتاحية، والأسئلة الشائعة، مع معاينة رسالة واتساب.', 'Brand name, short description (shown on the card and WhatsApp) and full description, instructions, contraindications, benefits, keywords and FAQ, with a WhatsApp preview.')},
            {'key': 'attributes', 'title': T('⚗️ الخصائص الدوائية', '⚗️ Pharmaceutical attributes'), 'body': T('التركيز، العبوة، العدد، درجة الحرارة، مدة الصلاحية، الوصفة الطبية، والتحذيرات.', 'Strength, pack, count, temperature, shelf life, prescription and warnings.')},
            {'key': 'seo', 'title': T('🔍 SEO والروابط', '🔍 SEO & links'), 'body': T('رابط المنتج (Slug) وعناوين وأوصاف الصفحة بالعربي والإنجليزي ومعاينة نتيجة جوجل. تغيير الرابط يكسر الروابط القديمة.', 'The product slug, page titles and descriptions in Arabic and English, and a Google result preview. Changing the slug breaks old links.')},
        ],
        'steps': [T('عدّل ثم «حفظ التغييرات» — الشاشة تنبهك لو هناك تغييرات غير محفوظة.', 'Edit then "Save changes" — the screen warns you of unsaved changes.')],
        'related': ['catalog.product'],
        'updated': '2026-10-10',
    },
    {
        'key': 'catalog.intel',
        'routes': ['/products/:id/intel'],
        'title': T('ذكاء الصنف (الملف الشامل)', 'Item intelligence (full file)'),
        'summary': T('كل بيانات الصنف من كل الموديولات في مكان واحد: بيانات SOFTECH، الإثراء، المحتوى، المواد الفعالة وتصنيف المزمن، مؤشرات الطلب، تاريخ الشراء من الموردين، وما يُشترى معه.',
                     'All the item\'s data from every module in one place: SOFTECH data, enrichment, content, active ingredients and chronic tag, demand indicators, purchase history from suppliers, and what is bought with it.'),
        'audience': T('الصيادلة والمشتريات والمدير.', 'Pharmacists, purchasing and admins.'),
        'tabs': [
            {'key': 'softech', 'title': T('🔗 بيانات SOFTECH', '🔗 SOFTECH data'), 'body': T('حقول الصنف كما هي في SOFTECH (للقراءة فقط).', 'The item fields as in SOFTECH (read-only).')},
            {'key': 'enrichment', 'title': T('🧬 الإثراء والبيانات', '🧬 Enrichment'), 'body': T('بيانات سريرية وتصنيفية مكمّلة (قابلة للتعديل) مع نسبة اكتمال البيانات وحالة النشر.', 'Supplementary clinical and classification data (editable) with a completeness score and publish status.')},
            {'key': 'content', 'title': T('📝 المحتوى والخصائص', '📝 Content & attributes'), 'body': T('نفس محتوى وخصائص صفحة الإدارة، للتعديل السريع.', 'The same content and attributes as the admin page, for quick edits.')},
            {'key': 'clinical', 'title': T('💊 المواد الفعّالة', '💊 Active ingredients'), 'body': T('ربط المواد الفعّالة بالصنف وتصنيفه كمزمن — هذا مصدر البدائل الموثوق وليس الاسم العلمي.', 'Link active ingredients to the item and tag it chronic — this is the reliable source for alternatives, not the scientific name.')},
            {'key': 'purchasing', 'title': T('📊 مؤشرات الطلب', '📊 Demand indicators'), 'body': T('فئة ABC، معدلات الطلب، والمبيعات الضائعة (للقراءة).', 'ABC class, demand rates and lost sales (read-only).')},
            {'key': 'purchase_history', 'title': T('🧾 تاريخ الشراء', '🧾 Purchase history'), 'body': T('متوسط وأقل وأعلى سعر شراء لكل مورد وأكواد الموردين.', 'Average, min and max purchase price per supplier and supplier item codes.')},
            {'key': 'fbt', 'title': T('🔀 يُشترى معاً', '🔀 Bought together'), 'body': T('الأصناف التي تُشترى عادةً مع هذا الصنف.', 'Items usually bought with this one.')},
        ],
        'related': ['catalog.product', 'chronic.composition'],
        'updated': '2026-10-10',
    },
    {
        'key': 'catalog.inventory',
        'routes': ['/inventory'],
        'title': T('لوحة المخزون', 'Inventory dashboard'),
        'summary': T('صحة المخزون من محرك الطلب: النواقص، الفائض، الراكد، والتوزيع بالفرع وبنوع الدواء، ورأس المال المحبوس. فلترة بالفرع ونوع الدواء وفئة ABC.',
                     'Stock health from the demand engine: shortages, overstock, dead stock, by branch and by medicine type, and tied-up capital. Filter by branch, medicine type and ABC class.'),
        'audience': T('المشتريات والصيادلة والمشرفون والجودة.', 'Purchasing, pharmacists, supervisors and quality.'),
        'tabs': [
            {'key': 'shortages', 'title': T('⚠️ النواقص', '⚠️ Shortages'), 'body': T('أصناف تحت حد الأمان مرتبة بالأولوية: الفجوة، المخزون، الأمان، متوسط الشهر، التغطية.', 'Items below safety stock, sorted by priority: gap, stock, safety, monthly average, coverage.')},
            {'key': 'overstock', 'title': T('📦 الفائض', '📦 Overstock'), 'body': T('أصناف أكثر من الحاجة مرتبة بقيمة الفائض — مرشحة للتحويل لفروع تحتاجها.', 'Items above need, sorted by excess value — candidates to transfer to branches that need them.')},
            {'key': 'dead_stock', 'title': T('💤 الراكد', '💤 Dead stock'), 'body': T('أصناف بلا مبيعات ولها مخزون — رأس مال راكد؛ راجعها للتحويل أو التخفيض أو الإيقاف.', 'Items with stock and no sales — idle capital; review for transfer, discount or delisting.')},
            {'key': 'by_branch', 'title': T('🏪 بالفرع', '🏪 By branch'), 'body': T('عدد وقيمة النواقص والفائض لكل فرع.', 'Count and value of shortages and overstock per branch.')},
            {'key': 'by_medicine', 'title': T('💊 بنوع الدواء', '💊 By medicine type'), 'body': T('النواقص والفائض والتغطية لكل نوع دواء.', 'Shortages, overstock and coverage per medicine type.')},
            {'key': 'investment', 'title': T('💰 رأس المال', '💰 Capital'), 'body': T('إجمالي رأس المال في المخزون، الراكد ونسبته، المرشحون للتصفية، والتوزيع حسب فئة ABC والفرع. يتطلب تشغيل محرك الطلب أولاً.', 'Total capital in stock, dead capital and its share, liquidation candidates, and distribution by ABC class and branch. Requires the demand engine to have run.')},
        ],
        'tips': [T('فئة A = الأصناف الأهم قيمةً؛ أي نقص فيها أولوية قصوى.', 'Class A = the most valuable items; any shortage there is top priority.')],
        'related': ['purchasing.engine', 'batches.main', 'transfers.new'],
        'updated': '2026-10-10',
    },
    {
        'key': 'catalog.intelligence',
        'routes': ['/catalog-intelligence'],
        'title': T('ذكاء الكتالوج', 'Catalog intelligence'),
        'summary': T('تنظيم الكتالوج وتحسين جودة بياناته.', 'Organise the catalog and improve its data quality.'),
        'audience': T('الصيادلة والمشتريات والمدير.', 'Pharmacists, purchasing and admins.'),
        'tabs': [
            {'key': 'variants', 'title': T('🔗 مجموعات المتغيرات', '🔗 Variant groups'), 'body': T('تجميع الأصناف التي هي نفس المنتج بأشكال أو أحجام مختلفة (مثلاً أقراص وشراب) في مجموعة واحدة.', 'Group items that are the same product in different forms or sizes (e.g. tablets and syrup).')},
            {'key': 'bundles', 'title': T('📦 الباقات', '📦 Bundles'), 'body': T('إنشاء باقات أصناف مع خصم اختياري (نسبة أو مبلغ ثابت) وإظهارها أو إخفاؤها.', 'Create item bundles with an optional discount (percent or fixed) and show or hide them.')},
            {'key': 'fbt', 'title': T('🧩 يُشترى معه عادةً', '🧩 Frequently bought together'), 'body': T('أزواج الأصناف التي تُشترى معاً بالتكرار والثقة (للقراءة؛ يحسبها محرك التوصيات).', 'Item pairs bought together with frequency and confidence (read-only; computed by the recommendation engine).')},
            {'key': 'enrichment', 'title': T('🤖 إثراء الكتالوج', '🤖 Catalog enrichment'), 'body': T('تقرير جودة الكتالوج (مكتمل/ناقص/فارغ)، ودفعات إثراء بالذكاء الاصطناعي لنطاق (كل الكتالوج، تصنيف، مورد، أصناف) مع حد نشر تلقائي، ومراجعة الاقتراحات المعلّقة.', 'Catalog quality report (complete/partial/empty), and AI enrichment batches for a scope (whole catalog, class, supplier, items) with an auto-publish threshold, and review of pending suggestions.')},
        ],
        'tips': [T('اقتراحات الذكاء الاصطناعي تُراجع قبل النشر؛ لا تعتمد البدائل الدوائية تلقائياً.', 'AI suggestions are reviewed before publishing; drug alternatives are never applied automatically.')],
        'related': ['catalog.images', 'catalog.recommendations'],
        'updated': '2026-10-10',
    },
    {
        'key': 'catalog.images',
        'routes': ['/image-enrichment'],
        'title': T('صور المنتجات', 'Product images'),
        'summary': T('البحث الآلي عن صور للأصناف ومراجعتها: النظام يجد صوراً مرشحة ويقيّم جودتها وتطابقها ووجود علامة مائية؛ ما فوق حد الثقة يُعتمد تلقائياً والباقي يُراجع يدوياً.',
                     'Automatic image search for items and its review: the system finds candidate images and scores quality, match and watermarks; above the confidence threshold they are auto-approved, the rest are reviewed manually.'),
        'audience': T('مسؤولو المحتوى والصيادلة والمشتريات.', 'Content managers, pharmacists and purchasing.'),
        'tabs': [
            {'key': 'dashboard', 'title': T('📊 لوحة التحكم', '📊 Dashboard'), 'body': T('نسبة التغطية بالصور، ما ينتظر المراجعة، والمهام الجارية والفاشلة.', 'Image coverage, pending review, and running and failed jobs.')},
            {'key': 'review', 'title': T('👁️ قائمة المراجعة', '👁️ Review queue'), 'body': T('قبول أو رفض الصور المرشحة. انتبه لمؤشر العلامة المائية — الصورة المشبوهة راجعها يدوياً.', 'Accept or reject candidate images. Watch the watermark indicator — review suspicious images manually.')},
            {'key': 'batch', 'title': T('🚀 إطلاق دفعة', '🚀 Launch batch'), 'body': T('بحث لدفعة أصناف بفلاتر (بلا صور، الأعلى مبيعاً، فئة، شركة، ABC) مع حد الموافقة التلقائية وتقدير التكلفة.', 'Search for a batch of items with filters (no image, top sellers, class, company, ABC) with an auto-approval threshold and a cost estimate.')},
            {'key': 'revise', 'title': T('🔄 مراجعة شاملة', '🔄 Revise all'), 'body': T('إعادة البحث حتى للأصناف التي لها صور، لاستبدال الصور الرديئة أو ذات العلامات المائية.', 'Search again even for items that have images, to replace poor or watermarked ones.')},
            {'key': 'history', 'title': T('📋 السجل', '📋 History'), 'body': T('سجل كل المهام.', 'The log of all jobs.')},
            {'key': 'gallery', 'title': T('🖼️ معرض المنتج', '🖼️ Product gallery'), 'body': T('صور صنف معيّن وإدارتها.', 'A specific item\'s images and their management.')},
            {'key': 'insights', 'title': T('🧠 نتائج التعلم', '🧠 Learning results'), 'body': T('ما تعلّمه النظام من قراراتك لتحسين الاختيار التلقائي.', 'What the system learned from your decisions to improve automatic selection.')},
        ],
        'related': ['catalog.content_admin'],
        'updated': '2026-10-10',
    },
    {
        'key': 'catalog.recommendations',
        'routes': ['/recommendations'],
        'title': T('التوصيات الذكية', 'Smart recommendations'),
        'summary': T('محرك التوصيات: يحلل الفواتير ليجد الأصناف التي تُشترى معاً، ويقترح لكل عميل أصنافاً حسب سلوكه، مع فلتر سلامة يستبعد ما يتعارض مع أدويته المزمنة.',
                     'The recommendation engine: analyses invoices to find items bought together, and suggests items per customer by their behaviour, with a safety filter that excludes anything conflicting with their chronic medicines.'),
        'audience': T('الصيادلة والكول سنتر والمشتريات.', 'Pharmacists, call center and purchasing.'),
        'tabs': [
            {'key': 'fbt', 'title': T('🔗 اقترانات الأصناف', '🔗 Item pairs'), 'body': T('الأزواج مع الدعم والثقة والرفع (Lift) — الرفع الأعلى من 1 يعني ارتباطاً حقيقياً.', 'Pairs with support, confidence and lift — lift above 1 means a real association.')},
            {'key': 'customer', 'title': T('👤 توصيات العملاء', '👤 Customer recommendations'), 'body': T('ابحث عن عميل لترى توصياته الشخصية.', 'Search a customer to see their personal recommendations.')},
            {'key': 'history', 'title': T('🕓 سجل التشغيل', '🕓 Run history'), 'body': T('مرات تشغيل المحرك ونتائجها.', 'Engine runs and their results.')},
        ],
        'steps': [{'text': T('«تشغيل المحرك» مع فترة الرصد والحد الأدنى للدعم والثقة.', '"Run engine" with the look-back period and minimum support and confidence.'), 'roles': ['admin', 'purchasing']}],
        'related': ['catalog.intelligence'],
        'updated': '2026-10-10',
    },
    {
        'key': 'catalog.vision',
        'routes': ['/vision-corpus'],
        'title': T('المحرك البصري (بيانات التعلّم)', 'Vision engine (training data)'),
        'summary': T('متابعة نمو قاعدة بيانات التعلّم المملوكة لنا: كل صورة روشتة أو صوت أو فاتورة مورّد يُقرأ ثم يُؤكد بشرياً يصبح مثال تدريب للمحرك الداخلي للقراءة الآلية. تعرض الحجم، نسبة التصنيف، المصادر، ودقة المحركات.',
                     'Follow the growth of our own training dataset: every prescription photo, voice note or supplier invoice that is read then confirmed by a person becomes a training example for the in-house reading engine. Shows size, label rate, sources and engine accuracy.'),
        'audience': T('الإدارة والمشرفون.', 'Management and supervisors.'),
        'tips': [T('كلما أكّدت قراءة صحيحة في نقطة البيع أو النواقص أو الفواتير زادت دقة المحرك الداخلي.', 'Every correct reading you confirm in the POS, shortages or invoices improves the in-house engine.')],
        'updated': '2026-10-10',
    },
    {
        'key': 'catalog.mobile_items',
        'routes': ['/m/items'],
        'title': T('بحث صنف ومخزون (موبايل)', 'Item & stock lookup (mobile)'),
        'summary': T('من بين الأرفف: امسح أو ابحث عن صنف لترى سعره ومخزونه الحي في كل الفروع وإجمالي الشبكة.', 'In the aisle: scan or search an item to see its price and live stock in every branch and the network total.'),
        'audience': T('الصيادلة والمندوبون.', 'Pharmacists and salespeople.'),
        'related': ['catalog.products'],
        'updated': '2026-10-10',
    },
]
