"""
Onboarding — what each role should learn first, and a short quiz per module.

ROLE_PATHS:  role → ordered screen keys (first week first). A role's checklist and its
             printed manual are built from this list. Every key must exist (test_help).
QUIZZES:     module key → questions. `answer` is the index of the right option; the
             server grades — answers and explanations are only sent back after submitting.
PASS_PERCENT: score needed to pass a module quiz.
"""
from . import T

PASS_PERCENT = 80

_START = ['general.help_center', 'general.dashboard', 'general.notifications',
          'general.announcements', 'general.me', 'general.security']
_SELF = ['hr.requests', 'hr.attendance', 'incentives.mine']

ROLE_PATHS = {
    'pharmacist': _START + [
        'pos.order', 'pos.mobile', 'reservations.board', 'reservations.new', 'reservations.detail',
        'demand.list', 'demand.detail', 'customers.list', 'customers.detail', 'catalog.products',
        'catalog.product', 'catalog.mobile_items', 'transfers.list', 'transfers.new', 'transfers.detail',
        'transfers.transits', 'followups.tasks', 'vouchers.main', 'loyalty.branch', 'shortage.list',
        'shortage.mobile', 'stockcount.sessions', 'stockcount.mobile', 'batches.main',
        'delivery.dashboard', 'tasks.list', 'pos.exceptions', 'chronic.ingredient_search',
        'pricing.approvals', 'replacement.cases', 'hr.approvals',
    ] + _SELF,
    'salesperson': _START + [
        'pos.order', 'pos.mobile', 'reservations.board', 'reservations.new', 'reservations.mobile_list',
        'demand.mobile_new', 'demand.list', 'customers.mobile', 'catalog.mobile_items',
        'transfers.mobile_list', 'vouchers.mobile', 'shortage.mobile', 'followups.tasks',
        'loyalty.program',
    ] + _SELF,
    'call_center': _START + [
        'callcenter.operator', 'omni.inbox', 'omni.whatsapp_inbox', 'callcenter.pbx', 'callcenter.cases',
        'customers.list', 'customers.detail', 'reservations.board', 'reservations.new',
        'reservations.detail', 'demand.list', 'demand.detail', 'demand.recovery', 'followups.tasks',
        'followups.reminders', 'pos.order', 'delivery.dashboard', 'delivery.dispatch', 'vouchers.main',
        'loyalty.program', 'loyalty.referral', 'chronic.ingredient_search', 'omni.campaigns',
        'customers.merge',
    ] + _SELF,
    'purchasing': _START + [
        'purchasing.engine', 'purchasing.supply', 'shortage.list', 'shortage.market', 'shortage.phantom',
        'purchasing.cash', 'catalog.inventory', 'batches.main', 'transfers.list', 'invoices.main',
        'pricing.approvals', 'pricing.alignment', 'purchasing.overview', 'purchasing.history',
        'purchasing.suppliers', 'purchasing.foc', 'purchasing.margins', 'purchasing.optimization',
        'purchasing.segments', 'purchasing.categories', 'finance.reconciliation', 'pos.offers',
        'incentives.programs', 'insurance.claims',
    ] + _SELF,
    'delivery': [
        'general.help_center', 'general.notifications', 'general.announcements',
        'delivery.driver',
    ] + _SELF,
    'viewer': _START + [
        'reservations.board', 'demand.list', 'transfers.list', 'customers.list',
        'catalog.products', 'analytics.sales',
    ],
    'supervisor': _START + [
        'hr.approvals', 'hr.mobile_approvals', 'reservations.board', 'demand.list', 'demand.dashboard',
        'transfers.list', 'callcenter.cases', 'callcenter.analytics', 'omni.inbox', 'omni.wallboard',
        'omni.automations', 'delivery.dashboard', 'pos.exceptions', 'tasks.list', 'tasks.dashboard',
        'tasks.schedules', 'analytics.kpi_board', 'analytics.targets', 'analytics.performance',
        'customers.merge', 'pricing.approvals', 'admin.users',
    ] + _SELF,
    'quality_manager': _START + [
        'hr.qa', 'admin.audit', 'callcenter.analytics', 'omni.analytics', 'batches.main',
        'stockcount.sessions', 'transfers.transits', 'demand.dashboard', 'analytics.sales',
        'analytics.insights', 'incentives.programs', 'hr.approvals',
    ] + _SELF,
    'admin': _START + [
        'admin.users', 'admin.permissions', 'admin.erp_permissions', 'admin.settings', 'admin.sync',
        'admin.audit', 'hr.approvals', 'pricing.approvals', 'pos.order', 'pos.exceptions',
        'reservations.board', 'transfers.list', 'purchasing.engine', 'analytics.sales',
        'analytics.kpi_board', 'finance.dashboard', 'omni.accounts',
    ],
}


def Q(q, options, answer, explain):
    return {'q': q, 'options': options, 'answer': answer, 'explain': explain}


QUIZZES = {
    'general': [
        Q(T('كيف تفتح شرح الشاشة التي تعمل عليها؟', 'How do you open the help for the screen you are on?'),
          [T('من القائمة الجانبية فقط', 'Only from the side menu'), T('زر «؟ مساعدة» أو مفتاح F1', 'The "? Help" button or the F1 key'), T('بإعادة تحميل الصفحة', 'By reloading the page')],
          1, T('زر «؟ مساعدة» أعلى الشاشة أو F1 يفتح شرح الشاشة والتبويب الحاليين.', 'The "? Help" button at the top or F1 opens the help for the current screen and tab.')),
        Q(T('ماذا تعني النقطة الصفراء على زر المساعدة؟', 'What does the yellow dot on the help button mean?'),
          [T('يوجد خطأ في الشاشة', 'The screen has an error'), T('شرح هذه الشاشة تغيّر منذ آخر قراءة', 'This screen\'s help changed since you last read it'), T('لديك إشعار جديد', 'You have a new notification')],
          1, T('النقطة تعني أن الشرح تحدّث (ميزة جديدة أو تعديل).', 'The dot means the help was updated (a new feature or a change).')),
        Q(T('إعلان داخلي هام وصلك، ما المطلوب؟', 'You received an important internal announcement. What is required?'),
          [T('قراءته ثم «تأكيد القراءة»', 'Read it then press "Acknowledge"'), T('حذفه', 'Delete it'), T('لا شيء', 'Nothing')],
          0, T('تأكيد القراءة يُسجَّل باسمك والإدارة تتابع من قرأ.', 'Acknowledging is recorded under your name and management tracks who read.')),
    ],
    'pos': [
        Q(T('ما الذي يفعله زر F9 في نقطة البيع؟', 'What does F9 do on the POS?'),
          [T('يرسل الأمر للكاشير', 'Sends the order to the cashier'), T('معاينة الإرسال بدون كتابة أي شيء في SOFTECH', 'Previews the send without writing anything to SOFTECH'), T('يحذف السطر', 'Deletes the line')],
          1, T('F9 معاينة تجريبية؛ F10 هو الإرسال الفعلي للكاشير.', 'F9 is a dry-run preview; F10 is the live send to the cashier.')),
        Q(T('انقطع الاتصال أثناء الإرسال. ماذا يحدث للأمر؟', 'The connection dropped while sending. What happens to the order?'),
          [T('يُرسل مرتين عند العودة', 'It is sent twice when back'), T('يدخل الطابور ويُرسل مرة واحدة عند عودة الاتصال', 'It joins the queue and is sent once when the connection returns'), T('يضيع ويجب إعادة إدخاله', 'It is lost and must be re-entered')],
          1, T('لكل أمر مفتاح فريد يمنع التكرار.', 'Each order has a unique key that prevents duplicates.')),
        Q(T('أي القنوات تكتسب نقاط ولاء؟', 'Which channels earn loyalty points?'),
          [T('النقدي والتوصيل فقط', 'Cash and delivery only'), T('كل القنوات', 'All channels'), T('التأمين فقط', 'Insurance only')],
          0, T('التعاقد والتأمين لا يكتسبان نقاطاً.', 'Contract and insurance earn no points.')),
        Q(T('ماذا تفعل لو ظهر تنبيه صحي للعميل (حساسية أو حمل)؟', 'What do you do if a customer health alert (allergy, pregnancy) shows?'),
          [T('أتجاهله لو العميل مستعجل', 'Ignore it if the customer is in a hurry'), T('أراجعه قبل البيع — السلامة قبل البيع', 'Check it before selling — safety before sales'), T('أخفيه', 'Hide it')],
          1, T('التنبيه الصحي يظهر قبل أي اقتراح بيع ولا يُتجاهل.', 'The health alert shows before any sales suggestion and is never ignored.')),
    ],
    'reservations': [
        Q(T('أي عمود في لوحة الحجوزات يحتاج تصرفاً أولاً؟', 'Which board column needs action first?'),
          [T('تم التسليم', 'Fulfilled'), T('المخزون متاح — اتصل بالعميل', 'Available — call the customer'), T('ملغي', 'Cancelled')],
          1, T('«المخزون متاح» ينتظر اتصالاً بالعميل.', '"Available" is waiting for a call to the customer.')),
        Q(T('هل الحجز يخصم من مخزون SOFTECH؟', 'Does a reservation deduct SOFTECH stock?'),
          [T('نعم فوراً', 'Yes, immediately'), T('لا، الصرف الفعلي يتم بفاتورة', 'No, the real dispense is an invoice'), T('بعد 24 ساعة', 'After 24 hours')],
          1, T('الحجز متابعة فقط.', 'A reservation is tracking only.')),
        Q(T('ظهر «حجز مكرر محتمل». ماذا تفعل؟', '"Possible duplicate" appears. What do you do?'),
          [T('أفتح الحجز الموجود بدل إنشاء جديد إلا لو الطلب مختلف', 'Open the existing reservation instead, unless the request is different'), T('أنشئ دائماً', 'Always create'), T('ألغي الاثنين', 'Cancel both')],
          0, T('هناك حجز مفتوح لنفس العميل والصنف.', 'An open reservation exists for the same customer and item.')),
        Q(T('حجز في حالة «منتهي — لا استجابة» — ما الممكن؟', 'A reservation is "Expired — no response". What is possible?'),
          [T('إعادة فتحه فيرجع «قيد الانتظار»', 'Reopen it, back to "Pending"'), T('لا شيء أبداً', 'Nothing ever'), T('تحويله لتم التسليم مباشرة', 'Mark it fulfilled directly')],
          0, T('المنتهي هو الوحيد الذي يُعاد فتحه.', 'Expired is the only one that can be reopened.')),
    ],
    'demand': [
        Q(T('خلال كم دقيقة يجب تعيين طلب العميل الجديد لموظف؟', 'Within how many minutes must a new request be assigned?'),
          [T('10 دقائق', '10 minutes'), T('ساعة', 'One hour'), T('يوم', 'One day')],
          0, T('SLA: التعيين خلال 10 دقائق والتواصل خلال 20 دقيقة من التعيين.', 'SLA: assign within 10 minutes, contact within 20 minutes of assignment.')),
        Q(T('عميل طلب صنفاً غير متوفر وسيمشي. هل تسجّله؟', 'A customer wants an unavailable item and is leaving. Do you record it?'),
          [T('لا داعي', 'No need'), T('نعم — الطلب باسم عميل حقيقي أقوى إشارة للمشتريات', 'Yes — a request under a real customer is the strongest signal for purchasing'), T('فقط لو اشترى شيئاً آخر', 'Only if they bought something else')],
          1, T('التسجيل يتيح الاسترداد لاحقاً ويوجّه المشتريات.', 'Recording enables recovery later and guides purchasing.')),
        Q(T('ماذا تعرض «قائمة الاسترداد»؟', 'What does the "Recovery queue" show?'),
          [T('عملاء طلبوا أصنافاً عادت للمخزون', 'Customers who asked for items now back in stock'), T('المرتجعات', 'Returns'), T('الموردين', 'Suppliers')],
          0, T('تواصل معهم لاسترداد البيعة.', 'Contact them to recover the sale.')),
    ],
    'transfers': [
        Q(T('من يعتمد طلب التحويل؟', 'Who approves a transfer request?'),
          [T('الفرع الطالب', 'The requesting branch'), T('الفرع المصدر (أو المشرف)', 'The supplying branch (or a supervisor)'), T('العميل', 'The customer')],
          1, T('الفرع الذي لديه المخزون يعتمد أو يرفض أو يطلب تعديلاً.', 'The branch with the stock approves, rejects or asks for changes.')),
        Q(T('هل اعتماد الطلب في النظام يحرّك المخزون؟', 'Does approving in the system move stock?'),
          [T('نعم', 'Yes'), T('لا — الحركة الفعلية تتم في SOFTECH', 'No — the actual movement happens in SOFTECH'), T('نصف الكمية', 'Half the quantity')],
          1, T('بعد الاعتماد يُصدر التحويل في SOFTECH ثم «إرسال للـ ERP».', 'After approval the transfer is issued in SOFTECH, then "Send to ERP".')),
        Q(T('ما فائدة «ورقة الترصيص»؟', 'What is the "stocking sheet" for?'),
          [T('ترتيب الأصناف حسب أرفف الفرع المستلم', 'Ordering items by the receiving branch\'s shelves'), T('حساب الضريبة', 'Calculating VAT'), T('طباعة الفاتورة', 'Printing the invoice')],
          0, T('تسرّع وضع الأصناف على الأرفف عند الاستلام.', 'It speeds up putting items away on receipt.')),
    ],
    'followups': [
        Q(T('متى تُغلق مهمة المتابعة تلقائياً؟', 'When does a follow-up task close automatically?'),
          [T('بعد أسبوع', 'After a week'), T('عندما تؤكد SOFTECH بيعاً جديداً لنفس الدواء', 'When SOFTECH confirms a new sale of the same medicine'), T('لا تُغلق أبداً', 'Never')],
          1, T('الحالة «أُغلق تلقائياً».', 'The status becomes "auto-closed".')),
        Q(T('لماذا يظهر الهاتف محجوباً (●●●)؟', 'Why is the phone masked (●●●)?'),
          [T('دورك لا يسمح برؤيته', 'Your role may not see it'), T('الرقم خاطئ', 'Wrong number'), T('العميل محظور', 'Customer blocked')],
          0, T('في هذه الحالة زر واتساب لا يظهر.', 'In that case the WhatsApp button is hidden.')),
        Q(T('هل رسالة التذكير بالصرف تذكر اسم الدواء؟', 'Does the refill reminder message name the medicine?'),
          [T('نعم', 'Yes'), T('لا، حفاظاً على الخصوصية', 'No, for privacy')],
          1, T('الصيدلي يؤكد الأصناف عند التجهيز.', 'The pharmacist confirms the items when preparing.')),
    ],
    'delivery': [
        Q(T('ماذا يُسجَّل كإثبات تسليم؟', 'What is recorded as proof of delivery?'),
          [T('اسم المستلم والمبلغ وصورة اختيارية والموقع تلقائياً', 'Recipient name, amount, optional photo and location automatically'), T('لا شيء', 'Nothing'), T('توقيع ورقي فقط', 'Only a paper signature')],
          0, T('موقع السائق يُسجَّل تلقائياً عند «تأكيد التسليم».', 'The driver\'s location is recorded automatically on "Confirm delivery".')),
        Q(T('ما «المسار» في لوحة التوزيع؟', 'What is a "route" on the dispatch board?'),
          [T('مجموعة طلبات جاهزة لسائق واحد تُطلق مرة واحدة', 'A group of ready orders for one driver, launched at once'), T('خريطة الفرع', 'The branch map'), T('فاتورة', 'An invoice')],
          0, T('«إطلاق المسار» يكلّف السائق بكل طلباته.', '"Launch route" assigns all its orders to the driver.')),
        Q(T('بعد التسليم، «تحصيل نقدي» يقارن المبلغ المحصّل بماذا؟', 'After delivery, "Cash collection" compares the amount collected with what?'),
          [T('قيمة الأصناف + رسوم التوصيل', 'Items value + delivery fee'), T('راتب السائق', 'The driver\'s salary')],
          0, T('النظام يعرض العجز أو الزيادة.', 'The system shows any shortage or excess.')),
    ],
    'stockcount': [
        Q(T('ما «اللقطة» في الجرد؟', 'What is the "snapshot" in a stock count?'),
          [T('تجميد الكميات المتوقعة من SOFTECH في لحظة', 'Freezing expected quantities from SOFTECH at one moment'), T('صورة للرف', 'A photo of the shelf'), T('تقرير المبيعات', 'A sales report')],
          0, T('الكمية المتوقعة لا تتغير بعد اللقطة.', 'Expected quantities never change after the snapshot.')),
        Q(T('أين تتم تسوية الفروق؟', 'Where is the variance adjusted?'),
          [T('في SOFTECH من ملف «تصدير للتسوية»', 'In SOFTECH from the "Export for adjustment" file'), T('تلقائياً في النظام', 'Automatically in the system')],
          0, T('النظام يحسب الفروق؛ التسوية في SOFTECH.', 'The system computes variances; the adjustment is in SOFTECH.')),
        Q(T('بيع حدث بين اللقطة والعد. ما أثره؟', 'A sale happened between snapshot and count. Effect?'),
          [T('يظهر كفرق', 'It shows as a variance'), T('لا أثر', 'No effect')],
          0, T('جمّد الحركة أو اجرد بسرعة بعد اللقطة.', 'Pause movement or count quickly after the snapshot.')),
    ],
    'tasks': [
        Q(T('أين تجد المهام المسندة لك فقط؟', 'Where do you find only the tasks assigned to you?'),
          [T('عرض «مهامي»', 'The "My tasks" view'), T('الجداول التلقائية', 'Schedules')],
          0, T('ابدأ يومك من «مهامي».', 'Start your day from "My tasks".')),
        Q(T('ما فائدة «الجداول التلقائية»؟', 'What are "Schedules" for?'),
          [T('إنشاء مهام متكررة تلقائياً', 'Creating recurring tasks automatically'), T('جدول الرواتب', 'Payroll schedule')],
          0, T('مثل جرد يومي أو تدقيق أسبوعي.', 'Like a daily count or a weekly audit.')),
        Q(T('كيف تنهي مهمة؟', 'How do you finish a task?'),
          [T('«إغلاق المهمة» مع ملاحظات الإغلاق', '"Close task" with closing notes'), T('أحذفها', 'Delete it')],
          0, T('ويمكن «إعادة فتح» لو احتاجت عملاً إضافياً.', 'It can be reopened if more work is needed.')),
    ],
    'customers': [
        Q(T('ما الكود الموحّد للعميل؟', 'What is the customer\'s unified code?'),
          [T('PIC', 'PIC'), T('رقم الفاتورة', 'Invoice number'), T('رقم الفرع', 'Branch number')],
          0, T('كود PIC فريد على مستوى الشبكة.', 'The PIC is unique across the network.')),
        Q(T('في دمج الأكواد المكررة، هل تعتمد زوجاً علّمته بنفسك؟', 'In duplicate-code merging, can you approve a pair you marked?'),
          [T('نعم', 'Yes'), T('لا — مراجع آخر يعتمده', 'No — another reviewer approves it')],
          1, T('مراجع يعلّم ومراجع مختلف يعتمد.', 'One reviewer marks, a different one approves.')),
        Q(T('تعديل نقاط العميل من ملفه يؤثر على…', 'Adjusting a customer\'s points from their profile affects…'),
          [T('رصيده في كل الفروع ويُسجَّل باسمك', 'Their balance in every branch, recorded under your name'), T('فرعك فقط', 'Your branch only')],
          0, T('السبب إلزامي والتعديل يُنفَّذ في SOFTECH.', 'A reason is required and it is applied in SOFTECH.')),
    ],
    'vouchers': [
        Q(T('كم دقيقة صلاحية رمز التحقق (OTP)؟', 'How long is the OTP valid?'),
          [T('3 دقائق و3 محاولات', '3 minutes and 3 tries'), T('يوم كامل', 'A whole day')],
          0, T('ومستند الصرف صالح 15 دقيقة.', 'The redemption document is valid for 15 minutes.')),
        Q(T('هل يُطلب من العميل إرسال الرمز في رسالة؟', 'Should the customer forward the code in a message?'),
          [T('لا، يقرأه لك فقط', 'No, they only read it to you'), T('نعم', 'Yes')],
          0, T('الرمز سري ولا يُخزَّن كنص.', 'The code is secret and never stored as plain text.')),
        Q(T('القسيمة «الخاصة» يستخدمها…', 'A "private" voucher can be used by…'),
          [T('العميل المحدد عليها فقط', 'Only the customer it is set for'), T('أي عميل', 'Any customer')],
          0, T('حسب فئة التوزيع.', 'According to its category.')),
    ],
    'loyalty': [
        Q(T('العميل في الفرع يسأل عن نقاطه. أي شاشة؟', 'A walk-in customer asks about their points. Which screen?'),
          [T('«استعلام نقاط الفرع»', '"Branch points lookup"'), T('الحوافز', 'Incentives')],
          0, T('عرض الرصيد فقط؛ الاستبدال من خدمة العملاء.', 'Shows the balance only; redemption via customer service.')),
        Q(T('متى يكافأ المُحيل؟', 'When is the referrer rewarded?'),
          [T('بعد التحقق من أن المُحال عميل حقيقي', 'After confirming the referred person is a real customer'), T('فور التسجيل', 'Right after registering')],
          0, T('التحقق يحمي من الاحتيال.', 'Validation protects against fraud.')),
    ],
    'catalog': [
        Q(T('هل تعتمد على «الاسم العلمي» في SOFTECH لاقتراح بديل؟', 'Do you rely on the SOFTECH "scientific name" to suggest an alternative?'),
          [T('نعم دائماً', 'Yes always'), T('لا — غير موثوق؛ استخدم المادة الفعالة المعتمدة', 'No — unreliable; use the approved active ingredient')],
          1, T('المادة الفعالة المعتمدة هي المصدر الموثوق.', 'The approved active ingredient is the reliable source.')),
        Q(T('صفحة المنتج تعرض توافر الفروع كـ…', 'The product page shows branch availability as…'),
          [T('متاح / محدود / غير متاح', 'Available / limited / unavailable'), T('الكمية بالضبط', 'The exact quantity')],
          0, T('بدون كميات.', 'Without quantities.')),
        Q(T('في لوحة المخزون، «الراكد» يعني…', 'On the inventory dashboard, "dead stock" means…'),
          [T('أصناف لها مخزون بلا مبيعات', 'Items with stock and no sales'), T('أصناف منتهية', 'Expired items')],
          0, T('رأس مال راكد يُراجع للتحويل أو التخفيض.', 'Idle capital to review for transfer or discount.')),
    ],
    'chronic': [
        Q(T('هل تنقية المواد الفعالة تعدّل SOFTECH؟', 'Does active-ingredient cleanup change SOFTECH?'),
          [T('لا', 'No'), T('نعم', 'Yes')],
          0, T('مراجعة واعتماد في النظام فقط.', 'Review and approval in the system only.')),
        Q(T('نتيجة «مقترحة» في بحث المواد الفعالة تعني…', 'A "suggested" result in ingredient search means…'),
          [T('لم يراجعها صيدلي بعد — تأكد قبل اقتراح بديل', 'Not reviewed by a pharmacist yet — verify before offering an alternative'), T('معتمدة', 'Approved')],
          0, T('اختر «معتمد فقط» للنتائج المؤكدة.', 'Choose "approved only" for confirmed results.')),
    ],
    'batches': [
        Q(T('ما قاعدة FEFO؟', 'What is the FEFO rule?'),
          [T('الأقرب انتهاءً يُصرف أولاً', 'First expiry, first out'), T('الأحدث يُصرف أولاً', 'Newest out first')],
          0, T('لتقليل الخسارة بالانتهاء.', 'To reduce losses to expiry.')),
        Q(T('هل يخصم النظام المخزون تلقائياً عند قرار الإتلاف؟', 'Does the system deduct stock automatically on a disposal decision?'),
          [T('لا — يُطبَّق يدوياً في SOFTECH', 'No — it is applied manually in SOFTECH'), T('نعم', 'Yes')],
          0, T('مسودة ← اعتماد ← تنفيذ في SOFTECH.', 'Draft → approval → executed in SOFTECH.')),
        Q(T('زر «إنقاذ قبل الانتهاء» يُنشئ…', 'The "rescue before expiry" button creates…'),
          [T('مسودة طلب تحويل', 'A draft transfer request'), T('فاتورة بيع', 'A sales invoice')],
          0, T('تمر بمسار التحويلات المعتاد.', 'It goes through the usual transfer flow.')),
    ],
    'shortage': [
        Q(T('النظام اقترح مطابقة لست متأكداً منها. ماذا تفعل؟', 'The system suggests a match you are unsure of. What do you do?'),
          [T('لا تؤكدها — اختر الصحيح أو ابحث', 'Do not confirm it — pick the right one or search'), T('أؤكدها', 'Confirm it')],
          0, T('مطابقة خاطئة = طلب صنف خاطئ.', 'A wrong match = ordering the wrong item.')),
        Q(T('«فحص المخزون» في النواقص يقترح…', '"Check stock" in shortages suggests…'),
          [T('تحويلاً من فرع آخر بدل الشراء إن أمكن', 'A transfer from another branch instead of buying where possible'), T('إلغاء القائمة', 'Cancelling the list')],
          0, T('التحويل أرخص من الشراء.', 'A transfer is cheaper than buying.')),
    ],
    'replacement': [
        Q(T('كيف تُسجَّل «رصيد» البدل في SOFTECH؟', 'How is a replacement "balance" recorded in SOFTECH?'),
          [T('فاتورة شراء على مورد افتراضي، وتُستهلك بسند صرف', 'A purchase invoice on a virtual supplier, consumed by a payment voucher'), T('خصم على الفاتورة', 'A discount on the invoice')],
          0, T('الموديول يربط كل مستندات الحالة.', 'The module links all of the case\'s documents.')),
        Q(T('هل يعتمد منشئ الحالة حالته؟', 'Can the case creator approve their own case?'),
          [T('لا', 'No'), T('نعم', 'Yes')],
          0, T('مراجع ومعتمد مختلفان.', 'Maker and checker are different people.')),
    ],
    'callcenter': [
        Q(T('شكوى تحتاج متابعة حتى الحل. ماذا تفتح؟', 'A complaint needs follow-up until resolved. What do you open?'),
          [T('«حالة» جديدة', 'A new "case"'), T('حجز', 'A reservation')],
          0, T('الحالة تُتابع حتى «محلولة» بالسبب الجذري.', 'A case is followed to "Resolved" with the root cause.')),
        Q(T('من 100، كم وزن «حل المشكلة» في تقييم جودة المكالمة؟', 'Out of 100, how much is "problem resolution" worth in call scoring?'),
          [T('30', '30'), T('10', '10'), T('50', '50')],
          0, T('الترحيب 20، الحل 30، الوضوح 25، الدقة 25.', 'Greeting 20, resolution 30, clarity 25, accuracy 25.')),
    ],
    'omni': [
        Q(T('آخر رسالة من العميل منذ يومين. كيف ترد على واتساب؟', 'The customer\'s last message was two days ago. How do you reply on WhatsApp?'),
          [T('بقالب معتمد — نافذة الـ 24 ساعة مغلقة', 'With an approved template — the 24-hour window is closed'), T('برسالة نصية حرة', 'With free text')],
          0, T('النص الحر مسموح فقط خلال 24 ساعة من رسالة العميل.', 'Free text is only allowed within 24 hours of the customer\'s message.')),
        Q(T('اقتراحات الرد من «مساعد الذكاء الاصطناعي»…', 'Reply suggestions from the "AI assistant"…'),
          [T('تُراجع قبل الإرسال', 'Are reviewed before sending'), T('تُرسل تلقائياً', 'Are sent automatically')],
          0, T('أنت المسؤول عن الرد.', 'You are responsible for the reply.')),
        Q(T('هل تُرسل حملة واتساب بدون اعتماد؟', 'Can a WhatsApp campaign be sent without approval?'),
          [T('لا — تمر بمسار اعتماد', 'No — it goes through approval'), T('نعم', 'Yes')],
          0, T('مسودة ← بانتظار الموافقة ← معتمدة ← جارية.', 'Draft → pending approval → approved → running.')),
    ],
    'purchasing': [
        Q(T('قبل الشراء في توصيات المحرك، بماذا تبدأ؟', 'Before buying from the engine\'s recommendations, where do you start?'),
          [T('التحويلات المقترحة بين الفروع', 'Suggested transfers between branches'), T('أشتري كل الفجوة', 'Buy the whole gap')],
          0, T('التحويل أرخص من الشراء.', 'A transfer is cheaper than buying.')),
        Q(T('«التكلفة الفعلية» في سجل المشتريات هي…', '"Effective cost" in purchase history is…'),
          [T('بعد البونص والضريبة', 'After bonus and VAT'), T('السعر الاسمي', 'The nominal price')],
          0, T('الأصدق لمقارنة الموردين.', 'The fairest way to compare suppliers.')),
        Q(T('في صندوق الإتاحة، هل تطلب كل ما عرضه المورد؟', 'In the availability inbox, do you order everything the supplier offered?'),
          [T('لا — ما نحتاجه فعلاً فقط', 'No — only what we actually need'), T('نعم', 'Yes')],
          0, T('النظام يحسب الاحتياج والتغطية الداخلية.', 'The system computes need and internal cover.')),
    ],
    'invoices': [
        Q(T('معاينة الترحيل أظهرت أخطاء. ماذا تفعل؟', 'The posting preview shows errors. What do you do?'),
          [T('أصحح الأخطاء أولاً — الأخطاء تمنع الترحيل', 'Fix them first — errors block posting'), T('أرحّل على أي حال', 'Post anyway')],
          0, T('التحذيرات فقط يمكن تجاوزها بعد مراجعتها.', 'Only warnings can be overridden after review.')),
        Q(T('سطر بثقة OCR منخفضة يحتاج…', 'A line with low OCR confidence needs…'),
          [T('مراجعة يدوية للصنف والكمية والسعر', 'Manual review of item, quantity and price'), T('لا شيء', 'Nothing')],
          0, T('أو «إعادة OCR» لو القراءة سيئة.', 'Or "re-run OCR" if the reading is poor.')),
    ],
    'pricing': [
        Q(T('أي حقل سعر تعدّله في طلب تعديل السعر؟', 'Which price field do you change in a price change request?'),
          [T('سعر العبوة (بدون ضريبة)', 'The pack price (before VAT)'), T('سعر الوحدة', 'The unit price')],
          0, T('سعر الوحدة والسعر شامل الضريبة محسوبان.', 'Unit price and price with VAT are derived.')),
        Q(T('عند الاعتماد، باسم من يُنفَّذ التعديل في SOFTECH؟', 'On approval, under whose name is the change executed in SOFTECH?'),
          [T('مستخدم SOFTECH الخاص بالمعتمد', 'The approver\'s own SOFTECH user'), T('مستخدم عام', 'A generic user')],
          0, T('لذلك يجب ربط حساب المعتمد بمستخدم SOFTECH.', 'So the approver\'s account must be linked to a SOFTECH user.')),
    ],
    'analytics': [
        Q(T('لوحة «تارجت/تحقيق» تأخذ المحقق من…', 'The target/achievement board takes "achieved" from…'),
          [T('فواتير SOFTECH (صافي بعد المرتجعات)', 'SOFTECH invoices (net after returns)'), T('تقديرات يدوية', 'Manual estimates')],
          0, T('والتارجت من الأهداف البيعية.', 'And the target from sales targets.')),
        Q(T('مؤشر موسمية أكبر من 1 يعني…', 'A seasonality index above 1 means…'),
          [T('موسم مرتفع', 'High season'), T('موسم منخفض', 'Low season')],
          0, T('أقل من 1 = موسم منخفض.', 'Below 1 = low season.')),
    ],
    'incentives': [
        Q(T('بعد «اعتماد التسويات نهائياً» للفترة…', 'After "finalize settlements" for a period…'),
          [T('تُقفل الفترة ولا يمكن التراجع', 'The period is locked and cannot be undone'), T('يمكن تعديلها بحرية', 'It can be freely edited')],
          0, T('الحركات المحتسبة لا تُعدَّل بعد الاعتماد.', 'Calculated entries are never edited after finalizing.')),
        Q(T('«حوافزي» تعرض التوقع نهاية الشهر بطريقة…', '"My incentives" projects the month end…'),
          [T('خطية من متوسطك اليومي — قد تختلف', 'Linearly from your daily average — may differ'), T('النتيجة النهائية المؤكدة', 'The confirmed final result')],
          0, T('النتيجة النهائية بعد الاحتساب والاعتماد.', 'The final result comes after calculation and finalizing.')),
    ],
    'finance': [
        Q(T('اعتماد ربط سند بفاتورة في «سداد الموردين» يُكتب في…', 'Approving a voucher-invoice link in "Supplier payments" is written to…'),
          [T('المرآة لدينا فقط، ليس SOFTECH', 'Our mirror only, not SOFTECH'), T('SOFTECH مباشرة', 'SOFTECH directly')],
          0, T('الشاشات المالية لا تكتب في SOFTECH.', 'The finance screens do not write to SOFTECH.')),
        Q(T('تاريخ شيك يقع في إجازة. ماذا يحدث؟', 'A cheque date falls on a holiday. What happens?'),
          [T('يُرحَّل تلقائياً لأقرب يوم عمل ويظهر الأصلي', 'It shifts to the nearest working day and shows the original'), T('يُلغى', 'It is cancelled')],
          0, T('مع مراعاة أيام العمل البنكية في مصر.', 'Egyptian banking days are respected.')),
    ],
    'insurance': [
        Q(T('هل اسم المريض المعدّل في المطالبة يؤثر على الإجماليات؟', 'Does editing a patient name in a claim change the totals?'),
          [T('لا — حقل طباعة فقط وقابل للتراجع', 'No — print-only and reversible'), T('نعم', 'Yes')],
          0, T('مراجعة الأسماء آمنة.', 'Name review is safe.')),
        Q(T('من أين تأتي نسب الخصم (محلي/مستورد/ترسية)؟', 'Where do the discount rates (local/imported/tender) come from?'),
          [T('من عقد الجهة', 'The payer\'s contract'), T('من الكتالوج', 'The catalog')],
          0, T('بدون عقد سارٍ تستورد المطالبة بلا نسب صحيحة.', 'Without a valid contract a claim imports without correct rates.')),
    ],
    'commerce': [
        Q(T('السعر في المستند التجاري…', 'The price in a commercial document…'),
          [T('شامل الضريبة ويُستخرج منه جزء 14%', 'Includes VAT; the 14% portion is extracted'), T('تُضاف عليه الضريبة', 'VAT is added on top')],
          0, T('للأصناف المعلَّمة كخاضعة فقط.', 'For items flagged as taxable only.')),
    ],
    'hr': [
        Q(T('طلب إجازة في حالة «مسودة»…', 'A leave request in "Draft"…'),
          [T('لا يصل لأحد — يجب تقديمه', 'Reaches nobody — it must be submitted'), T('معتمد تلقائياً', 'Is auto-approved')],
          0, T('التقديم يرسله لمسار الموافقات.', 'Submitting sends it to the approval flow.')),
        Q(T('الحضور يُحتسب «ضمن النطاق» عندما تكون…', 'Attendance counts as "within range" when you are…'),
          [T('داخل 200 متر من فرعك مع تفعيل الموقع', 'Within 200 m of your branch with location on'), T('في أي مكان', 'Anywhere')],
          0, T('بدون موقع يُسجَّل «غير مُتحقق».', 'Without location it is recorded "unverified".')),
    ],
    'admin': [
        Q(T('المصفوفة تمنع دوراً من إجراء. هل يكفي إخفاء الزر؟', 'The matrix denies a role an action. Is hiding the button enough?'),
          [T('السيرفر يطبق نفس المصفوفة على كل طلب', 'The server applies the same matrix to every request'), T('نعم إخفاء الزر يكفي', 'Yes, hiding the button is enough')],
          0, T('الصلاحيات تُطبَّق في السيرفر.', 'Permissions are enforced on the server.')),
        Q(T('من يستطيع تعديل الشرح داخل النظام؟', 'Who can edit the in-app help?'),
          [T('من لديه «تعديل» على موديول «دليل الاستخدام»', 'Those with "edit" on the "Help guide" module'), T('الجميع', 'Everyone')],
          0, T('تُمنح من مصفوفة الصلاحيات.', 'Granted in the permissions matrix.')),
        Q(T('«المجدول متوقف» في شاشة المزامنة يعني…', '"Scheduler stopped" on the sync screen means…'),
          [T('المهام التلقائية لا تعمل — أعد تشغيل الخدمة', 'Automatic jobs are not running — restart the service'), T('كل شيء طبيعي', 'All is normal')],
          0, T('المتابعات والتنبيهات والمزامنة الدورية متوقفة.', 'Follow-ups, alerts and periodic sync are stopped.')),
    ],
}
