from . import T

_HUB_NOTE = T(
    'شريط الفلاتر أعلى «ذكاء المشتريات» مشترك بين كل تبويباته: الفترة (اليوم، الأسبوع، الشهر، الربع، السنة، الكل، مخصص)، الفروع، فئات الموردين، وخصائص الأصناف — غيّره مرة فيتغير كل تبويب.',
    'The filter bar at the top of "Procurement intelligence" is shared by all its tabs: period (today, week, month, quarter, year, all, custom), branches, supplier categories and item attributes — change it once and every tab follows.')

MODULE = {
    'key': 'purchasing', 'group': 'purchasing', 'icon': '🛒',
    'title': T('المشتريات والتوريد', 'Purchasing & supply'),
    'summary': T(
        '«محرك الطلب» يحسب لكل صنف في كل فرع معدل البيع الموزون (30/90/365 يوماً)، فئة ABC (الأصناف الأهم قيمة)، حد الأمان، التغطية بالشهور، '
        'والفجوة التي تحتاج شراء — ويقترح تحويلات بين الفروع قبل الشراء. فوقه: «ذكاء المشتريات» لتحليل الموردين والأسعار والهوامش والبونص، '
        '«التوريد والمعدلات» لمتابعة عروض الموردين والنواقص اليومية وطلبات التوريد ومعدلات البيع في SOFTECH، و«تحسين الكاش» لمنع الشراء الزائد.',
        'The "demand engine" calculates, per item per branch, the weighted sales rate (30/90/365 days), ABC class (most valuable items), safety stock, coverage in months, '
        'and the gap that needs buying — and suggests transfers between branches before buying. On top: "Procurement intelligence" to analyse suppliers, prices, margins and bonuses, '
        '"Supply & rates" to follow supplier offers, daily shortages, supply requests and SOFTECH sales rates, and "Cash optimization" to prevent over-buying.'),
}

SCREENS = [
    {
        'key': 'purchasing.engine',
        'routes': ['/purchasing'],
        'title': T('توصيات الشراء (محرك الطلب)', 'Purchase recommendations (demand engine)'),
        'summary': T('نتائج محرك الطلب: ما يجب شراؤه ومن أين يمكن التحويل بدل الشراء، مرتبة بفئة ABC، مع حالة آخر تشغيل وتاريخ آخر بيانات مبيعات.',
                     'The demand engine\'s output: what must be bought and where a transfer can replace buying, by ABC class, with the last run status and the date of the latest sales data.'),
        'audience': T('المشتريات والمدير.', 'Purchasing and admins.'),
        'tabs': [
            {'key': 'agg', 'title': T('📦 الشبكة (ABC)', '📦 Network (ABC)'), 'body': T('نظرة مجمعة على كل الفروع: المعدل الشهري، المخزون، الفجوة، القيمة، الهامش الإجمالي والصافي، والنسبة التراكمية (باريتو). صفِّ بفئة A/B/C/X.', 'An aggregate view across branches: monthly rate, stock, gap, value, gross and net margin, and cumulative % (Pareto). Filter by class A/B/C/X.')},
            {'key': 'branch', 'title': T('🏭 بالفرع', '🏭 By branch'), 'body': T('لكل فرع: المتوسط الشهري، الأمان، البضاعة في الطريق (تُخصم من الفجوة)، التغطية، الأولوية، الحالة (نفد/حرج/منخفض/مقبول/جيد) وآخر بيع. «يحتاج شراء فقط» يختصر القائمة.', 'Per branch: monthly average, safety stock, goods in transit (deducted from the gap), coverage, priority, status (out/critical/low/ok/good) and last sale. "Needs purchase only" shortens the list.')},
            {'key': 'transfer', 'title': T('🔄 التحويلات المقترحة', '🔄 Suggested transfers'), 'body': T('توصيات نقل من فرع عنده فائض لفرع عنده نقص مع الكمية والقيمة والأولوية. راجع وافق أو ارفض؛ الموافقة تتحول لطلب تحويل.', 'Suggestions to move stock from a branch with excess to one with a shortage, with quantity, value and priority. Review and approve or reject; approval becomes a transfer request.')},
            {'key': 'lostsales', 'title': T('💸 مبيعات ضائعة', '💸 Lost sales'), 'body': T('تقدير المبيعات الضائعة بسبب نفاد المخزون.', 'Estimated sales lost to stock-outs.')},
        ],
        'steps': [
            T('تأكد أن «المبيعات حتى» حديثة؛ لو متأخرة اضغط «تعويض المبيعات المتأخرة» أو «مزامنة كاملة 365 يوم» ثم «تشغيل».', 'Make sure "sales up to" is recent; if behind press "Catch up late sales" or "Full 365-day sync", then "Run".'),
            T('ابدأ بالتحويلات المقترحة (أرخص من الشراء)، ثم الفجوة المتبقية في فئة A.', 'Start with suggested transfers (cheaper than buying), then the remaining gap in class A.'),
        ],
        'tips': [T('المعادلة الحالية مكتوبة أسفل الصفحة: موزون = معدل30×% + معدل90×% + معدل365×%.', 'The current formula is shown at the bottom: weighted = rate30×% + rate90×% + rate365×%.')],
        'related': ['purchasing.supply', 'catalog.inventory', 'shortage.market', 'purchasing.cash'],
        'tour': [
            {'target': 'purchasing-engine-run', 'text': T('«▶ تشغيل» يحسب التوصيات من جديد.',
                                              '"▶ Run" recalculates the recommendations.')},
            {'target': 'purchasing-engine-summary', 'text': T('الملخص: عدد الأصناف حسب الفئة وقيمة الفجوة.',
                                              'The summary: items per class and the gap value.')},
            {'target': 'purchasing-engine-view-tabs', 'text': T('العروض: الشبكة (ABC)، بالفرع، التحويلات المقترحة، المبيعات الضائعة.',
                                              'Views: network (ABC), by branch, suggested transfers, lost sales.')},
            {'target': 'purchasing-engine-abc-filter', 'text': T('فلتر الفئة A / B / C والفلاتر المتقدمة.',
                                              'Filter by class A / B / C and advanced filters.')},
            {'target': 'purchasing-engine-search', 'text': T('ابحث عن صنف.',
                                              'Search an item.')},
            {'target': 'purchasing-engine-export', 'text': T('«⬇ تصدير» يطلع القائمة Excel.',
                                              '"⬇ Export" downloads the list to Excel.')},
        ],
        'updated': '2026-10-10',
    },
    {
        'key': 'purchasing.cash',
        'routes': ['/cash-optimization'],
        'title': T('تحسين الكاش والمخزون', 'Cash & stock optimization'),
        'summary': T('رصد وتحرير الكاش المجمّد ومنع الشراء الزائد. التبويب المتاح «ذروة الطلب»: قفزة طلب حديثة قد لا تدوم — لو اشترينا لملاحقتها يركد المخزون. الذروة «القوية» يؤكدها إنسان فتصبح قابلة لتقليل الكمية المطلوبة؛ «المراقبة» للرصد فقط. التقليل يظهر على شيت النواقص فقط عند تفعيله في تشغيل المحرك.',
                     'Spot and free frozen cash and prevent over-buying. The available tab is "Demand spike": a recent jump in demand that may not last — buying to chase it leaves dead stock. A person confirms a "strong" spike so its order quantity can be reduced; "watch" spikes are monitor-only. The reduction shows on the shortage sheet only when enabled for the engine run.'),
        'audience': T('المشتريات والمشرفون والجودة.', 'Purchasing, supervisors and quality.'),
        'tabs': [
            {'key': 'spike', 'title': T('📈 ذروة الطلب', '📈 Demand spike'), 'body': T('لكل صنف: الدرجة، المضاعف (المعدل الحديث ÷ السابق)، الرصيد، المطلوب، وما بعد التقليل والتوفير المحتمل. «تأكيد (طبّق التقليل)» أو «إلغاء التأكيد».', 'Per item: grade, multiplier (recent ÷ previous rate), stock, required qty, after reduction and potential saving. "Confirm (apply reduction)" or "Unconfirm".')},
        ],
        'related': ['purchasing.engine'],
        'tour': [
            {'target': 'purchasing-cash-tabs', 'text': T('التبويبات: ذروة الطلب، والباقي قريباً.',
                                              'Tabs: demand spikes, the others coming soon.')},
            {'target': 'purchasing-cash-kpis', 'text': T('ذروات مكتشفة، قوية، للمراقبة، ومؤكدة، والتوفير.',
                                              'Spikes found, strong, to watch, confirmed, and the saving.')},
            {'target': 'purchasing-cash-filters', 'text': T('فلتر القوة والتصنيف والبحث.',
                                              'Filter by strength, category and search.')},
            {'target': 'purchasing-cash-table', 'text': T('الأصناف اللي مبيعاتها الأخيرة فيها ذروة غير طبيعية.',
                                              'Items whose recent sales show an abnormal spike.')},
            {'target': 'purchasing-cash-confirm', 'text': T('«تأكيد» بعد مراجعتك — بيطبّق التقليل على توصية الشراء.',
                                              '"Confirm" after your review — it applies the reduction to the purchase recommendation.')},
        ],
        'updated': '2026-10-10',
    },
    {
        'key': 'purchasing.supply',
        'routes': ['/supply'],
        'title': T('التوريد والمعدلات', 'Supply & rates'),
        'summary': T('مساحة عمل يومية للمشتريات: عروض الموردين، متابعة النواقص، معدلات البيع في SOFTECH، طلبات التوريد، تلبية طلبات الفروع، طلبات واتساب، والتوزيعة. النظام يحسب كل الأرقام؛ الكتابة في SOFTECH مقيدة بمفاتيح تشغيل ومسار اعتماد.',
                     'A daily workspace for purchasing: supplier offers, shortage follow-up, SOFTECH sales rates, supply requests, filling branch requests, WhatsApp requests and distribution. The system computes every number; writing to SOFTECH is behind switches and an approval flow.'),
        'audience': T('المشتريات والمشرفون.', 'Purchasing and supervisors.'),
        'tabs': [
            {'key': 'inbox', 'title': T('صندوق الإتاحة', 'Availability inbox'),
             'body': T('الصق قائمة عرض المورد من واتساب أو ارفع صورة/Excel ← النظام يطابق الأصناف ويحسب لكل صنف: هل نحتاجه، كم، بأي تكلفة فعلية، وهل يغطيه المخزون الداخلي ← اختر ما نحتاجه فعلاً (لا تطلب كل ما عرضه المورد) ← نسخ/واتساب/Excel للطلب وتسجيله.',
                       'Paste the supplier\'s offer list from WhatsApp or upload a photo/Excel → the system matches items and computes per item: do we need it, how many, at what real cost, and does internal stock cover it → pick what we actually need (never everything offered) → copy/WhatsApp/Excel the order and record it.')},
            {'key': 'cases', 'title': T('متابعة النواقص', 'Shortage follow-up'),
             'body': T('كل احتياج غير محلول حالة تستمر يوماً بعد يوم، مرتبة (عاجل ← ندرة ← الأقدم ← الأكبر فجوة) مع شرح سبب التوصية. اعتمد التحويل الداخلي (مسودة طلب تحويل) أو اطلب الباقي من مورد.',
                       'Every unresolved need is a case that carries over day to day, ordered (urgent → scarcity → oldest → biggest gap) with why the engine recommends it. Approve the internal transfer (a draft transfer request) or order the rest from a supplier.')},
            {'key': 'rates', 'title': T('معدلات البيع', 'Sales rates'),
             'body': T('دفع المعدل الشهري المحسوب من محرك الطلب إلى SOFTECH: مقترح ← معتمد ← مُنفّذ. اختر الفروع والأصناف وطريقة الحساب (محورية / متقدمة Croston) ووجهة الكتابة (سيرفر الفرع، نسخة الرئيسي، أو الاثنان). التنفيذ محجوب حتى تفعيل البوابة.',
                       'Push the engine\'s monthly rate to SOFTECH: proposed → approved → executed. Choose branches, items, method (pivot / advanced Croston) and target (branch server, HQ copy, or both). Execution is blocked until the gate is enabled.')},
            {'key': 'isr', 'title': T('طلبات التوريد / ISR', 'Supply requests (ISR)'),
             'body': T('معاينة طلبات التوريد المقترحة من الرئيسي للفروع (للقراءة حالياً).', 'Preview of proposed supply requests from HQ to branches (read-only for now).')},
            {'key': 'isrfill', 'title': T('تلبية طلبات الفروع', 'Fill branch requests'),
             'body': T('لطلبات التوريد التي رفعتها الفروع في SOFTECH: لكل صنف حالة الفرع الطالب وكل الفروع والرئيسي، وخطة التلبية (فائض الفروع ← الرئيسي ← نقص للشراء). «تحديث من SOFTECH» يعيد قراءة المخزون، والتصدير Excel قابل للتعديل.',
                       'For supply requests branches raised in SOFTECH: per item the requesting branch, every other branch and HQ, and the fill plan (other branches\' excess → HQ → shortage to buy). "Refresh from SOFTECH" re-reads stock; the Excel export is editable.')},
            {'key': 'wa', 'title': T('طلبات واتساب', 'WhatsApp requests'),
             'body': T('الصق محادثة مجموعة واتساب الفرع (أو صورة) ← تُقسَّم الرسائل وتُطابق الأصناف ← راجع سطراً سطراً (Enter للتأكيد) ← تحليل التوافر وExcel ← «إنشاء قائمة النواقص» للفرع.',
                       'Paste the branch WhatsApp group chat (or a photo) → messages are split and items matched → review line by line (Enter confirms) → availability analysis and Excel → "Create shortage list" for the branch.')},
            {'key': 'dist', 'title': T('التوزيعة', 'Distribution'),
             'body': T('توزيع استباقي: أصناف جديدة بلا معدل، أصناف غير مُدرجة بفرع، متكدسة بفرع، أو راكدة بالرئيسي — مع اقتراح توزيعها.', 'Proactive distribution: new items with no rate, items never stocked at a branch, piled up at a branch, or dormant at HQ — with a suggested distribution.')},
        ],
        'tips': [T('لا شيء في هذه الشاشة يكتب في SOFTECH بدون اعتماد صريح وبوابة مفعّلة.', 'Nothing on this screen writes to SOFTECH without explicit approval and an enabled gate.')],
        'related': ['purchasing.engine', 'shortage.list', 'transfers.list'],
        'tour': [
            {'target': 'purchasing-supply-tabs', 'text': T('التبويبات: صندوق الإتاحة، متابعة النواقص، معدلات البيع، طلبات التوريد…',
                                              'Tabs: availability inbox, shortage follow-up, sales rates, supply requests…')},
            {'target': 'purchasing-supply-batches', 'text': T('القوائم المستوردة من الموردين.',
                                              'The lists imported from suppliers.')},
            {'target': 'purchasing-supply-import', 'text': T('اختار المورد والمصدر، وارفع صورة أو ملف Excel / CSV.',
                                              'Choose the supplier and source, and upload an image or an Excel / CSV file.')},
            {'target': 'purchasing-supply-paste', 'text': T('أو الصق نص رسالة المورد هنا.',
                                              'Or paste the supplier\'s message text here.')},
            {'target': 'purchasing-supply-analyze', 'text': T('«تحليل القائمة» يطابق الأصناف ويعرض المتاح.',
                                              '"Analyze list" matches the items and shows what is available.')},
        ],
        'updated': '2026-10-10',
    },
    {
        'key': 'purchasing.overview',
        'routes': ['/procurement/overview'],
        'title': T('ذكاء المشتريات — نظرة عامة', 'Procurement intelligence — overview'),
        'summary': T('مؤشرات المشتريات: صافي المشتريات والكميات والأصناف والموردون والفواتير ومتوسط الهامش (30 و365 يوماً)، تركّز أعلى 3 موردين، المرتجعات، الاتجاه الشهري، التنبيهات المفتوحة، وأفضل الموردين بالدرجة.',
                     'Purchasing KPIs: net purchases, quantities, items, suppliers, invoices and average margin (30 and 365 days), top-3 supplier concentration, returns, the monthly trend, open alerts, and the best suppliers by score.'),
        'audience': T('المشتريات والمدير.', 'Purchasing and admins.'),
        'steps': [{'text': T('«تشغيل المحرك» يعيد حساب المؤشرات وخرائط المورد-صنف والتنبيهات.', '"Run engine" recalculates KPIs, supplier-item maps and alerts.'), 'roles': ['admin', 'purchasing']}],
        'tips': [_HUB_NOTE],
        'related': ['purchasing.suppliers', 'purchasing.optimization'],
        'updated': '2026-10-10',
    },
    {
        'key': 'purchasing.history',
        'routes': ['/procurement/history'],
        'title': T('سجل المشتريات المتقدم', 'Advanced purchase history'),
        'summary': T('كل سطور الشراء والمرتجعات من SOFTECH مع فلاتر كاملة (المورد، الصنف، المشتري، الهامش، التكلفة الفعلية، القيمة، البونص، المرتجع التالف أو العادي) وشريط إجماليات للنتائج كلها.',
                     'Every purchase and return line from SOFTECH with full filters (supplier, item, buyer, margin, effective cost, value, bonus, damaged or normal return) and a totals bar for all matches.'),
        'audience': T('المشتريات والمدير.', 'Purchasing and admins.'),
        'tips': [T('«التكلفة الفعلية» = بعد البونص والضريبة؛ هي الأصدق لمقارنة الموردين.', '"Effective cost" = after bonus and VAT; it is the fairest way to compare suppliers.'), _HUB_NOTE],
        'related': ['purchasing.foc'],
        'updated': '2026-10-10',
    },
    {
        'key': 'purchasing.segments',
        'routes': ['/procurement/segments'],
        'title': T('تصنيف الموردين', 'Supplier segmentation'),
        'summary': T('توزيع المشتريات على فئات الموردين (موزّع رئيسي، مصنع…) مبني على أكواد SOFTECH، مع قيمة الشراء والفواتير ومعدل البونص والمرتجعات لكل مورد. «تعديل» يغيّر فئة مورد يدوياً ويثبتها.',
                     'Purchases split by supplier category (main distributor, manufacturer…) based on SOFTECH codes, with value, invoices, bonus and return rate per supplier. "Edit" changes a supplier\'s category manually and pins it.'),
        'audience': T('المشتريات والمدير.', 'Purchasing and admins.'),
        'tips': [T('التعديل اليدوي يوقف التصنيف التلقائي لهذا المورد.', 'A manual edit stops automatic classification for that supplier.'), _HUB_NOTE],
        'related': ['purchasing.categories'],
        'updated': '2026-10-10',
    },
    {
        'key': 'purchasing.categories',
        'routes': ['/procurement/categories'],
        'title': T('فئات وقواعد تصنيف الموردين', 'Supplier categories & rules'),
        'summary': T('إدارة فئات الموردين (الاسم، الكود، اللون، الترتيب، الفئة الافتراضية) وقواعد ربط أكواد SOFTECH (نوع الشخص ptcode + التصنيف ptclassifcode) بالفئات بأولوية (الأقل يفوز). «إعادة تصنيف الموردين» يطبق القواعد من جديد.',
                     'Manage supplier categories (name, code, colour, order, default) and the rules mapping SOFTECH codes (person type ptcode + classification ptclassifcode) to categories with priority (lowest wins). "Reclassify suppliers" re-applies the rules.'),
        'audience': T('المدير والمشتريات.', 'Admins and purchasing.'),
        'tips': [T('الفئة «الموزّع الرئيسي/المصنع» تُستخدم في تقارير الصلاحية — صنّف الموردين بدقة.', 'The "main distributor/manufacturer" category feeds the expiry reports — classify suppliers carefully.')],
        'related': ['purchasing.segments', 'batches.main'],
        'updated': '2026-10-10',
    },
    {
        'key': 'purchasing.foc',
        'routes': ['/procurement/foc'],
        'title': T('البونص (FOC) والتكلفة الفعلية', 'Bonus (FOC) & effective cost'),
        'summary': T('تحليل التكلفة الحقيقية والكفاءة الشرائية.', 'Analysis of real cost and buying efficiency.'),
        'audience': T('المشتريات والمدير.', 'Purchasing and admins.'),
        'tabs': [
            {'key': 'foc', 'title': T('🎁 تحليل FOC', '🎁 FOC analysis'), 'body': T('نسبة البضاعة المجانية، أكثر الموردين كرماً، الاتجاه الشهري، ومقارنة التكلفة الاسمية بالفعلية بعد البونص والضريبة.', 'Free-goods rate, most generous suppliers, the monthly trend, and nominal vs effective cost after bonus and VAT.')},
            {'key': 'expiry', 'title': T('⚠️ مرتجعات التالف', '⚠️ Damaged returns'), 'body': T('المرتجعات التالفة مقابل العادية، نسبتها وقيمتها، وأكثر الأصناف والفروع في مرتجعات التالف.', 'Damaged vs normal returns, their rate and value, and the items and branches with the most damaged returns.')},
            {'key': 'tax', 'title': T('🧾 العبء الضريبي', '🧾 Tax burden'), 'body': T('إجمالي ضريبة القيمة المضافة على المشتريات ونسبتها واتجاهها.', 'Total VAT on purchases, its rate and trend.')},
        ],
        'tips': [_HUB_NOTE],
        'updated': '2026-10-10',
    },
    {
        'key': 'purchasing.suppliers',
        'routes': ['/procurement/suppliers', '/procurement/suppliers/:supplierCode'],
        'title': T('أداء الموردين', 'Supplier performance'),
        'summary': T('ترتيب الموردين بالدرجة (هامش الربح، التوافر/التكرار، معدل المرتجعات، استقرار الأسعار) مع صفحة لكل مورد: المشتريات الشهرية، الأصناف، الفروع المُزوّدة، وتفصيل الدرجة.',
                     'Suppliers ranked by score (margin, availability/frequency, return rate, price stability) with a page per supplier: monthly purchases, items, branches supplied, and the score breakdown.'),
        'audience': T('المشتريات والمدير.', 'Purchasing and admins.'),
        'related': ['purchasing.overview'],
        'tour': [
            {'target': 'purchasing-suppliers-search', 'text': T('ابحث باسم أو كود المورد.',
                                              'Search by supplier name or code.')},
            {'target': 'purchasing-suppliers-sort', 'text': T('الترتيب (الدرجة وغيرها).',
                                              'Sort (score and more).')},
            {'target': 'purchasing-suppliers-table', 'text': T('الموردين ودرجة أدائهم.',
                                              'The suppliers and their performance score.')},
            {'target': 'purchasing-suppliers-row', 'text': T('اضغط على مورد لتفصيل درجته.',
                                              'Click a supplier for its score breakdown.')},
        ],
        'updated': '2026-10-10',
    },
    {
        'key': 'purchasing.margins',
        'routes': ['/procurement/margins'],
        'title': T('الهوامش ومراقبة الأسعار', 'Margins & price control'),
        'summary': T('تحليل هوامش المشتريات ومراقبة تذبذب أسعار الشراء.', 'Purchase margin analysis and purchase-price volatility monitoring.'),
        'audience': T('المشتريات والمدير.', 'Purchasing and admins.'),
        'tabs': [
            {'key': 'margin', 'title': T('تحليل الهوامش', 'Margin analysis'), 'body': T('توزيع الهامش، أدنى الأصناف هامشاً، والهوامش حسب المورد للفترة المختارة.', 'Margin distribution, lowest-margin items, and margins by supplier for the chosen period.')},
            {'key': 'price', 'title': T('مراقبة الأسعار', 'Price control'), 'body': T('أصناف تذبذب سعر شرائها أكثر من الحد: أدنى وأعلى ومتوسط وآخر سعر — فرصة تفاوض أو خطأ إدخال.', 'Items whose purchase price varies more than the threshold: min, max, average and last price — a negotiation opportunity or an entry error.')},
        ],
        'related': ['pricing.approvals'],
        'updated': '2026-10-10',
    },
    {
        'key': 'purchasing.optimization',
        'routes': ['/procurement/optimization', '/procurement/mappings'],
        'title': T('تحسين المشتريات والتنبيهات', 'Procurement optimization & alerts'),
        'summary': T('أين نوفّر: الموردون الموصى بهم والمحذورون، فرص توفير السعر للأصناف التي لها عدة موردين، خريطة المورد-صنف، وتنبيهات المشتريات.',
                     'Where to save: recommended and avoided suppliers, price-saving opportunities for items with several suppliers, the supplier-item map, and purchasing alerts.'),
        'audience': T('المشتريات والمدير.', 'Purchasing and admins.'),
        'tabs': [
            {'key': 'optimization', 'title': T('🎯 التحسين', '🎯 Optimization'), 'body': T('الموردون الموصى بهم (هامش عالٍ) والمحذورون (مرتجعات عالية)، وفرص التوفير: أقل وأعلى سعر لنفس الصنف من موردين مختلفين.', 'Recommended suppliers (high margin) and avoided ones (high returns), and savings: lowest vs highest price for the same item from different suppliers.')},
            {'key': 'mapping', 'title': T('🔗 خريطة المورد-صنف', '🔗 Supplier-item map'), 'body': T('لكل صنف: مورّدوه، درجة الثقة، المورد الرئيسي، متوسط السعر وتذبذبه وآخر شراء.', 'Per item: its suppliers, confidence, the main supplier, average price, volatility and last purchase.')},
            {'key': 'alerts', 'title': T('🚨 التنبيهات', '🚨 Alerts'), 'body': T('تنبيهات حرجة/تحذير/معلومة (ارتفاع سعر، تركّز مورد…) — «تم الحل» بعد المعالجة.', 'Critical/warning/info alerts (price jump, supplier concentration…) — mark "resolved" after handling.')},
        ],
        'related': ['purchasing.overview'],
        'updated': '2026-10-10',
    },
]
