# Generated by Django 4.2.13 on 2026-08-03 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0005_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود القاعدة')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(max_length=150, verbose_name='الاسم (إنجليزي)')),
                ('category', models.CharField(choices=[('coverage', 'تغطية/سلامة البيانات'), ('volume', 'حجم المبيعات'), ('mix', 'مزيج المنتجات'), ('discount', 'الخصومات'), ('comparison', 'مقارنات'), ('highlight', 'إنجازات')], default='volume', max_length=12)),
                ('severity', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تنبيه'), ('critical', 'حرج')], default='warning', max_length=10)),
                ('threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='الحد')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='مُفعّلة')),
                ('periods', models.CharField(default='day,week,month', max_length=30, verbose_name='الفترات')),
            ],
            options={
                'verbose_name': 'قاعدة تحليل سردي',
                'verbose_name_plural': 'قواعد التحليل السردي',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='InsightRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('day', 'يوم'), ('week', 'أسبوع'), ('month', 'شهر')], db_index=True, max_length=6)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('narrative_ar', models.TextField(blank=True)),
                ('narrative_en', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.PositiveIntegerField(default=0, verbose_name='عدد المستلمين')),
            ],
            options={
                'verbose_name': 'تقرير سردي',
                'verbose_name_plural': 'التقارير السردية',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('wa_number', models.CharField(help_text='E.164 without + (e.g. 2010…)', max_length=20, verbose_name='رقم واتساب')),
                ('period_types', models.CharField(default='day,week,month', max_length=30, verbose_name='الفترات المُرسلة')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insight_recipients', to='branches.branch')),
            ],
            options={
                'verbose_name': 'مستلم تقرير',
                'verbose_name_plural': 'مستلمو التقارير',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InsightFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(db_index=True, max_length=50)),
                ('category', models.CharField(max_length=12)),
                ('severity', models.CharField(db_index=True, max_length=10)),
                ('scope_type', models.CharField(blank=True, max_length=15)),
                ('scope_key', models.CharField(blank=True, max_length=40)),
                ('scope_label', models.CharField(blank=True, max_length=150)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('baseline', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('message_ar', models.TextField()),
                ('message_en', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='insights.insightrun')),
            ],
            options={
                'verbose_name': 'ملاحظة سردية',
                'verbose_name_plural': 'الملاحظات السردية',
                'ordering': ['run', 'severity', 'category'],
            },
        ),
    ]
