# Generated by Django 4.2.13 on 2026-08-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightrecipient',
            name='salesperson_usercode',
            field=models.CharField(blank=True, db_index=True, help_text='لإرسال تقرير مسئول بيع بعينه (يتقدّم على الفرع)', max_length=20, verbose_name='كود مسئول البيع'),
        ),
    ]
