# Generated by Django 4.2.13 on 2026-08-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_insightrecipient_salesperson_usercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightrun',
            name='domain',
            field=models.CharField(choices=[('sales', 'المبيعات'), ('purchasing', 'المشتريات والتموين')], db_index=True, default='sales', max_length=12, verbose_name='نوع التقرير'),
        ),
    ]
