# Generated by Django 4.2.13 on 2026-07-04 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('omni', '0002_channelaccount_is_default_and_more'),
        ('users', '0019_alter_rolemoduleaccess_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('meta', 'Meta Graph'), ('telegram', 'Telegram'), ('tiktok', 'TikTok')], db_index=True, max_length=12)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'سجل Webhook اجتماعي',
                'verbose_name_plural': 'سجلات Webhook الاجتماعية',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(db_index=True, max_length=100, verbose_name='معرف المستخدم الخارجي')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='الاسم الظاهر')),
                ('last_message_preview', models.CharField(blank=True, max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_threads', to='omni.channelaccount', verbose_name='حساب القناة')),
                ('omni_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_threads', to='omni.conversation', verbose_name='المحادثة الموحدة')),
            ],
            options={
                'verbose_name': 'محادثة اجتماعية',
                'verbose_name_plural': 'المحادثات الاجتماعية',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'وارد'), ('outbound', 'صادر')], db_index=True, max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('audio', 'صوت'), ('video', 'فيديو'), ('file', 'ملف'), ('sticker', 'ملصق'), ('other', 'أخرى')], default='text', max_length=8)),
                ('status', models.CharField(choices=[('received', 'مُستلم'), ('sent', 'أُرسل'), ('failed', 'فشل')], default='received', max_length=10)),
                ('body', models.TextField(blank=True, verbose_name='النص')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('attachment_url', models.URLField(blank=True, max_length=1000)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_messages_sent', to='users.staffprofile')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.socialthread', verbose_name='المحادثة')),
            ],
            options={
                'verbose_name': 'رسالة اجتماعية',
                'verbose_name_plural': 'الرسائل الاجتماعية',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='socialthread',
            constraint=models.UniqueConstraint(fields=('account', 'external_user_id'), name='uniq_social_thread_per_account'),
        ),
        migrations.AddIndex(
            model_name='socialmessage',
            index=models.Index(fields=['thread', 'created_at'], name='social_soci_thread__4c1a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmessage',
            index=models.Index(fields=['external_id'], name='social_soci_externa_a33437_idx'),
        ),
    ]
