# Generated by Django 4.2.13 on 2026-04-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notif_recipient_unread_idx_notificatio_recipie_684eac_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_684eac_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_d8746a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_684eac_idx',
            old_name='notif_recipient_unread_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_notific_d8746a_idx',
            old_name='notif_type_idx',
        ),
    ]
