# Generated by Django 4.2.13 on 2026-05-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_reservation_order_source_fulfillment_images'),
        ('notifications', '0005_notificationlog_chattermessage_priority_dedup'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_recip_read_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chattermessage',
            new_name='notificatio_model_n_f26253_idx',
            old_name='chatter_model_record_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_8a1049_idx',
            old_name='notif_dedup_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_recipie_5a417d_idx',
            old_name='nlog_recip_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_recipie_1da90e_idx',
            old_name='nlog_recip_delivered_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_notific_ec37ab_idx',
            old_name='nlog_notif_delivered_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='demand_id_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='transfer_request_id_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
