# Generated by Django 4.2.13 on 2026-05-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_chattermessage_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('stock_available', '📦 مخزون متاح'), ('reservation_assigned', '👤 حجز مُعيَّن'), ('reservation_created', '➕ حجز جديد'), ('reservation_status', '🔄 تغيير حالة حجز'), ('call_logged', '📞 تحديث نشاط حجز'), ('follow_up_due', '📅 متابعة مستحقة اليوم'), ('followup', '💊 متابعة صرف مزمن'), ('churn_alert', '⚠️ تنبيه انقطاع عميل'), ('weekly_summary', '📊 ملخص أسبوعي'), ('monthly_report', '📈 تقرير شهري'), ('transfer_request', '🔀 طلب تحويل جديد'), ('transfer_response', '↩️ رد على طلب تحويل'), ('unfulfilled_transfer_flag', '⚠️ تحويل غير مُصرَّف'), ('demand_created', '🆕 طلب جديد'), ('demand_assigned', '👤 طلب مُعيَّن'), ('demand_status', '🔄 تغيير حالة طلب'), ('demand_follow_up', '📅 متابعة طلب'), ('chatter_mention', '💬 ذِكر في تعليق'), ('mention', '@ ذِكر'), ('system', '⚙️ نظام')], db_index=True, default='system', max_length=40, verbose_name='نوع الإشعار'),
        ),
    ]
