# Generated by Django 4.2.13 on 2026-06-11 20:58

from django.db import migrations, models


# Same mapping as Notification.TYPE_CATEGORY — kept inline so the migration is
# frozen against future model changes.
_TYPE_CATEGORY = {
    'demand_created':       'demand',
    'demand_assigned':      'demand',
    'demand_status':        'demand',
    'demand_follow_up':     'demand',
    'demand_back_in_stock': 'demand',
    'followup':             'followups',
}


def backfill_categories(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    for ntype, category in _TYPE_CATEGORY.items():
        Notification.objects.filter(notification_type=ntype).update(category=category)


def noop_reverse(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    Notification.objects.update(category='global')


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('global', 'عام'), ('demand', 'الطلب الضائع'), ('followups', 'المتابعات')], db_index=True, default='global', max_length=20, verbose_name='التصنيف'),
        ),
        migrations.RunPython(backfill_categories, noop_reverse),
    ]
