# Generated by Django 4.2.13 on 2026-06-14 00:20

from django.db import migrations, models


# Backfill existing rows for the newly module-scoped categories (delivery, transfers).
_TYPE_CATEGORY = {
    'delivery_new': 'delivery', 'delivery_status': 'delivery', 'delivery_sla_alert': 'delivery',
    'delivery_cash_variance': 'delivery', 'delivery_csat': 'delivery',
    'transfer_request': 'transfers', 'transfer_response': 'transfers',
    'unfulfilled_transfer_flag': 'transfers', 'transit_issued': 'transfers',
    'transit_approaching_cancel': 'transfers', 'transit_overdue': 'transfers',
    'transit_critical': 'transfers', 'transit_received': 'transfers', 'transit_cancelled': 'transfers',
}


def backfill(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    for ntype, cat in _TYPE_CATEGORY.items():
        Notification.objects.filter(notification_type=ntype).exclude(category=cat).update(category=cat)


def reverse(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    Notification.objects.filter(category__in=('delivery', 'transfers')).update(category='global')


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('global', 'عام'), ('demand', 'الطلب الضائع'), ('followups', 'المتابعات'), ('delivery', 'التوصيل'), ('transfers', 'التحويلات')], db_index=True, default='global', max_length=20, verbose_name='التصنيف'),
        ),
        migrations.RunPython(backfill, reverse),
    ]
