# Generated by Django 4.2.13 on 2026-06-14 00:26

from django.db import migrations, models


_RES_TYPES = ['reservation_created', 'reservation_assigned', 'reservation_status',
              'call_logged', 'stock_available', 'follow_up_due']


def backfill(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    Notification.objects.filter(notification_type__in=_RES_TYPES).exclude(
        category='reservations').update(category='reservations')


def reverse(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    Notification.objects.filter(category='reservations').update(category='global')


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('global', 'عام'), ('demand', 'الطلب الضائع'), ('followups', 'المتابعات'), ('delivery', 'التوصيل'), ('transfers', 'التحويلات'), ('reservations', 'الحجوزات')], db_index=True, default='global', max_length=20, verbose_name='التصنيف'),
        ),
        migrations.RunPython(backfill, reverse),
    ]
