# Generated by Django 4.2.13 on 2026-06-14 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_softechsystemmap_erpgroupmodulepermission'),
        ('notifications', '0019_reports_mentions_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleNotificationAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin — Full Access'), ('call_center', 'Call Center — All Branches'), ('pharmacist', 'Pharmacist — Own Branch'), ('salesperson', 'Sales Person — Own Branch'), ('purchasing', 'Purchasing — HQ Only'), ('delivery', 'Delivery'), ('viewer', 'Viewer — Read Only'), ('supervisor', 'Supervisor — Call Center Supervisor'), ('quality_manager', 'Quality Manager — QA & Scoring')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('global', 'عام'), ('demand', 'الطلب الضائع'), ('followups', 'المتابعات'), ('delivery', 'التوصيل'), ('transfers', 'التحويلات'), ('reservations', 'الحجوزات'), ('monitoring', 'المراقبة'), ('settings', 'النظام والإعدادات'), ('reports', 'التقارير الدورية'), ('mentions', 'الإشارات')], db_index=True, max_length=20)),
                ('is_allowed', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffprofile')),
            ],
            options={
                'verbose_name': 'ظهور إشعار للدور',
                'verbose_name_plural': 'ظهور الإشعارات للأدوار',
                'ordering': ['role', 'category'],
                'unique_together': {('role', 'category')},
            },
        ),
    ]
