# Generated by Django 4.2.13 on 2026-06-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_rolenotificationaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolenotificationaccess',
            options={'ordering': ['role', 'category'], 'verbose_name': 'إعداد إشعار للدور', 'verbose_name_plural': 'إعدادات الإشعارات للأدوار'},
        ),
        migrations.AddField(
            model_name='rolenotificationaccess',
            name='generate',
            field=models.BooleanField(default=True, help_text='عند الإيقاف لا تُنشأ إشعارات هذه الفئة لهذا الدور', verbose_name='يُنشأ'),
        ),
        migrations.AlterField(
            model_name='rolenotificationaccess',
            name='is_allowed',
            field=models.BooleanField(default=True, verbose_name='يظهر'),
        ),
    ]
