# Generated by Django 4.2.13 on 2026-06-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_alter_reservation_contract_subtype_and_more'),
        ('users', '0015_softechsystemmap_erpgroupmodulepermission'),
        ('notifications', '0021_alter_rolenotificationaccess_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='snooze_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد مرات التأجيل'),
        ),
        migrations.AddField(
            model_name='notification',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='مؤجَّل حتى'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('stock_available', '📦 مخزون متاح'), ('reservation_assigned', '👤 حجز مُعيَّن'), ('reservation_created', '➕ حجز جديد'), ('reservation_status', '🔄 تغيير حالة حجز'), ('call_logged', '📞 تحديث نشاط حجز'), ('follow_up_due', '📅 متابعة مستحقة اليوم'), ('followup', '💊 متابعة صرف مزمن'), ('churn_alert', '⚠️ تنبيه انقطاع عميل'), ('weekly_summary', '📊 ملخص أسبوعي'), ('monthly_report', '📈 تقرير شهري'), ('transfer_request', '🔀 طلب تحويل جديد'), ('transfer_response', '↩️ رد على طلب تحويل'), ('unfulfilled_transfer_flag', '⚠️ تحويل غير مُصرَّف'), ('transit_issued', '🚛 تحويل صادر'), ('transit_approaching_cancel', '⏳ مهلة إلغاء قاربت'), ('transit_overdue', '🟠 تحويل متأخر'), ('transit_critical', '🚨 تحويل حرج'), ('transit_received', '✅ تحويل مستلم'), ('transit_cancelled', '↩️ تحويل ملغي'), ('demand_created', '🆕 طلب جديد'), ('demand_assigned', '👤 طلب مُعيَّن'), ('demand_status', '🔄 تغيير حالة طلب'), ('demand_follow_up', '📅 متابعة طلب'), ('demand_back_in_stock', '🔔 صنف مطلوب عاد للمخزون'), ('chatter_mention', '💬 ذِكر في تعليق'), ('mention', '@ ذِكر'), ('delivery_new', '🚚 طلب توصيل جديد'), ('delivery_status', '📦 تغيير حالة توصيل'), ('delivery_sla_alert', '⏰ تجاوز SLA توصيل'), ('delivery_cash_variance', '💰 عجز نقدي توصيل'), ('delivery_csat', '⭐ تقييم عميل'), ('system', '⚙️ نظام'), ('branch_connectivity', '🔌 اتصال فرع'), ('personal_reminder', '⏰ تذكير شخصي')], db_index=True, default='system', max_length=40, verbose_name='نوع الإشعار'),
        ),
        migrations.CreateModel(
            name='PersonalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('remind_at', models.DateTimeField(db_index=True, verbose_name='وقت التذكير')),
                ('is_fired', models.BooleanField(db_index=True, default=False, verbose_name='تم التذكير')),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('demand_id_ref', models.IntegerField(blank=True, null=True)),
                ('transfer_request_id_ref', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_reminders', to='users.staffprofile', verbose_name='صاحب التذكير')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_reminders', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'تذكير شخصي',
                'verbose_name_plural': 'تذكيرات شخصية',
                'ordering': ['remind_at'],
                'indexes': [models.Index(fields=['owner', 'is_fired', 'remind_at'], name='notificatio_owner_i_cfd73a_idx')],
            },
        ),
    ]
