# Generated by Django 4.2.13 on 2026-06-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_staffprofile_muted_notification_categories'),
        ('notifications', '0022_notification_snooze_count_notification_snoozed_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('audience_roles', models.JSONField(blank=True, default=list, verbose_name='الأدوار المستهدفة')),
                ('audience_branch_ids', models.JSONField(blank=True, default=list, verbose_name='الفروع المستهدفة')),
                ('priority', models.CharField(choices=[('normal', 'عادي'), ('high', 'هام')], default='normal', max_length=10)),
                ('is_pinned', models.BooleanField(default=False, verbose_name='مثبّت')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='users.staffprofile', verbose_name='الكاتب')),
            ],
            options={
                'verbose_name': 'إعلان داخلي',
                'verbose_name_plural': 'الإعلانات الداخلية',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('stock_available', '📦 مخزون متاح'), ('reservation_assigned', '👤 حجز مُعيَّن'), ('reservation_created', '➕ حجز جديد'), ('reservation_status', '🔄 تغيير حالة حجز'), ('call_logged', '📞 تحديث نشاط حجز'), ('follow_up_due', '📅 متابعة مستحقة اليوم'), ('followup', '💊 متابعة صرف مزمن'), ('churn_alert', '⚠️ تنبيه انقطاع عميل'), ('weekly_summary', '📊 ملخص أسبوعي'), ('monthly_report', '📈 تقرير شهري'), ('transfer_request', '🔀 طلب تحويل جديد'), ('transfer_response', '↩️ رد على طلب تحويل'), ('unfulfilled_transfer_flag', '⚠️ تحويل غير مُصرَّف'), ('transit_issued', '🚛 تحويل صادر'), ('transit_approaching_cancel', '⏳ مهلة إلغاء قاربت'), ('transit_overdue', '🟠 تحويل متأخر'), ('transit_critical', '🚨 تحويل حرج'), ('transit_received', '✅ تحويل مستلم'), ('transit_cancelled', '↩️ تحويل ملغي'), ('demand_created', '🆕 طلب جديد'), ('demand_assigned', '👤 طلب مُعيَّن'), ('demand_status', '🔄 تغيير حالة طلب'), ('demand_follow_up', '📅 متابعة طلب'), ('demand_back_in_stock', '🔔 صنف مطلوب عاد للمخزون'), ('chatter_mention', '💬 ذِكر في تعليق'), ('mention', '@ ذِكر'), ('delivery_new', '🚚 طلب توصيل جديد'), ('delivery_status', '📦 تغيير حالة توصيل'), ('delivery_sla_alert', '⏰ تجاوز SLA توصيل'), ('delivery_cash_variance', '💰 عجز نقدي توصيل'), ('delivery_csat', '⭐ تقييم عميل'), ('system', '⚙️ نظام'), ('branch_connectivity', '🔌 اتصال فرع'), ('personal_reminder', '⏰ تذكير شخصي'), ('announcement', '📢 إعلان داخلي')], db_index=True, default='system', max_length=40, verbose_name='نوع الإشعار'),
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.announcement')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to='users.staffprofile')),
            ],
            options={
                'verbose_name': 'تأكيد قراءة إعلان',
                'verbose_name_plural': 'تأكيدات قراءة الإعلانات',
                'unique_together': {('announcement', 'staff')},
            },
        ),
    ]
