# Generated by Django 4.2.13 on 2026-06-20 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_drop_legacy_has_global_access'),
        ('notifications', '0023_announcement_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='نقطة النهاية')),
                ('p256dh', models.CharField(max_length=255, verbose_name='مفتاح p256dh')),
                ('auth', models.CharField(max_length=255, verbose_name='مفتاح auth')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='متصفح/جهاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='users.staffprofile', verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'اشتراك إشعارات المتصفح',
                'verbose_name_plural': 'اشتراكات إشعارات المتصفح',
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_fb452e_idx')],
            },
        ),
    ]
